import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { gasMassFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.3.1.3 Changes in mass when a reactant or product is a gas (unsealed containers; thermal decomposition of metal carbonates), as on the supplied revision page' }
const skill = 'C-GAS-MASS'
const why = author(skill, ['5.3.1.3'], ['aqa-chemistry'])
const reactant = author(skill, ['5.3.1.3'], ['aqa-chemistry'])
const product = author(skill, ['5.3.1.3'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const gasMassSections = [
  { id: 'C20-01', label: 'Start here', detail: 'Where does a gas go?' },
  { id: 'C20-02', label: 'Why can the mass seem to change?', detail: 'Sealed and unsealed containers' },
  { id: 'C20-04', label: 'When a reactant is a gas', detail: 'Magnesium burning: the mass goes up' },
  { id: 'C20-08', label: 'When a product is a gas', detail: 'Copper carbonate heated: the mass goes down' },
  { id: 'C20-12', label: 'On your own', detail: 'Data, a calculation and a flask question' },
]

const states: ScienceState[] = [
  { ...why.choice('C20-01', 'A gas is made in a reaction in an open beaker. Where do the gas particles go?', ['They stay in a layer at the bottom of the beaker', 'They disappear', 'They spread out into the air', 'They turn into a liquid'], 2, 'Think about how gas particles move.', ['Gas particles move freely and spread out to fill any space they can reach.', 'In an open beaker, that means they drift out into the air.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(why, 'C20-02', 'Why can the mass seem to change?'),
  why.choice('C20-03', 'During a reaction in an open beaker, the balance reading goes down. What is the most likely reason?', ['Some atoms were destroyed', 'A gas formed and escaped into the air', 'A gas from the air joined the reactants', 'The atoms in the beaker got smaller'], 1, 'Atoms are never destroyed. What could leave an open beaker?', ['No atoms are lost in a reaction, so the mass must have left the beaker in some way.', 'A gas that escapes into the air is no longer on the balance, so the reading goes down.']),
  t(reactant, 'C20-04', 'When a reactant is a gas'),
  reactant.worked('C20-05', 'Work out how much oxygen joined the magnesium', 'A crucible with magnesium ribbon has a mass of 25.24 g. After the ribbon burns in air, the crucible and magnesium oxide have a mass of 25.40 g. What mass of oxygen joined the magnesium?', ['The mass before is 25.24 g and the mass after is 25.40 g.', 'The reading went up, so a gas from the air joined the solid.', 'The extra mass is the difference: 25.40 − 25.24 = 0.16 g.', 'So 0.16 g of oxygen from the air joined the magnesium.'], 'gasmass-worked-mg'),
  reactant.choice('C20-06', 'A dish of copper weighs 22.40 g. After heating in air it weighs 22.65 g. What mass of oxygen joined?', ['22.65 g', '22.40 g', '0.25 g', '45.05 g'], 2, 'What is the difference between the two readings?', ['The reading went up, so oxygen from the air joined the copper.', 'Subtract: 22.65 − 22.40 = 0.25 g of oxygen.'], 'calculation'),
  reactant.choice('C20-07', 'Each reaction happens in an open container. Which one would make the balance reading go up?', ['copper carbonate(s) → copper oxide(s) + carbon dioxide(g)', 'copper(s) + oxygen(g) → copper oxide(s)', 'sodium hydroxide(aq) + hydrochloric acid(aq) → sodium chloride(aq) + water(l)', 'calcium carbonate(s) → calcium oxide(s) + carbon dioxide(g)'], 1, 'Look for a gas among the reactants.', ['Only the second reaction has a gas, oxygen(g), on the reactant side.', 'The oxygen joins the solid, so the mass in the open container goes up.']),
  t(product, 'C20-08', 'When a product is a gas'),
  product.worked('C20-09', 'Work out how much carbon dioxide escaped', 'An open tube holds 6.2 g of copper carbonate. After heating, the tube holds 4.0 g of copper oxide. What mass of carbon dioxide escaped? Ignore the mass of the tube.', ['The mass before is 6.2 g and the mass after is 4.0 g.', 'The mass went down, so a gas product escaped.', 'The missing mass is the difference: 6.2 − 4.0 = 2.2 g.', 'So 2.2 g of carbon dioxide escaped into the air.'], 'gasmass-worked-cu'),
  product.choice('C20-10', 'Heating 3.0 g of zinc carbonate in an open tube leaves 1.9 g of zinc oxide. What mass of carbon dioxide escaped?', ['4.9 g', '1.9 g', '3.0 g', '1.1 g'], 3, 'The mass went down. What is the difference?', ['The mass went down, so a gas product escaped from the tube.', 'Subtract: 3.0 − 1.9 = 1.1 g of carbon dioxide.'], 'calculation'),
  product.choice('C20-11', 'Copper carbonate is heated in an open tube and the balance reading goes down. Why?', ['Carbon dioxide gas escapes into the air', 'Some copper atoms are destroyed', 'Oxygen from the air joins the solid', 'The tube loses mass as it gets hot'], 0, 'Is a gas a reactant or a product here?', ['Carbon dioxide gas is a product. The tube is open, so it drifts out into the air.', 'The balance cannot weigh gas that has left, so the reading goes down. No atoms are lost.']),
  { ...product.choice('C20-12', 'Which experiment fits a reactant that is a gas from the air?', ['Experiment A', 'Experiment B', 'Experiment C', 'All three'], 0, 'Which experiment has a mass that goes up?', ['In experiment A the mass goes up, from 4.0 g to 5.0 g. A gas from the air joined the copper.', 'In B the mass stays the same, and in C it goes down, which fits a gas product escaping.']), phase: 'independent', evidenceRole: 'independent', dimensions: ['dataInterpretation'], visual: { id: 'gasmass-data', kind: 'dataTable', brief: 'Original data table of three open-container experiments.', accessibleDescription: 'A table of three experiments in open containers with masses before and after.', assessmentDescription: 'A table of three experiments in open containers with masses before and after.' }, exam: { marks: 1, ao: 'AO3', status: 'revilyDraft' } },
  product.choice('C20-13', 'Heating 5.0 g of a metal carbonate in an open tube leaves 3.2 g of metal oxide. How much carbon dioxide escaped?', ['2.2 g', '8.2 g', '3.2 g', '1.8 g'], 3, 'Subtract the mass after from the mass before.', ['The mass went down, so carbon dioxide gas escaped.', 'Subtract: 5.0 − 3.2 = 1.8 g.'], 'calculation', true),
  product.choice('C20-14', 'In both flasks a solid reacts and makes a gas. In which flask will the balance reading stay the same?', ['Flask 1 only', 'Flask 2 only', 'Both flasks', 'Neither flask'], 1, 'Which flask lets the gas escape?', ['Flask 1 is open, so the gas escapes and its reading goes down.', 'Flask 2 has a tight bung, so the gas is trapped and its reading stays the same.'], 'application', true, 'gasmass-question-flasks'),
  reactant.choice('C20-15', 'Magnesium burns in an open crucible and gains mass. A student says mass is not conserved. What is the best reply?', ['She is wrong: oxygen from the air joined the magnesium, so the crucible held more mass', 'She is right: new atoms were made in the reaction', 'She is wrong: mass can never change in any container', 'She is right: the balance must be faulty'], 0, 'Where did the extra mass come from?', ['The extra mass is oxygen that was in the air. It joined the magnesium and is now in the solid.', 'No atoms were made. Mass is conserved, but the oxygen was not on the balance at the start.'], 'application', true),
  product.written('C20-16', 'Heating calcium carbonate in an open tube lowers the mass. Explain why, and how to show mass is conserved.', 'Say what the calcium carbonate breaks down into. Then say where the gas goes and what the balance can weigh.', 'Heating breaks calcium carbonate down into calcium oxide, a solid, and carbon dioxide, a gas. The tube is open, so the carbon dioxide escapes into the air. The balance only weighs what is left in the tube, so the reading goes down, but no atoms are lost. If she trapped the gas in a sealed container, the total mass would stay the same.', ['Calcium carbonate breaks down (thermal decomposition) into calcium oxide, a solid, and carbon dioxide, a gas.', 'The tube is open, so the carbon dioxide escapes into the air.', 'The balance only weighs what is left in the tube, so the reading goes down. No atoms are lost.', 'To show mass is conserved, trap the gas (for example in a sealed container) and the total mass stays the same.'], ['Saying atoms were destroyed or lost.', 'Saying the mass goes down because the calcium carbonate got hot.', 'Giving a reason with no mention of a gas escaping.']),
]

export const lessonC20: ScienceLesson = {
  id: 'C-QNT-020-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'When mass seems to change', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
