import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { resistanceFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.6.3.4 Resistant bacteria: evolution by natural selection, MRSA, and reducing the rate of development' }
const a = author('B-ANTIBIOTIC-RESISTANCE', ['4.6.3.4'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const resistanceSections = [
  { id: 'B43-01', label: 'Start here', detail: 'Bacteria an antibiotic no longer kills' },
  { id: 'B43-02', label: 'How does resistance evolve?', detail: 'Natural selection in bacteria' },
  { id: 'B43-05', label: 'Why is it a problem?', detail: 'No treatment, easy spread, superbugs' },
  { id: 'B43-08', label: 'How can we slow it down?', detail: 'Doctors, patients, farmers and new drugs' },
  { id: 'B43-11', label: 'On your own', detail: 'Four stages, chickens, hospital data and a new drug' },
]

const states: ScienceState[] = [
  { ...a.choice('B43-01', 'An antibiotic no longer kills one strain of bacteria. What are these bacteria called?', ['Immune', 'Extinct', 'Resistant', 'Vaccinated'], 2, 'You met this word when you learned about medicines.', ['Immune and vaccinated describe people, not bacteria; extinct means none are left.', 'Bacteria that an antibiotic no longer kills are resistant.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B43-02', 'How does resistance evolve?'),
  a.choice('B43-03', 'Why does the resistant bacterium survive when the patient takes the antibiotic?', ['It learns to fight the antibiotic', 'A random mutation means the antibiotic does not kill it', 'It hides inside a white blood cell', 'The patient becomes immune to the antibiotic'], 1, 'Where did the resistance come from, before the antibiotic was taken?', ['The resistance came from a random mutation in its DNA, not from learning or the patient.', 'So the antibiotic does not kill it, and it survives.']),
  a.choice('B43-04', 'Why can bacteria evolve much more quickly than animals such as rabbits?', ['Bacteria are bigger', 'Bacteria never mutate', 'Bacteria live longer', 'Bacteria reproduce very fast, so many generations grow in a short time'], 3, 'Evolution happens over generations. How fast do bacteria make new generations?', ['Evolution happens as genes are passed on over many generations.', 'Bacteria reproduce very fast, so many generations grow in a short time.']),
  t('B43-05', 'Why is it a problem?'),
  a.choice('B43-06', 'Why can a new resistant strain spread easily between people?', ['People are not immune to it, and it is hard to treat', 'It is caused by a virus', 'Antibiotics make it spread faster'], 0, 'Think about the two reasons in the walkthrough.', ['People are not immune to a new strain.', 'It is also hard to treat, so it can spread easily.']),
  a.choice('B43-07', 'Which is one reason antibiotic resistance is becoming more common?', ['Too few people are ill', 'Bacteria are becoming extinct', 'Antibiotics are overused', 'Viruses are turning into bacteria'], 2, 'What happens each time an antibiotic is used?', ['Each use of an antibiotic gives resistant bacteria a chance to survive and spread.', 'Antibiotics are overused, so resistance is becoming more common.']),
  t('B43-08', 'How can we slow it down?'),
  a.choice('B43-09', 'Why should patients take the full course of antibiotics they are prescribed?', ['So they do not need to see a doctor again', 'So all the bacteria are destroyed and none are left to mutate', 'So the antibiotic kills viruses too'], 1, 'What could happen to bacteria left alive?', ['Bacteria left alive could mutate and form resistant strains.', 'Taking the full course destroys all the bacteria, so none are left to mutate.']),
  a.choice('B43-10', 'A doctor does not prescribe antibiotics for a mild sore throat caused by a virus. How does this help slow down resistance?', ['Using antibiotics less gives resistant bacteria fewer chances to survive and spread', 'The virus becomes resistant instead', 'It makes the patient immune to all bacteria'], 0, 'Antibiotics do not kill viruses. What happens each time one is used?', ['Antibiotics would not help an illness caused by a virus anyway.', 'Using them less gives resistant bacteria fewer chances to survive and spread.']),
  a.choice('B43-11', 'Look at the four numbered stages. Which stage shows the resistant bacteria reproducing?', ['Stage 1', 'Stage 2', 'Stage 3', 'Stage 4'], 2, 'Find the stage where one survivor becomes several.', ['Stage 1 shows a random mutation, stage 2 the antibiotic killing the other bacteria, and stage 4 a resistant strain.', 'Stage 3 shows the resistant bacterium reproducing.'], 'understanding', true, 'evolve-res-question'),
  a.choice('B43-12', 'A farmer gives antibiotics to healthy chickens so that they grow faster. Why could this harm people?', ['The chickens would lay fewer eggs', 'Resistant strains could develop in the chickens and spread to people', 'The antibiotics would give people viruses'], 1, 'What can happen to bacteria that meet an antibiotic again and again?', ['Using antibiotics on farm animals can lead to resistant strains in the animals.', 'These strains can spread to people, for example when they prepare meat.'], 'application', true),
  a.choice('B43-13', 'The graph shows the percentage of resistant infections in one hospital over 15 years. Which conclusion fits it?', ['The percentage of resistant infections rose from 2010 to 2025', 'Overuse of antibiotics in this hospital caused the rise', 'Every infection will be resistant by 2040', 'The number of patients fell'], 0, 'Describe the line. Does the graph show the cause, or anything after 2025?', ['The percentage rose from 4% to 14%; the graph does not show what caused it or what happens next.', 'The percentage of resistant infections rose from 2010 to 2025.'], 'dataInterpretation', true, 'evolve-res-data'),
  a.choice('B43-14', 'A drug company develops a new antibiotic. Why is it unlikely to solve the problem of resistant bacteria for good?', ['New antibiotics never kill bacteria', 'Bacteria cannot mutate any more', 'People would become immune to it', 'Bacteria could evolve resistance to it too, and new drugs are slow and expensive to make'], 3, 'Could the same natural selection happen again?', ['Random mutations could make some bacteria resistant to the new drug, and natural selection would follow.', 'New drugs are also slow and expensive to develop, so they are unlikely to keep up.'], 'application', true),
  a.written('B43-15', 'Explain how a population of bacteria can become resistant to an antibiotic. Then give two ways to slow this down.', 'Start with a mutation, then say what the antibiotic does, then what the survivors do. Finish with two actions.', 'A random mutation in its DNA makes one bacterium resistant to the antibiotic. When the antibiotic is used, it kills the bacteria that are not resistant, but the resistant one survives. It reproduces many times and passes on the gene for resistance, so the gene becomes common and a resistant strain forms. To slow this down, doctors should only prescribe antibiotics when really needed, and patients should take the full course.', ['A random mutation makes a bacterium resistant.', 'The antibiotic kills the bacteria that are not resistant; the resistant ones survive.', 'The resistant bacteria reproduce and pass on the gene for resistance.', 'The gene becomes common, forming a resistant strain.', 'One correct way to slow it down, such as only prescribing antibiotics when really needed.', 'A second correct way, such as taking the full course or restricting antibiotic use in farming.'], ['Saying bacteria become resistant because they get used to the antibiotic, or learn.', 'Saying the patient becomes resistant or immune to the antibiotic.', 'Saying antibiotics should be used for viral infections.', 'Saying the antibiotic causes the mutation.']),
]

export const lesson43: ScienceLesson = {
  id: 'B-GEN-043-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Antibiotic-resistant bacteria', prerequisites: ['B-EVOLUTION', 'B-MEDICINES'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
