import type { TeachingFrame } from '../../teachingFrame'

// The scientific method: observation, hypothesis, prediction, test, peer review, accepted or rejected, and models.
// Examples come from all three sciences; the atom-model history is a one-clause link back to earlier lessons.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const wsMethodFrames: Record<string, TeachingFrame[]> = {
  'W1-02': [
    f('Start with an observation', 'Scientists notice something they cannot yet explain, then suggest a possible explanation called a hypothesis.', 'notice, then explain', 'Science starts when someone looks closely at something they cannot yet explain. A gardener might notice that plants on one side of a fence grow taller. That is an observation. Someone then suggests a possible explanation, such as "those plants get more sunlight". A possible explanation like this is called a hypothesis.', 'wsmethod-observe'),
    f('Make a prediction', 'A prediction is a statement, based on the hypothesis, that you can test.', 'if the hypothesis is right, then…', 'You cannot test a hypothesis directly, so scientists use it to make a prediction. A prediction says what should happen if the hypothesis is right, and it can be tested. For the fence, a prediction is: "Plants moved into the shade will grow less."', 'wsmethod-predict'),
    f('Test the prediction', 'Carry out an experiment. If the prediction is right, that is evidence the hypothesis might be right.', 'experiment, result, evidence', 'Next the scientist tests the prediction with an experiment and records what happens. If the prediction is right, that is evidence that the hypothesis might be right too. If the prediction is wrong, the hypothesis is in trouble. One good result does not prove a hypothesis for certain.', 'wsmethod-test'),
    f('The whole chain', 'Observation, hypothesis, prediction, test. The result of the test is the evidence.', 'four steps in order', 'Put the steps in order. First an observation, then a hypothesis to explain it, then a prediction, then a test. The result of the test is the evidence. Scientists in Biology, Chemistry and Physics all follow the same chain.', 'wsmethod-chain'),
  ],
  'W1-05': [
    f('Other scientists check', 'Other scientists check the evidence, for example whether the experiment was done in a sensible way. This is peer review.', 'checking someone else\'s work', 'Scientists do not keep their results to themselves. Other scientists check the evidence, for example whether the experiment was carried out in a sensible way. This checking is called peer review. It helps to catch mistakes before a claim is trusted.', 'wsmethod-peer'),
    f('Share the results', 'Results are shared in scientific papers so that everyone can read the evidence and repeat the work.', 'papers, repeat, compare', 'Scientists share their results in scientific papers, so that other scientists can read exactly what was done. Other teams can then repeat the experiment, or try new experiments, to test the same hypothesis. Repeating work is a good way to spot a result that was a one-off.', 'wsmethod-share'),
    f('More evidence, for or against', 'Sometimes the new evidence supports the hypothesis. Sometimes it shows the hypothesis is wrong.', 'support or contradict', 'Sometimes other teams find more evidence that the hypothesis is right. Sometimes they find evidence that shows it is wrong. Both outcomes are useful. Together the evidence helps scientists decide what to believe.', 'wsmethod-evidence'),
  ],
  'W1-08': [
    f('An accepted theory', 'If all the evidence supports a hypothesis, it can become an accepted theory.', 'lots of testing over years', 'If all the evidence that has been found supports a hypothesis, it can become the basis of an accepted theory. Accepted theories may go into textbooks. They are the ideas that have survived lots of testing over many years.', 'wsmethod-accepted'),
    f('When the evidence says no', 'If the evidence shows a hypothesis is wrong, scientists change it or come up with a new one, then test again.', 'change it or replace it', 'Sometimes the evidence shows that a hypothesis is wrong. Then scientists must do one of two things. They can change the hypothesis, or they can come up with a new one. Either way, the testing starts again.', 'wsmethod-rejected'),
    f('Ideas change', 'Explanations have changed as new evidence has been found.', 'old idea, new evidence, new idea', 'Long ago, many people believed the Sun goes round the Earth. Careful observations of the planets fitted a Sun-centred idea much better, so the accepted idea changed. Ideas about the structure of the atom changed in the same way, as you saw when you learned how the atom model developed.', 'wsmethod-history'),
  ],
  'W1-11': [
    f('A model is a simple picture', 'A model is a simple way of describing or showing what is going on in real life.', 'simple, explains, predicts', 'A model is a simple way of describing or showing what is going on in real life. A diagram of the water cycle and a toy model of the heart are models. Models can be used to explain ideas and to make predictions.', 'wsmethod-model'),
    f('Spatial models', 'A spatial model shows where the different parts of something are placed in space.', 'where things are', 'A spatial model shows where different parts of a structure are located in space. A ball-and-stick model of a water molecule shows which atoms are joined and roughly how they are arranged. You can turn it round and see it from every side.', 'wsmethod-spatial'),
    f('Computational models', 'A computational model uses a computer to simulate a complex real-life process.', 'computer simulation', 'Some processes are too big or too complicated to build by hand. A computational model uses a computer to simulate them. Examples are how a flu virus might spread through a city, or how the climate might change over fifty years.', 'wsmethod-computational'),
    f('Every model has limits', 'A single model cannot explain everything about an idea.', 'what does it leave out', 'All models have limits. A single model cannot explain everything about an idea. The ball-and-stick water molecule, for example, does not show the electrons that make the bonds.', 'wsmethod-limits'),
    f('Example: the Bohr model', 'The Bohr model of the atom explains some patterns in the periodic table but not every observation.', 'useful, but limited', 'The Bohr model shows an atom with electrons in shells around a nucleus. It can explain trends in the periodic table, such as why elements in the same group react in similar ways. But there are some observations about atoms that it cannot explain.', 'wsmethod-bohr'),
  ],
}
