import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { equilibriumFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.6.2.4 The effect of changing conditions on equilibrium (HT): Le Chatelier’s principle, position of equilibrium; 5.6.2.5 The effect of changing concentration (HT); 5.6.2.6 The effect of temperature changes on equilibrium (HT); 5.6.2.7 The effect of pressure changes on equilibrium (HT), as on the supplied revision pages' }
const skill = 'C-EQM'
const principle = author(skill, ['5.6.2.4'], ['aqa-chemistry'])
const temperature = author(skill, ['5.6.2.4', '5.6.2.6'], ['aqa-chemistry'])
const pressure = author(skill, ['5.6.2.4', '5.6.2.7'], ['aqa-chemistry'])
const concentration = author(skill, ['5.6.2.4', '5.6.2.5'], ['aqa-chemistry'])
const pressureAndConcentration = author(skill, ['5.6.2.4', '5.6.2.5', '5.6.2.7'], ['aqa-chemistry'])
const all = author(skill, ['5.6.2.4', '5.6.2.6', '5.6.2.7'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const equilibriumSections = [
  { id: 'C36H-01', label: 'Start here', detail: 'Why does cooling change the direction?' },
  { id: 'C36H-02', label: 'The system pushes back', detail: 'Position of equilibrium and Le Chatelier’s principle' },
  { id: 'C36H-06', label: 'Changing the temperature', detail: 'Hotter goes endothermic, cooler goes exothermic' },
  { id: 'C36H-10', label: 'Pressure and concentration', detail: 'Counting gas molecules, adding and removing' },
  { id: 'C36H-15', label: 'On your own', detail: 'New reactions, molecules, a table and a factory' },
]

const states: ScienceState[] = [
  { ...principle.choice('C36H-01', 'Heating ammonium chloride gives ammonia and hydrogen chloride. What happens when the mixture is cooled?', ['More ammonia and hydrogen chloride form', 'More ammonium chloride forms', 'Nothing, because the reaction has stopped', 'The ammonia turns into hydrogen chloride'], 1, 'Which direction does cooling make this reaction go?', ['Cooling makes the backward reaction go, so ammonia and hydrogen chloride react to make ammonium chloride again.', 'So changing the conditions changes which way a reversible reaction goes. Next you will find out why.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(principle, 'C36H-02', 'The system pushes back'),
  principle.choice('C36H-03', 'What does Le Chatelier’s principle say happens when you change the conditions of a reaction at equilibrium?', ['The reaction stops until the conditions change back', 'The system always makes more products', 'The system responds to counteract the change', 'The system makes the change even bigger'], 2, 'Think of the system pushing back.', ['Le Chatelier’s principle says the system responds to counteract, or work against, the change.', 'It does not always make more products. Which way it moves depends on what was changed.']),
  principle.choice('C36H-04', 'A reaction is at equilibrium. The equilibrium lies to the left. What does this tell you?', ['The reaction has stopped', 'There are more products than reactants', 'The amounts of reactants and products are equal', 'There are more reactants than products'], 3, 'Which side of the equation are the reactants on?', ['Reactants are on the left of the equation. If the equilibrium lies to the left, there are more reactants than products.', 'The reaction has not stopped. Both reactions carry on at the same rate.']),
  principle.choice('C36H-05', 'A change of conditions moves the position of equilibrium to the right. What happens?', ['More products form and some reactants are used up', 'More reactants form and some products are used up', 'The forward and backward reactions both stop', 'Nothing changes, because it was at equilibrium'], 0, 'Which side of the equation is on the right?', ['Products are on the right, so moving to the right means the forward reaction makes more products.', 'Some reactants are used up to make them. Then equilibrium is reached again.'], 'application'),

  t(temperature, 'C36H-06', 'Temperature'),
  temperature.worked('C36H-07', 'Predict the effect of temperature', 'Methanol is made from carbon monoxide and hydrogen: CO(g) + 2H₂(g) ⇌ CH₃OH(g). The forward reaction is exothermic. Predict how raising the temperature changes the amount of methanol.', ['What has changed? The temperature has been raised.', 'The system works against this by taking in heat, so the equilibrium moves in the endothermic direction.', 'The forward reaction is exothermic, so the backward reaction is endothermic.', 'The equilibrium moves to the left, so there is less methanol at equilibrium.'], 'hequil-worked-temp'),
  temperature.choice('C36H-08', 'CH₄(g) + H₂O(g) ⇌ CO(g) + 3H₂(g). The forward reaction is endothermic. The temperature is raised. Which way does the equilibrium move?', ['To the left, making less hydrogen', 'To the right, making more hydrogen', 'It does not move, because temperature has no effect', 'To the left, making more hydrogen'], 1, 'Raising the temperature moves the equilibrium in the endothermic direction. Which direction is that here?', ['Raising the temperature moves the equilibrium in the endothermic direction, to take in heat.', 'The forward reaction is endothermic, so the equilibrium moves to the right. More carbon monoxide and hydrogen form.']),
  temperature.choice('C36H-09', 'In N₂ + 3H₂ ⇌ 2NH₃, the forward reaction is exothermic. Which change gives more ammonia at equilibrium?', ['Raising the temperature', 'Keeping the temperature the same', 'Lowering the temperature'], 2, 'More ammonia means moving to the right. Which direction is exothermic?', ['To get more ammonia, the equilibrium must move to the right. The forward reaction is exothermic.', 'Lowering the temperature moves the equilibrium in the exothermic direction. So it moves to the right and makes more ammonia.'], 'application'),

  t(pressureAndConcentration, 'C36H-10', 'Pressure and concentration'),
  pressure.worked('C36H-11', 'Predict the effect of pressure', 'Hydrogen can be made from methane and steam: CH₄(g) + H₂O(g) ⇌ CO(g) + 3H₂(g). Predict how raising the pressure changes the amount of hydrogen.', ['All four substances are gases (g), so pressure matters.', 'Count the molecules of gas. Left: 1 + 1 = 2. Right: 1 + 3 = 4.', 'Raising the pressure moves the equilibrium to the side with fewer molecules of gas. That is the left side.', 'So the equilibrium moves to the left, and there is less hydrogen at equilibrium.'], 'hequil-worked-pressure'),
  pressure.choice('C36H-12', 'CO(g) + 2H₂(g) ⇌ CH₃OH(g). The pressure is raised. What happens to the amount of methanol at equilibrium?', ['It goes down, because the left has more molecules', 'It stays the same, because all are gases', 'It goes down, because the equilibrium moves left', 'It goes up, because the right has fewer molecules of gas'], 3, 'Count the molecules of gas on each side.', ['The left has 1 + 2 = 3 molecules of gas. The right has 1.', 'Raising the pressure moves the equilibrium to the side with fewer molecules, the right. So more methanol forms.']),
  pressure.choice('C36H-13', 'N₂(g) + O₂(g) ⇌ 2NO(g). What is the effect of raising the pressure on the position of equilibrium?', ['No effect, because each side has 2 molecules of gas', 'It moves to the right, because NO is the product', 'It moves to the left, because there are two reactants', 'It moves to the right, because pressure always helps products'], 0, 'Count the molecules of gas on each side, not the number of different substances.', ['The left has 1 + 1 = 2 molecules of gas. The right also has 2.', 'Neither side has fewer molecules, so changing the pressure does not move this equilibrium.'], 'application'),
  concentration.choice('C36H-14', 'CO(g) + 2H₂(g) ⇌ CH₃OH(g) is at equilibrium. More hydrogen is pumped in. What happens?', ['Some methanol breaks down', 'More methanol forms', 'Nothing, because hydrogen is a reactant', 'All the hydrogen is used up'], 1, 'The system works against the change. What does it do with the extra hydrogen?', ['The system counteracts the extra hydrogen by using some of it up.', 'So the equilibrium moves to the right and more methanol forms, until equilibrium is reached again.']),

  pressure.choice('C36H-15', 'The diagram shows 2NO(g) + O₂(g) ⇌ 2NO₂(g) as molecules. The pressure is raised. Which way does the equilibrium move?', ['To the left', 'It does not move', 'To the right', 'To the left, then back again'], 2, 'Count the molecules of gas on each side of the equation.', ['The left has 2 + 1 = 3 molecules of gas. The right has 2.', 'Raising the pressure moves the equilibrium to the side with fewer molecules, so it moves to the right and more NO₂ forms.'], 'application', true, 'hequil-question-molecules'),
  temperature.choice('C36H-16', 'H₂(g) + CO₂(g) ⇌ H₂O(g) + CO(g). The forward reaction is endothermic. It is cooled. What happens to the amount of CO?', ['It goes up, because cooling moves the equilibrium right', 'It stays the same, because each side has 2 molecules', 'It goes up, because the forward reaction is endothermic', 'It goes down, because the equilibrium moves to the left'], 3, 'Cooling moves the equilibrium in the exothermic direction. Which direction is that?', ['The forward reaction is endothermic, so the backward reaction is exothermic.', 'Cooling moves the equilibrium in the exothermic direction, to the left. So there is less carbon monoxide. Equal numbers of gas molecules only matter for pressure.'], 'application', true),
  temperature.choice('C36H-17', 'The table shows the percentage of Y at equilibrium for X ⇌ Y. What does it tell you about the forward reaction?', ['It is exothermic', 'It is endothermic', 'It stops at 400 °C', 'It has fewer molecules of gas on the right'], 1, 'As the temperature rises, does the equilibrium move left or right?', ['As the temperature rises, the percentage of Y goes up. So heating moves the equilibrium to the right.', 'Heating moves the equilibrium in the endothermic direction, so the forward reaction is endothermic. The table says nothing about gas molecules, and the reaction has not stopped.'], 'dataInterpretation', true, 'hequil-question-data'),
  concentration.choice('C36H-18', 'CH₄(g) + H₂O(g) ⇌ CO(g) + 3H₂(g) is at equilibrium. Extra hydrogen is pumped in. What happens to the amount of methane?', ['It goes up, as the equilibrium moves to the left', 'It goes down, as more methane reacts', 'It stays the same, as no methane was added', 'It goes up, as the equilibrium moves to the right'], 0, 'Hydrogen is a product here. How does the system work against having extra of it?', ['Hydrogen is a product. The system counteracts the extra hydrogen by using some of it up in the backward reaction.', 'So the equilibrium moves to the left, and more methane and steam form.'], 'application', true),
  all.written('C36H-19', '2SO₂(g) + O₂(g) ⇌ 2SO₃(g). The forward reaction is exothermic. Explain how to change the pressure and temperature to get more SO₃.', 'Use Le Chatelier’s principle. For pressure, count the molecules of gas on each side. For temperature, find the exothermic direction.', 'Le Chatelier’s principle says the system responds to counteract a change. The left side has 2 + 1 = 3 molecules of gas and the right side has 2. Raising the pressure moves the equilibrium to the side with fewer molecules of gas, so it moves to the right and more SO₃ forms. The forward reaction is exothermic. Lowering the temperature moves the equilibrium in the exothermic direction, to give out heat, so it also moves to the right. So raise the pressure and lower the temperature.', ['Counts the molecules of gas: 3 on the left and 2 on the right.', 'Raising the pressure moves the equilibrium to the side with fewer molecules of gas, the right.', 'The forward reaction is exothermic, so lowering the temperature moves the equilibrium in the exothermic (forward) direction.', 'Both changes move the equilibrium to the right, so more SO₃ forms.', 'Links each change to the system counteracting it (Le Chatelier’s principle).'], ['Raising the temperature to get more SO₃.', 'Counting substances (2 on the left, 1 on the right) or atoms instead of molecules of gas.', 'Saying pressure has no effect because all the substances are gases.', 'Explaining only with how fast the reaction goes, not with the position of equilibrium.']),
]

export const lessonC36H: ScienceLesson = {
  id: 'C-EQM-036H-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Le Chatelier’s principle', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
