import type { TeachingFrame } from '../../teachingFrame'

// Le Chatelier's principle builds on reversible reactions and equilibrium: the sealed flask of A, B, C and D, the ⇌
// sign, "more products means going forwards", opposite energy changes, and heating ammonium chloride. Each teaching
// section keeps one drawing on screen and changes it frame by frame: the flask with a position-of-equilibrium track,
// the ammonia equation with its energy arrows and a thermometer, and the ammonia equation counted in gas molecules over
// a cylinder of gas. The last frame of each puts the steps together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const equilibriumFrames: Record<string, TeachingFrame[]> = {
  'C36H-02': [
    f('Position of equilibrium', 'The position of equilibrium is the mix of reactants and products once the amounts stop changing.', 'amounts steady → position of equilibrium', 'You met equilibrium when you learned about reversible reactions. In a closed system, the forward and backward reactions end up at the same rate. Then the amounts of reactants and products stop changing. The mix you have then is called the position of equilibrium.', 'hequil-push-position'),
    f('Right or left', 'If the equilibrium lies to the right, there are more products. If it lies to the left, there are more reactants.', 'products on the right, reactants on the left', 'In an equation, the reactants are on the left and the products are on the right. If there are more products than reactants, the equilibrium lies to the right. If there are more reactants than products, it lies to the left.', 'hequil-push-sides'),
    f('It depends on the conditions', 'The position of equilibrium depends on the temperature, the pressure and the concentrations.', 'temperature, pressure, concentration', 'The position of equilibrium is not fixed. It depends on the conditions. These are the temperature, the pressure and the concentrations of the reactants and products. Pressure only matters when the reaction has gases in it.', 'hequil-push-conditions'),
    f('The system pushes back', 'Le Chatelier’s principle: if you change the conditions, the system responds to counteract the change.', 'change → system counteracts', 'Imagine a reaction at equilibrium. Now change one of the conditions. The system responds by working against the change. To work against a change is to counteract it. This idea is called Le Chatelier’s principle. It lets you predict which way the equilibrium will move.', 'hequil-push-principle'),
    f('Put it together', 'Ask what changed, which direction works against it, then move the equilibrium that way.', 'what changed? → which way works against it? → moves that way', 'To predict what happens, use three steps. Step 1: what has changed? Step 2: which direction of the reaction would work against that change? Step 3: the equilibrium moves that way. Moving to the right makes more products. Moving to the left makes more reactants.', 'hequil-push-all'),
  ],
  'C36H-06': [
    f('Heat both ways', 'If the forward reaction gives out heat, the backward reaction takes in heat.', 'forward exothermic → backward endothermic', 'Ammonia is made from nitrogen and hydrogen: N₂ + 3H₂ ⇌ 2NH₃. The forward reaction gives out heat, so it is exothermic. The two directions have opposite energy changes. So the backward reaction takes in heat. It is endothermic.', 'hequil-temp-energy'),
    f('Turn the heat up', 'Raising the temperature moves the equilibrium in the endothermic direction.', 'hotter → endothermic direction → takes in heat', 'Now raise the temperature. The system works against this by taking in heat. So the equilibrium moves in the endothermic direction. For ammonia, the backward reaction is endothermic. So the equilibrium moves to the left, and there is less ammonia.', 'hequil-temp-up'),
    f('Turn the heat down', 'Lowering the temperature moves the equilibrium in the exothermic direction.', 'cooler → exothermic direction → gives out heat', 'Now lower the temperature instead. The system works against this by giving out heat. So the equilibrium moves in the exothermic direction. For ammonia, the forward reaction is exothermic. So the equilibrium moves to the right, and there is more ammonia.', 'hequil-temp-down'),
    f('Ammonium chloride explained', 'When the forward reaction is endothermic, heating moves the equilibrium to the right.', 'forward endothermic → heat → right', 'You saw that heating ammonium chloride makes more ammonia and hydrogen chloride. Now you can explain it. Breaking down ammonium chloride takes in heat, so the forward reaction is endothermic. Heating moves the equilibrium in the endothermic direction. So it moves to the right.', 'hequil-temp-nh4cl'),
    f('Put it together', 'Hotter: the endothermic direction. Cooler: the exothermic direction.', 'temperature up → endothermic; down → exothermic', 'First find which direction is exothermic and which is endothermic. A question will tell you about one direction. The other direction is the opposite. Raise the temperature and the equilibrium moves in the endothermic direction. Lower it and the equilibrium moves in the exothermic direction.', 'hequil-temp-all'),
  ],
  'C36H-10': [
    f('Count the gas molecules', 'Use the balanced equation to count the molecules of gas on each side.', 'N₂ + 3H₂: 4 molecules; 2NH₃: 2 molecules', 'Changing the pressure only affects equilibria with gases in them. The state symbol (g) shows a gas. Use the balanced equation to count the molecules of gas on each side. In N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the left has 1 + 3 = 4 molecules. The right has 2.', 'hequil-pc-count'),
    f('Squeeze the gases', 'Raising the pressure moves the equilibrium to the side with fewer molecules of gas.', 'pressure up → side with fewer gas molecules', 'Fewer gas molecules in the same space give a lower pressure. So if you raise the pressure, the system works against it by moving to the side with fewer molecules. For ammonia, that is the right, so more ammonia forms. Lowering the pressure does the opposite. The equilibrium moves to the side with more molecules of gas.', 'hequil-pc-pressure'),
    f('Add a reactant', 'Adding more of a reactant moves the equilibrium to the right, making more products.', 'more N₂ → some used up → more NH₃', 'Changing a concentration also upsets the equilibrium. Suppose you pump in more nitrogen. The system works against this by using some of it up. So the equilibrium moves to the right and more ammonia forms. Then equilibrium is reached again.', 'hequil-pc-add'),
    f('Take a product away', 'Removing a product moves the equilibrium to the right, so more product is made.', 'remove NH₃ → more NH₃ made', 'Now suppose you take some ammonia out as it forms. The system works against this by making more ammonia. More nitrogen and hydrogen react, so the equilibrium moves to the right. Adding a product, or removing a reactant, would move it to the left.', 'hequil-pc-remove'),
    f('Put it together', 'Pressure: count the gas molecules. Concentration: the system uses up what you add and replaces what you take away.', 'count → fewer side; add → use up; remove → replace', 'For pressure, count the molecules of gas on each side first. Raising the pressure moves the equilibrium to the side with fewer molecules. If both sides have the same number, pressure has no effect. For concentration, the system uses up some of what you add. It replaces some of what you take away.', 'hequil-pc-all'),
  ],
}
