// Variant B: independent lesson copy; shared rendering and assessment engine.
import type { ScienceLesson, ScienceState } from '../../../types'
import { author, biologySource, sampledRequirements } from '../../../lessonAuthoring'
import { divisionFrames as frames } from './teachingFrames'
const a = author('B-CELL-DIVISION', ['4.1.2.1', '4.1.2.2', '4.1.2.3'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])
export const divisionSections = [
  { id: 'B5-01', label: 'Chapter 1 · Chromosomes', detail: 'Cell, nucleus, DNA and genes' },
  { id: 'B5-05', label: 'Chapter 2 · Cell cycle', detail: 'Copy, separate and divide' },
  { id: 'B5-14', label: 'Chapter 3 · Stem cells', detail: 'Three sources and possible uses' },
  { id: 'B5-24', label: 'Independent checks', detail: 'Apply and evaluate' },
]
const states: ScienceState[] = [
  { ...a.choice('B5-01', 'Where are chromosomes normally found in an animal body cell?', ['In the nucleus', 'Outside the cell membrane', 'Inside a cell wall'], 0, 'Recall where genetic material is held.', ['The nucleus contains chromosomes made of DNA.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B5-02', 'Chromosomes, DNA and genes'),
  a.choice('B5-03', 'Which statement correctly links chromosomes, DNA and genes?', ['Each gene contains many separate cells', 'Each chromosome is made of DNA and carries many genes', 'DNA is a type of mitochondrion'], 1, 'What are chromosomes made of? Where are genes?', ['Each chromosome is made of a long DNA molecule.', 'Genes are sections of that DNA.']),
  a.choice('B5-04', 'A model body cell has 3 pairs of chromosomes. How many chromosomes does it have?', ['3', '9', '6'], 2, 'A pair contains two.', ['3 × 2 = 6 chromosomes.'], 'calculation'),
  t('B5-05', 'Prepare to divide'),
  a.choice('B5-06', 'Before division, what must happen to DNA?', ['It replicates, providing two copies of each chromosome', 'It all leaves the cell', 'It becomes a cell membrane'], 0, 'Both new cells need genetic information.', ['Replication copies the DNA.', 'Copying provides enough genetic information for each new cell to receive a complete set.']),
  t('B5-07', 'Mitosis'),
  a.choice('B5-08', 'What happens during mitosis?', ['Only the cell grows larger', 'One chromosome set moves to each end and the nucleus divides', 'Genes become mitochondria'], 1, 'Focus on genetic information and the nucleus.', ['The copied chromosomes separate into two complete sets, one at each end of the cell.', 'New nuclei form around the sets. The cytoplasm and membrane divide afterwards.']),
  t('B5-09', 'Make two daughter cells'),
  a.choice('B5-10', 'Our starting cell had 2 chromosomes. How many are in each daughter after the complete cycle?', ['1', '4', '2'], 2, 'Copying provides a full set for EACH cell.', ['Each daughter gets a complete chromosome set.', 'The original chromosome number is retained.'], 'understanding', false, 'cycle-question'),
  a.worked('B5-11', 'Follow the chromosome number through division', 'A model cell has 4 chromosomes. It copies its DNA. The copies separate, then the cell divides.', ['DNA copying gives two copies of each of the 4 chromosomes.', 'Mitosis separates the copies into two complete sets.', 'Each daughter cell has 4 chromosomes, not 8.'], 'cycle-worked'),
  t('B5-12', 'Why cells divide'),
  a.choice('B5-13', 'In a fully grown animal, division replaces worn-out skin cells. What is its role?', ['Replacement of cells in tissue', 'Making every adult grow forever', 'Making cells without DNA'], 0, 'Use the mature-animal context.', ['New cells replace old cells.', 'Mature-animal division mainly serves repair and replacement.']),
  t('B5-14', 'Embryonic stem cells'),
  a.choice('B5-15', 'Which example shows a stem cell becoming specialised, rather than making more stem cells?', ['One stem cell produces more stem cells', 'A stem cell becomes a specialised nerve cell', 'A cell only copies its DNA'], 1, 'Look for a new specialised function.', ['Differentiation produces a specialised type.', 'Self-renewal produces more stem cells.']),
  t('B5-16', 'Adult bone-marrow stem cells'),
  a.choice('B5-17', 'How do embryonic and adult bone-marrow stem cells compare?', ['All adult body cells can form any human cell type', 'Bone-marrow cells can only form plant roots', 'Embryonic stem cells can form more cell types than adult bone-marrow stem cells'], 2, 'Compare which cell types they can become, not their size.', ['Embryonic stem cells can differentiate into most types of human cell.', 'Adult bone-marrow stem cells have a more limited range, including blood cells.']),
  t('B5-18', 'Meristems and plant clones'),
  a.choice('B5-19', 'Why clone a rare plant from meristem stem cells?', ['To increase numbers and help protect the species from extinction', 'To guarantee every clone has a new different gene set', 'To stop any plant growth'], 0, 'A clone is genetically identical.', ['Cloning can increase the number of rare plants.', 'It does not create new genetic variation.']),
  t('B5-20', 'Medical uses, risks and ethics'),
  a.choice('B5-21', 'Which statement identifies a risk rather than an ethical objection?', ['A person objects to using embryos', 'Viral infection might be transferred', 'Damaged tissue may be replaced'], 1, 'Separate possible harm from a judgement about right and wrong.', ['Viral infection is a medical risk.', 'An objection to embryo use is an ethical or religious issue.']),
  a.choice('B5-22', 'Why are matching genes useful in therapeutic cloning?', ['They guarantee there can be no infection', 'They change all cells into plants', 'The patient’s body does not reject the matching stem cells'], 2, 'Focus on immune rejection, not all risks.', ['The embryo has the same genes as the patient.', 'The matching cells are not rejected. Other risks, such as viral infection, remain.']),
  a.choice('B5-23', 'In an example trial, 6 of 10 people improve after a proposed treatment and 4 do not. What can you conclude from these numbers?', ['Some people improved, but this does not show a guaranteed cure', 'The treatment cures everyone', 'There are no possible risks'], 0, 'Do the results show that everyone improved?', ['4 people did not improve.', 'This small example does not show that the treatment will work for everyone or that it is safe.'], 'dataInterpretation', false, 'trial'),
  a.choice('B5-24', 'Which sequence describes the three overall stages of a complete cell cycle?', ['Cytoplasm divides → DNA copies → nucleus separates', 'Growth and DNA copying → mitosis and nucleus division → cytoplasm/membrane division', 'Mitosis → all DNA disappears → growth'], 1, 'Both daughters need a copied complete set first.', ['The cell grows and copies its DNA before the chromosome copies separate during mitosis.', 'Cytoplasm and membrane then divide into two cells.'], 'recall', true),
  a.choice('B5-25', 'A model body cell has 8 chromosomes before DNA replication. After mitosis and cell division, each daughter has…', ['16 chromosomes', '4 chromosomes', '8 chromosomes'], 2, 'Count chromosomes in one daughter, not both combined.', ['A complete set goes to each daughter.', 'Each retains the starting number: 8.'], 'application', true),
  a.choice('B5-26', 'A mature animal produces new cells at the edge of a wound. What does mitosis help to do?', ['Repair tissue by producing new cells', 'Turn every cell into a stem cell', 'Remove all chromosomes from the tissue'], 0, 'Use the context of damaged tissue.', ['Division produces new cells.', 'They help repair the tissue, not directly mend a single damaged cell.'], 'application', true),
  a.choice('B5-27', 'Which stem-cell source can form plant cell types throughout a plant’s life?', ['Human bone marrow', 'Meristem tissue', 'A mature human nerve cell'], 1, 'Think about which source belongs to a plant and is found at its growing tips.', ['Meristems contain plant stem cells.', 'They retain differentiation ability throughout life.'], 'recall', true),
  a.choice('B5-28', 'A proposed treatment has possible benefits and a viral-infection risk. Which conclusion is justified?', ['Benefits mean risk need not be studied', 'The treatment is certain to cure paralysis', 'Evidence of benefit, risk and ethical issues should be considered'], 2, 'Evaluate more than one side of the claim.', ['Potential benefit does not establish certainty.', 'Risk and ethical issues still need consideration.'], 'application', true),
  a.choice('B5-29', 'In an example comparison, 12 of 20 people improve with treatment and 9 of 20 improve without it. Which conclusion is supported?', ['More improved with treatment, but this alone does not prove a reliable cure', 'Every treated person improved', 'The comparison shows infection is impossible'], 0, 'Use both groups and avoid a stronger claim than the data.', ['12 is greater than 9; 8 treated people did not improve.', 'The treatment group had more improvements, but this small comparison alone does not establish a reliable cure or show that treatment is safe.'], 'dataInterpretation', true),
  a.choice('B5-31', 'A model body cell has 9 chromosome pairs. How many chromosomes are in that cell?', ['9', '18', '81'], 1, 'Each pair has two chromosomes.', ['9 pairs × 2 = 18 chromosomes in one body cell.'], 'calculation', true),
  a.written('B5-30', 'Embryonic stem cells could replace damaged nerve cells. Evaluate this idea: give a possible benefit, a medical risk and an ethical issue.', 'How could the cells help? What harm could occur? Why might someone object to using embryos? Weigh these points; do not claim a guaranteed cure.', 'Embryonic stem cells could become nerve cells and replace damaged cells. This might help paralysis. They could pass on a viral infection. Some people object to using embryos for ethical or religious reasons. These concerns must be weighed against possible benefits and risks. A cure is not guaranteed.', ['Potential differentiation into replacement nerve cells linked to helping damaged tissue/paralysis.', 'Medical risk: transfer of viral infection.', 'Ethical/religious objection to embryo use, considered alongside possible benefit.'], ['Guaranteed cure.', 'All adult specialised cells can form every type.', 'An ethical objection is described as a viral infection.']),
]
export const lesson5: ScienceLesson = { id: 'B-CELL-005-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology', title: 'Chromosomes, mitosis and stem cells', prerequisites: ['B-SPECIALISATION'], reviewStatus: 'draftNeedsTeacherReview', sources: [biologySource], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states) }
