import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { moleFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.3.2.1 Moles (HT): the Avogadro constant, the mass of one mole, number of moles = mass ÷ Mᵣ; 5.3.2.2 Amounts of substances in equations (HT); 5.3.2.3 Using moles to balance equations (HT); 5.3.2.4 Limiting reactants (HT), as on the supplied revision pages' }
const skill = 'C-MOLES'
const mole = author(skill, ['5.3.2.1'], ['aqa-chemistry'])
const equation = author(skill, ['5.3.2.2', '5.3.2.3'], ['aqa-chemistry'])
const limiting = author(skill, ['5.3.2.4'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const moleSections = [
  { id: 'C20H-01', label: 'Start here', detail: 'The Mᵣ of water' },
  { id: 'C20H-02', label: 'The mole', detail: 'Avogadro’s constant, moles and mass' },
  { id: 'C20H-08', label: 'Moles in equations', detail: 'Mole ratios and balancing from masses' },
  { id: 'C20H-13', label: 'Limiting reactants', detail: 'Used up, in excess, and the mass of product' },
  { id: 'C20H-17', label: 'On your own', detail: 'An equation, a mistake and some data' },
]

const states: ScienceState[] = [
  { ...mole.choice('C20H-01', 'Water is H₂O. Using H = 1 and O = 16, what is its relative formula mass, Mᵣ?', ['17', '18', '33'], 1, 'How many hydrogen atoms are in one H₂O?', ['H₂O has 2 hydrogen atoms and 1 oxygen atom.', 'So Mᵣ = (2 × 1) + 16 = 18. You will use Mᵣ values like this all through this topic.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(mole, 'C20H-02', 'The mole'),
  mole.worked('C20H-03', 'Work out the number of moles in a mass', 'How many moles are there in 60 g of magnesium oxide, MgO? Aᵣ: Mg = 24, O = 16.', ['Work out the Mᵣ of MgO: 24 + 16 = 40.', 'Write the formula: number of moles = mass ÷ Mᵣ.', 'Put in the numbers: 60 ÷ 40 = 1.5.', 'So 60 g of magnesium oxide is 1.5 mol.'], 'hmole-worked-moles'),
  mole.worked('C20H-04', 'Work out the mass of a number of moles', 'What is the mass of 0.25 mol of calcium carbonate, CaCO₃? Aᵣ: Ca = 40, C = 12, O = 16.', ['Work out the Mᵣ of CaCO₃: 40 + 12 + (3 × 16) = 100.', 'Rearrange the formula: mass = number of moles × Mᵣ.', 'Put in the numbers: 0.25 × 100 = 25.', 'So 0.25 mol of calcium carbonate has a mass of 25 g.'], 'hmole-worked-mass'),
  mole.choice('C20H-05', 'How many moles are in 34 g of ammonia, NH₃? (N = 14, H = 1)', ['0.5 mol', '578 mol', '51 mol', '2 mol'], 3, 'Work out the Mᵣ of NH₃ first. Then divide the mass by it.', ['Mᵣ of NH₃ = 14 + (3 × 1) = 17.', 'Number of moles = mass ÷ Mᵣ = 34 ÷ 17 = 2 mol.'], 'calculation'),
  mole.choice('C20H-06', 'What is the mass of 0.5 mol of sodium hydroxide, NaOH? (Na = 23, O = 16, H = 1)', ['20 g', '80 g', '0.0125 g', '40 g'], 0, 'Find the Mᵣ, then use the rearranged formula.', ['Mᵣ of NaOH = 23 + 16 + 1 = 40.', 'Mass = number of moles × Mᵣ = 0.5 × 40 = 20 g.'], 'calculation'),
  mole.choice('C20H-07', 'Which holds the same number of atoms as 24 g of magnesium? (Mg = 24, C = 12, Ca = 40)', ['24 g of carbon', '24 g of calcium', '48 g of magnesium', '12 g of carbon'], 3, 'Work out how many moles each one is.', ['24 g of magnesium is 24 ÷ 24 = 1 mol, so it holds 6.02 × 10²³ atoms.', '12 g of carbon is 12 ÷ 12 = 1 mol, so it holds the same number of atoms. 24 g of carbon is 2 mol, 24 g of calcium is 0.6 mol and 48 g of magnesium is 2 mol.'], 'application'),

  t(equation, 'C20H-08', 'Moles in equations'),
  equation.worked('C20H-09', 'Balance an equation from reacting masses', '11.2 g of iron reacts with 21.3 g of chlorine, Cl₂, to make 32.5 g of iron chloride, FeCl₃. Mᵣ: Fe = 56, Cl₂ = 71, FeCl₃ = 162.5. Write the balanced equation.', ['Moles: Fe = 11.2 ÷ 56 = 0.2. Cl₂ = 21.3 ÷ 71 = 0.3. FeCl₃ = 32.5 ÷ 162.5 = 0.2.', 'Divide by the smallest, 0.2: Fe = 1, Cl₂ = 1.5, FeCl₃ = 1.', '1.5 is not a whole number, so multiply them all by 2: 2, 3 and 2.', 'Write the numbers in front of the formulas: 2Fe + 3Cl₂ → 2FeCl₃.'], 'hmole-worked-balance'),
  equation.choice('C20H-10', 'In N₂ + 3H₂ → 2NH₃, how many moles of hydrogen react with 2 moles of nitrogen?', ['3 mol', '2 mol', '6 mol', '1.5 mol'], 2, 'What does the equation say reacts with 1 mole of N₂?', ['The big numbers show that 1 mol of N₂ reacts with 3 mol of H₂.', 'So 2 mol of N₂ reacts with 2 × 3 = 6 mol of H₂.']),
  equation.choice('C20H-11', '5.4 g of aluminium reacts with 21.3 g of chlorine to make 26.7 g of aluminium chloride. Which equation is correct?', ['Al + Cl₂ → AlCl₃', '2Al + 3Cl₂ → 2AlCl₃', 'Al + 1.5Cl₂ → AlCl₃', '2Al + Cl₂ → 2AlCl₃'], 1, 'Use the Mᵣ values in the table to find the moles. Then follow the four steps.', ['Moles: Al = 5.4 ÷ 27 = 0.2, Cl₂ = 21.3 ÷ 71 = 0.3, AlCl₃ = 26.7 ÷ 133.5 = 0.2.', 'Divide by the smallest, 0.2: 1, 1.5 and 1. Multiply them all by 2 to make whole numbers: 2, 3 and 2.'], 'calculation', false, 'hmole-question-al'),
  equation.choice('C20H-12', 'After dividing by the smallest, a student gets 1, 2.5 and 2. What should they do next?', ['Multiply every number by 2', 'Round 2.5 up to 3', 'Leave out the substance with 2.5', 'Divide every number by 2.5'], 0, 'The big numbers in an equation must be whole numbers, in the same ratio.', ['2.5 is not a whole number, but the numbers in an equation must be whole.', 'Multiplying every number by 2 keeps the same ratio and gives 2, 5 and 4. Rounding would change the ratio.']),

  t(limiting, 'C20H-13', 'Limiting reactants'),
  limiting.worked('C20H-14', 'Work out the mass of product from the limiting reactant', '8.0 g of oxygen reacts with excess hydrogen: 2H₂ + O₂ → 2H₂O. What mass of water is made? Aᵣ: H = 1, O = 16.', ['The balanced equation is 2H₂ + O₂ → 2H₂O. Hydrogen is in excess, so oxygen is the limiting reactant.', 'Mᵣ of O₂ = 2 × 16 = 32. Mᵣ of H₂O = (2 × 1) + 16 = 18.', 'Moles of O₂ = 8.0 ÷ 32 = 0.25 mol.', 'The equation shows 1 mol of O₂ makes 2 mol of H₂O. So 0.25 mol of O₂ makes 0.5 mol of H₂O.', 'Mass of water = 0.5 × 18 = 9.0 g.'], 'hmole-worked-water'),
  limiting.choice('C20H-15', 'The diagram shows hydrogen and chlorine before and after they react. Which is the limiting reactant?', ['Chlorine, Cl₂', 'Hydrogen, H₂', 'Hydrogen chloride, HCl', 'Neither, because both are used up'], 0, 'Which reactant is missing from the “after” box?', ['After the reaction there are no chlorine molecules left, but 3 hydrogen molecules are left over.', 'Chlorine is used up, so it is the limiting reactant. Hydrogen is in excess. Hydrogen chloride is the product.'], 'understanding', false, 'hmole-question-limiting'),
  limiting.choice('C20H-16', 'Use the card. What mass of ammonia, NH₃, forms from 5.6 g of nitrogen and excess hydrogen?', ['3.4 g', '6.8 g', '0.4 g', '11.2 g'], 1, 'Find the moles of N₂. How many moles of NH₃ does 1 mol of N₂ make?', ['Mᵣ of N₂ = 2 × 14 = 28, so moles of N₂ = 5.6 ÷ 28 = 0.2 mol.', 'The equation shows 1 mol of N₂ makes 2 mol of NH₃, so 0.2 mol makes 0.4 mol.', 'Mᵣ of NH₃ = 14 + 3 = 17, so mass = 0.4 × 17 = 6.8 g.'], 'calculation', false, 'hmole-question-nh3'),

  equation.choice('C20H-17', 'The table shows the masses that react when methane burns. Which balanced equation do they give?', ['CH₄ + O₂ → CO₂ + H₂O', '2CH₄ + O₂ → 2CO₂ + H₂O', 'CH₄ + 2O₂ → CO₂ + 2H₂O', 'CH₄ + 4O₂ → CO₂ + 4H₂O'], 2, 'Find the moles of each substance, then divide by the smallest.', ['Moles: CH₄ = 1.6 ÷ 16 = 0.1, O₂ = 6.4 ÷ 32 = 0.2, CO₂ = 4.4 ÷ 44 = 0.1, H₂O = 3.6 ÷ 18 = 0.2.', 'Divide by the smallest, 0.1: 1, 2, 1 and 2. So the equation is CH₄ + 2O₂ → CO₂ + 2H₂O.'], 'calculation', true, 'hmole-data-methane'),
  limiting.choice('C20H-18', 'A student worked out the mass of sodium oxide made from 4.6 g of sodium. Which numbered line has the mistake?', ['Line 1', 'Line 2', 'Line 3', 'Line 4'], 2, 'In the equation, how many Na₂O does 4Na make?', ['Line 3 doubles the moles. The equation shows 4 mol of Na makes 2 mol of Na₂O, so halve: 0.2 ÷ 2 = 0.1 mol.', 'So the mass of Na₂O is 0.1 × 62 = 6.2 g, not 24.8 g.'], 'application', true, 'hmole-question-error'),
  limiting.choice('C20H-19', 'A student burned different masses of magnesium in excess oxygen. Which conclusion do these data support?', ['Oxygen was the limiting reactant in these runs', 'The mass of product did not depend on the magnesium', 'Doubling the magnesium always doubles the product, however much is used', 'In these runs, doubling the magnesium doubled the magnesium oxide'], 3, 'Compare the runs. Is the claim about these runs, or about any amount?', ['Each time the mass of magnesium doubled, the mass of magnesium oxide doubled: 1.0 g, 2.0 g, then 4.0 g.', 'Magnesium was the limiting reactant, because the oxygen was in excess. Three runs cannot show what happens with any amount: with enough magnesium, the oxygen could run out.'], 'dataInterpretation', true, 'hmole-data-magnesium'),
  limiting.written('C20H-20', '4.8 g of Mg burns in excess oxygen (2Mg + O₂ → 2MgO). Which reactant limits it? Find the mass of MgO.', 'Aᵣ: Mg = 24, O = 16. Which reactant runs out? Then find its moles, use the equation ratio and multiply by the Mᵣ.', 'Oxygen is in excess, so magnesium is used up: it is the limiting reactant. Moles of magnesium = 4.8 ÷ 24 = 0.2 mol. The equation shows 2 mol of Mg makes 2 mol of MgO, so 0.2 mol of Mg makes 0.2 mol of MgO. The Mᵣ of MgO is 24 + 16 = 40, so the mass of MgO = 0.2 × 40 = 8.0 g.', ['Magnesium is the limiting reactant, because the oxygen is in excess and the magnesium gets used up.', 'Moles of magnesium = 4.8 ÷ 24 = 0.2 mol.', 'The ratio of Mg to MgO is 2 : 2 (1 : 1), so 0.2 mol of MgO forms.', 'Mᵣ of MgO = 40, so mass = 0.2 × 40 = 8.0 g.'], ['Saying oxygen is the limiting reactant.', 'Doubling or halving the moles because of the big 2s, for example 0.4 mol or 0.1 mol of MgO.', 'Giving 8.0 g with no working.']),
]

export const lessonC20H: ScienceLesson = {
  id: 'C-MOL-020H-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Moles', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
