import type { TeachingFrame } from '../../teachingFrame'

// Moles are built on relative formula mass and balanced equations, which the student already has. Each teaching section
// keeps one drawing on screen and changes it frame by frame: a heap of magnesium on a balance for the mole, one equation
// table (2Mg + O₂ → 2MgO) read forwards then worked backwards, and two boxes of molecules (H₂ + Cl₂ → 2HCl) for limiting
// reactants. The last frame of each puts the steps together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const moleFrames: Record<string, TeachingFrame[]> = {
  'C20H-02': [
    f('A very big number', 'Chemists count atoms in huge groups of 6.02 × 10²³.', 'too small to count → count in huge groups', 'Atoms are far too small to count one by one. So chemists count them in huge groups, a bit like counting eggs in dozens. One group is 602 000 000 000 000 000 000 000 particles. We write this as 6.02 × 10²³. This number is called the Avogadro constant.', 'hmole-mole-avogadro'),
    f('One mole', 'One mole of a substance is 6.02 × 10²³ of its particles.', 'one mole → 6.02 × 10²³ particles', 'An amount of a substance that holds 6.02 × 10²³ particles is called one mole. The particles can be atoms, molecules, ions or electrons. So one mole of magnesium is 6.02 × 10²³ magnesium atoms. The short way to write mole is mol.', 'hmole-mole-one'),
    f('The mass of one mole', 'One mole has a mass in grams equal to its Aᵣ or Mᵣ.', 'Aᵣ or Mᵣ → the same number in grams', 'The Aᵣ of magnesium is 24, so one mole of magnesium has a mass of 24 g. For a compound, use its Mᵣ. Water, H₂O, has an Mᵣ of 18, so one mole of water is 18 g. The masses are different, but both hold 6.02 × 10²³ particles.', 'hmole-mole-mass'),
    f('Finding the number of moles', 'Number of moles = mass in g ÷ Mᵣ.', 'mass ÷ Mᵣ → moles', 'To find how many moles you have, divide the mass in grams by the Mᵣ. For an element, use its Aᵣ instead. For example, 48 g of magnesium is 48 ÷ 24 = 2 mol. Twice the mass of one mole means two moles.', 'hmole-mole-formula'),
    f('Put it together', 'Rearrange the formula to find a mass: mass = moles × Mᵣ.', 'cover what you want → the rest is the sum', 'You can rearrange the formula to find a mass: mass = number of moles × Mᵣ. A formula triangle helps. Put mass at the top, and moles and Mᵣ at the bottom. Cover the one you want to find, and what is left shows the sum.', 'hmole-mole-triangle'),
  ],
  'C20H-08': [
    f('Big numbers count particles', 'The big numbers in a balanced equation count particles.', '2Mg + O₂ → 2MgO → 2 : 1 : 2', 'You met balanced equations when you learned about conservation of mass. In 2Mg + O₂ → 2MgO, the big numbers count particles. Two magnesium atoms react with one oxygen molecule. They make two lots of magnesium oxide.', 'hmole-eq-particles'),
    f('Big numbers count moles', 'The big numbers also give the numbers of moles that react.', 'same ratio → 2 mol : 1 mol : 2 mol', 'Now multiply every particle by 6.02 × 10²³. The ratio stays 2 : 1 : 2. So 2 moles of magnesium react with 1 mole of oxygen to make 2 moles of magnesium oxide. The big numbers tell you the numbers of moles too.', 'hmole-eq-moles'),
    f('Working backwards', 'Divide each reacting mass by its Mᵣ to find the moles.', 'mass ÷ Mᵣ → moles of each substance', 'You can also work backwards, from masses to the equation. Suppose 4.8 g of magnesium reacts with 3.2 g of oxygen to make 8.0 g of magnesium oxide. First, divide each mass by its Mᵣ. Magnesium: 4.8 ÷ 24 = 0.2 mol. Oxygen: 3.2 ÷ 32 = 0.1 mol. Magnesium oxide: 8.0 ÷ 40 = 0.2 mol.', 'hmole-eq-masses'),
    f('Divide by the smallest', 'Divide every number of moles by the smallest one.', '0.2 : 0.1 : 0.2 → ÷ 0.1 → 2 : 1 : 2', 'Next, divide each number of moles by the smallest one. Here the smallest is 0.1. So 0.2 ÷ 0.1 = 2, and 0.1 ÷ 0.1 = 1. This gives 2, 1 and 2, which are the big numbers: 2Mg + O₂ → 2MgO.', 'hmole-eq-divide'),
    f('Put it together', 'Four steps turn reacting masses into a balanced equation.', 'moles → ÷ smallest → whole numbers → equation', 'Step 1: divide each mass by its Mᵣ to get moles. Step 2: divide them all by the smallest number of moles. Step 3: if any answer is not a whole number, multiply them all by the same number. Step 4: write the numbers in front of the formulas.', 'hmole-eq-steps'),
  ],
  'C20H-13': [
    f('A reaction stops', 'A reaction stops when one of the reactants is used up.', 'one reactant runs out → the reaction stops', 'Hydrogen reacts with chlorine to make hydrogen chloride: H₂ + Cl₂ → 2HCl. Here there are 2 hydrogen molecules and 5 chlorine molecules. Each hydrogen molecule reacts with one chlorine molecule. Once both hydrogen molecules have reacted, nothing more can happen. The reaction stops.', 'hmole-limit-used'),
    f('The limiting reactant', 'The reactant that is used up is the limiting reactant.', 'used up → limits the product', 'The reactant that gets used up is called the limiting reactant. It limits how much product can form. Here it is hydrogen. With only 2 hydrogen molecules, only 4 hydrogen chloride molecules can form.', 'hmole-limit-limiting'),
    f('In excess', 'A reactant that is left over is in excess.', 'left over → in excess', 'Three chlorine molecules are left over at the end. A reactant that is left over is said to be in excess. Chemists often add one reactant in excess. This makes sure the other reactant gets used up completely.', 'hmole-limit-excess'),
    f('Double it', 'Double the limiting reactant and you double the product.', '2 H₂ → 4 HCl, so 4 H₂ → 8 HCl', 'Now start with 4 hydrogen molecules and the same 5 chlorine molecules. Hydrogen is still the limiting reactant. This time 8 hydrogen chloride molecules form, twice as many as before. The amount of product is directly proportional to the amount of limiting reactant.', 'hmole-limit-double'),
    f('Put it together', 'Use the moles of the limiting reactant to find the mass of product.', 'limiting reactant → moles → ratio → mass', 'You can use this idea to find the mass of product a reaction makes. Write the balanced equation and work out the Mᵣ values you need. Find the moles of the limiting reactant. Use the equation ratio to find the moles of product. Then mass = moles × Mᵣ.', 'hmole-limit-steps'),
  ],
}
