import { numeric, remainder, select, working, type Diagram } from '../../written-methods/model'
import { author } from '../../written-methods/tutor/content'
import { divisionWorking, longDivisionWorking, methodWorking } from '../../written-methods/tutor/methodWorking'
import type { TutorMethodLesson } from '../../written-methods/tutor/model'

const { add, finish } = author(5)
const layout = 'long-division-layout', regroup = 'long-division-regrouping', leftover = 'long-division-remainders', check = 'long-division-check'
const twoDigits = 'long-division-two-digit'
const bus = (dividend: string, divisor: number, quotient?: string, active?: number, carry?: { index: number; value: number }): Diagram => ({ kind: 'division', dividend, divisor, quotient, active, carry })
const diagram = (d: Diagram) => ({ kind: 'diagram' as const, diagram: d })
const text = (...lines: string[]) => ({ kind: 'text' as const, lines })
const hint = 'Start on the left. Divide the current amount, write the quotient digit in its place, and exchange the remainder into the next place before including the next digit.'

add(layout, 'Divide from the largest place', 'N4.1 introduction; method terminology clarification', methodWorking(divisionWorking(375, 5)), undefined, undefined, undefined, 'Use the bus-stop layout to divide one place at a time. With a one-digit divisor, this compact written method is also called short division. The dividend is under the bracket, the divisor is outside, and the quotient goes above. Work from left to right.')
const videoState = add(layout, 'Work out 375 ÷ 5 using the bus-stop method.', 'N4.1 Q1; video 23.52.49', methodWorking(divisionWorking(375, 5)))
videoState.video = {
  id: 'lesson5-division', src: '/media/lesson-5/division.mp4', poster: '/media/lesson-5/division.jpg',
  title: 'Bus-stop division: 375 ÷ 5', durationSeconds: 36.7, sourceFile: 'WhatsApp Video 2026-09-17 at 23.52.49.mp4',
  textAlternative: ['3 hundreds divided by 5 gives 0 hundreds, with 3 hundreds left.', 'Exchange into tens: 30 + 7 = 37 tens; divide by 5 to get 7 tens, with 2 tens left.', 'Exchange into units: 20 + 5 = 25 units; divide by 5 to get 5 units and remainder 0.', 'The quotient is 75.'],
}
add(layout, 'Work out 84 ÷ 4 using the bus-stop method.', 'N4.1 Q2', diagram(bus('84', 4)), numeric(21), working('21', ['Divide the tens.', '8 tens ÷ 4 = 2 tens. Write 2 above the tens.'], ['Divide the units.', '4 units ÷ 4 = 1 unit. Write 1 above the units.'], ['Check the quotient.', '21 × 4 = 84.']), 'Divide the 8 tens first and then the 4 units. Each divides exactly, so there is no remainder to carry.')
add(regroup, 'Regroup what is left before using the next digit', 'N4.1 Q3 preparation; N4.1 Q1 place-value clarification', text('Remainder in hundreds → exchange into tens', 'Remainder in tens → exchange into units'), undefined, undefined, undefined, 'A carried remainder keeps its value. Multiply it by ten when moving to the next smaller place, then add the next digit. Carry the remainder, rather than the quotient digit.')
add(regroup, 'Work out 138 ÷ 6 using the bus-stop method.', 'N4.1 Q3', diagram(bus('138', 6)), numeric(23), working('23', ['Divide the hundreds and regroup.', '1 hundred ÷ 6 gives 0 hundreds, remainder 1 hundred. Exchange for 10 tens; 10 + 3 = 13 tens.'], ['Divide the tens and regroup.', '13 tens ÷ 6 gives 2 tens, remainder 1 ten. Exchange for 10 units; 10 + 8 = 18 units.'], ['Divide the units.', '18 units ÷ 6 = 3 units, remainder 0. The quotient is 23; no leading zero is needed.'], ['Check the quotient.', '23 × 6 = 138.']), hint)
add(leftover, 'A baker has 250 buns. She packs them into boxes of 8. Use the bus-stop method to find how many full boxes she can pack and how many buns are left over.', 'N4.1 Q4a', diagram(bus('250', 8)), remainder(250, 8), working('31 full boxes, with 2 buns left over', ['Divide the hundreds and regroup.', '2 hundreds ÷ 8 gives 0 hundreds, remainder 2 hundreds. 20 + 5 = 25 tens.'], ['Divide the tens and regroup.', '25 tens ÷ 8 gives 3 tens, remainder 1 ten. 10 + 0 = 10 units.'], ['Divide the units.', '10 units ÷ 8 gives 1 unit, remainder 2. The quotient is 31 and the remainder is 2.'], ['Interpret and check.', '31 × 8 + 2 = 250. The remainder 2 is less than 8, so 31 boxes are full and 2 buns remain.']), 'Divide 250 by 8. Give the whole-number quotient as the full boxes and the final remainder as the buns left over. A valid remainder is smaller than 8.')
add(leftover, 'The baker wants to pack every bun into a box, with none left over. How many boxes does she need in total?', 'N4.1 Q4b', text('250 buns', '8 buns in each full box'), numeric(32), working('32 boxes', ['Use the result from part a.', '250 ÷ 8 = 31 remainder 2, so 31 boxes are full and 2 buns remain.'], ['Give the remaining buns a box.', 'The 2 buns need one more box: 31 + 1 = 32. The last box does not have to be full.']), 'Full boxes and all boxes are different totals. If buns remain after filling whole boxes, they still need one more box.')
add(check, 'Work out 624 ÷ 8 using the bus-stop method.', 'N4.1 Q5a', diagram(bus('624', 8)), numeric(78), working('78', ['Divide the hundreds and regroup.', '6 hundreds ÷ 8 gives 0 hundreds, remainder 6 hundreds. 60 + 2 = 62 tens.'], ['Divide the tens and regroup.', '62 tens ÷ 8 gives 7 tens, remainder 6 tens. 60 + 4 = 64 units.'], ['Divide the units.', '64 units ÷ 8 = 8 units, remainder 0. The quotient is 78.'], ['Check the quotient.', '78 × 8 = 624.']), hint)
add(check, 'What is the remainder at the very last step of your working for 624 ÷ 8?', 'N4.1 Q5b', diagram(bus('624', 8)), numeric(0), working('0', ['Use the last partial dividend from part a.', 'The carried 6 tens and next 4 units make 64 units.'], ['Divide the units.', '64 ÷ 8 = 8 exactly. 64 - 8 × 8 = 0, so the final remainder is 0.']), 'Use the final units calculation. Earlier carried remainders do not have to equal the final remainder.')
add(check, 'Sam says: “If a division has no remainder at the end, there must have been no carries during the bus-stop method.” Is Sam correct? Give a reason using 624 ÷ 8.', 'N4.1 Q5c (reason and counterexample choices)', text('624 ÷ 8 = 78'), select([
  'No. In 624 ÷ 8, a remainder of 6 hundreds and later 6 tens were carried, but the final remainder was 0.',
  'Yes. A final remainder of 0 means every earlier division was exact.',
  'No. The last remainder in 624 ÷ 8 was 6, so it was not exact.',
], 0), working('No. Carries can occur even when the final remainder is 0.', ['Identify the first carried remainder.', '6 hundreds divided by 8 leaves 6 hundreds, which become 60 tens before including the next 2 tens.'], ['Identify the next carried remainder.', '62 tens divided by 8 gives 7 tens with 6 tens left. These become 60 units before including the next 4 units.'], ['Check the final step.', '64 units ÷ 8 = 8 units, remainder 0. Thus 624 ÷ 8 is a counterexample to Sam’s claim.']), 'A claim about every division can be disproved by one counterexample. Compare the remainders carried in the middle of 624 ÷ 8 with the final remainder.')
add(twoDigits, 'Work through 235 ÷ 17 using long division.', 'User-added worked example: 235 ÷ 17', methodWorking(longDivisionWorking(235, 17)), undefined, undefined, undefined, 'For a two-digit divisor, write the subtraction underneath. Choose the first group of digits that is large enough, then divide, multiply, subtract and bring down the next digit. Finish with a remainder smaller than 17.')
add(twoDigits, 'Work through 289 ÷ 29 using long division.', 'User-added worked example: 289 ÷ 29', methodWorking(longDivisionWorking(289, 29)), undefined, undefined, undefined, '29 does not fit into 2 or 28, so use all three digits: 289. Compare multiples of 29, write the quotient above the units, then multiply and subtract to find the remainder.')
add('mixed', 'Divide, regroup and interpret the remainder', 'N4.1 consolidation', text('Work from left to right', 'Remainder × 10 + next digit', 'Two-digit divisors: divide, multiply, subtract, bring down', 'Quotient × divisor + remainder = dividend'), undefined, undefined, undefined, 'Use bus-stop division for the supplied one-digit examples and long division with written subtraction for the two-digit examples. The final remainder must be smaller than the divisor. Use the context to decide whether to count full groups or add a group for leftovers.')
const states = finish({ videoFirst: true })
const answerWorking = {
  'N4.1 Q2': methodWorking(divisionWorking(84, 4)), 'N4.1 Q3': methodWorking(divisionWorking(138, 6)),
  'N4.1 Q4a': methodWorking(divisionWorking(250, 8)), 'N4.1 Q4b': methodWorking(divisionWorking(250, 8)),
  'N4.1 Q5a': methodWorking(divisionWorking(624, 8)), 'N4.1 Q5b': methodWorking(divisionWorking(624, 8)),
  'N4.1 Q5c': methodWorking(divisionWorking(624, 8)),
}
states.forEach(state => { state.working = answerWorking[state.sourceRef.split(' (')[0]] })
export const tutorLongDivisionLesson: TutorMethodLesson = { id: 'L005', number: 5, title: 'Long division', level: 'GCSE Foundation', goal: 'Use bus-stop and long division, regroup or bring down digits, and interpret quotients and remainders.', labels: { [layout]: 'Bus-stop division', [regroup]: 'Regrouping', [leftover]: 'Remainders in context', [check]: 'Checking carries', [twoDigits]: 'Two-digit divisors', mixed: 'Review' }, states }
