import type { TeachingFrame } from '../../teachingFrame'

// Follow one compound, water, to learn what a compound is; then learn to read formulas; then write one reaction
// (hydrogen + chlorine → hydrogen chloride) in words and symbols; and only then balance that same equation.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const compoundFrames: Record<string, TeachingFrame[]> = {
  'C2-02': [
    f('New substances', 'A chemical reaction makes at least one new substance.', 'reaction → new substance, often an energy change', 'Hydrogen and oxygen are both gases. When they react, they make water, which is a completely new substance. The mixture also gets hot, so there is an energy change. A change that makes at least one new substance is called a chemical reaction.', 'cmpd-compound-new'),
    f('Compounds', 'Atoms of different elements can join together.', 'atoms of two or more elements joined → compound', 'Look closely at one particle of water. It has 2 hydrogen atoms and 1 oxygen atom, joined together. A substance made of atoms of two or more different elements, chemically joined, is called a compound. So water is a compound, but hydrogen and oxygen are elements.', 'cmpd-compound-compound'),
    f('Fixed proportions', 'A compound always has the same amounts of each element.', 'water: always 2 H for every 1 O', 'Every water particle has 2 hydrogen atoms for every 1 oxygen atom. Water from a tap, a river or a cloud is just the same. The amounts of each element in a compound never change. We say the elements are in fixed proportions.', 'cmpd-compound-fixed'),
    f('Chemical bonds', 'The atoms in a compound are held together.', 'atoms held together → chemical bonds', 'The atoms in a compound do not just sit side by side. Strong forces hold them together. These forces are called chemical bonds. In the drawings, each bond is a short line joining two atoms.', 'cmpd-compound-bonds'),
    f('Splitting a compound', 'Only a chemical reaction can split a compound into its elements.', 'compound → elements only by a reaction', 'Boiling water only turns it into steam, which is still water. Filtering it does not split it either. The chemical bonds hold the atoms together. So the only way to separate a compound into its elements is by another chemical reaction.', 'cmpd-compound-split'),
    f('Put it together', 'A compound: two or more elements, fixed proportions, held by bonds.', 'reaction → compound → bonds → reaction to split', 'Water is a compound made in a chemical reaction. It contains hydrogen and oxygen atoms in fixed proportions, 2 to 1. Chemical bonds hold its atoms together. So only another chemical reaction can split it back into hydrogen and oxygen.', 'cmpd-compound-all'),
  ],
  'C2-05': [
    f('A formula', 'Symbols show which elements are in a compound.', 'symbols → which elements', 'Carbon dioxide is a compound of carbon and oxygen. We can write it as CO₂. The symbols C and O show which elements it contains. A short way of writing a substance using symbols is called its formula.', 'cmpd-formula-symbols'),
    f('Small numbers', 'A small number counts the atoms of the element just before it.', 'small number after a symbol → how many of that atom', 'In CO₂, the small 2 comes after the O. It means there are 2 oxygen atoms. There is no number after the C, so there is just 1 carbon atom. A small number only counts the symbol just before it.', 'cmpd-formula-number'),
    f('Elements in pairs', 'Some elements are made of pairs of joined atoms.', 'O₂, H₂, N₂, Cl₂ → pairs of the same atom', 'Oxygen gas is made of pairs of oxygen atoms joined together, so we write it as O₂. A particle made of atoms joined together is called a molecule. Hydrogen (H₂), nitrogen (N₂) and chlorine (Cl₂) also go around in pairs. They are still elements, because each molecule has only one kind of atom.', 'cmpd-formula-pairs'),
    f('Brackets', 'A number after a bracket multiplies everything inside it.', 'Mg(OH)₂ → 2 × everything in the bracket', 'Magnesium hydroxide is written Mg(OH)₂. The small 2 after the bracket doubles everything inside it. So there are 2 oxygen atoms and 2 hydrogen atoms. Mg is outside the bracket, so there is 1 magnesium atom. That makes 5 atoms altogether.', 'cmpd-formula-brackets'),
    f('Formulas worth knowing', 'A few formulas come up again and again.', 'H₂O, CO₂, NaCl, HCl, NH₃, CH₄', 'Water is H₂O and carbon dioxide is CO₂. Sodium chloride, or table salt, is NaCl. Hydrogen chloride is HCl and ammonia is NH₃. Methane, the gas used in cookers, is CH₄. You can count the atoms in each one using the small numbers.', 'cmpd-formula-common'),
  ],
  'C2-08': [
    f('Word equations', 'A word equation names what reacts and what is made.', 'names + arrow = react to make', 'Hydrogen reacts with chlorine to make hydrogen chloride. We can write this as hydrogen + chlorine → hydrogen chloride. The arrow means “react to make”. A reaction written with the names of the chemicals is called a word equation.', 'cmpd-equation-word'),
    f('Reactants', 'The chemicals you start with go on the left.', 'left of the arrow → reactants', 'Hydrogen and chlorine are on the left of the arrow. They are the chemicals that react with each other. The substances you start with in a reaction are called reactants.', 'cmpd-equation-reactants'),
    f('Products', 'The new substances go on the right.', 'right of the arrow → products', 'Hydrogen chloride is on the right of the arrow. It is the new substance made in the reaction. The substances made in a reaction are called products. A plus sign goes between two reactants or two products.', 'cmpd-equation-products'),
    f('Symbol equations', 'Formulas can take the place of the names.', 'names → formulas', 'Now swap each name for its formula: H₂ for hydrogen, Cl₂ for chlorine and HCl for hydrogen chloride. The reaction becomes H₂ + Cl₂ → HCl. An equation written with formulas is called a symbol equation. Count the atoms on each side: they do not match yet, and you will fix that next.', 'cmpd-equation-symbol'),
  ],
  'C2-11': [
    f('Atoms are not lost', 'An equation must have the same atoms on both sides.', 'atoms on the left = atoms on the right', 'In a reaction, atoms are only rearranged into new substances. No atoms are made and none disappear. So there must be the same number of each kind of atom on both sides. An equation like this is called balanced. H₂ + Cl₂ → HCl has 2 H and 2 Cl on the left, but only 1 of each on the right.', 'cmpd-balance-count'),
    f('Numbers in front', 'A big number in front of a formula means more molecules.', '2HCl = two molecules of HCl', 'To fix it, write a big 2 in front of HCl. 2HCl means two molecules of HCl, so it has 2 H atoms and 2 Cl atoms. Now each side has 2 H and 2 Cl. So H₂ + Cl₂ → 2HCl is balanced.', 'cmpd-balance-front'),
    f('Never change a formula', 'Changing a small number makes a different substance.', 'change numbers in front, never the small numbers', 'You might try writing H₂Cl₂ instead of 2HCl. That is wrong, because H₂Cl₂ is not hydrogen chloride. Changing a formula changes the substance. So when you balance an equation, only ever put numbers in front of formulas.', 'cmpd-balance-formula'),
    f('The method', 'Count, put a number in front, count again.', 'count → number in front → count again', 'First, count each kind of atom on both sides. Next, find one that does not match and put a number in front of a formula. Then count again, because one number can change two elements at once. Keep going until every kind of atom matches.', 'cmpd-balance-method'),
  ],
}
