import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { bloodGlucoseFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.5.3.2 Control of blood glucose concentration (Foundation content): the pancreas, insulin, glycogen in liver and muscle cells, Type 1 and Type 2 diabetes and their treatment, interpreting glucose and insulin graphs' }
const a = author('B-BLOOD-GLUCOSE', ['4.5.3.2'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const bloodGlucoseSections = [
  { id: 'B34-01', label: 'Start here', detail: 'Where does glucose come from?' },
  { id: 'B34-02', label: 'Glucose in, glucose out', detail: 'Meals, respiration, exercise and the pancreas' },
  { id: 'B34-05', label: 'When glucose is too high', detail: 'Insulin and glycogen' },
  { id: 'B34-08', label: 'Read the graph', detail: 'Which line is insulin?' },
  { id: 'B34-10', label: 'What is diabetes?', detail: 'Type 1, Type 2 and their treatments' },
  { id: 'B34-13', label: 'On your own', detail: 'Meals, organs, graphs and exercise' },
]

const states: ScienceState[] = [
  { ...a.choice('B34-01', 'When you digest a meal, which kind of food is broken down into glucose?', ['Proteins', 'Carbohydrates, such as starch', 'Fats (lipids)', 'Vitamins'], 1, 'You met this when you learned about digestion and enzymes.', ['Proteins are broken down into amino acids, and fats into fatty acids and glycerol.', 'Carbohydrates, such as starch, are broken down into sugars such as glucose.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B34-02', 'Glucose in, glucose out'),
  a.choice('B34-03', 'What makes the blood glucose level rise?', ['Eating a meal that contains carbohydrate', 'Running for a bus', 'Cells using glucose for respiration', 'Insulin being released'], 0, 'Where does the glucose in the blood come from?', ['Exercise and respiration use glucose up, so they lower the level.', 'Digesting carbohydrate from a meal puts glucose into the blood, so the level rises.']),
  a.choice('B34-04', 'Which organ monitors the blood glucose level?', ['The liver', 'The heart', 'The pancreas', 'The small intestine'], 2, 'Which organ detects when the level is too high?', ['The small intestine absorbs glucose, and the liver stores it.', 'The pancreas monitors the blood glucose level.']),
  t('B34-05', 'When glucose is too high'),
  a.choice('B34-06', 'What does insulin do?', ['It makes glucose move from the blood into cells', 'It breaks down starch in the gut', 'It carries oxygen in the blood', 'It makes the pancreas release glucose'], 0, 'What happens to the glucose level after insulin is released?', ['Insulin is a hormone released when blood glucose is too high.', 'It makes glucose move from the blood into cells, so the level falls.']),
  a.choice('B34-07', 'Where is extra glucose stored as glycogen?', ['In the pancreas', 'In liver and muscle cells', 'In the blood plasma', 'In the small intestine'], 1, 'Which cells take in a lot of glucose when insulin is released?', ['The pancreas releases insulin, but it does not store the glucose.', 'Liver and muscle cells turn glucose into glycogen and store it.']),
  t('B34-08', 'Read the graph'),
  a.choice('B34-09', 'The graph shows glucose and insulin in the blood after a meal. Which line shows insulin?', ['Line 1, because it rises first', 'Line 2, because it rises after glucose rises', 'Line 1, because it has the higher peak'], 1, 'Which comes first after a meal: glucose or insulin?', ['Eating makes glucose rise first, and the pancreas releases insulin in response.', 'So insulin rises later: it is line 2.'], 'dataInterpretation', false, 'hormone-graph-question'),
  t('B34-10', 'What is diabetes?'),
  a.choice('B34-11', 'What causes Type 1 diabetes?', ['The pancreas makes too little insulin, or none', 'The body’s cells stop responding to insulin', 'Eating too much carbohydrate at one meal', 'The liver stores too much glycogen'], 0, 'Which type is about not making enough insulin?', ['In Type 2, the cells stop responding to insulin properly.', 'In Type 1, the pancreas makes too little insulin, or none.']),
  a.choice('B34-12', 'How is Type 2 diabetes often controlled?', ['By eating as much carbohydrate as possible', 'By removing the pancreas', 'With a carbohydrate-controlled diet and regular exercise', 'By storing more glycogen in the pancreas'], 2, 'How can less glucose enter the blood, and more be used up?', ['A carbohydrate-controlled diet limits how much glucose enters the blood, and exercise uses glucose up.', 'So Type 2 is often controlled with a carbohydrate-controlled diet and regular exercise.']),
  a.choice('B34-13', 'Leo has Type 1 diabetes. Why does he inject insulin around mealtimes?', ['A meal raises his blood glucose, and his pancreas cannot make enough insulin to bring it down', 'Insulin gives him the energy to digest his food', 'Insulin turns the meal into glycogen in his stomach', 'His cells are resistant to the glucose in the meal'], 0, 'What happens to blood glucose after a meal, and what is missing in Type 1?', ['After a meal, glucose enters the blood and the level rises.', 'His pancreas makes too little insulin to bring the level down, so he injects it.'], 'application', true),
  a.choice('B34-14', 'Look at the numbered organs. Which number shows the organ that releases insulin?', ['Organ 1', 'Organ 2', 'Organ 3', 'Organ 4'], 3, 'Insulin is released by a gland just below the stomach.', ['Organ 1 is the small intestine, organ 2 the liver and organ 3 a muscle.', 'Organ 4 is the pancreas, which releases insulin.'], 'understanding', true, 'hormone-glucose-question'),
  a.choice('B34-15', 'The graph shows blood glucose in two people after the same meal. Which conclusion fits the data best?', ['Person A’s glucose stayed high for longer than person B’s', 'Person B’s glucose stayed high for longer than person A’s', 'Person B has Type 2 diabetes', 'Both people will get the same result after every meal'], 1, 'Compare where each line is at 120 and 180 minutes.', ['Person A’s glucose was back to about 4 by 120 minutes, but person B’s was still above 7 at 180 minutes. One graph cannot show what type of diabetes, if any, person B has.', 'So person B’s glucose stayed high for longer than person A’s.'], 'dataInterpretation', true, 'hormone-two-people'),
  a.choice('B34-16', 'During a long football match, Mia’s muscles work hard and she eats nothing. What happens to her blood glucose level?', ['It rises, because exercise makes glucose', 'It stays exactly the same', 'It falls, because her muscle cells take glucose from the blood for respiration', 'It rises, because insulin is released'], 2, 'What do working muscles need more of?', ['Working muscles need more energy, so they take more glucose from the blood for respiration.', 'With no food to top it up, her blood glucose level falls.'], 'application', true),
  a.written('B34-17', 'Explain how the body brings the blood glucose level back down after a meal. Then explain why a person with Type 1 diabetes needs insulin injections.', 'Follow the glucose from the meal to the cells, naming the organ and the hormone. Then say what is different in Type 1.', 'Glucose from the meal enters the blood, so the level rises. The pancreas detects the high level and releases insulin into the blood. Insulin makes glucose move from the blood into cells, and liver and muscle cells store it as glycogen. In Type 1 diabetes the pancreas makes too little insulin, or none, so the person injects insulin to bring the level down.', ['Glucose from the meal enters the blood, so the level rises.', 'The pancreas detects the high level and releases insulin into the blood.', 'Insulin makes glucose move from the blood into cells.', 'Liver and muscle cells store the glucose as glycogen.', 'In Type 1 the pancreas makes too little or no insulin, so insulin has to be injected.'], ['Saying insulin is made by the liver.', 'Saying glycogen is stored in the pancreas or in the blood.', 'Saying insulin itself is turned into glycogen.', 'Confusing Type 1 (too little insulin) with Type 2 (cells do not respond properly).']),
]

export const lesson34: ScienceLesson = {
  id: 'B-HOM-034-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Controlling blood glucose and diabetes', prerequisites: ['B-HORMONES'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
