import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { calcForceFrames as frames } from './teachingFrames'

const source = { id: 'aqa-physics', title: 'AQA 8464 Physics subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', locator: '6.5.1.4 Resultant forces (HT only): using scale vector diagrams to find the resultant of two forces, to show when forces are balanced (equilibrium), and to resolve a single force into two components at right angles, as on the supplied revision page; 6.5.1.1 force arrows as vectors for the opening question' }
const skill = 'P-FORCE-DRAWING'
const prior = author(skill, ['6.5.1.1'], ['aqa-physics'])
const draw = author(skill, ['6.5.1.4'], ['aqa-physics'])
const balance = author(skill, ['6.5.1.4'], ['aqa-physics'])
const split = author(skill, ['6.5.1.4'], ['aqa-physics'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const calcForceSections = [
  { id: 'P40H-01', label: 'Start here', detail: 'What the length of a force arrow shows' },
  { id: 'P40H-02', label: 'Finding a resultant by drawing', detail: 'Scale, tip-to-tail, measure' },
  { id: 'P40H-07', label: 'Forces in equilibrium', detail: 'A closed triangle and a missing force' },
  { id: 'P40H-11', label: 'Splitting a force into components', detail: 'Across and up on a square grid' },
  { id: 'P40H-14', label: 'On your own', detail: 'New forces, a drawing and a grid' },
]

const states: ScienceState[] = [
  { ...prior.choice('P40H-01', 'On a force diagram, arrow A is drawn twice as long as arrow B. What does this show?', ['Force A acts for twice as long', 'Force A is twice as big as force B', 'Force A acts in the opposite direction', 'Force A is a contact force'], 1, 'Force is a vector. What does an arrow’s length stand for?', ['Force is a vector: it has a size and a direction. An arrow shows both.', 'The length of the arrow shows the size of the force, so a twice-as-long arrow means a force twice as big. This lesson uses that idea to measure forces from drawings.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(draw, 'P40H-02', 'Finding a resultant by drawing'),
  draw.worked('P40H-03', 'Find a resultant with a scale drawing', 'Two strings pull a ring: 15 N to the right and 20 N straight up. Use a scale drawing to find the resultant force.', ['Choose a scale: 1 cm = 5 N. So 15 N is drawn 3 cm long and 20 N is drawn 4 cm long.', 'Draw the 15 N arrow 3 cm to the right with a ruler.', 'Draw the 20 N arrow 4 cm straight up, starting at the tip of the first arrow (tip-to-tail).', 'Draw the resultant from the start of the first arrow to the tip of the second. It measures 5 cm, and 5 × 5 = 25 N.', 'Measure the angle from the horizontal with a protractor: 53°. The resultant is 25 N at 53° above the horizontal.'], 'hfdraw-worked-ring'),
  draw.choice('P40H-04', 'The scale of a drawing is 1 cm = 5 N. How long should you draw a 30 N force?', ['150 cm', '35 cm', '6 cm', '0.6 cm'], 2, 'How many lots of 5 N are there in 30 N?', ['Each centimetre stands for 5 N.', '30 ÷ 5 = 6, so the arrow is drawn 6 cm long.'], 'calculation'),
  draw.choice('P40H-05', 'Two force arrows are drawn tip-to-tail. Where should you draw the resultant?', ['From the start of the first arrow to the tip of the last arrow', 'From the tip of the first arrow to the start of the last arrow', 'Along the longer of the two arrows', 'Halfway between the two arrows'], 0, 'The resultant has the same effect as following both arrows, one after the other.', ['Following the arrows tip-to-tail takes you from the start of the first arrow to the tip of the last.', 'The resultant is the straight line that makes the same journey in one go, so it goes from the start of the first to the tip of the last.'], 'recall'),
  draw.choice('P40H-06', 'Forces at right angles are drawn at 1 cm = 4 N. The resultant is 6.5 cm long. What force is it?', ['6.5 N', '10.5 N', '1.6 N', '26 N'], 3, 'Change the length back into a force using the scale.', ['Each centimetre stands for 4 N.', '6.5 × 4 = 26, so the resultant force is 26 N. Multiply the length by the scale; do not add or divide.'], 'calculation'),

  t(balance, 'P40H-07', 'Forces in equilibrium'),
  balance.choice('P40H-08', 'Three forces are drawn tip-to-tail to scale, and they make a closed triangle. What does this tell you?', ['The object must be speeding up', 'The resultant force is zero, so the object is in equilibrium', 'The biggest force wins', 'One of the forces has been drawn wrongly'], 1, 'In a closed shape, where does the last tip end up?', ['The tip of the last arrow ends where the first arrow started, so there is no gap.', 'No gap means the resultant force is zero. The forces are balanced, and the object is in equilibrium.'], 'understanding'),
  balance.choice('P40H-09', 'An object is in equilibrium. You draw the known forces tip-to-tail. How do you draw the missing force?', ['From the start of the first arrow to the tip of the last', 'Along the same line as the biggest force', 'From the tip of the last arrow back to the start of the first', 'You cannot find it from a drawing'], 2, 'In equilibrium the arrows must make a closed shape.', ['In equilibrium the forces must make a closed shape, ending where they started.', 'So the missing force goes from the tip of the last arrow back to the start of the first, and closes the shape.'], 'recall'),
  balance.choice('P40H-10', 'This object is in equilibrium, and each square is 1 N. What is the missing force shown by the dashed line?', ['5 N, up and to the right', '5 N, down and to the left', '7 N, up and to the right', '1 N, up and to the right'], 0, 'The missing force goes back to where the first arrow started.', ['The dashed line is 5 squares long, and each square is 1 N, so the missing force is 5 N.', 'It must go from the tip of the last arrow back to the start of the first, which is up and to the right.'], 'application', false, 'hfdraw-q-missing'),

  t(split, 'P40H-11', 'Splitting a force into components'),
  split.choice('P40H-12', 'What are the components of a force?', ['The forces that balance it', 'The objects the force acts on', 'Its size and its direction', 'Two forces at right angles that together have the same effect as it'], 3, 'Think about splitting one slanted arrow into an across part and an up part.', ['A force at an angle can be split into two forces at right angles, usually horizontal and vertical.', 'These two forces are its components. Acting together, they have the same effect as the single force.'], 'recall'),
  split.choice('P40H-13', 'Force F is drawn on a grid where each square is 2 N. What is its horizontal component?', ['4 N', '8 N', '6 N', '10 N'], 1, 'Count the squares across, then use the scale.', ['Follow the grid line across from the start of F to below its tip: that is 4 squares.', 'Each square is 2 N, so the horizontal component is 4 × 2 = 8 N.'], 'calculation', false, 'hfdraw-q-grid'),

  draw.choice('P40H-14', 'Two forces at right angles give a 5 cm resultant at 1 cm = 3 N. What is the resultant force?', ['8 N', '5 N', '15 N', '1.7 N'], 2, 'Use the scale to turn the length of the resultant into a force.', ['Each centimetre stands for 3 N.', '5 × 3 = 15, so the resultant force is 15 N. Multiply the length by the scale; do not add or divide.'], 'calculation', true),
  draw.choice('P40H-15', 'A student made this scale drawing of two forces. Which numbered arrow is the resultant force?', ['Arrow 1', 'Arrow 2', 'Arrow 3', 'None of them'], 0, 'Find the arrow that starts where the first force starts.', ['Arrows 2 and 3 are the two forces, joined tip-to-tail.', 'Arrow 1 goes from the start of the first force to the tip of the last, so it is the resultant.'], 'understanding', true, 'hfdraw-q-arrows'),
  split.choice('P40H-16', 'Force F is drawn on a grid where each square is 5 N. What is its vertical component?', ['3 N', '20 N', '25 N', '15 N'], 3, 'Count the squares up, then use the scale.', ['From below the tip, the line straight up to the tip is 3 squares long.', 'Each square is 5 N, so the vertical component is 3 × 5 = 15 N.'], 'calculation', true, 'hfdraw-q-comp'),
  balance.choice('P40H-17', 'An object in equilibrium has forces of 6 N right, 8 N down and one more. What is the missing force?', ['10 N, down and to the right', '10 N, up and to the left', '14 N, up and to the left', '5 N, up and to the left'], 1, 'Draw the two forces tip-to-tail to scale, then close the shape back to the start.', ['At 1 cm = 2 N, draw 3 cm right and then 4 cm down. The line that closes the shape is 5 cm, so the missing force is 5 × 2 = 10 N.', 'The arrows end down and to the right of the start. The missing force goes back to the start, so it points up and to the left.'], 'application', true),
  draw.written('P40H-18', 'Describe how to use a scale drawing to find the resultant of 12 N right and 5 N up.', 'Scale, tip-to-tail, the resultant line, then measure. The resultant line measures 13 cm at a scale of 1 cm = 1 N.', 'Choose a scale, such as 1 cm = 1 N. Use a ruler to draw the 12 N force as a 12 cm arrow to the right. Start the 5 N force at the tip of the first arrow and draw it 5 cm straight up, tip-to-tail. Draw a straight line from the start of the first arrow to the tip of the second: this is the resultant. Measure it: it is 13 cm long, so the resultant is 13 N. Measure its angle from the horizontal with a protractor, about 23°, to give its direction.', ['Choose a sensible scale, e.g. 1 cm = 1 N, and draw the 12 N arrow 12 cm to the right.', 'Draw the 5 N arrow 5 cm straight up, starting at the tip of the first (tip-to-tail).', 'Draw the resultant from the start of the first arrow to the tip of the second.', 'Measure its length and use the scale: 13 cm, so 13 N.', 'Measure the angle from the horizontal with a protractor (about 23°) for the direction.'], ['Adding the forces to get 17 N.', 'Drawing the resultant from the tip of the first arrow, or with the arrowhead at the start.', 'Giving a size with no direction, or a direction with no size.']),
]

export const lessonP40H: ScienceLesson = {
  id: 'P-FOR-040H-P', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'physics',
  title: 'Calculating forces', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
