import type { TeachingFrame } from '../../teachingFrame'

// Required practical preparation: adding identical resistors in series, then in parallel, measuring current and pd,
// calculating total resistance with R = V ÷ I, and what the two graphs should look like. Never claims the online lesson completes the practical.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const resistorPracFrames: Record<string, TeachingFrame[]> = {
  'P22-02': [
    f('The question and the kit', 'The investigation asks how adding resistors changes the total resistance of a circuit. You need at least four identical resistors.', 'identical resistors, cell, ammeter', 'The question is: how does adding more resistors change the total resistance of the circuit? You need at least four identical resistors, a cell or battery, an ammeter, a switch and wires. Identical means every resistor has the same resistance.', 'rprac-kit'),
    f('Build with one resistor', 'Connect the cell, switch, one resistor and the ammeter in series. Note the pd of the cell.', 'ammeter in series', 'Build a simple series circuit with one resistor. The ammeter goes in series, in the same loop. Write down the pd of the cell. This is the pd across the whole circuit.', 'rprac-one-resistor'),
    f('Measure and calculate', 'Close the switch, read the current, then calculate the total resistance with R = V ÷ I.', 'R = V ÷ I', 'Close the switch and read the current on the ammeter. Then work out the total resistance with the word equation: resistance = pd ÷ current. In symbols, R = V ÷ I. Open the switch again as soon as you have the reading.', 'rprac-calculate'),
    f('Worked example', 'A 6.0 V cell and a current of 0.50 A gives R = 6.0 ÷ 0.50 = 12 Ω. Two resistors in series gave 0.25 A, so R = 24 Ω.', 'divide pd by current', 'One resistor: the cell is 6.0 V and the ammeter reads 0.50 A. So R = 6.0 ÷ 0.50 = 12 Ω. Now add a second identical resistor in series. The current falls to 0.25 A. So R = 6.0 ÷ 0.25 = 24 Ω.', 'rprac-worked'),
    f('Add one at a time', 'Add another resistor in series each time, repeat the measurement and calculation, and record every result in a table.', 'one more, measure again', 'Keep adding one identical resistor at a time in series. Each time, read the current and calculate the total resistance. Record the number of resistors and the total resistance in a table. Then you can plot a graph.', 'rprac-add-series'),
  ],
  'P22-05': [
    f('Same circuit, one change', 'To test parallel, start with the same circuit and add each new resistor in parallel with the first.', 'the only change is where it goes', 'Investigating parallel resistors uses almost the same method. Start with the same first circuit. The only change is that each new resistor is added in parallel with the first, on its own branch.', 'rprac-parallel-build'),
    f('Measure again', 'For each number of resistors in parallel, read the current from the ammeter and calculate R = V ÷ I.', 'current from the ammeter', 'Each time you add a branch, read the current on the ammeter next to the cell. This is the total current. Calculate the total resistance with R = V ÷ I, using the cell pd as before.', 'rprac-parallel-measure'),
    f('A fair test', 'Use the same cell, the same type of resistors and the same meters for series and parallel so the results can be compared.', 'same equipment both times', 'If you want to compare series with parallel, use the same equipment for both parts. That means the same cell, identical resistors and the same ammeter. Then any difference in the results is caused by how the resistors are connected.', 'rprac-fair'),
  ],
  'P22-08': [
    f('What to expect', 'Adding resistors in series decreases the current and increases the total resistance. In parallel it increases the current and decreases the total resistance.', 'series up, parallel down', 'Your results should follow the rules for series and parallel circuits. Adding a resistor in series makes the total current smaller and the total resistance larger. Adding a resistor in parallel makes the total current larger and the total resistance smaller.', 'rprac-expect'),
    f('The series graph', 'Plot total resistance against the number of identical resistors. In series the line slopes upwards.', 'rising line', 'Put the number of identical resistors on the horizontal axis. Put the total resistance, in ohms, on the vertical axis. For resistors in series the points lie on a straight line that slopes upwards. More resistors means a larger total resistance.', 'rprac-graph-series'),
    f('The parallel graph', 'In parallel the curve falls: more resistors means a smaller total resistance.', 'falling curve', 'For resistors in parallel, the graph uses the same axes. This time the line is a curve that slopes downwards. More resistors means a smaller total resistance. The curve flattens out but never reaches zero.', 'rprac-graph-parallel'),
    f('Safety and reliability', 'Resistors and wires can get warm, so open the switch between readings. Repeat readings to check them.', 'warm parts, switch off', 'Resistors and wires can warm up when a current flows for a while. Open the switch between readings, and do not touch hot parts. A warm resistor can also change its resistance and spoil your results. Repeat each reading and check they agree.', 'rprac-safety'),
  ],
}
