import type { TeachingFrame } from '../../teachingFrame'

// Meet the group first (where it is, 7 outer electrons, pairs of atoms), then what a halogen does when it reacts
// (gains or shares one electron), then how that changes down the group, and last the displacement reactions,
// which need both the reactivity order and the idea of a halide salt.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const halogenFrames: Record<string, TeachingFrame[]> = {
  'C10-02': [
    f('Group 7', 'Group 7 is a column of non-metals near the right of the periodic table.', 'Group 7 → the halogens', 'Group 7 is the column one place in from the right-hand edge of the periodic table. From the top, it holds fluorine, chlorine, bromine, iodine and astatine. They are all non-metals. The elements in Group 7 are called the halogens.', 'hal-group'),
    f('Seven outer electrons', 'Every halogen atom has 7 electrons in its outer shell.', '7 outer electrons → similar reactions', 'Fluorine is 2,7 and chlorine is 2,8,7. So both have 7 electrons in their outer shell, and so do bromine and iodine. The outer electrons decide how an element reacts. So all the halogens react in similar ways.', 'hal-outer'),
    f('Pairs of atoms', 'Halogen atoms join up in pairs to make molecules.', 'two atoms joined → one molecule, Cl₂', 'You met molecules when you learned about compounds. In a halogen, two atoms of the same element join together. So chlorine gas is made of chlorine molecules, written Cl₂. The small 2 means two atoms. Fluorine, bromine and iodine are the same: F₂, Br₂ and I₂.', 'hal-molecule'),
    f('What they look like', 'At room temperature, the halogens go from gases to a liquid to a solid.', 'gas, gas, liquid, solid', 'At room temperature, fluorine is a pale yellow gas and chlorine is a pale green gas. Chlorine is poisonous, so it is only used in small amounts, with care. Bromine is a red-brown liquid. Iodine is a dark grey solid.', 'hal-looks'),
  ],
  'C10-05': [
    f('Gaining one electron', 'With a metal, a halogen atom gains one electron.', '7 outer electrons + 1 → full outer shell, 1− charge', 'A chlorine atom has 7 outer electrons, so it needs one more for a full outer shell. When chlorine reacts with a metal, each chlorine atom takes one electron from the metal. Now it has 17 protons but 18 electrons. So it becomes an ion with a 1− charge, written Cl⁻. You met ions when you learned about atoms.', 'hal-ion'),
    f('Halide ions', 'The 1− ions of the halogens are called halide ions.', '-ine → -ide', 'Every halogen forms an ion with a 1− charge in the same way. The name changes its ending from -ine to -ide. So fluorine forms fluoride, F⁻, chlorine forms chloride, Cl⁻, bromine forms bromide, Br⁻, and iodine forms iodide, I⁻. Together, these are called halide ions.', 'hal-halides'),
    f('Halide salts', 'A metal and a halogen make an ionic compound.', 'metal + halogen → metal halide (made of ions)', 'Sodium reacts with chlorine to make sodium chloride, a white solid. Each sodium atom gives its outer electron to a chlorine atom. That makes a sodium ion, Na⁺, and a chloride ion, Cl⁻. A compound made of ions like this is called an ionic compound. Sodium chloride is one of the halide salts.', 'hal-salt'),
    f('Sharing with non-metals', 'With a non-metal, a halogen shares electrons instead.', 'non-metal + halogen → share a pair → covalent bond', 'Hydrogen is a non-metal, so it does not give its electron away. Instead, a hydrogen atom and a chlorine atom share a pair of electrons. Now both have a full outer shell. A bond made by sharing a pair of electrons is called a covalent bond. Hydrogen chloride, HCl, is made of small molecules like this.', 'hal-share'),
    f('Put it together', 'Either way, the halogen atom ends up with a full outer shell.', 'metal → ions; non-metal → shared pair', 'With a metal, a halogen atom gains one electron and becomes a halide ion. The product is an ionic halide salt, such as sodium chloride. With a non-metal, a halogen atom shares a pair of electrons. The product is made of small molecules, such as hydrogen chloride. You will learn more about both kinds of bond later.', 'hal-both'),
  ],
  'C10-09': [
    f('Heavier atoms', 'Relative atomic mass goes up down the group.', 'down the group → heavier, bigger atoms', 'Going down Group 7, each atom has more protons, neutrons and electrons. So the relative atomic mass goes up: fluorine 19, chlorine 35.5, bromine 80 and iodine 127. Each atom also has more shells, so the atoms get bigger.', 'hal-trend-mass'),
    f('Higher boiling points', 'Melting and boiling points go up down the group.', 'bigger molecules → higher melting and boiling points', 'Chlorine boils at −34 °C, but bromine boils at 59 °C and iodine at 184 °C. Bigger molecules attract each other more strongly, so more heating is needed to separate them. So melting and boiling points go up down the group. That is why bromine is a liquid and iodine is a solid at room temperature.', 'hal-trend-bp'),
    f('Less reactive', 'Reactivity goes down down the group.', 'further down → less reactive', 'Fluorine is the most reactive halogen. Chlorine is a little less reactive, and bromine less again. Iodine is the least reactive of these four. A pattern that changes steadily down a group like this is called a trend.', 'hal-trend-react'),
    f('Why reactivity falls', 'Lower halogens find it harder to gain an electron.', 'outer shell further from nucleus → weaker pull → less reactive', 'When a halogen reacts, each atom gains one electron into its outer shell. The positive nucleus pulls that electron in. Further down the group, the outer shell is further from the nucleus. So the pull is weaker, the atom gains an electron less easily, and it is less reactive.', 'hal-trend-why'),
    f('Put it together', 'You can use the trends to predict properties.', 'follow the trend → predict astatine', 'Down Group 7, relative atomic mass goes up, melting and boiling points go up, and reactivity goes down. You can use these trends to predict. Astatine is below iodine, and iodine is already a solid. So astatine should have an even higher melting point and be a solid at room temperature too.', 'hal-trend-all'),
  ],
  'C10-13': [
    f('A halogen meets a salt', 'Chlorine water turns potassium bromide solution orange.', 'pale green + colourless → orange', 'Potassium bromide is a halide salt, and its solution in water is colourless. Chlorine water is chlorine dissolved in water. When a little chlorine water is added, the mixture turns orange. Orange is the colour of bromine dissolved in water. So bromine has been made.', 'hal-disp-mix'),
    f('Taking its place', 'The more reactive chlorine pushes bromine out of the salt.', 'more reactive halogen takes the place of the less reactive one', 'Chlorine is more reactive than bromine. So chlorine takes bromine’s place in the salt. The chlorine becomes chloride ions, and the bromide ions become bromine. A reaction like this, where a more reactive element pushes a less reactive one out of its compound, is called a displacement reaction.', 'hal-disp-swap'),
    f('The equation', 'Chlorine and potassium bromide make bromine and potassium chloride.', 'Cl₂ + 2KBr → Br₂ + 2KCl', 'The word equation is chlorine + potassium bromide → bromine + potassium chloride. The balanced symbol equation is Cl₂ + 2KBr → Br₂ + 2KCl. Check it: there are 2 chlorine, 2 potassium and 2 bromine atoms on each side.', 'hal-disp-equation'),
    f('No swap the other way', 'A less reactive halogen cannot displace a more reactive one.', 'less reactive halogen → no reaction', 'Now add bromine water to potassium chloride solution. Bromine is less reactive than chlorine, so it cannot take chlorine’s place. Nothing happens. The mixture is just the colour of the bromine water that was added.', 'hal-disp-none'),
    f('Put it together', 'A halogen displaces the halogens below it in the group.', 'higher in Group 7 → displaces the ones below', 'Chlorine displaces bromine and iodine from their salts. Bromine displaces iodine, but not chlorine. Iodine displaces neither. When iodine is made in water, the solution turns brown. So a halogen can only displace a halogen that is lower down Group 7.', 'hal-disp-rule'),
  ],
}
