import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { bondEnergyFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.5.1.3 Energy changes of reactions (HT only): breaking bonds is endothermic and making bonds is exothermic; the overall energy change is the energy needed to break bonds in the reactants minus the energy released when bonds in the products form; calculating energy changes from bond energies, as on the supplied revision page' }
const skill = 'C-BOND-ENERGY'
const prior = author(skill, ['5.5.1.1'], ['aqa-chemistry'])
const bonds = author(skill, ['5.5.1.3'], ['aqa-chemistry'])
const calc = author(skill, ['5.5.1.3'], ['aqa-chemistry'])
const compare = author(skill, ['5.5.1.3'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const bondEnergySections = [
  { id: 'C30H-01', label: 'Start here', detail: 'What happens to the atoms when hydrogen burns' },
  { id: 'C30H-02', label: 'Breaking and making bonds', detail: 'Energy in, energy out' },
  { id: 'C30H-06', label: 'Calculating the energy change', detail: 'Bonds broken minus bonds made' },
  { id: 'C30H-11', label: 'Comparing reactions', detail: 'Why you need the actual numbers' },
  { id: 'C30H-14', label: 'On your own', detail: 'New reactions, a diagram and a mistake' },
]

const states: ScienceState[] = [
  { ...prior.choice('C30H-01', 'Hydrogen burns in oxygen: 2H₂ + O₂ → 2H₂O. How do the atoms end up in water molecules?', ['The atoms are destroyed and new ones are made', 'The bonds in H₂ and O₂ break, then new bonds form', 'The molecules stick together without any bonds breaking'], 1, 'Atoms are never made or destroyed in a reaction. They are rearranged.', ['In a reaction the atoms are rearranged. To do that, the bonds holding H₂ and O₂ together must break.', 'Then new bonds form between hydrogen and oxygen atoms to make water. The energy of breaking and making bonds is what this lesson is about.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(bonds, 'C30H-02', 'Breaking and making bonds'),
  bonds.choice('C30H-03', 'Which statement about bonds in a chemical reaction is correct?', ['Breaking bonds releases energy', 'Making bonds needs energy to be supplied', 'Breaking bonds needs energy, and making bonds releases energy', 'Breaking and making bonds both release energy'], 2, 'Think about pulling apart two atoms that attract each other.', ['Atoms in a bond attract each other, so energy is needed to pull them apart. Bond breaking is endothermic.', 'When a new bond forms, energy is released. Bond making is exothermic.'], 'recall'),
  bonds.choice('C30H-04', 'A reaction takes in 1200 kJ/mol to break bonds and releases 1500 kJ/mol making bonds. What kind of reaction is it?', ['Exothermic, because more energy is released than taken in', 'Endothermic, because more energy is released than taken in', 'Endothermic, because bonds are broken', 'Neither, because both happen'], 0, 'Which is bigger: the energy taken in or the energy given out?', ['More energy is given out making bonds (1500 kJ/mol) than is taken in breaking them (1200 kJ/mol).', 'So overall energy is given out to the surroundings. The reaction is exothermic.']),
  bonds.choice('C30H-05', 'Which statement is true for an endothermic reaction?', ['No bonds are broken', 'Less energy is used breaking bonds than is released making them', 'No new bonds are made', 'More energy is used breaking bonds than is released making them'], 3, 'Endothermic means energy is taken in overall.', ['Every reaction breaks some bonds and makes some new ones.', 'In an endothermic reaction, the energy used to break bonds is greater than the energy released making them. So energy is taken in overall.'], 'understanding'),

  t(calc, 'C30H-06', 'Calculating the energy change'),
  calc.worked('C30H-07', 'Calculate an energy change from bond energies', 'Methane burns: CH₄ + 2O₂ → CO₂ + 2H₂O. Bond energies in kJ/mol: C–H 413, O=O 498, C=O 805, O–H 464. Calculate the overall energy change.', ['Count the bonds from the displayed formulae. CH₄ has 4 C–H. Each O₂ has 1 O=O. CO₂ is O=C=O, with 2 C=O. Each H₂O has 2 O–H.', 'Bonds broken: (4 × 413) + (2 × 498) = 1652 + 996 = 2648 kJ/mol.', 'Bonds made: (2 × 805) + (4 × 464) = 1610 + 1856 = 3466 kJ/mol.', 'Overall energy change = bonds broken − bonds made = 2648 − 3466 = −818 kJ/mol.', 'The answer is negative, so burning methane is exothermic. That is why it is a useful fuel.'], 'hbond-worked-methane'),
  calc.choice('C30H-08', 'N₂ + O₂ → 2NO. Bond energies: N≡N 945, O=O 498, N=O 607 kJ/mol. What is the overall energy change?', ['−229 kJ/mol', '+229 kJ/mol', '+2657 kJ/mol', '+836 kJ/mol'], 1, 'Bonds broken − bonds made. Remember there are two NO molecules.', ['Bonds broken: 945 + 498 = 1443 kJ/mol. Bonds made: 2 × 607 = 1214 kJ/mol.', '1443 − 1214 = +229 kJ/mol. The answer is positive, so this reaction is endothermic.'], 'calculation'),
  calc.choice('C30H-09', 'Propane, C₃H₈, burns in oxygen. How many C–H bonds break in each propane molecule?', ['3', '10', '8', '11'], 2, 'Each hydrogen atom makes one bond, to a carbon atom.', ['Every hydrogen atom in propane is joined to a carbon by one C–H bond. There are 8 hydrogen atoms, so there are 8 C–H bonds.', 'Propane also has 2 C–C bonds. That makes 10 bonds in all, but only 8 of them are C–H.'], 'application', false, 'hbond-q-propane'),
  calc.choice('C30H-10', 'A reaction has an overall energy change of +60 kJ/mol. What does this tell you?', ['It is exothermic', 'More energy is released making bonds than is used breaking them', 'No bonds are broken', 'It is endothermic: more energy is used breaking bonds than is released'], 3, 'What does a positive answer to bonds broken − bonds made mean?', ['A positive answer means the energy to break bonds is bigger than the energy released making bonds.', 'So energy is taken in overall, and the reaction is endothermic.']),

  t(compare, 'C30H-11', 'Comparing reactions'),
  compare.choice('C30H-12', 'Reaction X needs less energy to break its bonds than reaction Y. What else must you know to compare their energy changes?', ['Nothing, because X must give out more energy', 'The energy released making bonds in each reaction', 'Which reaction is faster', 'The mass of each reactant'], 1, 'The overall change has two parts. You only know one of them.', ['The overall energy change is bonds broken − bonds made. Knowing only the bonds broken is half the story.', 'You need the energy released making bonds for each reaction, then the actual numbers, to say which gives out more.']),
  compare.choice('C30H-13', 'Use the data for reactions A and B. Which reaction gives out more energy overall?', ['Reaction A', 'Reaction B', 'They give out the same', 'Neither gives out energy'], 0, 'Work out bonds broken − bonds made for each one.', ['Reaction A: 600 − 700 = −100 kJ/mol. Reaction B: 900 − 950 = −50 kJ/mol.', 'Both are exothermic, but A gives out more energy overall, even though B releases more energy making bonds.'], 'dataInterpretation', false, 'hbond-q-ab'),

  calc.choice('C30H-14', 'Hydrogen peroxide decomposes: 2H₂O₂ → 2H₂O + O₂. Use the bond energies shown. What is the overall energy change?', ['+206 kJ/mol', '−1280 kJ/mol', '+292 kJ/mol', '−206 kJ/mol'], 3, 'Draw H–O–O–H to count its bonds. Remember the 2 in front of each formula.', ['Each H–O–O–H has 2 O–H and 1 O–O. Bonds broken: 2 × ((2 × 464) + 146) = 2 × 1074 = 2148 kJ/mol.', 'Bonds made: 4 O–H in two waters and 1 O=O: (4 × 464) + 498 = 2354 kJ/mol. So 2148 − 2354 = −206 kJ/mol, exothermic.'], 'calculation', true, 'hbond-q-peroxide'),
  bonds.choice('C30H-15', 'On this energy diagram, which numbered arrow shows the energy released when new bonds form?', ['Arrow 3', 'Arrow 1', 'Arrow 2', 'None of them'], 2, 'Making bonds gives energy out, so the energy goes down. Where does it go down from?', ['Arrow 2 goes down from the separate atoms to the products. That is the energy released as new bonds form.', 'Arrow 1 goes up: energy taken in to break bonds. Arrow 3 is the overall energy change.'], 'understanding', true, 'hbond-q-arrows'),
  calc.choice('C30H-16', 'A student calculated the energy change for 2CO + O₂ → 2CO₂. Which numbered line has the first mistake?', ['Line 1', 'Line 2', 'Line 3', 'Line 4'], 1, 'Draw a CO₂ molecule. How many C=O bonds does it have?', ['Line 2 counts only 2 C=O bonds. Each CO₂ molecule, O=C=O, has 2 C=O bonds, so 2CO₂ has 4.', 'Bonds made = 4 × 805 = 3220 kJ/mol. So 2652 − 3220 = −568 kJ/mol: the reaction is exothermic.'], 'application', true, 'hbond-q-working'),
  compare.choice('C30H-17', 'The table shows bond energy totals for three reactions. Which reaction is endothermic?', ['Reaction P', 'Reaction R', 'All three', 'Reaction Q'], 3, 'Work out bonds broken − bonds made for each. Look for a positive answer.', ['P: 2000 − 2400 = −400. Q: 1500 − 1300 = +200. R: 900 − 1000 = −100 kJ/mol.', 'Only Q has a positive energy change, so only Q is endothermic. It takes in more energy breaking bonds than it releases.'], 'dataInterpretation', true, 'hbond-q-table'),
  calc.written('C30H-18', 'Hydrogen reacts with fluorine: H₂ + F₂ → 2HF. Calculate the energy change and explain what it shows.', 'Bond energies in kJ/mol: H–H 436, F–F 158, H–F 568. Bonds broken − bonds made. Then say what the sign tells you.', 'Bonds broken: one H–H and one F–F, so 436 + 158 = 594 kJ/mol. Bonds made: two H–F bonds, so 2 × 568 = 1136 kJ/mol. Overall energy change = 594 − 1136 = −542 kJ/mol. The answer is negative, so the reaction is exothermic. More energy is released when the H–F bonds form than is needed to break the H–H and F–F bonds, so energy is given out to the surroundings.', ['Energy to break bonds: 436 + 158 = 594 kJ/mol.', 'Energy released making bonds: 2 × 568 = 1136 kJ/mol (two H–F bonds).', 'Overall energy change = 594 − 1136 = −542 kJ/mol.', 'Negative, so the reaction is exothermic.', 'Because more energy is released making the new bonds than is used breaking the old ones.'], ['Using only one H–F bond (594 − 568 = +26 kJ/mol).', 'Subtracting the wrong way round (+542 kJ/mol) or adding the totals.', 'Saying bond breaking releases energy, or calling a negative answer endothermic.']),
]

export const lessonC30H: ScienceLesson = {
  id: 'C-BOND-030H-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Bond energies', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
