import type { TeachingFrame } from '../../teachingFrame'

// Bond energies build on exothermic and endothermic reactions, reaction profiles and covalent bonds (displayed formulae),
// without re-teaching them. Each teaching section keeps one drawing on screen and changes it frame by frame: hydrogen
// burning (2H₂ + O₂ → 2H₂O) as molecules, separate atoms and products; the same reaction as a calculation board with
// displayed formulae and bond energies; and hydrogen with bromine beside hydrogen with iodine as pairs of energy bars.
// The last frame of each puts the steps together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const bondEnergyFrames: Record<string, TeachingFrame[]> = {
  'C30H-02': [
    f('Bonds break, bonds form', 'In a reaction, bonds in the reactants break and new bonds form in the products.', 'old bonds break → atoms rearrange → new bonds form', 'Hydrogen burns in oxygen to make water: 2H₂ + O₂ → 2H₂O. The atoms in each molecule are held together by covalent bonds. For the atoms to rearrange, the bonds in H₂ and O₂ must break. Then new bonds form to make water molecules.', 'hbond-bond-rearrange'),
    f('Breaking takes energy in', 'Breaking a bond needs energy, so bond breaking is endothermic.', 'break a bond → energy in', 'The atoms in a bond attract each other strongly. To pull them apart, energy must be supplied. So breaking bonds takes in energy from the surroundings. A process that takes in energy is endothermic.', 'hbond-bond-break'),
    f('Making gives energy out', 'Forming a bond releases energy, so bond making is exothermic.', 'make a bond → energy out', 'When separate atoms join to form a new bond, energy is released. So making bonds gives out energy to the surroundings. A process that gives out energy is exothermic. Here, new O–H bonds form to make two water molecules.', 'hbond-bond-make'),
    f('Which is bigger?', 'Compare the energy taken in breaking bonds with the energy given out making bonds.', 'more out than in → exothermic', 'Every reaction breaks some bonds and makes some new ones. If more energy is released making bonds than is used breaking them, the reaction is exothermic. If more is used breaking bonds than is released making them, it is endothermic. Burning hydrogen gives out more than it takes in.', 'hbond-bond-compare'),
    f('Put it together', 'Up to break the bonds, down to make new ones. The gap is the overall energy change.', 'break ↑, make ↓, overall = the gap', 'You can show this on an energy diagram, a bit like a reaction profile. Breaking bonds takes the reactants up to separate atoms. Making bonds brings the energy down to the products. For burning hydrogen the down arrow is longer, so the products end up lower. The gap is the energy given out.', 'hbond-bond-together'),
  ],
  'C30H-06': [
    f('Bond energies', 'A bond energy is the energy needed to break one mole of a bond, in kJ/mol.', 'H–H: 436 kJ/mol', 'Each kind of bond has its own bond energy. It is the energy needed to break one mole of that bond. It is measured in kilojoules per mole, kJ/mol. The same amount is released when one mole of that bond forms. For example, H–H is 436 kJ/mol.', 'hbond-calc-table'),
    f('Add up the bonds broken', 'Draw the reactants, count each bond, and add up the energy to break them.', '2 × H–H + 1 × O=O', 'Draw the displayed formula of each reactant, so you can count every bond. Two H₂ molecules have 2 H–H bonds. One O₂ molecule has 1 O=O double bond, which has its own bond energy. Energy to break them = (2 × 436) + 498 = 1370 kJ/mol.', 'hbond-calc-broken'),
    f('Add up the bonds made', 'Count the bonds in the products and add up the energy released forming them.', '2H₂O → 4 × O–H', 'Now count the bonds in the products. Each water molecule, H–O–H, has 2 O–H bonds. So two water molecules have 4 O–H bonds. Energy released making them = 4 × 464 = 1856 kJ/mol.', 'hbond-calc-made'),
    f('Subtract', 'Overall energy change = energy to break bonds − energy released making bonds.', '1370 − 1856 = −486', 'Overall energy change = energy needed to break bonds − energy released making bonds. For burning hydrogen, 1370 − 1856 = −486 kJ/mol. Always take the bonds made away from the bonds broken, not the other way round.', 'hbond-calc-subtract'),
    f('Put it together', 'A negative answer means exothermic. A positive answer means endothermic.', 'negative → exothermic · positive → endothermic', 'The answer is negative because more energy is released than is taken in. A negative energy change means the reaction is exothermic. A positive energy change means it is endothermic. The steps: draw the molecules, add up the bonds broken, add up the bonds made, then subtract.', 'hbond-calc-sign'),
  ],
  'C30H-11': [
    f('Two similar reactions', 'Hydrogen reacts with bromine and with iodine in the same way.', 'H–H and X–X break → 2 H–X form', 'Hydrogen reacts with bromine to make hydrogen bromide: H₂ + Br₂ → 2HBr. It reacts with iodine in the same way: H₂ + I₂ → 2HI. Each reaction breaks one H–H bond and one bond between two halogen atoms. Each makes two new bonds to hydrogen.', 'hbond-compare-pair'),
    f('Less to break', 'The iodine reaction needs less energy to break its bonds.', 'iodine: 587 is less than 629', 'Bromine: 436 + 193 = 629 kJ/mol to break the bonds. Iodine: 436 + 151 = 587 kJ/mol. The I–I bond is weaker, so less energy is needed. You might think the iodine reaction must give out more energy. But that is only half the story.', 'hbond-compare-break'),
    f('Less released too', 'The iodine reaction also releases less energy making its bonds.', 'iodine: 598 is less than 732', 'Bromine: 2 × 366 = 732 kJ/mol is released making H–Br bonds. Iodine: 2 × 299 = 598 kJ/mol is released making H–I bonds. The H–I bond is weaker too, so less energy is released when it forms.', 'hbond-compare-make'),
    f('Put it together', 'To compare reactions, work out each energy change with the actual numbers.', '−103 compared with −11 kJ/mol', 'Bromine: 629 − 732 = −103 kJ/mol. Iodine: 587 − 598 = −11 kJ/mol. Both are exothermic, but the bromine reaction gives out far more energy. Knowing which needs less energy to break is not enough. You need the actual numbers for both parts.', 'hbond-compare-together'),
  ],
}
