import type { TeachingFrame } from '../../teachingFrame'

// Wind first (the most familiar), then solar, then geothermal, each as what it is, where it is used, pros, then cons.
// A last frame compares the three on reliability, because "which is more reliable" is the question students meet most.
// Cost figures and how a generator works are out of scope: the page only asks for pros, cons and uses.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const windSolarFrames: Record<string, TeachingFrame[]> = {
  'P11-02': [
    f('Wind turns the blades', 'Wind turbines are put up in open spaces. The moving wind turns the blades, and electricity is produced.', 'wind, then blades, then electricity', 'A wind turbine has large blades. When the wind blows, it turns the blades. The turning blades produce electricity. Wind turbines are put up in open spaces, such as on moors or out at sea. Wind is renewable, so it never runs out.', 'windsol-turbine'),
    f('Good points of wind power', 'There is no pollution once the turbines are built, and they cause no lasting damage to the landscape.', 'no pollution, no lasting damage', 'Once a wind turbine is built, it does not pollute the air or the water. It also does no permanent damage to the land. If the turbines are taken away, the area goes back to normal. These are the pros, or advantages, of wind power.', 'windsol-wind-pros'),
    f('Bad points: view and noise', 'Some people say turbines spoil the view. They can also be very noisy for people who live nearby.', 'spoil the view, noisy', 'Now for the cons, or disadvantages. Some people think that wind turbines spoil the view. Turbines can also be very noisy for people who live nearby.', 'windsol-wind-noise'),
    f('Bad points: the wind changes', 'Turbines stop when there is little wind, and have to be stopped if the wind is too strong. The supply cannot be increased on demand.', 'too little wind, too much wind', 'A turbine needs the right amount of wind. If there is little or no wind, the turbines stop. If the wind is too strong, they have to be stopped so they do not get damaged. On average, wind turbines produce electricity for about 70 to 85 per cent of the time. The supply also cannot be increased when there is extra demand. Demand means how much electricity people want.', 'windsol-wind-limits'),
  ],
  'P11-05': [
    f('Solar cells', 'Solar cells generate electricity directly from sunlight.', 'sunlight in, electricity out', 'A solar cell is a flat panel. Energy from the Sun is transferred to the cell by light. The cell transfers it on electrically, straight away. There are no blades to turn. Sunlight is renewable, so it never runs out.', 'windsol-cell'),
    f('Where solar power is used', 'Solar power is often used in remote places, and to power road signs and satellites.', 'places with no other choice', 'Solar cells are very useful in remote places, where there is not much choice. One example is a weather station high on a mountain, with no power cables. Solar cells are also used to power electric road signs and satellites.', 'windsol-uses'),
    f('Good points of solar power', 'No pollution once built. Very reliable in sunny countries. The energy is free, so running costs are almost zero.', 'no pollution, free energy', 'Once solar panels have been built, they give out no pollution. They are a very reliable source of energy in sunny countries. The energy from the Sun is free, so the running costs are almost zero. Solar power is even fairly reliable in cloudy places like Britain.', 'windsol-solar-pros'),
    f('Bad points of solar power', 'Solar cells only produce energy in the daytime. Lots of energy is used to build them. The output cannot be increased on demand.', 'daytime only, cost of building', 'Solar cells only produce electricity in the daytime. Quite a lot of energy is used to build the solar panels. The power output of solar panels cannot be increased when there is extra demand. So solar cells alone cannot supply electricity all through the night.', 'windsol-solar-cons'),
  ],
  'P11-08': [
    f('Hot rocks underground', 'Geothermal power uses energy from the thermal energy stores of hot rocks below the Earth\'s surface.', 'hot rocks below the ground', 'Deep below the ground, the rocks are hot. Energy is stored in the thermal energy stores of these hot rocks. Geothermal power uses this energy. Geothermal means heat from the Earth.', 'windsol-hotrock'),
    f('Two uses of geothermal energy', 'The energy can be used to generate electricity or to heat buildings directly.', 'electricity or heating', 'Water can be pumped down to the hot rocks. It comes back up hot. The hot water can be used to generate electricity. It can also be piped to heat buildings directly.', 'windsol-geouses'),
    f('Good points of geothermal power', 'It is a reliable source of energy, because the hot rocks are always hot. It does little damage to the environment.', 'always hot, little damage', 'Geothermal power is a reliable source of energy. The rocks are always hot, by day and by night, in any weather. It also does little damage to the environment. So, unlike wind or solar power, the supply does not depend on the weather.', 'windsol-geopros'),
    f('Bad points of geothermal power', 'There are not many suitable locations. The cost of building a geothermal power plant is usually quite high.', 'few places, high cost', 'Geothermal power can only be used in certain places. There are not many suitable locations. The cost of building a geothermal power plant is also usually quite high.', 'windsol-geocons'),
    f('Comparing the three', 'Wind stops when the wind drops. Solar works in daylight. Geothermal works all the time.', 'which one is always available', 'Here are the three resources side by side. Wind turbines stop when there is little wind. Solar cells only work in daylight. Geothermal power works all the time, because the rocks are always hot. But it can only be built in a few places.', 'windsol-compare'),
  ],
}
