import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { metallicFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.2.1.5 Metallic bonding; 5.2.2.7 Properties of metals and alloys; 5.2.2.8 Metals as conductors' }
const skill = 'C-METALLIC-BONDING'
const bond = author(skill, ['5.2.1.5'], ['aqa-chemistry'])
const conduct = author(skill, ['5.2.2.8', '5.2.1.5'], ['aqa-chemistry'])
const props = author(skill, ['5.2.2.7', '5.2.1.5'], ['aqa-chemistry'])
const alloy = author(skill, ['5.2.2.7'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const metallicSections = [
  { id: 'C16-01', label: 'Start here', detail: 'Metals at home' },
  { id: 'C16-02', label: 'What holds a metal together?', detail: 'Positive ions, delocalised electrons and metallic bonds' },
  { id: 'C16-05', label: 'Why do metals conduct?', detail: 'Carrying charge and thermal energy' },
  { id: 'C16-08', label: 'Why are metals solid but easy to shape?', detail: 'Strong bonds and sliding layers' },
  { id: 'C16-11', label: 'Why are alloys harder?', detail: 'Atoms of a different size distort the layers' },
  { id: 'C16-14', label: 'On your own', detail: 'Gold rings, a metal diagram and dent data' },
]

const states: ScienceState[] = [
  { ...conduct.choice('C16-01', 'Wires are made of copper, and saucepans are often made of steel or aluminium. What do these metals have in common?', ['They snap easily when bent', 'They conduct electricity and heat well', 'They melt at low temperatures', 'They are all gases when pure'], 1, 'What does a wire or a pan need to let through?', ['A wire must let electricity through, and a pan must let heat through to the food.', 'So these metals are useful because they conduct electricity and heat well.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(bond, 'C16-02', 'What holds a metal together?'),
  bond.choice('C16-03', 'What are the delocalised electrons in a metal?', ['Pairs of electrons shared between two atoms', 'Electrons that stay in one atom’s inner shell', 'Outer-shell electrons that are free to move through the whole metal', 'Electrons gained by the metal atoms'], 2, 'Where do the outer electrons go in a metal?', ['In a metal, the outer-shell electrons are not held by one atom.', 'So they are free to move through the whole structure: they are delocalised.']),
  bond.choice('C16-04', 'What is a metallic bond?', ['The attraction between positive metal ions and delocalised electrons', 'A pair of electrons shared between two metal atoms', 'The attraction between positive and negative ions in a salt', 'A weak force between separate metal molecules'], 0, 'Which two things with opposite charges are in a metal?', ['A metal contains positive metal ions and negative delocalised electrons.', 'So the strong electrostatic attraction between them is the metallic bond.']),
  t(conduct, 'C16-05', 'Why do metals conduct?'),
  conduct.choice('C16-06', 'Why does a copper wire conduct electricity?', ['Its copper atoms share pairs of electrons', 'It has a very high melting point', 'Its positive ions move along the wire', 'Its delocalised electrons move through it, carrying charge'], 3, 'Which particles in a metal are free to move?', ['The positive ions stay in their fixed rows, but the delocalised electrons are free to move.', 'So the delocalised electrons carry electric charge through the wire.']),
  conduct.choice('C16-07', 'One end of a steel spoon sits in hot soup. Why does the other end soon get warm?', ['Heat cannot travel through a solid', 'Delocalised electrons carry thermal energy along the spoon', 'The metal ions flow up the spoon', 'The spoon’s metallic bonds all break'], 1, 'What carries energy through a metal?', ['Delocalised electrons move through the whole metal structure.', 'So they carry thermal energy from the hot end to the cold end.']),
  t(props, 'C16-08', 'Why are metals solid but easy to shape?'),
  props.choice('C16-09', 'Why do most metals have high melting points?', ['There are only weak forces between their molecules', 'Their electrons cannot move', 'Lots of energy is needed to break their strong metallic bonds', 'Their positive ions repel each other'], 2, 'How strong are metallic bonds?', ['Metals have strong metallic bonds all through their giant structure.', 'So lots of energy is needed to break them, which gives high melting points.']),
  props.choice('C16-10', 'A plumber bends a copper pipe to fit round a corner. Why can the pipe bend without snapping?', ['Layers of copper atoms slide over each other', 'The copper melts as it bends', 'Its metallic bonds are very weak', 'Its electrons leave the pipe'], 0, 'What happens to the layers when a metal is pushed?', ['The copper atoms are in layers that can slide over each other.', 'So the pipe changes shape, and the delocalised electrons keep holding the ions together.']),
  t(alloy, 'C16-11', 'Why are alloys harder?'),
  alloy.choice('C16-12', 'Why is an alloy harder than the pure metal it is made from?', ['All its atoms are the same size', 'It has no delocalised electrons', 'Its metallic bonds are much weaker', 'Different-sized atoms distort the layers, so they cannot slide easily'], 3, 'What do the added atoms do to the layers?', ['The added atoms are a different size, so they distort the layers.', 'So the layers cannot slide over each other easily, and the alloy is harder.']),
  alloy.choice('C16-13', 'Which of these is an alloy?', ['Pure copper', 'Steel, which is iron mixed with a little carbon', 'Sodium chloride, a compound of sodium and chlorine', 'Oxygen gas'], 1, 'An alloy is a mixture. What must it contain?', ['An alloy is a mixture of a metal with at least one other element.', 'Steel is iron mixed with carbon, so it is an alloy. Sodium chloride is a compound, not a mixture.']),
  alloy.choice('C16-14', 'Pure gold bends and scratches easily. Jewellers often mix gold with some copper to make rings. Why?', ['Copper makes the gold conduct electricity', 'It makes the gold melt at a lower temperature', 'The different-sized copper atoms distort the layers, so the ring is harder', 'It turns the gold into a compound'], 2, 'What happens to the layers when atoms of another size are added?', ['Copper atoms are a different size from gold atoms, so they distort the layers.', 'So the layers cannot slide easily, and the ring is harder and keeps its shape.'], 'application', true),
  props.choice('C16-15', 'The diagram shows the particles in a metal. Which numbered particles move through the metal to carry electric charge?', ['Particles 1', 'Particles 2', 'Both 1 and 2', 'Neither: nothing moves in a solid'], 1, 'Which particles are free to move, and which stay in rows?', ['Particles 1 are positive metal ions, fixed in a regular pattern. Particles 2 are delocalised electrons, free to move.', 'So particles 2 move through the metal and carry the charge.'], 'understanding', true, 'metal-question'),
  alloy.choice('C16-16', 'A student measured the force needed to dent three samples. Which conclusion does the data support?', ['In this test, both alloys needed more force to dent than pure copper', 'Every alloy is harder than every pure metal', 'Bronze is the best material for every job', 'Pure copper cannot be dented'], 0, 'Does the data cover every metal, or just these three samples?', ['Brass (120 N) and bronze (140 N) needed more force to dent than pure copper (50 N).', 'So in this test the alloys were harder, but three samples cannot show that every alloy is harder than every metal.'], 'dataInterpretation', true, 'metal-dent-data'),
  bond.written('C16-17', 'Use the structure of a metal to explain why metals conduct electricity and have high melting points.', 'Describe the particles first, then the bond between them. Then use them to explain each property.', 'A metal is a giant structure of positive metal ions arranged in a regular pattern. The outer-shell electrons are delocalised, so they are free to move through the whole structure. There is a strong electrostatic attraction between the positive ions and the delocalised electrons: these are metallic bonds. A lot of energy is needed to break these strong bonds, so metals have high melting points. The delocalised electrons can move through the metal carrying electric charge, so metals conduct electricity.', ['A metal is a giant structure of positive metal ions in a regular pattern, with delocalised (free-moving) outer-shell electrons.', 'Metallic bonds are strong electrostatic attractions between the positive metal ions and the delocalised electrons.', 'A lot of energy is needed to break the strong metallic bonds, so the melting point is high.', 'The delocalised electrons move through the metal and carry electric charge, so metals conduct electricity.'], ['Saying the metal ions move to carry the charge.', 'Saying metals are made of small molecules with weak forces between them.', 'Describing a metallic bond as a shared pair of electrons between two atoms.']),
]

export const lessonC16: ScienceLesson = {
  id: 'C-BND-016-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Metallic bonding and alloys', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
