import type { TeachingFrame } from '../../teachingFrame'

// Build one picture of a metal first (atoms → delocalised electrons → positive ions → metallic bond), then use that same
// picture to explain each property in turn: conducting (the moving electrons), high melting points (strong bonds everywhere),
// bending (layers slide), and finally why alloys are harder (different-sized atoms stop the layers sliding).
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const metallicFrames: Record<string, TeachingFrame[]> = {
  'C16-02': [
    f('A giant structure', 'A piece of metal is a huge number of atoms packed in a regular pattern.', 'metal atoms → packed in neat rows → giant structure', 'Metal atoms pack tightly together in neat, repeating rows. Even a tiny piece of metal holds billions of atoms, all bonded to each other. A structure with this many atoms joined in a regular pattern is called a giant structure.', 'metal-bond-atoms'),
    f('Free electrons', 'The outer-shell electrons leave their own atoms.', 'outer electrons → free to move → delocalised', 'Metal atoms have only a few electrons in their outer shell. In a metal, these outer electrons are not held by one atom. They move freely through the whole structure. Electrons that are free to move like this are called delocalised electrons. In the drawing, each atom gives up one electron.', 'metal-bond-free'),
    f('Positive ions', 'The atoms left behind are positive ions.', 'lose outer electrons → positive metal ions', 'Each atom has lost its outer electrons, so it now has more protons than electrons. So it is a positive ion. You met ions when you learned how ions form. The positive metal ions stay in their regular rows.', 'metal-bond-ions'),
    f('Metallic bonds', 'Positive ions and negative electrons attract each other strongly.', 'positive ions + negative electrons → attraction → metallic bond', 'Opposite charges attract. So the positive metal ions and the negative delocalised electrons pull strongly on each other. This is an electrostatic attraction, and it acts in every direction. The strong attraction between metal ions and delocalised electrons is called a metallic bond.', 'metal-bond-bond'),
    f('Put it together', 'Metallic bonds hold the ions in a regular pattern.', 'ions + shared electrons → strong bonds all through the metal', 'A metal is a giant structure of positive ions in a regular pattern. The delocalised electrons are shared by all the ions. The attraction between them makes strong metallic bonds all through the metal. The rest of this lesson uses this one picture to explain how metals behave.', 'metal-bond-whole'),
  ],
  'C16-05': [
    f('Carrying charge', 'Delocalised electrons carry electric charge through a metal.', 'charged electrons free to move → charge flows', 'An electric current is a flow of charge. Delocalised electrons are charged and free to move. When a wire is connected to a cell, they drift through the metal towards the positive end. So they carry charge through the whole structure, while the positive ions stay in place.', 'metal-conduct-charge'),
    f('Carrying heat', 'Delocalised electrons also carry thermal energy.', 'hot end → electrons pass energy along → cold end warms', 'When one end of a metal is heated, the particles there gain energy. The delocalised electrons move through the structure and pass this energy along. So energy spreads quickly from the hot end to the cold end. Energy that heats things up is called thermal energy.', 'metal-conduct-heat'),
    f('Put it together', 'Metals are good conductors of electricity and heat.', 'delocalised electrons → carry charge and energy → good conductor', 'The same delocalised electrons carry both electric charge and thermal energy. So metals are good conductors of electricity and of heat. That is why copper is used for wires and metals are used for saucepans.', 'metal-conduct-uses'),
  ],
  'C16-08': [
    f('Strong bonds', 'Metallic bonds are strong and act in every direction.', 'many strong bonds → lots of energy to break them', 'Every ion in a metal is held by metallic bonds pulling in all directions. To melt the metal, many of these strong bonds must be broken. So a lot of energy is needed to melt a metal, and even more to boil it.', 'metal-shape-strong'),
    f('High melting points', 'Most metals melt only at high temperatures.', 'strong bonds → high melting point → solid at room temperature', 'Because so much energy is needed, most metals have high melting and boiling points. Iron melts at 1538 °C and copper at 1085 °C. Room temperature is only about 25 °C. So most metals are solid at room temperature. Mercury is a rare exception: it is a liquid.', 'metal-shape-melt'),
    f('Layers of atoms', 'In a pure metal, the atoms are arranged in layers.', 'all atoms the same size → flat, neat layers', 'In a pure metal, every atom is of the same element, so they are all the same size. They pack together in flat, neat layers. The drawing shows the layers from the side.', 'metal-shape-layers'),
    f('Layers slide', 'A push makes the layers slide over each other.', 'push → layers slide → metal bends', 'When you push hard on a metal, whole layers of atoms can slide over each other. The delocalised electrons move too and still hold the ions together. So the metal bends into a new shape instead of shattering. This is why metals can be hammered, bent or pressed into shapes.', 'metal-shape-slide'),
  ],
  'C16-11': [
    f('Pure metals are soft', 'Neat layers slide easily, so many pure metals are soft.', 'same-size atoms → layers slide easily → soft', 'The layers in a pure metal slide over each other quite easily. So many pure metals are too soft for everyday jobs. For example, pure gold bends and scratches easily.', 'metal-alloy-pure'),
    f('Alloys', 'Mixing another element into a metal makes an alloy.', 'metal + another element → mixture → alloy', 'Most metals we use are mixed with at least one other element. The other element can be another metal or a non-metal. A mixture like this is called an alloy. Steel is iron with a little carbon, and brass is copper with zinc.', 'metal-alloy-mix'),
    f('Distorted layers', 'Atoms of a different size push the layers out of line.', 'different-sized atoms → layers pushed out of line', 'The added element’s atoms are a different size from the metal’s atoms. They break up the neat rows, so the layers are no longer flat. Layers pushed out of shape like this are called distorted.', 'metal-alloy-distort'),
    f('Harder to slide', 'Distorted layers cannot slide easily, so alloys are harder.', 'distorted layers → catch on each other → harder', 'When you push an alloy, the uneven layers catch on each other. So it is much harder for the layers to slide. This makes an alloy harder than the pure metal it is made from.', 'metal-alloy-hard'),
    f('Put it together', 'Alloys are harder, which makes them more useful.', 'pure metal: layers slide → soft; alloy: layers stuck → harder', 'A pure metal has neat layers that slide, so it is soft. An alloy has distorted layers that do not slide easily, so it is harder. That is why most metal objects, from bike frames to cutlery, are made of alloys. Next, you will see how particles are arranged in solids, liquids and gases.', 'metal-alloy-compare'),
  ],
}
