import type { TeachingFrame } from '../../teachingFrame'

// Three water-based resources in the order of the page: hydro-electric (dam), wave, tidal barrage. Each teaches how it works,
// then pros, then cons, so the pros and cons structure repeats and students can build the same checklist for each one.
// Detail of turbine design is out of scope: the page only asks how each one works, its pros and its cons.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const waterPowerFrames: Record<string, TeachingFrame[]> = {
  'P12-02': [
    f('A dam across a valley', 'Hydro-electric power uses falling water. A big dam is built across a valley, and the valley behind it is flooded.', 'dam, then flooded valley', 'Hydro-electric power uses falling water. A big dam is built across a valley. The valley behind the dam is flooded, so a lot of water is stored high up. Water at a height has energy in its gravitational potential store.', 'waterpow-dam'),
    f('Water through the turbines', 'Water flows out through turbines, and this generates electricity.', 'falling water turns turbines', 'The water is allowed to flow out through pipes. As it falls, energy is transferred from the gravitational potential store to the kinetic store of the water. The moving water turns turbines. The turning turbines generate electricity.', 'waterpow-turbines'),
    f('Good points', 'There is no pollution when the plant is running. The flow of water can be controlled, so the plant can respond straight away to extra demand.', 'no pollution, quick to respond', 'Once a hydro-electric power plant is running, it gives out no pollution. The flow of water can be controlled. So the plant can respond straight away when there is extra demand for electricity. Extra demand means more people want electricity.', 'waterpow-hydro-pros'),
    f('Bad points: cost and flooding', 'The initial costs are high. Flooding the valley has a big impact on the environment.', 'high cost, flooded habitats', 'The initial costs of building the power plant are high. Flooding the valley also has a big impact on the environment. Plants under the water rot and release greenhouse gases, which lead to global warming. Animals and plants also lose their habitats. A habitat is where a living thing lives.', 'waterpow-hydro-cons'),
    f('It needs plenty of rain', 'Hydro-electric power is reliable in areas with high rainfall, but not in dry climates or during a drought.', 'rain fills the reservoir', 'The water behind the dam needs to be topped up by rain. In areas with high rainfall, hydro-electric power is reliable. But it is not suitable in dry climates. It is also unreliable in periods of drought. A drought is a long time with very little rain.', 'waterpow-rain'),
  ],
  'P12-05': [
    f('Turbines turned by waves', 'Waves turn turbines to generate electricity. The turbines have to be in the sea, usually near the coast.', 'waves turn the turbines', 'Wave power uses lots of little wave-powered turbines. The waves turn the turbines, and electricity is generated. The turbines have to be in the sea. It is usually easiest for them to be near the coast.', 'waterpow-wave'),
    f('Good points of wave power', 'There is no pollution. Wave power could be useful on islands, where there is a lot of coastline.', 'no pollution, islands', 'Wave turbines give out no pollution. They could be useful on islands. An island has a lot of coastline, so there is plenty of room for turbines by the sea.', 'waterpow-wave-pros'),
    f('Bad points of wave power', 'Turbines can disturb the seabed and animal habitats. The energy is fairly unreliable. The turbines are difficult and expensive to maintain.', 'habitats, waves die out, upkeep', 'The turbines can disturb the seabed and the habitats of animals. The amount of energy they generate is fairly unreliable. The waves tend to die out when the wind drops. The turbines are also difficult and expensive to maintain. To maintain something means to look after it and repair it.', 'waterpow-wave-cons'),
  ],
  'P12-08': [
    f('A dam across an estuary', 'Tidal barrages are big dams with turbines in them, built across estuaries. Water passing through the turbines generates electricity.', 'barrage across the river mouth', 'A tidal barrage is a big dam with turbines inside it. It is built across an estuary. An estuary is the part of a river that meets the sea. As the tide moves water in and out, the water passes through the turbines. This generates electricity.', 'waterpow-barrage'),
    f('Tides are reliable', 'Tides are caused by the Sun and Moon\'s gravity, and happen twice a day. There is no pollution once a barrage is running.', 'twice a day, no pollution', 'The pull of gravity from the Moon and the Sun causes the tides. The sea level rises and falls twice a day. This always happens, so tides are reliable. There is also no pollution once a barrage is up and running.', 'waterpow-tides'),
    f('Bad points: habitats and places', 'A barrage can change the habitats of wildlife. There are not many suitable estuaries.', 'habitats, few suitable estuaries', 'A barrage can change the habitats of wildlife, such as birds and sea creatures. There are also not many suitable estuaries. So a barrage cannot be built everywhere.', 'waterpow-barrage-cons'),
    f('Tides are not all the same size', 'The amount of energy changes with the tides. Smaller tides do not provide as much energy.', 'big tide, small tide', 'Tides are not all the same size. The amount of energy from a barrage changes with the tides. Smaller tides do not provide as much energy. But the tides themselves always happen.', 'waterpow-tide-size'),
  ],
}
