import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { giantFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.2.2.5 Polymers, 5.2.2.6 Giant covalent structures, 5.2.3.1 Diamond, 5.2.3.2 Graphite, 5.2.3.3 Graphene and fullerenes (with 5.2.1.4 for drawing polymers)' }
const skill = 'C-GIANT-COVALENT'
const recap = author(skill, ['5.2.2.4'], ['aqa-chemistry'])
const poly = author(skill, ['5.2.2.5', '5.2.1.4'], ['aqa-chemistry'])
const giant = author(skill, ['5.2.2.6'], ['aqa-chemistry'])
const carbon = author(skill, ['5.2.3.1', '5.2.3.2'], ['aqa-chemistry'])
const fuller = author(skill, ['5.2.3.3'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const giantSections = [
  { id: 'C15-01', label: 'Start here', detail: 'What breaks when oxygen boils' },
  { id: 'C15-02', label: 'What is a polymer?', detail: 'Long molecules and the repeating unit' },
  { id: 'C15-05', label: 'What is a giant covalent structure?', detail: 'Silicon dioxide and very high melting points' },
  { id: 'C15-08', label: 'How are diamond and graphite different?', detail: 'Four bonds, three bonds and layers' },
  { id: 'C15-11', label: 'What are graphene and fullerenes?', detail: 'One layer, hollow balls and nanotubes' },
  { id: 'C15-14', label: 'On your own', detail: 'Three structures, four solids and a new polymer' },
]

const states: ScienceState[] = [
  { ...recap.choice('C15-01', 'Oxygen, O₂, is a gas at room temperature. When liquid oxygen boils, what is broken?', ['The covalent bond inside each O₂ molecule', 'The weak forces between the O₂ molecules', 'The oxygen atoms themselves'], 1, 'Is oxygen gas still made of O₂ molecules?', ['Oxygen gas is still made of O₂ molecules, so the covalent bonds inside them do not break.', 'So boiling only breaks the weak forces between the molecules, which is why oxygen boils at a low temperature.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(poly, 'C15-02', 'What is a polymer?'),
  poly.choice('C15-03', 'Why are most polymers solid at room temperature?', ['Their molecules are small', 'They contain ions', 'The forces between their long molecules are quite strong', 'Their molecules have no covalent bonds'], 2, 'What is there between the long molecules?', ['Polymer molecules are very long, so the intermolecular forces between them are larger than between small molecules.', 'So more energy is needed to separate them, and most polymers are solid at room temperature.']),
  poly.choice('C15-04', 'PTFE is the polymer on non-stick pans. Its repeating unit is shown. What is the molecular formula of PTFE?', ['(C₂F₄)n', 'C₂F₄', '(C₂H₄)n', '(C₂F₂)n'], 0, 'Count the atoms inside the brackets, then add brackets and n.', ['The repeating unit has 2 carbon atoms and 4 fluorine atoms: C₂F₄.', 'So the formula of the polymer is (C₂F₄)n, where n is a large number.'], 'application', false, 'giant-q-ptfe'),
  t(giant, 'C15-05', 'What is a giant covalent structure?'),
  giant.choice('C15-06', 'Why does silicon dioxide have a very high melting point?', ['Its molecules are very large', 'It contains ions', 'There are weak forces between its molecules', 'Many strong covalent bonds must break to melt it'], 3, 'What holds every atom in place in silicon dioxide?', ['In silicon dioxide, every atom is held by strong covalent bonds. There are no separate molecules.', 'So melting means breaking lots of strong bonds, which takes a lot of energy.']),
  giant.choice('C15-07', 'Which needs more energy to melt, poly(ethene) or silicon dioxide?', ['Poly(ethene), because its molecules are longer', 'Silicon dioxide, because covalent bonds must break', 'Poly(ethene), because its covalent bonds must break', 'Neither: both have covalent bonds, so both melt at the same temperature'], 1, 'What must break to melt each one?', ['To melt poly(ethene), only the forces between its molecules break. To melt silicon dioxide, strong covalent bonds must break.', 'So silicon dioxide needs much more energy to melt.']),
  t(carbon, 'C15-08', 'How are diamond and graphite different?'),
  carbon.choice('C15-09', 'Why is graphite soft and slippery?', ['It has a low melting point', 'Its carbon atoms have no covalent bonds', 'There are no covalent bonds between its layers, so they slide', 'It has delocalised electrons'], 2, 'What is there between the layers?', ['The atoms in each layer are held by strong covalent bonds, but there are no covalent bonds between the layers.', 'So the layers can slide over each other, which makes graphite soft and slippery.']),
  carbon.choice('C15-10', 'Graphite conducts electricity, but diamond does not. Why?', ['Graphite has one delocalised electron from each carbon atom', 'Graphite contains ions', 'Diamond has fewer covalent bonds per atom', 'The bonds in graphite’s layers are weak'], 0, 'How many outer electrons does each carbon atom use in bonds?', ['In graphite, each carbon atom uses three outer electrons in bonds, so one is free to move. In diamond, all four are used in bonds.', 'So graphite has delocalised electrons that carry charge, but diamond has none.']),
  t(fuller, 'C15-11', 'What are graphene and fullerenes?'),
  fuller.choice('C15-12', 'What is graphene?', ['A hollow ball of 60 carbon atoms', 'A polymer made of carbon and hydrogen', 'A form of diamond', 'A single layer of graphite, one atom thick'], 3, 'What do you get if you lift off one sheet of graphite?', ['Graphite is made of layers of carbon hexagons.', 'So one layer on its own, just one atom thick, is graphene.']),
  fuller.choice('C15-13', 'A nanotube is about 1 nanometre wide and 1000 nanometres long. What does this show?', ['It is wider than it is long', 'It has a high length to diameter ratio', 'It is a hollow ball', 'It cannot conduct electricity'], 1, 'How many times longer than its width is it?', ['The nanotube is about 1000 times longer than it is wide.', 'So it has a high length to diameter ratio, like all nanotubes.'], 'dataInterpretation'),
  carbon.choice('C15-14', 'Three structures are shown. Which numbered structure would conduct electricity?', ['Structure 1', 'Structure 2', 'Structure 3', 'None of them'], 2, 'Which carbon atoms have an outer electron not used in a bond?', ['In structure 3, each carbon atom forms only three bonds, so each has one electron free to move. This is graphite.', 'So structure 3 conducts. In structures 1 and 2, every outer electron is used in a bond.'], 'application', true, 'giant-q-structures'),
  giant.choice('C15-15', 'The table shows data for four solids. Which one is most likely to have a giant covalent structure?', ['Solid A', 'Solid B', 'Solid C', 'Solid D'], 0, 'Which one has a very high melting point and never conducts?', ['Solid A melts at 1610 °C and does not conduct, even when melted. That fits a giant covalent structure.', 'B conducts when melted and D conducts as a solid, so they have charged particles that can move. C melts at a low temperature. The data makes A most likely, but does not prove it.'], 'dataInterpretation', true, 'giant-q-data'),
  poly.choice('C15-16', 'The repeating unit of poly(propene) is shown. What is the molecular formula of poly(propene)?', ['(C₂H₄)n', 'C₃H₆', '(C₃H₇)n', '(C₃H₆)n'], 3, 'Count every C and every H inside the brackets.', ['The repeating unit has 3 carbon atoms and 6 hydrogen atoms: C₃H₆.', 'So the polymer is (C₃H₆)n, with brackets round the unit and n after them.'], 'application', true, 'giant-q-propene'),
  carbon.written('C15-17', 'Diamond is used on drill tips for cutting rock; graphite in pencils and electrodes. Explain how their structures suit these uses.', 'For each one, say how many bonds each carbon atom forms, what that does to the structure, and which property it gives.', 'In diamond, each carbon atom forms four strong covalent bonds, making a rigid giant network. So diamond is very hard and has a very high melting point, which suits drill tips for cutting rock. In graphite, each carbon atom forms three covalent bonds in layers. There are no covalent bonds between the layers, so they slide over each other and graphite is soft and slippery, so it rubs off in a pencil. Each carbon atom in graphite also has one delocalised electron, free to move, so graphite conducts electricity, which suits electrodes.', ['In diamond, each carbon atom forms four covalent bonds in a rigid giant network.', 'So diamond is very hard (with a very high melting point), which suits cutting rock.', 'In graphite, each carbon atom forms three bonds in layers, with no covalent bonds between the layers, so the layers slide: soft and slippery for pencils.', 'Graphite has one delocalised electron per carbon atom, free to move, so it conducts electricity, which suits electrodes.'], ['Saying graphite’s layers slide because its covalent bonds are weak.', 'Saying graphite conducts because it contains ions.', 'Saying diamond is hard because of strong forces between molecules.']),
]

export const lessonC15: ScienceLesson = {
  id: 'C-BND-015-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Polymers, giant covalent structures and carbon', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
