import type { TeachingFrame } from '../../teachingFrame'

// Build up in size: long molecules (polymers) first, then structures with no separate molecules at all (giant covalent,
// silicon dioxide), then carbon's two giant structures (diamond, graphite), and last the newer forms made from
// graphite's layer (graphene, fullerenes, nanotubes). Each step reuses the idea before it.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const giantFrames: Record<string, TeachingFrame[]> = {
  'C15-02': [
    f('Small molecules join up', 'Lots of small molecules can join into one very long molecule.', 'many small molecules → one long chain', 'You met small molecules such as oxygen when you learned about covalent bonding. Some small molecules can join together, end to end, thousands of times. This makes one very long molecule. A substance made of very long molecules like this is called a polymer.', 'giant-poly-join'),
    f('Strong bonds all along', 'Every atom in a polymer molecule is held by strong covalent bonds.', 'shared pairs of electrons → strong chain', 'Every atom in the long molecule is joined to its neighbours by covalent bonds. A covalent bond is a shared pair of electrons. These bonds are strong. So a polymer molecule does not easily break apart.', 'giant-poly-bonds'),
    f('Forces between the chains', 'Long molecules attract each other more strongly than small ones do.', 'big molecules → larger forces between them → solid', 'The long molecules lie next to each other. The forces of attraction between them are called intermolecular forces. Because polymer molecules are so big, these forces are larger than between small molecules. So more energy is needed to separate them, and most polymers are solid at room temperature. They are still weaker than covalent bonds, so polymers melt at lower temperatures than ionic compounds such as salt.', 'giant-poly-forces'),
    f('The repeating unit', 'A polymer chain is one small section repeated over and over.', 'same section again and again → repeating unit', 'Poly(ethene) is the polymer used to make plastic bags. Its long chain is the same small section, over and over again. This section has 2 carbon atoms and 4 hydrogen atoms. The section that repeats is called the repeating unit.', 'giant-poly-unit'),
    f('Writing the formula', 'A polymer’s formula is its repeating unit’s formula in brackets, with n.', 'count atoms in the unit → brackets → n', 'To draw a polymer, you draw one repeating unit in brackets. A bond sticks out through each bracket, to join on to the next unit. To write the molecular formula, count the atoms in the unit: C₂H₄. Put brackets round it and write n after them: (C₂H₄)n. The n stands for a large number of units.', 'giant-poly-formula'),
  ],
  'C15-05': [
    f('A giant network', 'In some substances every atom is bonded to its neighbours, with no separate molecules.', 'bonds in every direction → no separate molecules', 'Sand is mostly silicon dioxide, also called silica. In silicon dioxide, each silicon atom is joined to four oxygen atoms by covalent bonds. Each oxygen atom is joined to two silicon atoms. The bonding carries on in every direction, so there are no separate molecules. This is called a giant covalent structure.', 'giant-gc-network'),
    f('Very high melting points', 'To melt a giant covalent substance, strong covalent bonds must break.', 'melt → break strong covalent bonds → lots of energy', 'To melt a giant covalent substance, its atoms must be pulled apart. That means breaking lots of strong covalent bonds. This takes a lot of energy. So giant covalent substances have very high melting and boiling points. Silicon dioxide melts at about 1700 °C.', 'giant-gc-melt'),
    f('No charged particles', 'Most giant covalent substances do not conduct electricity.', 'no ions, no free electrons → no current', 'To conduct electricity, a substance needs charged particles that are free to move. Silicon dioxide has no ions. All its outer electrons are held in bonds, so none are free to move. So it does not conduct electricity. Graphite, a form of carbon, is an exception you will meet next.', 'giant-gc-conduct'),
    f('Put it together', 'What must break to melt a substance depends on its structure.', 'weak forces → larger forces → covalent bonds', 'To melt a simple molecular substance, you only break weak forces between small molecules. To melt a polymer, you break the larger forces between long molecules. To melt a giant covalent substance, you break strong covalent bonds. So melting points go from low, to higher, to very high.', 'giant-gc-compare'),
  ],
  'C15-08': [
    f('Diamond', 'In diamond, each carbon atom is bonded to four others.', '4 bonds per atom → rigid network → very hard', 'Carbon atoms can join up in different ways to make different substances. In diamond, each carbon atom forms four covalent bonds with other carbon atoms. This makes a giant, rigid network. So diamond is very hard. The drawing is flat, but real diamond is a 3D network.', 'giant-diamond'),
    f('No free electrons', 'Diamond has a very high melting point and does not conduct.', 'all outer electrons in bonds → no conduction', 'Melting diamond means breaking lots of strong covalent bonds. So diamond has a very high melting point. Each carbon atom uses all four of its outer electrons in bonds. There are no free electrons and no ions. So diamond does not conduct electricity.', 'giant-diamond-props'),
    f('Graphite', 'In graphite, each carbon atom is bonded to three others in flat sheets.', '3 bonds per atom → rings of six → flat layers', 'Graphite is another form of carbon, used in pencils. Each carbon atom forms three covalent bonds. The atoms make rings of six, called hexagons. The hexagons join up into flat sheets, which are stacked in layers.', 'giant-graphite'),
    f('Layers slide', 'Graphite is soft and slippery because its layers can slide.', 'no bonds between layers → layers slide → soft', 'There are no covalent bonds between the layers, only weak forces. So the layers can slide over each other. This makes graphite soft and slippery. When you write with a pencil, layers rub off onto the paper. The bonds within each layer are strong, so graphite still has a very high melting point.', 'giant-graphite-layers'),
    f('Free electrons', 'Graphite conducts electricity because some electrons can move.', '1 spare electron per atom → free to move → conducts', 'Each carbon atom in graphite uses only three of its four outer electrons in bonds. The fourth electron is free to move along the layer. Electrons that are free to move like this are called delocalised electrons. They can carry charge, so graphite conducts electricity. They also carry heat, a bit like in a metal.', 'giant-graphite-electrons'),
    f('Put it together', 'Diamond and graphite are both carbon, but their bonding gives them different properties.', '4 bonds → hard, no conduction; 3 bonds → soft, conducts', 'Diamond and graphite are both made only of carbon atoms. Diamond has four bonds per atom, so it is very hard and does not conduct. Graphite has three bonds per atom, in layers, so it is soft and does conduct. Both have very high melting points, because both are giant covalent structures.', 'giant-carbon-compare'),
  ],
  'C15-11': [
    f('Graphene', 'Graphene is a single layer of graphite.', 'one layer → strong, light, conducts', 'Imagine lifting off just one layer of graphite. This sheet of carbon hexagons is only one atom thick. It is called graphene. Its covalent bonds make it very strong, and it is also very light. It has delocalised electrons, so it conducts electricity.', 'giant-graphene'),
    f('Fullerenes', 'Some carbon molecules are hollow balls or tubes.', 'hexagons plus rings of 5 or 7 → curved, hollow', 'Carbon atoms can also form molecules shaped like hollow balls or closed tubes. These molecules are called fullerenes. Their atoms are mostly in rings of six. Some rings have five or seven atoms instead, which lets the sheet curve. The first one found was buckminsterfullerene, C₆₀, a hollow ball of 60 carbon atoms.', 'giant-fullerene'),
    f('Nanotubes', 'A nanotube is a fullerene shaped like a very thin tube.', 'tiny cylinder → very long compared with its width', 'Some fullerenes are tiny cylinders of carbon, called nanotubes. A nanotube is very long compared with its diameter. We say it has a high length to diameter ratio. Nanotubes are very strong for how light they are.', 'giant-nanotube'),
    f('Put it together', 'Each form of carbon’s properties suit different uses.', 'property → use', 'Graphene can be added to other materials to make them stronger but hardly heavier. Its free electrons make it useful in electronics. Hollow fullerene balls can carry drugs into the body, and they can be used as catalysts to speed up reactions. Nanotubes are used in electronics and to strengthen materials without adding much weight.', 'giant-carbon-uses'),
  ],
}
