import type { TeachingFrame } from '../../teachingFrame'

// Bio-fuels first (the last renewable), then why non-renewables are still used (reliable), then the environmental problems
// they create, one per frame, ending with a side-by-side summary. Greenhouse gases and air pollution are met in Chemistry, so
// they are recalled in one clause and not explained here.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const biofuelFrames: Record<string, TeachingFrame[]> = {
  'P13-02': [
    f('What a bio-fuel is', 'Bio-fuels are renewable energy resources made from plant products or animal dung.', 'made from living things', 'A bio-fuel is a fuel made from living things. It is made from plant products or from animal dung. Bio-fuels are renewable, because more plants can always be grown. They can be burnt to produce electricity. They can also be used to run cars, in the same way as fossil fuels.', 'biofuel-what'),
    f('Good points of bio-fuels', 'Crops can be grown all year. Extra bio-fuel can be made and stored for when it is needed.', 'grow, store, use', 'Crops for bio-fuel can be grown throughout the year. Extra bio-fuel can be constantly produced and stored. It can then be used when it is needed. This makes bio-fuels a reliable resource.', 'biofuel-pros'),
    f('A bad point: clearing forests', 'Areas of forest are often cleared to grow bio-fuel crops. Plants are destroyed and animals lose their habitats.', 'forest cleared, habitats lost', 'Areas of forest are often cleared to make room to grow bio-fuel crops. This can lead to lots of plants being destroyed. Animals also lose their natural habitats.', 'biofuel-con'),
    f('Carbon dioxide in, carbon dioxide out', 'Bio-fuels release carbon dioxide when burnt, but the plants absorbed carbon dioxide while they were growing.', 'taken in while growing, given out when burnt', 'Bio-fuels release carbon dioxide when they are burnt. But the plants used to make them absorbed a lot of carbon dioxide while they were growing. So the carbon dioxide is taken in first, and given out later. This is one reason that bio-fuels are less harmful to the environment than fossil fuels.', 'biofuel-co2'),
  ],
  'P13-05': [
    f('Fossil fuels and nuclear fuel are reliable', 'Fossil fuels and nuclear fuel are reliable. There is enough of them to meet current demand.', 'reliable, enough for now', 'Fossil fuels and nuclear fuel are reliable energy resources. There is enough of them to meet current demand. That is why they are still used so much. The three main fossil fuels are coal, oil and natural gas.', 'biofuel-reliable'),
    f('Always some in stock', 'A power plant has a stock of fuel, so it can respond quickly to changes in demand.', 'a stock of fuel to hand', 'Power plants keep a stock of these fuels. So there is always some fuel ready to use. A power plant can then respond quickly to changes in demand. That means it can make more electricity when more people want it.', 'biofuel-stock'),
    f('But they are running out', 'These fuels are slowly running out. Some fossil fuels may run out within a hundred years, if no new ones are found.', 'non-renewable means it can run out', 'However, these fuels are non-renewable. They are slowly running out. Some fossil fuels may run out within a hundred years, if no new ones are found. Once they are used up, they cannot be replaced.', 'biofuel-running-out'),
  ],
  'P13-08': [
    f('Global warming', 'Burning coal, oil and gas releases carbon dioxide into the atmosphere. This leads to global warming.', 'carbon dioxide, then warming', 'When coal, oil and gas are burnt, they release carbon dioxide into the atmosphere. Carbon dioxide is a greenhouse gas, which you may have met in Chemistry. Greenhouse gases cause the Earth to warm up. This is called global warming.', 'biofuel-warming'),
    f('Acid rain', 'Burning coal and oil also releases sulfur dioxide, which causes acid rain.', 'sulfur dioxide, then acid rain', 'Burning coal and oil also releases a gas called sulfur dioxide. This gas causes acid rain. Acid rain makes lakes and rivers acidic, which can kill animals and plants. It can also damage trees and soils.', 'biofuel-acid'),
    f('Damaged habitats', 'Coal mining makes a mess of the landscape and destroys habitats. Oil spills harm sea creatures.', 'mining, spills', 'Coal mining makes a mess of the landscape. It also destroys the habitats of local animals and plants. Oil spills cause big environmental problems. They harm sea creatures.', 'biofuel-habitat'),
    f('Nuclear power and radiation', 'Nuclear power is clean, but nuclear waste is very dangerous and hard to get rid of. There is a risk of a big accident.', 'clean but dangerous waste', 'Nuclear power does not release carbon dioxide, so it is clean. But nuclear waste is very dangerous, and it is difficult to get rid of. There is also a risk of a big accident that could release a lot of radiation. Radiation can be very dangerous to humans.', 'biofuel-nuclear'),
    f('The problems side by side', 'Each non-renewable resource creates its own problems for the environment.', 'four problems, four causes', 'Here are the problems side by side. Burning coal, oil and gas releases carbon dioxide, which leads to global warming. Burning coal and oil also releases sulfur dioxide, which causes acid rain. Mining and oil spills destroy habitats. Nuclear power brings the risk of radiation.', 'biofuel-whole'),
  ],
}
