import type { TeachingFrame } from '../../teachingFrame'

// Builds on acids making H⁺ ions and the pH scale (pH and neutralisation) and on concentration (solutions), without
// re-teaching them. Each teaching section keeps one drawing on screen and changes it frame by frame: two beakers of acid
// (hydrochloric and ethanoic) for strong and weak, one pH strip with ×10 hops for hydrogen ions, and beakers of acid
// sorted by strength and concentration. The last frame of each puts the ideas together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const acidStrengthFrames: Record<string, TeachingFrame[]> = {
  'C22H-02': [
    f('Acids split into ions', 'In water, acid particles split up and release hydrogen ions, H⁺.', 'acid in water → splits → H⁺ ions', 'You met hydrogen ions when you learned about the pH scale. Every acid makes H⁺ ions in water. Each acid particle splits into an H⁺ ion and a negative ion. For hydrochloric acid, HCl → H⁺ + Cl⁻. Splitting up into ions like this is called ionising.', 'hacid-strong-ionise'),
    f('Strong acids', 'A strong acid ionises completely in water.', 'strong → every particle ionises', 'In hydrochloric acid, every HCl particle splits into ions. None are left whole. An acid that ionises completely in water is called a strong acid. Hydrochloric acid, nitric acid and sulfuric acid are strong acids.', 'hacid-strong-strong'),
    f('Weak acids', 'A weak acid only partly ionises in water.', 'weak → only a few particles ionise', 'Ethanoic acid is the acid in vinegar. In water, only a few of its molecules split into ions. Most stay whole. An acid that only partly ionises is called a weak acid. Ethanoic acid, citric acid and carbonic acid are weak acids.', 'hacid-strong-weak'),
    f('Both ways at once', 'A weak acid ionises in a reversible reaction, shown by ⇌.', 'molecules ⇌ ions, both ways', 'In ethanoic acid, some molecules split into ions. At the same time, some ions join back up into molecules. A reaction that goes both ways is reversible. We show it with the sign ⇌: CH₃COOH ⇌ H⁺ + CH₃COO⁻. Most of the acid stays as whole molecules.', 'hacid-strong-reversible'),
    f('Put it together', 'Strong acids ionise completely; weak acids only partly, so they release fewer H⁺ ions.', 'strong → all ionise · weak → a few ionise', 'Both beakers hold the same number of acid particles. The strong acid has ionised completely, so it has lots of H⁺ ions. The weak acid has only partly ionised, so it has far fewer H⁺ ions. Strong and weak describe how much an acid ionises.', 'hacid-strong-together'),
  ],
  'C22H-06': [
    f('More H⁺, lower pH', 'The more H⁺ ions in a volume of solution, the lower the pH.', 'more H⁺ ions → lower pH', 'The pH scale measures how many H⁺ ions there are in a certain volume of solution. This is the concentration of H⁺ ions. The more H⁺ ions, the lower the pH. A solution at pH 1 has far more H⁺ ions than a solution at pH 6.', 'hacid-ph-more'),
    f('Ten times for each step', 'Each step down the pH scale means 10 times the H⁺ ion concentration.', 'one pH step down → × 10', 'The steps on the pH scale are not equal amounts of H⁺. Each step down the scale multiplies the H⁺ ion concentration by 10. So a solution at pH 3 has 10 times the H⁺ ions of a solution at pH 4.', 'hacid-ph-ten'),
    f('Count the steps', 'For more than one step, multiply by 10 once for each step.', 'two steps down → 10 × 10 = 100', 'From pH 4 down to pH 2 is two steps. The first step multiplies the H⁺ concentration by 10. The second step multiplies it by 10 again. So pH 2 has 10 × 10 = 100 times the H⁺ ions of pH 4.', 'hacid-ph-steps'),
    f('Going up the scale', 'Each step up the pH scale divides the H⁺ ion concentration by 10.', 'one pH step up → ÷ 10', 'It works the other way too. Each step up the pH scale divides the H⁺ ion concentration by 10. So a solution at pH 3 has 10 times fewer H⁺ ions than a solution at pH 2.', 'hacid-ph-up'),
    f('Put it together', 'The factor the H⁺ concentration changes by is 10⁻ˣ, where X is the change in pH.', 'X = final pH − initial pH · factor = 10⁻ˣ', 'You can write the rule as a formula: factor = 10⁻ˣ. X is the difference in pH: final pH − initial pH. From pH 4 to pH 2, X = 2 − 4 = −2. So the factor is 10⁻⁽⁻²⁾ = 10² = 100, the same as counting two steps.', 'hacid-ph-formula'),
  ],
  'C22H-12': [
    f('How much acid', 'Concentration is how much acid is dissolved in a certain volume of water.', 'more acid in the same volume → more concentrated', 'You met concentration when you learned about solutions. It is how much acid is dissolved in a certain volume. A solution with lots of acid in the volume is concentrated. A solution with only a little acid is dilute.', 'hacid-conc-amount'),
    f('How much it ionises', 'Strength is how much of the acid ionises, whatever the amount.', 'strong or weak → how much ionises', 'Strength is a different idea. These two beakers hold the same amount of acid, so they have the same concentration. But the strong acid has ionised completely, and the weak acid has hardly ionised. Strength tells you how much of the acid ionises.', 'hacid-conc-strength'),
    f('Same concentration, different pH', 'At the same concentration, a stronger acid has a lower pH.', 'same concentration → strong acid → more H⁺ → lower pH', 'At the same concentration, the strong acid releases far more H⁺ ions. So it has a lower pH. Here the hydrochloric acid is about pH 1 and the ethanoic acid is about pH 3. For a given concentration, the stronger the acid, the lower the pH.', 'hacid-conc-ph'),
    f('Four kinds of acid solution', 'An acid can be dilute and strong, or concentrated and weak.', 'concentration and strength → two separate questions', 'Because they are separate ideas, you can have any mix. A dilute solution of a strong acid has only a little acid, but all of it is ionised. A concentrated solution of a weak acid has lots of acid, but only a few particles are ionised.', 'hacid-conc-grid'),
    f('Put it together', 'Strength is how much ionises; concentration is how much acid. More concentrated means a lower pH.', 'strong ≠ concentrated · weak ≠ dilute', 'Strong and weak are about how much the acid ionises. Concentrated and dilute are about how much acid is in the volume. Making any acid more concentrated adds more H⁺ ions to the same volume. So its pH goes down, whether it is strong or weak.', 'hacid-conc-together'),
  ],
}
