import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { mixtureFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.1.1.2 Mixtures (mixtures, unchanged properties, separation by physical processes including paper chromatography); 5.1.1.1 Atoms, elements and compounds (compounds for contrast)' }
const skill = 'C-MIXTURES'
const mixtures = author(skill, ['5.1.1.2', '5.1.1.1'], ['aqa-chemistry'])
const properties = author(skill, ['5.1.1.2'], ['aqa-chemistry'])
const separating = author(skill, ['5.1.1.2', '5.1.1.1'], ['aqa-chemistry'])
const chromatography = author(skill, ['5.1.1.2'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const mixtureSections = [
  { id: 'C3-01', label: 'Start here', detail: 'Paper clips in the rice' },
  { id: 'C3-02', label: 'What is a mixture?', detail: 'Mixed, but not chemically combined' },
  { id: 'C3-05', label: 'Does each part change?', detail: 'Each part keeps its own properties' },
  { id: 'C3-08', label: 'How can you separate a mixture?', detail: 'Physical methods make no new substances' },
  { id: 'C3-10', label: 'Set up paper chromatography', detail: 'Pencil line, ink spot, solvent and lid' },
  { id: 'C3-13', label: 'Read a chromatogram', detail: 'Spots, speeds and the solvent front' },
  { id: 'C3-16', label: 'On your own', detail: 'A green ink, sea water and three pens' },
]

const states: ScienceState[] = [
  { ...mixtures.choice('C3-01', 'Some steel paper clips fall into a tub of dry rice. What is the quickest way to get them out?', ['Pull them out with a magnet', 'Cook the rice until the clips melt', 'You cannot, because the clips and rice have joined together'], 0, 'Is steel or rice attracted to a magnet?', ['The clips and the rice are only mixed. They have not joined together.', 'Steel is attracted to a magnet and rice is not, so a magnet can pull the clips out.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(mixtures, 'C3-02', 'What is a mixture?'),
  mixtures.choice('C3-03', 'Each box shows the particles in a substance. Which box shows a mixture?', ['Box 1', 'Box 2', 'Box 3'], 2, 'Look for different particles that are not joined to each other.', ['Box 1 has hydrogen and oxygen atoms bonded together, so it is a compound. Box 2 has only one kind of atom, so it is an element.', 'Box 3 has hydrogen particles and oxygen particles that are not joined to each other, so it is a mixture.'], 'understanding', false, 'mix-boxes-question'),
  mixtures.choice('C3-04', 'What is the difference between a mixture and a compound?', ['A mixture contains only elements, never compounds', 'Only a compound has chemical bonds between its parts', 'The parts of a mixture are held together by chemical bonds', 'A compound contains only one kind of atom'], 1, 'Which one has chemical bonds holding its parts together?', ['In a compound, atoms of different elements are joined by chemical bonds.', 'In a mixture, the parts are together but not chemically combined, so there are no bonds between them.']),
  t(properties, 'C3-05', 'Does each part change?'),
  properties.choice('C3-06', 'Iron filings and sulfur powder are stirred together. Which statement is true?', ['A new substance has formed', 'The iron and sulfur are now joined by chemical bonds', 'The iron is still attracted to a magnet', 'The iron has lost its own properties'], 2, 'Does stirring change the iron itself?', ['Stirring only mixes the iron and sulfur. No new substance forms and no bonds are made.', 'So the iron keeps its own properties, and it is still attracted to a magnet.']),
  properties.choice('C3-07', 'Air is a mixture. Why can the oxygen in air still help things burn?', ['The oxygen keeps its own properties in the mixture', 'The oxygen is bonded to the nitrogen in air', 'Air is a compound of oxygen and nitrogen'], 0, 'What happens to the properties of each part of a mixture?', ['Air is a mixture, so the oxygen is not bonded to the other gases.', 'So the oxygen keeps its own properties, including helping things burn.']),
  t(separating, 'C3-08', 'How can you separate a mixture?'),
  separating.choice('C3-09', 'Why is filtration called a physical method?', ['It breaks chemical bonds', 'It uses a chemical reaction', 'It turns a mixture into a compound', 'It makes no new substances'], 3, 'What do all the ways of separating a mixture have in common?', ['A physical method separates the parts of a mixture without a chemical reaction.', 'So no new substances are made: you get back the same substances that were mixed.']),
  t(chromatography, 'C3-10', 'Set up paper chromatography'),
  chromatography.choice('C3-11', 'Why is the start line drawn in pencil, not in pen?', ['Pencil is easier to see', 'Pencil does not dissolve in the solvent', 'Pen ink would stop the solvent moving', 'Pencil helps the dyes dissolve'], 1, 'What would happen to a line of pen ink when the solvent reached it?', ['Pen ink could dissolve in the solvent and run up the paper with the dyes.', 'Pencil does not dissolve, so the line stays where it is.']),
  chromatography.choice('C3-12', 'Why must the solvent be below the pencil line when the paper goes in?', ['So the lid fits on the beaker', 'So the solvent evaporates faster', 'So the dyes move faster', 'So the ink does not dissolve into the pool of solvent'], 3, 'Where would the ink go if it sat under the solvent?', ['If the spot were under the solvent, the ink would dissolve into the liquid in the beaker.', 'With the solvent below the line, the solvent soaks up to the ink and carries it up the paper.']),
  t(chromatography, 'C3-13', 'Read a chromatogram'),
  chromatography.choice('C3-14', 'A brown food colouring gives three spots, with nothing left on the pencil line. How many dyes does it show?', ['1', '2', '3', '4'], 2, 'How many spots does each dye make?', ['Each dye makes one spot in its own place.', 'There are three spots and none on the line, so the chromatogram shows three dyes.'], 'application'),
  chromatography.choice('C3-15', 'After chromatography, one spot of a red ink is still on the pencil line. Why?', ['That dye is insoluble in the solvent', 'That dye moved the fastest', 'The pencil soaked up that dye', 'The solvent front stopped that dye'], 0, 'Which dyes are carried up by the solvent?', ['The solvent carries up only the dyes that dissolve in it.', 'A dye that is insoluble in the solvent is not carried up, so it stays on the pencil line.']),
  chromatography.choice('C3-16', 'This chromatogram is from a green ink. Which numbered part is a dye that did not dissolve in the solvent?', ['Part 1', 'Part 2', 'Part 3'], 1, 'Where does a dye stay if the solvent cannot carry it?', ['Part 1 is the solvent front and part 3 is a dye that moved up the paper.', 'Part 2 is still on the pencil line, so it is a dye that did not dissolve in the solvent.'], 'understanding', true, 'mix-gram-question'),
  separating.choice('C3-17', 'Sea water is a mixture of water and dissolved salts. Which statement about separating it is correct?', ['The salts are bonded to the water, so a reaction is needed', 'Separating it makes new substances', 'It is a compound, because it contains more than one substance', 'The water can be separated by a physical method, making no new substances'], 3, 'Are the salts and the water chemically combined?', ['Sea water is a mixture, so the salts and the water are not bonded to each other.', 'So they can be separated by a physical method, and no new substances are made.'], 'application', true),
  chromatography.choice('C3-18', 'Three inks, A, B and C, were tested on one sheet. Which conclusion does this chromatogram support?', ['Ink A contains no dyes', 'Ink B contains at least three different dyes', 'All the dyes in ink C dissolve in the solvent', 'Ink B is a compound of three dyes'], 1, 'Count the spots for each ink, including any on the pencil line.', ['Ink B gives three spots, and each dye makes its own spot, so ink B contains at least three dyes.', 'Ink A gives one spot, so it has a dye. Ink C has a spot left on the line, so one of its dyes did not dissolve.'], 'dataInterpretation', true, 'mix-pens'),
  chromatography.written('C3-19', 'Black ink is a mixture of dyes. Explain why paper chromatography can separate the dyes, and what the chromatogram shows.', 'Think about bonds between the dyes, how fast each dye moves, and what each spot means.', 'The dyes in the ink are mixed, not chemically combined, so there are no bonds between them and a physical method can separate them without making new substances. Each dye keeps its own properties, so each one moves up the paper with the solvent at its own speed. The dyes end up in different places, with one spot for each dye. A dye that is insoluble in the solvent is not carried up, so it stays on the pencil line.', ['The dyes are mixed, not chemically combined, so a physical method can separate them and no new substances form.', 'Each dye keeps its own properties, so each moves up the paper at a different speed.', 'The dyes end up in different places: one spot for each dye.', 'A dye that is insoluble in the solvent stays on the pencil line.'], ['Saying the dyes react with the solvent to make new substances.', 'Saying black ink is a compound of dyes.', 'Saying an insoluble dye moves furthest up the paper.']),
]

export const lessonC3: ScienceLesson = {
  id: 'C-ATM-003-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Mixtures and chromatography', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
