import type { TeachingFrame } from '../../teachingFrame'

// Define a mixture against the element and compound the student already knows (iron, sulfur, iron sulfide),
// then show that each part keeps its properties, which is why physical methods can separate it. Chromatography
// comes last: it needs "mixture", "no new substances" and "each part keeps its own properties" (its own speed).
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const mixtureFrames: Record<string, TeachingFrame[]> = {
  'C3-02': [
    f('Elements and compounds', 'You have already met elements and compounds.', 'element → one kind of atom; compound → different atoms bonded', 'An element is made of only one kind of atom, like iron. You met compounds when you learned about formulas and equations. In a compound, atoms of different elements are joined by chemical bonds. Iron sulfide is a compound of iron and sulfur.', 'mix-kinds-recap'),
    f('Mixed, not joined', 'Substances can be mixed without joining together.', 'together but not chemically combined → mixture', 'Stir iron powder and sulfur powder together. The iron and sulfur are now mixed, but they have not joined. Two or more elements or compounds that are together but not chemically combined are called a mixture.', 'mix-kinds-mixture'),
    f('No bonds', 'Nothing holds the parts of a mixture together.', 'mixture → no chemical bonds between the parts', 'In a compound, chemical bonds hold the different atoms together in a fixed pattern. In a mixture, there are no chemical bonds between the different parts. The grains of iron and grains of sulfur just sit side by side. So the parts of a mixture can be separated quite easily.', 'mix-kinds-bonds'),
    f('Air', 'Air is a mixture of gases.', 'air → nitrogen, oxygen, argon, carbon dioxide', 'Air is a mixture of different gases. It is mainly nitrogen and oxygen, with a little argon and carbon dioxide. Nitrogen, oxygen and argon are elements, and carbon dioxide is a compound. So a mixture can hold elements and compounds together.', 'mix-examples-air'),
    f('Crude oil', 'Crude oil is a mixture of many compounds.', 'crude oil → many different compounds', 'Crude oil is a thick, dark liquid found underground. It is a mixture of many different compounds. Most of them are made of carbon and hydrogen atoms, in chains of different lengths. These compounds are not bonded to each other, so they can be separated.', 'mix-examples-crude'),
  ],
  'C3-05': [
    f('Properties', 'Every substance has its own features.', 'what it is like + how it behaves → properties', 'Iron is grey and is attracted to a magnet. Sulfur is yellow and is not attracted to a magnet. What a substance is like and how it behaves are called its properties. Melting point and hardness are properties too.', 'mix-props-look'),
    f('Each part stays the same', 'In a mixture, each part keeps its own properties.', 'mixture → each part unchanged', 'Mixing iron and sulfur does not change either of them. You can still see grey bits of iron and yellow bits of sulfur. A magnet still picks out the iron and leaves the sulfur behind. So each part of a mixture keeps its own properties.', 'mix-props-magnet'),
    f('A compound is different', 'A compound has new properties of its own.', 'heat → reaction → new substance, new properties', 'If iron and sulfur are heated strongly, they react. They make iron sulfide, a new substance. It is a compound, and its properties are different from those of iron and of sulfur. This is not a mixture any more.', 'mix-props-react'),
  ],
  'C3-08': [
    f('Getting the parts back', 'A mixture can be separated without a reaction.', 'no reaction, no new substances → physical method', 'There are no bonds between the parts of a mixture. So you can separate them without a chemical reaction. Pulling iron out with a magnet is one example. Ways of separating that make no new substances are called physical methods.', 'mix-sep-physical'),
    f('Five main methods', 'Chemists choose a physical method to suit the mixture.', 'filtration, crystallisation, simple and fractional distillation, chromatography', 'Different mixtures need different physical methods. The main ones are filtration, crystallisation, simple distillation, fractional distillation and chromatography. You will learn the first four in the next lesson. The rest of this lesson is about chromatography.', 'mix-sep-methods'),
    f('Put it together', 'A physical method cannot split up a compound.', 'mixture → physical method; compound → only a reaction', 'The iron and sulfur in iron sulfide are held together by chemical bonds. So a magnet cannot pull the iron out of it. Physical methods cannot separate a compound into its elements. Only a chemical reaction can do that.', 'mix-sep-compare'),
  ],
  'C3-10': [
    f('Paper chromatography', 'Ink is often a mixture of coloured dyes.', 'dyes carried up paper → chromatography', 'Many inks are a mixture of different coloured dyes. One way to separate the dyes is to let a liquid carry them up a sheet of paper. This method is called paper chromatography. You will do it in class, and this lesson helps you get ready.', 'mix-chrom-intro'),
    f('A pencil line', 'The start line is drawn in pencil.', 'pencil → does not dissolve, so it stays put', 'Draw a line near the bottom of a sheet of filter paper. Use a pencil, not a pen. Pencil marks do not dissolve, so the line will not run up the paper.', 'mix-chrom-line'),
    f('A spot of ink', 'The ink goes on the pencil line.', 'small spot of ink → on the line', 'Put a small spot of the ink on the middle of the pencil line. A small, neat spot gives the clearest result.', 'mix-chrom-spot'),
    f('The solvent', 'A shallow layer of liquid goes in the beaker.', 'liquid that dissolves things → solvent; keep it below the line', 'A liquid that dissolves other substances is called a solvent. Pour a shallow layer of solvent into a beaker. Water often works, but sometimes another solvent, like ethanol, is needed. Hang the paper so it dips in, with the ink above the solvent. Otherwise the ink would dissolve into the pool of solvent.', 'mix-chrom-solvent'),
    f('A lid', 'A lid goes on top of the beaker.', 'lid → solvent does not evaporate', 'Put a lid on the beaker. The lid stops the solvent evaporating, so it can soak steadily up the paper.', 'mix-chrom-lid'),
    f('Let it run', 'The solvent moves up and carries the ink with it.', 'solvent soaks up → dyes carried up → take out, dry', 'The solvent slowly soaks up the paper and carries the ink with it. When the solvent has nearly reached the top, take the paper out and let it dry. In class, follow your teacher’s safety rules. Some solvents, like ethanol, catch fire easily, so keep them away from flames.', 'mix-chrom-run'),
  ],
  'C3-13': [
    f('Different speeds', 'Each dye moves up the paper at its own speed.', 'different speeds → dyes spread apart', 'As the solvent moves up, it carries the dyes with it. Each dye moves at a different speed. So the dyes spread apart and separate from each other.', 'mix-gram-speeds'),
    f('One spot per dye', 'Each dye ends up as a spot in its own place.', 'one spot for each dye → chromatogram', 'When the paper dries, each dye is left as a spot in a different place. There should be one spot for each dye in the ink. The pattern of spots on the paper is called a chromatogram.', 'mix-gram-spots'),
    f('A dye that stays put', 'A dye that does not dissolve stays on the line.', 'does not dissolve → insoluble → stays on the line', 'Sometimes a dye does not dissolve in the solvent. A substance that does not dissolve is called insoluble. The solvent cannot carry an insoluble dye, so it stays on the pencil line. It still counts as one of the dyes.', 'mix-gram-insoluble'),
    f('The solvent front', 'The solvent reaches a highest point.', 'furthest the solvent got → solvent front', 'The solvent keeps soaking up until you take the paper out. The furthest point the solvent reaches is called the solvent front. Every dye that dissolved is somewhere below it.', 'mix-gram-front'),
    f('Put it together', 'The chromatogram shows the dyes in the ink.', 'count every spot, including any on the line', 'This black ink gave four spots, so it contains four dyes. Three dyes dissolved and moved up at different speeds. The yellow dye moved fastest, so it is nearest the solvent front. One dye is insoluble in this solvent, so it stayed on the pencil line.', 'mix-gram-all'),
  ],
}
