import type { TeachingFrame } from '../teachingFrame'

// One meal all the way through: break it down, absorb it, then test a sample of it.
// One new word per screen. Plain meaning first, then the GCSE term.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const digestionFrames: Record<string, TeachingFrame[]> = {
  'B9-02': [
    f('One meal', 'A cheese sandwich contains starch, protein and fat.', 'bread, cheese, butter', 'Bread is mostly starch. Cheese contains protein and fat. Butter is mostly fat. Fats and oils are called lipids. You met the digestive system, where this meal travels, when you learned about organ systems.', 'digestive-all'),
    f('Too big to get through', 'Food molecules must be made small before they can get into the blood.', 'large → small and soluble', 'Starch, protein and lipid molecules are large. They cannot pass through the wall of the gut. Enzymes break them into small molecules that dissolve in water. Breaking food down like this is called digestion.', 'digestion-size'),
    f('Starch becomes sugars', 'Carbohydrases break carbohydrates into simple sugars.', 'starch → sugars', 'Starch is a carbohydrate. Enzymes that break carbohydrates into simple sugars are called carbohydrases. Amylase is a carbohydrase. It breaks the starch in the bread into sugars.', 'digestion-amylase'),
    f('Protein becomes amino acids', 'Proteases break proteins into amino acids.', 'protein → amino acids', 'The cheese contains protein. Enzymes that break proteins into amino acids are called proteases. Amino acids are small and soluble.', 'digestion-protease'),
    f('Fat becomes glycerol and fatty acids', 'Lipases break lipids into glycerol and fatty acids.', 'lipid → glycerol + fatty acids', 'The butter and cheese contain lipids. Enzymes that break lipids down are called lipases. Lipase breaks each lipid into glycerol and fatty acids.', 'digestion-lipase'),
    f('Put the meal together', 'Each kind of food has its own group of enzymes.', 'three foods → three enzyme groups', 'Carbohydrases turn starch into sugars. Proteases turn protein into amino acids. Lipases turn lipids into glycerol and fatty acids. Enzymes speed up each of these reactions, as you saw when you learned about enzymes.', 'digestion-together'),
  ],
  'B9-05': [
    f('In the mouth', 'Salivary glands make amylase, so starch digestion starts as you chew.', 'mouth → amylase', 'Glands in your mouth make saliva. They are called salivary glands. Saliva contains amylase. So the starch in the bread starts to break down in your mouth.', 'digestive-upper'),
    f('In the stomach', 'The stomach makes a protease, so protein digestion starts here.', 'stomach → protease + acid', 'The stomach makes a protease. So the protein in the cheese starts to break down here. The stomach also makes an acid, called hydrochloric acid.', 'digestive-upper'),
    f('In the small intestine', 'The pancreas and small intestine make all three kinds of enzyme.', 'small intestine → digestion finishes', 'The pancreas is an organ next to the stomach. It makes amylase, proteases and lipases, and sends them into the small intestine. The small intestine makes all three too. So all three work here, and digestion finishes here.', 'digestive-all'),
    f('Put the route together', 'Where an enzyme is made is not always where it works.', 'made in → works in', 'Amylase works in the mouth and the small intestine. Proteases work in the stomach and the small intestine. Lipases work only in the small intestine. Lipases are made only in the pancreas and small intestine.', 'enzyme-sites'),
  ],
  'B9-07': [
    f('Bile joins in', 'Bile is made in the liver and stored in the gall bladder.', 'make → store → release', 'The liver makes a liquid called bile. The gall bladder stores it. Bile is released into the small intestine, where it helps fat digestion. Bile is not an enzyme.', 'bile-route'),
    f('Bile cancels out the acid', 'Bile is alkaline, so it neutralises stomach acid.', 'acid + alkali → neutral', 'Food arriving from the stomach contains hydrochloric acid. Bile is alkaline. Cancelling out an acid like this is called neutralising it. So the small intestine becomes alkaline, where its enzymes work well.', 'digestive-bile'),
    f('Bile breaks up fat', 'Bile breaks big drops of fat into many tiny droplets.', 'one big drop → many small droplets', 'Fat does not mix with water, so it forms big drops. Bile breaks these into many tiny droplets. This is called emulsification.', 'bile-emulsify'),
    f('Why tiny droplets help', 'Tiny droplets give lipase more surface to work on.', 'more surface area → faster', 'Many tiny droplets have far more surface area than one big drop. So lipase can work on more fat at once, and fat is digested faster. Emulsification does not chemically digest the fat. Lipase still does that.', 'bile-emulsify'),
    f('Into the blood', 'Small soluble molecules pass through the gut wall into the blood.', 'small intestine → blood', 'Now the meal is small soluble molecules: sugars, amino acids, glycerol and fatty acids. They pass through the wall of the small intestine into the blood. This is called absorption. Tiny folds in the wall give a large surface for it.', 'exchange-intestine'),
    f('Put it together', 'Digest the meal, then absorb it into the blood.', 'digest → absorb → carried to cells', 'Enzymes digest the sandwich into small soluble molecules. Bile helps with the fat. The small molecules are absorbed into the blood. The blood carries them to cells all over the body. So food gets into the blood. Next, you will see how oxygen gets in, through the lungs.', 'digestion-absorption'),
  ],
  'B9-11': [
    f('Safety first', 'Heating and test chemicals need teacher supervision.', 'risk assessment and eye protection', 'This lesson prepares you for required practical 3. It does not replace doing it. Do not perform these tests at home. Follow the school risk assessment and wear the required eye protection. Use a water bath or other equipment exactly as instructed. Reagents must be handled and disposed of safely.', 'food-safety'),
    f('Prepare the sample', 'Crush the food with water to make a sample to test.', 'one sample, several tests', 'In a supervised laboratory, crush a little of the sandwich with distilled water. Filter it if the test needs a clear liquid. Follow your teacher’s exact method. A chemical you add to test for something is called a reagent.', 'food-sample'),
    f('Test for sugar', 'Benedict’s solution tests for sugars such as glucose.', 'blue → green, yellow, orange or brick-red', 'Sugars that Benedict’s solution detects are called reducing sugars. Add Benedict’s solution and heat it in a hot water bath. Staying blue means no sugar was found. Green, yellow, orange or brick-red means sugar is present. The colour depends on how much.', 'food-benedict'),
    f('Test for starch', 'Iodine solution tests for starch.', 'brown-orange → blue-black', 'Add a few drops of iodine solution to the sample. Staying brown-orange means no starch was found. Blue-black means starch is present.', 'food-iodine'),
    f('Test for protein', 'Biuret reagent tests for protein.', 'blue → lilac or purple', 'Add Biuret reagent safely and mix as instructed. Staying blue means no protein was found. Lilac or purple means protein is present.', 'food-biuret'),
  ],
  'B9-14': [
    f('Test for fat', 'Ethanol and water test for lipids.', 'cloudy white = lipid', 'The current AQA handbook uses ethanol and water for a lipid test. Mix the sample with ethanol, then add the liquid to water. A cloudy white layer means lipid is present. This cloudy mixture is called an emulsion.', 'food-lipid'),
    f('Keep ethanol away from flames', 'Ethanol catches fire very easily.', 'flammable → no flames', 'Ethanol is highly flammable, so it must be kept away from flames. Never use ethanol near a Bunsen burner. Follow the school risk assessment.', 'food-safety'),
    f('Another fat test', 'Some schools use a red dye instead of ethanol.', 'follow the method you are given', 'Some school methods use Sudan III instead. It is a red dye that stains fats red. Follow the method named in the question or by the teacher.', 'food-lipid'),
    f('See first, then decide', 'Write down what you see before you say what it means.', 'observation → conclusion', 'What you see, such as a colour or a cloudy layer, is called an observation. What it tells you is the conclusion. The observation is your evidence, so record it first. Record the starting colour too.', 'food-sample'),
    f('Put the tests together', 'One sample can contain several kinds of food.', 'one test, one result, one conclusion', 'Match each result to its own test. Do not decide from how the food looks. A known positive and a known negative sample help check that the reagents worked. So you can find out what the sandwich contained.', 'food-results'),
  ],
}
