'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckSquare, Layers, Lightbulb, RotateCcw } from 'lucide-react'
import { CellModel } from '../components/CellModel'
import { AreaModel, BacterialCellModel, PlantCellModel } from '../components/OtherCellModels'
import { alignmentRows, cardGroups, practiceTasks, revisionCards, sourceReview, specificationUrl, type CardGroup } from './content'
import { newRevisionSession, restoreRevisionSession, revisionReducer, REVISION_STORAGE_KEY, type RevisionAction, type RevisionSession } from './engine'
import '../coach/ScienceCoach.css'
import './ExamRevision.css'

type View = 'home' | 'cards' | 'practice' | 'alignment'
const href = (view: View, id?: string) => `/preview/scienceB${view === 'home' ? '' : '?view=' + view}${id ? '&' + (view === 'cards' ? 'card' : 'task') + '=' + encodeURIComponent(id) : ''}`
export default function ExamRevisionPreview({ view, initialCard, initialTask, initialReviewOnly = false }: { view: View; initialCard?: string; initialTask?: string; initialReviewOnly?: boolean }) {
  const [session, setSession] = useState<RevisionSession>(newRevisionSession)
  const [ready, setReady] = useState(false), [storage, setStorage] = useState(true), [notice, setNotice] = useState('')
  const [revealed, setRevealed] = useState(false), [reviewOnly, setReviewOnly] = useState(initialReviewOnly)
  const [group, setGroup] = useState<CardGroup | 'All'>('All')
  const cardHeading = useRef<HTMLHeadingElement>(null), taskHeading = useRef<HTMLHeadingElement>(null)
  useEffect(() => {
    let opened = newRevisionSession()
    try {
      const raw = localStorage.getItem(REVISION_STORAGE_KEY)
      if (raw) {
        let saved = null
        try { saved = restoreRevisionSession(JSON.parse(raw)) } catch { /* Preserve unreadable data. */ }
        if (saved) opened = saved
        else { setStorage(false); setNotice('Saved revision data could not be read. You can practise, but saving is disabled to preserve that record.') }
      }
    } catch { setStorage(false) }
    if (initialCard) opened = revisionReducer(opened, { type: 'card', id: initialCard })
    if (initialTask) opened = revisionReducer(opened, { type: 'task', id: initialTask })
    if (initialReviewOnly && !initialCard && opened.reviewIds.length) opened = revisionReducer(opened, { type: 'card', id: opened.reviewIds[0] })
    setSession(opened); setReady(true)
  }, [initialCard, initialTask, initialReviewOnly])
  useEffect(() => {
    if (!ready || !storage) return
    try { localStorage.setItem(REVISION_STORAGE_KEY, JSON.stringify(session)) } catch { setStorage(false) }
  }, [session, ready, storage])
  function act(action: RevisionAction) { setSession(current => revisionReducer(current, action)) }
  const card = revisionCards.find(c => c.id === session.cardId)!
  const task = practiceTasks.find(t => t.id === session.taskId)!
  const taskIndex = practiceTasks.indexOf(task), submitted = session.answers[task.id], modelSeen = session.models.includes(task.id)
  const filtered = revisionCards.filter(c => (group === 'All' || c.group === group) && (!reviewOnly || session.reviewIds.includes(c.id)))
  const cardIndex = filtered.findIndex(c => c.id === card.id)
  useEffect(() => { setRevealed(false) }, [session.cardId])
  function selectCard(id: string) { act({ type: 'card', id }); setRevealed(false); requestAnimationFrame(() => cardHeading.current?.focus({ preventScroll: true })) }
  function selectTask(id: string) { act({ type: 'task', id }); requestAnimationFrame(() => taskHeading.current?.focus({ preventScroll: true })) }
  function changeGroup(value: CardGroup | 'All') {
    setGroup(value)
    const next = revisionCards.find(c => (value === 'All' || c.group === value) && (!reviewOnly || session.reviewIds.includes(c.id)))
    if (next) selectCard(next.id)
  }
  function checkCard(value: 'again' | 'remembered') {
    act({ type: 'selfCheck', value })
    if (reviewOnly && value === 'remembered') {
      const next = filtered.find(c => c.id !== card.id)
      if (next) selectCard(next.id)
    }
  }
  const recallStats = Object.values(session.cards).filter(record => record.selfCheck).length
  const independent = practiceTasks.filter(t => t.stage === 'independent')
  return <div className="coach exam-revision">
    <header className="coach-header"><Link className="coach-brand" href={href('home')}><span aria-hidden="true"><Layers size={23} /></span><strong>Science Revision</strong></Link><span className="coach-header__label">AQA Trilogy · Foundation</span><Link className="coach-home-link" href={href('home')}>Lesson 1 · Cells</Link></header>
    <main className="coach-main" aria-busy={!ready}>
      <nav className="revision-nav" aria-label="Lesson 1 revision"><Link href={href('home')} aria-current={view === 'home' ? 'page' : undefined}>Overview</Link><Link href={href('cards')} aria-current={view === 'cards' ? 'page' : undefined}>Revision cards</Link><Link href={href('practice')} aria-current={view === 'practice' ? 'page' : undefined}>Exam practice</Link><Link href={href('alignment')} aria-current={view === 'alignment' ? 'page' : undefined}>Alignment & sources</Link></nav>
      {!ready ? <p role="status">Opening your Cells revision…</p> : view === 'home' ? <>
        <section className="coach-welcome revision-hero"><div><span className="coach-eyebrow">Biology Paper 1 · Lesson 1 only</span><h1>Learn the cells.<br />Know how to answer.</h1><p>Animal, plant and bacterial cells. Short cards for the essentials. Practice for using them in an answer.</p></div><div className="revision-lesson-stamp"><strong>01</strong><span>Cells</span><small>Not the whole Cell Biology unit</small></div></section>
        <div className="revision-trust"><span><Check size={15} /> Specification-mapped content</span><span>Original practice · teacher review pending</span><Link href={href('alignment')}>Past-paper verification pending</Link></div>
        <section aria-labelledby="revision-start"><div className="coach-section-title"><h2 id="revision-start">Two useful things to do</h2><span>No card-making. No revision planning.</span></div><div className="revision-start-grid">
          <article className="coach-card coach-card--learn"><span className="coach-card__icon"><Layers size={22} /></span><span className="coach-eyebrow">1 · Learn and recall</span><h3>{revisionCards.length} ready-made revision cards</h3><p>Try the question. Reveal a concise answer. Open the easy explanation only when you need it.</p><Link className="coach-button" href={href('cards')}>{Object.keys(session.cards).length ? 'Continue your cards' : 'Start the revision cards'}<ArrowRight size={17} /></Link><small>{recallStats} cards self-checked · self-checks are not exam marks</small></article>
          <article className="coach-card"><span className="coach-card__icon"><CheckSquare size={22} /></span><span className="coach-eyebrow">2 · Practise using it</span><h3>Short exam-style practice</h3><p>See one worked answer, build one guided answer, then try {independent.length} short checks. Answer before seeing the guidance.</p><Link className="coach-button coach-button--light" href={href('practice')}>Open exam practice <ArrowRight size={17} /></Link><small>Original questions and draft marking points—not official AQA questions</small></article>
        </div></section>
        {session.reviewIds.length > 0 && <aside className="revision-revisit"><RotateCcw size={21} /><div><strong>{session.reviewIds.length} cards to revisit</strong><p>From wrong checked answers or your own “practise again” choices.</p></div><Link className="coach-button coach-button--light" href="/preview/scienceB?view=cards&filter=again">Practise these cards</Link></aside>}
        <section aria-labelledby="revision-coverage"><div className="coach-section-title"><h2 id="revision-coverage">What this lesson covers</h2><span>Six small sections · one lesson</span></div><div className="revision-group-grid">{cardGroups.map((name, index) => <Link className="revision-group" href={href('cards', revisionCards.find(c => c.group === name)!.id)} key={name}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{name}</h3><p>{revisionCards.filter(c => c.group === name).length} cards</p></div><ArrowRight size={17} /></Link>)}</div></section>
        <aside className="revision-scope"><strong>Keep the scope clear</strong><p>This is Lesson 1: Cells, mainly specification 4.1.1.1–4.1.1.2 plus linked maths and scientific skills. Microscopy, specialised cells, mitosis, stem cells and transport are not populated here.</p></aside>
      </> : view === 'cards' ? <>
        <div className="revision-title"><span className="coach-eyebrow">Lesson 1 · Learn and recall</span><h1>Revision cards</h1><p>Think of an answer first. Then check it. These are self-checks—not a test score.</p></div>
        <div className="revision-card-filters"><label>Section<select value={group} onChange={event => changeGroup(event.target.value as CardGroup | 'All')}><option value="All">All sections</option>{cardGroups.map(name => <option key={name}>{name}</option>)}</select></label><label className="revision-review-filter"><input type="checkbox" checked={reviewOnly} onChange={event => {
          const value = event.target.checked; setReviewOnly(value)
          const next = revisionCards.find(c => (group === 'All' || c.group === group) && (!value || session.reviewIds.includes(c.id)))
          if (next) selectCard(next.id)
        }} /> Only cards to revisit ({session.reviewIds.length})</label></div>
        {!filtered.length ? <section className="coach-review-card"><h2>No cards to revisit in this selection.</h2><p>Change the section or turn off the filter to see more cards.</p><button type="button" className="coach-button" onClick={() => { setReviewOnly(false); setGroup('All'); selectCard(revisionCards[0].id) }}>Show all cards</button></section> : <div className="revision-cards-layout"><nav className="revision-card-list" aria-label="Revision card questions">{filtered.map(c => <button type="button" aria-current={c.id === card.id ? 'true' : undefined} key={c.id} onClick={() => selectCard(c.id)}><span>{c.question}</span>{session.reviewIds.includes(c.id) && <small>Revisit</small>}</button>)}</nav><article className="coach-review-card revision-flashcard">
          <div className="coach-question-meta"><span>{card.group}</span><span>{cardIndex + 1} of {filtered.length}</span></div><h2 ref={cardHeading} tabIndex={-1}>{card.question}</h2>
          {!revealed ? <><p>Say the answer to yourself, or jot it down.</p><button className="coach-button" type="button" onClick={() => { act({ type: 'revealCard', at: new Date().toISOString() }); setRevealed(true) }}>Reveal the answer <ArrowRight size={17} /></button></> : <section className="revision-card-answer" aria-live="polite"><span className="coach-eyebrow">The concise answer</span><p>{card.answer}</p><details><summary><Lightbulb size={16} /> Explain it more simply</summary><p>{card.easy}</p></details>{card.visual && <div className="revision-model">{card.visual === 'animal' ? <CellModel labelled /> : card.visual === 'plant' ? <PlantCellModel /> : card.visual === 'bacterium' ? <BacterialCellModel /> : <AreaModel length={5} width={2} />}</div>}<aside className="revision-slip"><strong>Avoid this mix-up</strong><p>{card.slip}</p></aside><div className="coach-button-row"><button type="button" className="coach-button coach-button--light" aria-pressed={session.cards[card.id]?.selfCheck === 'again'} onClick={() => checkCard('again')}><RotateCcw size={16} /> Practise again</button><button type="button" className="coach-button" aria-pressed={session.cards[card.id]?.selfCheck === 'remembered'} onClick={() => checkCard('remembered')}><Check size={16} /> I remembered it</button></div><small>Your own judgement—not an automatically assessed recall result.</small></section>}
          <div className="revision-card-controls"><button type="button" className="coach-text-button" disabled={cardIndex <= 0} onClick={() => selectCard(filtered[cardIndex - 1].id)}><ArrowLeft size={16} /> Previous card</button><button type="button" className="coach-text-button" disabled={cardIndex >= filtered.length - 1} onClick={() => selectCard(filtered[cardIndex + 1].id)}>Next card <ArrowRight size={16} /></button></div><details className="revision-card-spec"><summary>Where this fits</summary><p>Specification / skills: {card.spec.join(' · ')}</p><p>Original revision wording. <Link href={href('alignment')}>See the alignment and source status.</Link></p></details>
        </article></div>}
      </> : view === 'practice' ? <>
        <div className="revision-title"><span className="coach-eyebrow">Lesson 1 · Apply the essentials</span><h1>Practise how to answer</h1><p>Worked example → guided answer → your own answers. Draft marks describe these original tasks, not official AQA marking.</p></div>
        <div className="revision-practice-layout"><nav className="revision-task-list" aria-label="Practice questions">{practiceTasks.map((item, index) => <button type="button" key={item.id} aria-current={item.id === task.id ? 'true' : undefined} onClick={() => selectTask(item.id)}><span>{index + 1}. {item.title}</span><small>{item.stage === 'worked' ? 'Worked example' : item.stage === 'supported' ? 'Guided answer' : `${item.marks} draft ${item.marks === 1 ? 'mark' : 'marks'}`}{session.answers[item.id] ? ' · Saved' : ''}</small></button>)}</nav><article className="coach-review-card revision-practice-card">
          <div className="coach-question-meta"><span>{task.stage === 'worked' ? 'Worked example' : task.stage === 'supported' ? 'Guided answer · supported practice' : 'Your own answer'}</span><span>{task.marks} draft {task.marks === 1 ? 'mark' : 'marks'}</span></div><h2 ref={taskHeading} tabIndex={-1}>{task.title}</h2>
          {task.visual === 'animal-target' && <div className="revision-model"><CellModel pointer alternate description="Original simplified animal-cell model, not to scale. A pointer ends at the outer boundary. Labels are hidden." /></div>}
          <p className="revision-prompt">{task.prompt}</p><aside className="revision-command"><strong>{task.command}:</strong> {task.command === 'Explain' ? 'Give the reason. Link the cell part to what it does.' : task.command === 'Compare' ? 'State a difference by referring to both cells.' : task.command === 'Calculate' ? 'Show your working and include units where requested.' : 'Give or select the requested answer.'}</aside>
          {task.support && <aside className="coach-reminder"><strong>Build your answer</strong><ol>{task.support.map(line => <li key={line}>{line}</li>)}</ol></aside>}
          {task.stage !== 'worked' && (task.kind === 'choice' ? <div className="coach-choices" role="group" aria-label="Choose your practice answer">{task.options.map((option, index) => <button type="button" className={`coach-choice ${submitted && index === task.answer ? 'coach-choice--correct' : submitted?.response === String(index) ? 'coach-choice--retry' : ''}`} key={option} disabled={Boolean(submitted)} aria-pressed={submitted?.response === String(index)} onClick={() => act({ type: 'submit', response: String(index), at: new Date().toISOString() })}><span>{option}</span>{submitted && index === task.answer && <Check size={18} aria-label="Correct answer" />}</button>)}</div> : <form className="revision-answer-form" onSubmit={event => { event.preventDefault(); act({ type: 'submit', at: new Date().toISOString() }) }}><label htmlFor="revision-answer">{task.kind === 'number' ? 'Your numerical answer' : 'Your answer'}</label>{task.kind === 'number' ? <div className="revision-numeric"><input id="revision-answer" type="text" inputMode="decimal" maxLength={30} value={submitted?.response ?? session.drafts[task.id] ?? ''} readOnly={Boolean(submitted)} pattern="([+]|-)?([0-9]+([.][0-9]*)?|[.][0-9]+)" onChange={event => act({ type: 'draft', text: event.target.value })} /><span>{task.unit}</span></div> : <textarea id="revision-answer" maxLength={2000} rows={5} value={submitted?.response ?? session.drafts[task.id] ?? ''} readOnly={Boolean(submitted)} onChange={event => act({ type: 'draft', text: event.target.value })} placeholder="Write a short, clear answer…" />}{!submitted && <button type="submit" className="coach-button" disabled={!session.drafts[task.id]?.trim()}>Save and check your answer <ArrowRight size={16} /></button>}</form>)}
          {task.stage === 'independent' && !submitted && <details className="revision-support" onToggle={event => { if (event.currentTarget.open) act({ type: 'support' }) }}><summary>I need to revisit the essentials</summary><p>Using these cards makes this a supported attempt.</p>{task.cardIds.map(id => <Link href={href('cards', id)} key={id}>{revisionCards.find(c => c.id === id)!.question}</Link>)}</details>}
          {submitted && <section className="revision-feedback" role="status"><strong>{submitted.result === 'pendingReview' ? 'Saved—not automatically marked.' : submitted.result === 'correct' ? 'That answer is correct.' : 'Let’s check the missing step.'}</strong><p>{submitted.result === 'pendingReview' ? 'Compare your reasoning with the draft guidance. A teacher must decide the marks; this preview does not send your work to one.' : 'Only this selected or numerical answer is checked. It does not certify the whole topic.'}</p>{submitted.supported && <small>Supported practice · help was used</small>}<small>Your submitted answer is locked and stays saved.</small></section>}
          {!modelSeen && (task.stage === 'worked' || submitted) && <button className="coach-button coach-button--light" type="button" onClick={() => act({ type: 'model' })}>{task.stage === 'worked' ? 'Show the worked answer' : 'Compare with the answer guidance'}<ArrowRight size={16} /></button>}
          {modelSeen && <section className="revision-marking" aria-label="Original draft answer guidance"><h3>{task.stage === 'worked' ? 'Worked answer' : 'Example answer'}</h3><p>{task.model}</p><h3>Draft marking points</h3><ol>{task.points.map(point => <li key={point}>{point}</li>)}</ol><p className="revision-equivalents">Other scientifically correct wording may be valid. These are Revily draft points, not a verified official mark scheme.</p><aside className="revision-slip"><strong>Watch out</strong><p>{task.slip}</p></aside>{task.stage !== 'worked' && <button type="button" className="coach-text-button" onClick={() => act({ type: 'reviewCards', ids: task.cardIds })}><RotateCcw size={16} /> Add these essentials to my revisit cards</button>}<p><small>You’ve seen the guidance. Reopening this question is practice, not a fresh assessment.</small></p></section>}
          <div className="revision-card-controls"><button type="button" className="coach-text-button" disabled={taskIndex === 0} onClick={() => selectTask(practiceTasks[taskIndex - 1].id)}><ArrowLeft size={16} /> Previous question</button>{taskIndex < practiceTasks.length - 1 ? <button type="button" className="coach-button" disabled={task.stage === 'worked' ? !modelSeen : !submitted} onClick={() => selectTask(practiceTasks[taskIndex + 1].id)}>Next question <ArrowRight size={16} /></button> : <Link className="coach-button" href={href('home')}>Back to revision <ArrowRight size={16} /></Link>}</div>
        </article></div>
      </> : <>
        <div className="revision-title"><span className="coach-eyebrow">Lesson 1 · Evidence behind the content</span><h1>Alignment & sources</h1><p>Keep three things separate: specification mapping, our original answer guidance, and verified official paper matches.</p></div>
        <section className="revision-alignment"><h2>Specification coverage</h2><p>Our lesson design maps the {revisionCards.length} cards to these Cells outcomes. This is not the full Cell Biology unit or GCSE syllabus.</p><div className="revision-table-scroll"><table><thead><tr><th scope="col">What students need</th><th scope="col">Specification / skills</th><th scope="col">Cards and practice</th></tr></thead><tbody>{alignmentRows.map(row => <tr key={row.title}><th scope="row">{row.title}</th><td>{row.refs.join(' · ')}</td><td><div>{row.groups.map(name => <Link key={name} href={href('cards', revisionCards.find(c => c.group === name)!.id)}>{name}</Link>)}</div><small>{row.practice.length} linked original practice {row.practice.length === 1 ? 'task' : 'tasks'}</small></td></tr>)}</tbody></table></div><a href={specificationUrl} target="_blank" rel="noreferrer">Open the current AQA Biology specification <ArrowRight size={15} /></a></section>
        <section className="revision-alignment"><h2>Marking approach</h2><p>One point should express one relevant scientific idea. Explanations link the part, its process and the stated job. Comparisons refer to both cells. Calculations use matching units and square units for area.</p><p>This is original draft guidance informed by our existing Lesson 1 research notes. It is not a question-specific, verified AQA marking scheme. Written responses remain unmarked until reviewed by a teacher.</p><a href="https://www.aqa.org.uk/resources/science/gcse/teach/command-words" target="_blank" rel="noreferrer">AQA command-word guidance</a></section>
        <section className="revision-alignment revision-source-pending"><span className="coach-eyebrow">Pending—not verified</span><h2>Past-paper and mark-scheme calibration</h2><p><strong>{sourceReview.paper}</strong></p><p>{sourceReview.note}</p><p>No official question, diagram or mark-scheme text has been imported. Exact-source verification requires an appropriate permitted workflow and qualified review. AQA restricts putting its materials into AI tools.</p><div className="revision-source-links"><a href={sourceReview.paperUrl} target="_blank" rel="noreferrer">Existing question-paper reference</a><a href={sourceReview.schemeUrl} target="_blank" rel="noreferrer">Existing mark-scheme reference</a><a href="https://www.aqa.org.uk/subjects/science/gcse/science-8464/assessment-resources" target="_blank" rel="noreferrer">Official assessment-resource finder</a><a href={sourceReview.policyUrl} target="_blank" rel="noreferrer">AQA use policy</a></div><p>Past-paper patterns must not remove required specification content. No predictions or guaranteed marks are claimed.</p></section>
        <aside className="revision-scope"><strong>Outside Lesson 1</strong><p>Magnification and required microscopy practical work belong in the later microscopy lessons. Specialisation, cell division, stem cells, diffusion, osmosis and active transport are also outside this page. Real required practicals cannot be replaced by online cards.</p></aside>
      </>}
      {notice && <p className="coach-storage-warning" role="status">{notice}</p>}
      <footer className="coach-footer"><p>AQA Combined Science: Trilogy 8464 · Foundation · Lesson 1: Cells only · Original drafts awaiting teacher review; exact past-paper alignment pending.</p><p>{storage ? 'Revision cards, self-checks and practice drafts are saved on this browser only, separately from the original lessons and previous Coach experiment.' : 'Saving is unavailable. New work may be lost when you leave.'}</p><Link href="/preview/science?lesson=1&variant=b">Open the unchanged original Lesson 1 <ArrowRight size={14} /></Link></footer>
    </main>
  </div>
}
