import type { TeachingFrame } from '../../teachingFrame'

// What has changed (a graph of UK electricity use built up in two frames), why people want more renewables (a chain of
// pressure from the public to governments to energy providers), then what limits renewables (evidence, money, politics, people).
// The graph is schematic: the page gives the shape and the dates, not numbers, so no values are shown.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const energyTrendFrames: Record<string, TeachingFrame[]> = {
  'P14-02': [
    f('Use of electricity rose', 'Electricity use in the UK increased a lot in the 20th century, because the population and the number of things using electricity grew.', 'more people, more gadgets', 'Over time, the energy resources we use change. In the 20th century, our use of electricity increased a lot. One reason is that the population grew. Another is that the number of things that use electricity grew too, such as lights, fridges and televisions.', 'etrend-rise'),
    f('Use has slowly fallen', 'Since the early 2000s, electricity use in the UK has been decreasing slowly.', 'the line bends down', 'But since the early 2000s, electricity use in the UK has been decreasing. It has only fallen slowly. So the line on the graph stopped rising and now bends gently downwards.', 'etrend-graph'),
    f('Why use has fallen', 'We are getting better at making appliances more efficient, and we are being more careful with our energy use.', 'efficient appliances, careful people', 'There are two reasons. First, appliances are being made more efficient. An efficient appliance wastes less energy, so it needs less electricity to do the same job. Second, people are being more careful with their energy use. For example, they switch things off when they are not using them.', 'etrend-why-fall'),
    f('We still need non-renewables', 'At the moment, we still use non-renewable resources for some of our electricity, transport and heating.', 'still used for three jobs', 'Even so, we still use non-renewable resources. At the moment, they are still used for some of our electricity, some of our transport and some of our heating.', 'etrend-still'),
  ],
  'P14-05': [
    f('Damage to the environment', 'Burning fossil fuels is very damaging to the environment, so many people want to use more renewables.', 'fossil fuels damage, renewables better', 'We now know that burning fossil fuels is very damaging to the environment. This makes many people want to use more renewable energy resources. Renewables are better for the environment. Many people also think it is better to move to renewables before non-renewables run out.', 'etrend-damage'),
    f('Pressure on governments', 'Pressure from other countries and the public leads governments to set targets for using renewables.', 'pressure leads to targets', 'The public and other countries put pressure on governments. This pressure leads governments to set targets for using renewable resources. A target is an amount of renewable energy that a country aims to use.', 'etrend-pressure'),
    f('Pressure on energy providers', 'Targets put pressure on energy providers to build new renewable power plants, or they could lose business and money.', 'targets, then new power plants', 'Energy providers are the companies that supply our electricity. The government targets put pressure on them. They are pushed to build new power plants that use renewable resources. If they do not, they could lose business and money.', 'etrend-providers'),
    f('Cars are changing too', 'Car companies have been affected too. Electric cars and hybrids are becoming more popular.', 'electric cars and hybrids', 'Car companies have also been affected by the push for renewables. Electric cars are becoming more popular. Hybrid cars are also becoming more popular. A hybrid is powered by two fuels, for example petrol and electricity.', 'etrend-cars'),
    f('The chain of pressure', 'People worry about the environment, governments set targets, energy providers build renewables, and the resources we use change.', 'one push leads to the next', 'Here is the whole chain. People worry about the environment. Governments set targets for renewables. Energy providers build more renewable power plants. Over time, the energy resources we use change.', 'etrend-chain'),
  ],
  'P14-08': [
    f('Evidence is not enough', 'There is a lot of scientific evidence supporting renewables, but scientists can only give advice.', 'advice, not power', 'There is a lot of scientific evidence supporting renewables. But scientists can only give advice. They do not have the power to make people, companies or governments change what they do. So the use of renewables is limited by other factors. Three important ones are money, politics and people.', 'etrend-evidence'),
    f('Money', 'Building renewable power plants costs money, more research is needed, and electric cars usually cost more than petrol cars.', 'building, research, cars', 'Money is the first factor. Building new renewable power plants costs money. More research is needed to make renewables cheaper and more reliable, and this takes time and money. An electric car is usually more expensive than a petrol car of a similar size.', 'etrend-money'),
    f('Politics', 'Switching has to be paid for through bills or taxes. Some people do not want to pay, or cannot afford to.', 'who pays for the change', 'Politics is the second factor. The cost of switching to renewable power has to be paid through energy bills or taxes. Some people do not want to pay, or cannot afford to pay. There are arguments about whether it is ethical, meaning right or wrong, to make them pay.', 'etrend-politics'),
    f('People', 'Many people do not want to live near a power plant such as a wind farm. Some think it is not ethical to make them.', 'not in my back yard', 'People are the third factor. Many people do not want to live near a power plant such as a wind farm or a hydro-electric dam. Some people think it is not ethical to make them put up with a new power plant built near them.', 'etrend-people'),
    f('Some renewables cannot keep up', 'Some renewables are not as reliable as fossil fuels, because they cannot increase their output on demand.', 'output cannot rise on demand', 'There is one more limit. Some renewables are not as reliable as fossil fuels. This is because they cannot increase their output when demand goes up. So non-renewable resources are still needed for now.', 'etrend-demand'),
  ],
}
