import { useId } from 'react'
const ink = '#37627b', blue = '#4ca9d1', amber = '#dca739'
function Chromosome({ x, y, copied = false, colour = blue }: { x: number; y: number; copied?: boolean; colour?: string }) {
  return <g stroke={colour} strokeWidth="7" strokeLinecap="round">{copied ? <><path d={`M${x-8} ${y-16}l16 32`} /><path d={`M${x+8} ${y-16}l-16 32`} /></> : <path d={`M${x} ${y-16}v32`} />}</g>
}
export function DivisionVisual({ focus, assessment = false }: { focus: string; assessment?: boolean }) {
  const title = useId()
  if (focus === 'chromosomes') return <div className="science-bio-model"><svg viewBox="0 0 440 150" role="img" aria-labelledby={title}><title id={title}>Spatial zoom: a cell contains a nucleus; its chromosomes consist of DNA; a highlighted section of DNA represents a gene. Original schematic, not to scale.</title><ellipse cx="58" cy="67" rx="43" ry="48" fill="#dff3fb" stroke="#37627b" strokeWidth="2" /><circle cx="58" cy="67" r="20" fill="#ddd2ef" /><path d="M78 58L124 34M78 77L124 99" stroke="#a68bd0" strokeDasharray="3 3" /><circle cx="157" cy="67" r="37" fill="#efe6fb" stroke="#8c72b4" /><Chromosome x={144} y={67} /><Chromosome x={171} y={67} colour={amber} /><path d="M184 56L226 36M184 78L226 100" stroke="#4ca9d1" strokeDasharray="3 3" /><Chromosome x={242} y={67} /><path d="M253 56L289 24M253 78L289 113" stroke="#4ca9d1" strokeDasharray="3 3" /><path d="M293 25Q350 25 407 112M407 25Q350 25 293 112" fill="none" stroke="#4ca9d1" strokeWidth="4" />{[37,53,69,85,101].map((y,i)=><path key={y} d={`M${305+i*18} ${y}H${396-i*18}`} stroke={i===2?'#9c70c7':'#87b4c8'} strokeWidth={i===2?8:2}/>)}<rect x="325" y="55" width="52" height="27" rx="5" fill="none" stroke="#9c70c7" strokeDasharray="3 3" />{['Cell','Nucleus','Chromosome','DNA · highlighted gene'].map((s,i)=><text key={s} x={[58,157,242,351][i]} y="140" textAnchor="middle" fill={ink} fontSize="12">{s}</text>)}</svg><ol className="science-bio-key"><li>Cell → nucleus → chromosome → DNA.</li><li>The outlined section of DNA represents one gene.</li><li>Dotted lines show a closer view of the same structure.</li></ol></div>
  if (focus === 'pairs') return <div className="science-bio-model"><svg viewBox="0 0 440 145" role="img" aria-labelledby={title}><title id={title}>Simplified body-cell nucleus containing four chromosomes arranged as two pairs; not a complete human chromosome set.</title><ellipse cx="220" cy="68" rx="125" ry="55" fill="#eee5f8" stroke="#8c72b4" /><Chromosome x={154} y={66}/><Chromosome x={182} y={66}/><Chromosome x={254} y={66} colour={amber}/><Chromosome x={282} y={66} colour={amber}/><text x="166" y="135" textAnchor="middle" fill={ink} fontSize="13">Pair 1</text><text x="269" y="135" textAnchor="middle" fill={ink} fontSize="13">Pair 2</text></svg></div>
  if (focus === 'cycle-worked') return <div className="science-bio-model"><svg viewBox="0 0 440 150" role="img" aria-labelledby={title}><title id={title}>A starting body-cell model with four chromosomes. Follow the revealed reasoning to determine the number in each daughter cell.</title><ellipse cx="220" cy="70" rx="120" ry="56" fill="#dff3fb" stroke={ink}/><ellipse cx="220" cy="70" rx="85" ry="43" fill="#e8def5" stroke="#a68bd0"/>{[166,202,238,274].map((x,i)=><Chromosome key={x} x={x} y={70} colour={i<2?blue:amber}/>)}</svg><p className="science-bio-note">Starting model: 4 chromosomes. Reveal the reasoning one step at a time.</p></div>
  if (focus.startsWith('cycle')) {
    const copy = focus === 'cycle-copy', separate = focus === 'cycle-separate', daughters = focus === 'cycle-daughters'
    return <div className="science-bio-model"><svg viewBox="0 0 440 175" role="img" aria-labelledby={title}><title id={title}>{(assessment ? 'A simplified cell model with chromosome symbols; use the supplied starting count in the question.' : copy ? 'One cell with two replicated chromosomes, each with two joined DNA copies.' : separate ? 'One cell with two forming nuclei; each receives one blue and one amber chromosome.' : 'Two daughter cells, each containing one blue and one amber chromosome.') + " Only two starting chromosomes are shown for clarity, not to scale."}</title>{daughters ? [126,314].map(cx=><g key={cx}><ellipse cx={cx} cy="83" rx="74" ry="67" fill="#dff3fb" stroke={ink} strokeWidth="2" /><ellipse cx={cx} cy="83" rx="41" ry="37" fill="#e8def5" stroke="#a68bd0" /><Chromosome x={cx-15} y={83}/><Chromosome x={cx+15} y={83} colour={amber}/></g>) : <g><ellipse cx="220" cy="83" rx="151" ry="64" fill="#dff3fb" stroke={ink} strokeWidth="2" />{separate ? [128,312].map(cx=><g key={cx}><ellipse cx={cx} cy="83" rx="35" ry="36" fill="#e8def5" stroke="#a68bd0" strokeDasharray="4 3" /><Chromosome x={cx-12} y={83}/><Chromosome x={cx+12} y={83} colour={amber}/></g>) : <g><ellipse cx="220" cy="83" rx="67" ry="45" fill="#e8def5" stroke="#a68bd0" /><Chromosome x={197} y={83} copied={copy}/><Chromosome x={243} y={83} copied={copy} colour={amber}/></g>}{separate && <><path d="M205 83H180l8-6m-8 6l8 6M235 83h25l-8-6m8 6l-8 6" stroke={ink} strokeWidth="2" fill="none" /></>}</g>}</svg>{!assessment && <p className="science-bio-note">{copy ? 'DNA copied: two copies of each starting chromosome.' : separate ? 'Mitosis: complete sets separate; two nuclei form.' : 'Each new daughter cell has the same chromosome number as the starting cell.'}</p>}</div>
  }
  if (focus.startsWith('stem-') && !['stem-benefits','stem-risks'].includes(focus)) {
    const embryo = focus === 'stem-embryo', marrow = focus === 'stem-marrow'
    const options = embryo ? ['Nerve cell','Muscle cell','Blood cell'] : marrow ? ['Red blood cell','White blood cell'] : ['Root cell','Leaf cell','Xylem cell']
    return <div className="science-bio-model"><svg viewBox="0 0 440 135" role="img" aria-labelledby={title}><title id={title}>{(embryo ? 'Embryonic' : marrow ? 'Bone-marrow' : 'Meristem') + " stem-cell branching model. The top branch makes more stem cells; the other two branches represent possible differentiated cell types listed below. Not a photograph."}</title><circle cx="64" cy="66" r="31" fill={marrow?'#f1dfec':embryo?'#e1ddf5':'#def2dc'} stroke={ink} /><circle cx="64" cy="66" r="12" fill="#a68bd0" /><path d="M96 66H187M187 66V27H285M187 66H285M187 66V108H285" fill="none" stroke={ink} strokeWidth="2" /><circle cx="315" cy="27" r="15" fill="#e1ddf5" stroke={ink} /><text x="339" y="31" fontSize="11" fill={ink}>Stem cell</text><circle cx="315" cy="68" r="15" fill="#d6ecf5" stroke={ink} /><circle cx="315" cy="109" r="15" fill="#e1efd8" stroke={ink} /><text x="64" y="119" textAnchor="middle" fontSize="12" fill={ink}>Stem cell</text></svg><p className="science-bio-note">Top branch: division makes more stem cells (self-renewal). Other branches: stem cells become specialised (differentiation). Examples include {options.join(', ')}{embryo ? ' and most other human types.' : marrow ? ' and a limited range of other types.' : ' and any other plant type.'}</p></div>
  }
  const notes: Record<string,string[]> = {
    repair: ['Worn-out or damaged tissue', 'Mitosis produces new cells', 'Replacement or tissue repair'],
    'stem-benefits': ['Could replace damaged cells', 'Possible help for diabetes or paralysis', 'Evidence needed; no guaranteed cure'],
    'stem-risks': ['Medical risk: viral infection', 'Ethical issue: embryo use', 'Weigh risks, benefits and objections'],
    therapeutic: ['Embryo with patient’s genes', 'Matching stem cells are not rejected', 'Other treatment risks remain'],
    trial: ['Example trial · not real treatment evidence', '6/10 improved', '4/10 did not improve'],
  }
  return notes[focus] ? <div className="science-bio-cards">{notes[focus].map(s=><div key={s}>{s}</div>)}</div> : null
}
