import { useId, useState } from 'react'
import { transportData } from '../lesson-6/practicalData'

const ink = '#37627b', blue = '#52aed0', amber = '#e5b442', green = '#67ab8b'
function ParticleModel({ focus, assessment }: { focus: string; assessment: boolean }) {
  const id = useId().replace(/:/g, '')
  const osmosis = focus.startsWith('osmosis'), active = focus === 'active' || focus === 'gut-active'
  const leftCount = active ? 3 : osmosis ? 14 : 16, rightCount = active ? 9 : osmosis ? 8 : 6
  function particles(count: number, offset: number, square = false) {
    return Array.from({ length: count }, (_, i) => {
      const x=offset+18+(i%4)*28, y=25+Math.floor(i/4)*28
      return square ? <rect key={i} x={x-5} y={y-5} width="10" height="10" fill={amber} stroke={ink} /> : <circle key={i} cx={x} cy={y} r="5" fill={blue} />
    })
  }
  return <div className="science-bio-model"><div className="science-bio-pair"><span>{active ? 'Lower ion/sugar concentration' : osmosis ? 'Dilute · lower solute concentration' : 'Higher concentration'}</span><span>{active ? 'Higher ion/sugar concentration' : osmosis ? 'Concentrated · higher solute concentration' : 'Lower concentration'}</span></div><svg viewBox="0 0 360 175" role="img" aria-labelledby={`${id}-title`}><title id={`${id}-title`}>{(osmosis ? 'Equal-sized solution regions separated by a membrane. Left: more water circles and fewer solute squares; right: fewer water circles and more solute squares. In this model only water crosses the membrane.' : active ? 'Equal-sized regions with fewer solute squares on the left and more on the right, separated by a cell membrane.' : 'Equal-sized regions with more particles on the left and fewer on the right. Small arrows show example random movements.') + (assessment ? ' No net-direction arrow is shown.' : ' A large arrow shows net movement.') + " Original schematic, representative particles, not to scale."}</title><defs><marker id={`${id}-arrow`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill={ink}/></marker></defs><rect x="10" y="8" width="150" height="122" rx="7" fill="#f1f9fd" stroke="#b7d9e6" /><rect x="200" y="8" width="150" height="122" rx="7" fill="#f5f4fc" stroke="#cfc5df" />{particles(leftCount,15,active)}{particles(rightCount,205,active)}{osmosis && <>{[42,106].map((x,i)=><rect key={x} x={x} y={i*55+43} width="10" height="10" fill={amber} stroke={ink}/>)}{[214,246,278,310,230,265,301].map((x,i)=><rect key={i} x={x} y={37+(i%3)*34} width="10" height="10" fill={amber} stroke={ink}/>)}</>}
    {(osmosis||active) && <><path d="M175 7v44m0 10v44m0 10v17M185 7v44m0 10v44m0 10v17" stroke={green} strokeWidth="3" />{osmosis && <path d="M170 56h20M170 110h20" stroke="#b7d9e6" strokeWidth="2" strokeDasharray="2 2" />}</>}
    {!active && <><path d="M75 40l12-8M102 96l-12 7M242 85l11 7M278 44l-10-9" stroke={ink} strokeWidth="1.3" markerEnd={`url(#${id}-arrow)`}/></>}
    {!assessment && <><path d="M125 152H239" stroke={ink} strokeWidth="3" markerEnd={`url(#${id}-arrow)`}/><text x="181" y="169" textAnchor="middle" fill={ink} fontSize="11">{active ? 'Against gradient · energy required' : osmosis ? 'Net water movement' : 'Net movement'}</text></>}
  </svg><p className="science-bio-note">{osmosis ? 'Key: blue circles = water; amber squares = solute. The partially permeable membrane allows water through, not this solute.' : active ? 'Key: amber squares = transported substance. The green boundary represents a cell membrane; energy is supplied by respiration.' : 'Key: blue dots = one substance. Small arrows = example random motion. Compare equal volumes.'}</p></div>
}
function ExchangeSurface({ focus }: { focus: string }) {
  const id = useId()
  const lung=focus==='exchange-lung', intestine=focus==='exchange-intestine', gill=focus==='exchange-gill'
  return <div className="science-bio-model"><svg viewBox="0 0 360 155" role="img" aria-labelledby={id}><title id={id}>{(lung ? 'Simplified branching airway ending in several air sacs, with a blood-vessel network around them.' : intestine ? 'Simplified intestinal surface with finger-like projections and blood vessels close to the surface.' : gill ? 'Simplified gill with many thin projecting filaments supplied by blood vessels and water passing around them.' : 'Simplified leaf cross section: surface pore, internal air spaces and surrounding plant cells.') + " Original model, not to scale."}</title>{lung ? <g><path d="M180 10V49L90 83M180 49L269 83" fill="none" stroke="#91b9cb" strokeWidth="16" />{[83,146,213,277].map((x,i)=><g key={x}><path d={`M${x} ${i%2===0?89:102}L180 49`} stroke="#91b9cb" strokeWidth="10" /><circle cx={x} cy={i%2===0?101:113} r="25" fill="#dff1f7" stroke={ink} strokeWidth="2" /><path d={`M${x-28} ${i%2===0?89:101}q-12 38 23 39q35 0 35-32`} fill="none" stroke="#d199ad" strokeWidth="4" /></g>)}</g> : intestine ? <g><path d="M20 137H48V60Q66 10 83 60V137H125V60Q143 10 160 60V137H202V60Q220 10 237 60V137H278V60Q296 10 314 60V137H342" fill="#edf6dc" stroke={green} strokeWidth="4" />{[65,142,219,295].map(x=><path key={x} d={`M${x-7} 140V67q7-16 14 0v73`} fill="none" stroke="#d199ad" strokeWidth="3" />)}</g> : gill ? <g><path d="M70 15v129" stroke="#d199ad" strokeWidth="12" />{[28,48,68,88,108,128].map(y=><g key={y}><path d={`M76 ${y}Q150 ${y-13} 240 ${y}`} stroke={green} strokeWidth="8" fill="none" /><path d={`M76 ${y}H232`} stroke="#d199ad" strokeWidth="2" /></g>)}<path d="M276 20v114l-7-10m7 10l7-10" stroke={blue} strokeWidth="3" fill="none" /></g> : <g><path d="M20 22H158M202 22H340M20 130H340" stroke={green} strokeWidth="8" />{[40,91,240,293].map((x,i)=><g key={x}><rect x={x} y={i%2===0?48:71} width="34" height="36" rx="10" fill="#dbefce" stroke={green} /><circle cx={x+9} cy={i%2===0?58:81} r="4" fill={green}/><circle cx={x+24} cy={i%2===0?72:95} r="4" fill={green}/></g>)}<ellipse cx="156" cy="23" rx="16" ry="12" fill="#b6d99e" stroke={green}/><ellipse cx="203" cy="23" rx="16" ry="12" fill="#b6d99e" stroke={green}/><path d="M180 4v45l-5-7m5 7l5-7" stroke={blue} fill="none" strokeWidth="2" /></g>}</svg><p className="science-bio-note">{lung ? 'Air reaches many alveoli. Nearby blood vessels and ventilation help maintain gas concentration differences.' : intestine ? 'Villi increase area. A thin surface and nearby blood supply support absorption.' : gill ? 'Many thin gill surfaces provide a large area. Water flow and blood supply help maintain gradients.' : 'Stomata allow gas passage. Air spaces expose thin cell surfaces for diffusion.'}</p></div>
}
function CubeRatios() {
  return <div className="science-bio-cards">{[1,2].map(s=><div key={s}><svg viewBox="0 0 160 100" role="img" aria-label={`Model cube, side ${s} cm; use supplied dimensions, not screen measurements.`}><g transform={s===1?'translate(35 42) scale(0.5)':undefined}><path d="M40 30L64 13H117L94 30ZM40 30H94V84H40ZM94 30L117 13V67L94 84Z" fill={s===1?'#daedf9':'#e8def7'} stroke={ink} strokeWidth="2"/></g><text x="65" y="98" textAnchor="middle" fill={ink} fontSize="12">{s} cm side</text></svg>Area: {6*s*s} cm²<br/>Volume: {s*s*s} cm³<br/>SA:V = {6/s}:1</div>)}</div>
}
function PracticalSetup() {
  const id=useId()
  return <div className="science-bio-model"><svg viewBox="0 0 440 170" role="img" aria-labelledby={id}><title id={id}>Five labelled containers from dilute to concentrated, each holding matching plant-tissue pieces. A tissue piece is blotted consistently, then placed on a balance. Teacher-supervised preparation; original schematic, not to scale.</title>{transportData.map((d,i)=><g key={d.concentration}><path d={`M${15+i*58} 17v65h44V17`} fill="none" stroke={ink} strokeWidth="2"/><path d={`M${16+i*58} 42h42v39h-42Z`} fill="#d9edf7"/><rect x={31+i*58} y="51" width="12" height="24" rx="3" fill="#e4ce92" stroke="#a28e54"/><text x={37+i*58} y="101" textAnchor="middle" fontSize="12" fill={ink}>{d.concentration.toFixed(1)}</text></g>)}<path d="M309 61h20l-6-5m6 5l-6 5" fill="none" stroke={ink} strokeWidth="2"/><rect x="339" y="23" width="81" height="37" rx="4" fill="#f4f3ee" stroke="#b1aaa1"/><rect x="372" y="32" width="12" height="22" rx="3" fill="#e4ce92" stroke="#a28e54"/><text x="380" y="75" textAnchor="middle" fontSize="12" fill={ink}>Blot</text><path d="M380 81v14l-5-5m5 5l5-5" fill="none" stroke={ink}/><path d="M342 108h76l8 35h-92Z" fill="#dfeaf1" stroke={ink}/><path d="M349 106h61" stroke={ink} strokeWidth="4"/><rect x="366" y="96" width="26" height="9" rx="3" fill="#e4ce92"/><rect x="352" y="119" width="58" height="16" rx="2" fill="#fff" stroke={ink}/><text x="381" y="131" textAnchor="middle" fontSize="11" fill={ink}>mass / g</text><text x="153" y="126" textAnchor="middle" fontSize="12" fill={ink}>Concentration (mol/dm³)</text><text x="153" y="148" textAnchor="middle" fontSize="12" fill={ink}>Matching tissue dimensions · same solution volume</text></svg><p className="science-bio-note">Measure initial mass; immerse for the same time at the same temperature; blot consistently and measure final mass. Keep tissue type and dimensions the same; repeat each concentration. Cutting and solution preparation require teacher supervision and a risk assessment.</p></div>
}
export function PracticalGraph({ plot = false }: { plot?: boolean }) {
  const id=useId(), [selected,setSelected]=useState<number|null>(null), [plotted,setPlotted]=useState<number|null>(null)
  const x=(c:number)=>54+c/0.8*262, y=(v:number)=>99-v*3.2
  return <div className="science-bio-model"><p className="science-bio-note">Example data · not laboratory measurements.</p><svg className="science-bio-graph" viewBox="0 0 360 230" role="img" aria-labelledby={id}><title id={id}>{"Graph of solution concentration against percentage mass change, with labelled axes. Equivalent values are in the table. " + (plot ? 'The point at 0.2 mol/dm³ can be plotted using the controls below.' : 'A straight illustrative trend crosses the zero mass-change line between 0.2 and 0.4 mol/dm³.')}</title>{[-25,-20,-15,-10,-5,0,5,10,15,20].map(v=><g key={v}><path d={`M54 ${y(v)}H316`} stroke={v===0?'#91acc0':'#e3ecf2'} strokeDasharray={v===0?'4 3':undefined}/><text x="45" y={y(v)+4} textAnchor="end" fill={ink} fontSize="12">{v>0?'+':''}{v}</text></g>)}<path d="M54 35V179H328" fill="none" stroke={ink} strokeWidth="2" />{[0,.1,.2,.3,.4,.5,.6,.7,.8].map(c=><text key={c} x={x(c)} y="194" textAnchor="middle" fontSize="12" fill={ink}>{c.toFixed(1)}</text>)}{!plot && <path d={`M${x(0)} ${y(15)}L${x(.8)} ${y(-25)}`} fill="none" stroke="#9c80c4" strokeWidth="2"/>}{transportData.filter(d=>!plot||d.concentration!==.2).map(d=><circle key={d.concentration} cx={x(d.concentration)} cy={y(d.percent)} r="4" fill={blue} stroke={ink}/>)}{plot&&plotted!==null&&<circle cx={x(.2)} cy={y(plotted)} r="6" fill={amber} stroke={ink}/>}<text x="187" y="218" textAnchor="middle" fontSize="12" fill={ink}>Concentration (mol/dm³)</text><text transform="translate(16 111) rotate(-90)" textAnchor="middle" fontSize="12" fill={ink}>Mass change (%)</text></svg>
    <table className="science-bio-table"><caption>Example plant-tissue results</caption><thead><tr><th scope="col">Concentration<br/>(mol/dm³)</th><th scope="col">Initial<br/>(g)</th><th scope="col">Final<br/>(g)</th><th scope="col">Change<br/>(%)</th></tr></thead><tbody>{transportData.map(d=><tr key={d.concentration}><th scope="row">{d.concentration.toFixed(1)}</th><td>{d.initial.toFixed(2)}</td><td>{d.final.toFixed(2)}</td><td>{d.percent>0?'+':''}{d.percent}</td></tr>)}</tbody></table>
    {plot&&<div className="science-bio-plot"><p>At 0.2 mol/dm³, select the percentage mass change to plot.</p><div role="group" aria-label="Select graph point">{[-5,5,15].map(v=><button className="science-secondary" type="button" key={v} aria-pressed={selected===v} onClick={()=>{setSelected(v);setPlotted(null)}}>{v>0?'+':''}{v}%</button>)}</div><button className="science-secondary" type="button" disabled={selected===null} onClick={()=>setPlotted(selected)}>Plot point</button>{plotted!==null&&<p role="status">{plotted===5?'Point plotted at (0.2, +5).':'Compare your plotted point with the table: the value is +5%, above the zero line.'}</p>}</div>}
  </div>
}
export function TransportVisual({ focus, assessment = false }: { focus: string; assessment?: boolean }) {
  if (focus==='diffusion'||focus==='diffusion-question'||focus.startsWith('osmosis')||focus==='active'||focus==='gut-active') return <ParticleModel focus={focus} assessment={assessment}/>
  if (focus.startsWith('exchange-')) return <ExchangeSurface focus={focus}/>
  if (focus==='ratio') return <CubeRatios/>
  if (focus==='practical-setup') return <PracticalSetup/>
  if (['practical-data','practical-graph','graph-question','plot'].includes(focus)) return <PracticalGraph plot={focus==='plot'}/>
  const notes: Record<string,string[]> = {
    'diffusion-examples':['Oxygen: blood → cells when cell concentration is lower','Carbon dioxide: respiring cells → blood','Urea: cells → blood plasma'],
    'diffusion-rate':['Steeper gradient → faster net diffusion','Higher temperature → faster particle movement','Larger area → more particles can cross at once'],
    'tissue-gain':['Outside: more dilute','Net water enters cells','Tissue can gain mass'],
    'tissue-loss':['Outside: more concentrated','Net water leaves cells','Tissue can lose mass'],
    'transport-compare':['Diffusion: net higher → lower concentration','Osmosis: water, dilute → concentrated across a partially permeable membrane','Active transport: lower → higher concentration; energy from respiration'],
    'practical-setup':['Teacher-prepared plant tissue and labelled concentration range','Balance: initial and consistently blotted final mass','Same time, temperature, volumes, tissue type/dimensions; repeats'],
    percentage:['Example sample','Initial mass: 2.00 g','Final mass: 2.20 g'],
    'ratio-worked':['Cube side: 2 cm','Six equal square faces','Area = 6 × side²; volume = side³'],
    'uptake-rate':['Example mass gain: 0.20 g','Time taken: 40 min','Rate = 0.005 g/min'],
  }
  return notes[focus] ? <div className="science-bio-cards">{notes[focus].map(s=><div key={s}>{s}</div>)}</div> : null
}
