import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { shcPracticalFrames as frames } from './teachingFrames'

const source = { id: 'aqa-physics', title: 'AQA 8464 Physics subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', locator: '6.1.1.3 Specific heat capacity, required practical (method with a block and an electric heater, the heater energy from power × time, ΔE = m × c × Δθ rearranged for c), as on the supplied revision page' }
const skill = 'P-SHC-PRACTICAL'
const setup = author(skill, ['6.1.1.3'], ['aqa-physics'])
const method = author(skill, ['6.1.1.3'], ['aqa-physics'])
const calc = author(skill, ['6.1.1.3'], ['aqa-physics'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const shcPracticalSections = [
  { id: 'P7-01', label: 'Start here', detail: 'A hot block in a cool room' },
  { id: 'P7-02', label: 'What are we measuring?', detail: 'The aim, the equipment and what to control' },
  { id: 'P7-05', label: 'How do you run it?', detail: 'The method and staying safe' },
  { id: 'P7-08', label: 'How do you find c?', detail: 'Energy from power × time, then c = ΔE ÷ (m × Δθ)' },
  { id: 'P7-12', label: 'On your own', detail: 'A calculation, the results and the set-up' },
]

const states: ScienceState[] = [
  { ...setup.choice('P7-01', 'A hot metal block is left on a bench in a cool room. What happens to its energy?', ['It stays in the block for ever', 'It is transferred by heating to the cooler surroundings', 'It disappears', 'It turns into extra mass'], 1, 'Think about what happens to a hot drink left out on a table.', ['Energy moves from the hot block to the cooler air around it, by heating.', 'Energy is never destroyed, so it is still there, just spread out into the surroundings.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(setup, 'P7-02', 'What are we measuring?'),
  setup.choice('P7-03', 'Why is a layer of insulation wrapped round the block?', ['To make the heater more powerful', 'To stop the block getting warm', 'To reduce the energy lost to the surroundings', 'To measure the mass of the block'], 2, 'Where would energy go if the block was left bare?', ['A bare block would transfer energy by heating to the air.', 'Insulation reduces this loss, so more of the heater energy stays in the block.'], 'practicalReasoning'),
  setup.choice('P7-04', 'A student compares two materials. Which set of things should stay the same?', ['The material of the block', 'The mass, heater power and heating time', 'The temperature rise', 'The final temperature'], 1, 'You want a fair test: only the material should change.', ['Keep the mass, the heater power and the heating time the same for each material.', 'The temperature rise is what you measure, so it is allowed to differ.'], 'practicalReasoning'),
  t(method, 'P7-05', 'How do you run it?'),
  method.choice('P7-06', 'The heating time is finished. What is the safest thing to do?', ['Switch off, then leave the hot equipment to cool before moving it', 'Lift the block straight away to read the mass', 'Touch the block to check it is still hot', 'Pour cold water on the block'], 0, 'The heater and block are hot, and the heater is electrical.', ['Switch off the power, then let the hot heater and block cool.', 'Touching hot metal can burn you, and water near electrical equipment is dangerous.'], 'practicalReasoning'),
  method.choice('P7-07', 'Which two things should you record before you switch on the heater?', ['The final temperature and the heating time', 'The mass of the block and its starting temperature', 'The specific heat capacity and the final temperature', 'The energy transferred and the power'], 1, 'These are measurements you can take before any heating happens.', ['You measure the mass on a balance and read the starting temperature before you switch on.', 'The final temperature and the time come later. The energy and the specific heat capacity are calculated.'], 'practicalReasoning'),
  t(calc, 'P7-08', 'How do you find c?'),
  calc.worked('P7-09', 'Work out the specific heat capacity of a block', 'A 2.0 kg block is heated by a 100 W heater for 3 minutes. Its temperature rises from 20 °C to 29 °C. Assume all the energy from the heater goes into the block. What is its specific heat capacity?', ['Change the time to seconds: 3 minutes = 3 × 60 = 180 s.', 'Energy from the heater: E = P × t = 100 × 180 = 18 000 J. So ΔE = 18 000 J.', 'Temperature change: Δθ = 29 − 20 = 9 °C.', 'c = ΔE ÷ (m × Δθ) = 18 000 ÷ (2.0 × 9) = 18 000 ÷ 18 = 1000 J/kg°C.'], 'shcprac-worked'),
  calc.choice('P7-10', 'A 1.5 kg block is heated at 60 W for 5 minutes, from 18 °C to 28 °C. What is c?', ['20 J/kg°C', '1800 J/kg°C', '1200 J/kg°C', '18 000 J/kg°C'], 2, 'Work in this order: time in seconds, energy, temperature change, then c.', ['5 minutes = 300 s. E = 60 × 300 = 18 000 J. Δθ = 28 − 18 = 10 °C.', 'c = 18 000 ÷ (1.5 × 10) = 18 000 ÷ 15 = 1200 J/kg°C.'], 'calculation'),
  calc.choice('P7-11', 'Which equation gives the specific heat capacity from the results of the experiment?', ['c = ΔE × m × Δθ', 'c = (m × Δθ) ÷ ΔE', 'c = m ÷ (ΔE × Δθ)', 'c = ΔE ÷ (m × Δθ)'], 3, 'Start from ΔE = m × c × Δθ and get c on its own.', ['Divide both sides of ΔE = m × c × Δθ by m × Δθ.', 'That leaves c = ΔE ÷ (m × Δθ).'], 'recall'),
  calc.choice('P7-12', 'A 200 W heater warms a 0.50 kg block for 1 minute, from 20 °C to 50 °C. What is c?', ['400 J/kg°C', '24 000 J/kg°C', '800 J/kg°C', '12 000 J/kg°C'], 2, 'Change 1 minute to seconds first, then find the energy and the temperature change.', ['1 minute = 60 s. E = 200 × 60 = 12 000 J. Δθ = 50 − 20 = 30 °C.', 'c = 12 000 ÷ (0.50 × 30) = 12 000 ÷ 15 = 800 J/kg°C.'], 'calculation', true),
  setup.choice('P7-13', 'In a real experiment some energy still escapes to the air. How does this affect the value of c you calculate?', ['Too high', 'Too low', 'It has no effect', 'It is impossible to say'], 0, 'Less energy reached the block than you assumed. What does that do to the temperature rise?', ['You calculated the energy from the heater, but some never reached the block.', 'The block warmed less than it should, so dividing by a small temperature rise makes c too high.'], 'practicalReasoning', true),
  setup.choice('P7-14', 'Which numbered part of the set-up reduces the energy transferred to the air?', ['Part 1', 'Part 2', 'Part 3', 'Part 4'], 3, 'It is wrapped around the outside of the block.', ['Part 4 is the layer of insulation round the block.', 'It slows the transfer of energy by heating to the surroundings.'], 'practicalReasoning', true, 'shcprac-q-setup'),
  calc.choice('P7-15', 'Two blocks of equal mass are heated by the same heater for the same time. Which has the higher c?', ['Block Y', 'Both are equal', 'It cannot be told', 'Block X'], 3, 'Both blocks received the same energy. Which warmed less?', ['The same energy went into each block, and block X warmed less.', 'It took more energy for each degree of warming, so block X has the higher specific heat capacity.'], 'dataInterpretation', true, 'shcprac-q-results'),
  setup.written('P7-16', 'Describe how you would find the specific heat capacity of a metal block using an electric heater. Include one safety point.', 'Cover the measurements, the heating, the calculation and safety.', 'Measure the mass of the block and wrap it in insulation. Put the heater and thermometer in the holes and record the starting temperature. Switch on the heater and time it for a set number of minutes, then read the final temperature. Work out the energy from power × time, with time in seconds, and the temperature change. Then c = ΔE ÷ (m × Δθ). The heater and block get hot, so let them cool before moving them.', ['Measure the mass of the block, and wrap it in insulation.', 'Record the starting temperature, heat for a measured time, then record the final temperature.', 'Energy from the heater = power × time, with time in seconds.', 'Temperature change = final − starting temperature.', 'c = ΔE ÷ (m × Δθ).', 'One sensible safety point, such as letting the hot heater and block cool before touching them.'], ['Using time in minutes in the equation.', 'Saying the online lesson has completed the practical.', 'Forgetting to mention insulation or the mass.']),
]

export const lessonP7: ScienceLesson = {
  id: 'P-ENE-007-P', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'physics',
  title: 'Investigating specific heat capacity', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
