import type { TeachingFrame } from '../../teachingFrame'

// Preparation for the specific heat capacity required practical: aim and kit, the method and safety, then the calculation.
// The heater's power is given in watts, so energy = power × time is used (not P = VI). The online lesson prepares students;
// the practical itself is done in the lab with a teacher.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const shcPracticalFrames: Record<string, TeachingFrame[]> = {
  'P7-02': [
    f('The aim', 'Heat a block, measure how much its temperature rises, and use the results to find its specific heat capacity.', 'energy in, temperature rise', 'Specific heat capacity tells you how much energy it takes to warm 1 kg of a material by 1 °C. In this practical you heat a block and find the value from your measurements. Your teacher runs it in the lab. Here you learn the method so you can do it well.', 'shcprac-aim'),
    f('The equipment', 'You need a block with two holes, a heater, a thermometer, a power supply, insulation, a balance and a stopwatch.', 'block, heater, thermometer, insulation', 'The block is a solid piece of metal with two holes. The electric heater fits in one hole and the thermometer in the other. A layer of insulation, such as thick newspaper, is wrapped round the block. You also need a balance to measure the mass, a stopwatch, and a power supply.', 'shcprac-kit'),
    f('Where the energy goes', 'Energy is transferred electrically to the heater, then by heating to the block. Insulation cuts the energy lost to the air.', 'power supply → heater → block', 'Energy is transferred electrically from the power supply to the heater. The heater then transfers energy by heating to the thermal store of the block, so the block warms up. The insulation reduces the energy that escapes into the air. We assume all the energy from the heater goes into the block.', 'shcprac-energy'),
    f('What to control', 'Measure the temperature rise. Keep the mass, the heater power and the heating time the same when comparing materials.', 'change one thing, keep the rest', 'To compare two materials, change only the material. The temperature rise is what you measure. Keep the mass of the block, the power of the heater and the heating time the same. Then any difference in temperature rise is because of the material.', 'shcprac-variables'),
  ],
  'P7-05': [
    f('Set up', 'Find the mass of the block, wrap it in insulation, then put the heater and thermometer into the holes.', 'mass first, then assemble', 'First measure the mass of the block on a balance and write it down. Wrap the block in insulation. Push the heater into one hole and the thermometer into the other. Connect the heater to the power supply, but leave it switched off.', 'shcprac-setup'),
    f('Starting temperature', 'Read the starting temperature. Then switch on and start the stopwatch at the same moment.', 'start temperature, then switch on', 'Read the thermometer and record the starting temperature. Then switch on the power supply and start the stopwatch at the same time. Your teacher will give you the power of the heater in watts, for example 50 W.', 'shcprac-start'),
    f('Heat for a fixed time', 'Heat for a set time, such as 10 minutes. Then read the final temperature and switch off.', 'set time, final temperature', 'Leave the heater on for a set time, such as 10 minutes. When the time is up, read the final temperature and switch off the power. Write down the time you used. You will change it to seconds later.', 'shcprac-end'),
    f('Stay safe', 'The heater and block get hot. Do not touch them, and let them cool before you move anything.', 'hot equipment', 'The heater and the block can get very hot. Do not touch them while the power is on. After switching off, leave them to cool before you move them. Keep the electrical parts away from water, and take care with the glass thermometer.', 'shcprac-safety'),
    f('Try another material', 'Repeat with another block. For a liquid, use an insulated beaker with a known mass of liquid.', 'same method, new material', 'You can repeat the whole method with a block of a different material. To test a liquid, put the heater and thermometer into an insulated beaker holding a known mass of the liquid. Keep the mass, power and time the same each time, so the results can be compared.', 'shcprac-repeat'),
  ],
  'P7-08': [
    f('Energy from the heater', 'The heater transfers energy = power × time. Time must be in seconds.', 'E = P × t', 'The heater is given as a power in watts. The energy it transfers is E = P × t. Time must be in seconds. A 50 W heater on for 10 minutes runs for 10 × 60 = 600 s. It transfers 50 × 600 = 30 000 J.', 'shcprac-energy-pt'),
    f('All the energy reaches the block', 'We assume all the energy from the heater goes into the block, so E is the change in its thermal energy, ΔE.', 'energy from heater = ΔE', 'We assume all the energy from the heater is transferred to the thermal store of the block. Then the energy you worked out from the heater is the same as the change in the thermal energy of the block. This is written ΔE. In real life a little energy still escapes.', 'shcprac-assume'),
    f('The temperature rise', 'Change in temperature = final temperature − starting temperature.', 'final − start', 'The change in temperature is written Δθ. To find it, take the final temperature and subtract the starting temperature. A block that starts at 20 °C and ends at 26 °C has Δθ = 26 − 20 = 6 °C.', 'shcprac-dtheta'),
    f('Turn the equation round', 'ΔE = m × c × Δθ becomes c = ΔE ÷ (m × Δθ). The unit is J/kg°C.', 'divide by m × Δθ', 'You already know ΔE = m × c × Δθ. To get c on its own, divide both sides by m × Δθ. That gives c = ΔE ÷ (m × Δθ). The mass m is in kilograms, so c comes out in J/kg°C.', 'shcprac-rearrange'),
  ],
}
