/*
 * Higher-only sections for chapter P6 (waves), from the CGP AQA Combined Science Higher guide pages 229 and 230 (scope
 * only; all wording, diagrams, numbers and questions are original). AQA 8464 HT content: 6.6.2.2 (use wave front diagrams
 * to explain refraction in terms of the change of speed; the same spec point as the Foundation lesson) and 6.6.2.3 (radio
 * waves are produced by oscillations in electrical circuits; when absorbed they may create an alternating current with the
 * same frequency). Diagrams: components/HigherWaveVisuals.tsx ('hwave-').
 */
import { addition, f, type HigherAddition } from './helpers'

// Physics Lesson 56 · Higher p229: wave fronts, one end slowing first, shorter wavelength, same frequency. Before "On your own".
const wavefronts = addition('P-WAV-056-P', 'P56-13', 'P-HIGHER-REFRACT-FRONTS', ['6.6.2.2'],
  { id: 'P56-H01', higher: true, label: 'Why waves bend', detail: 'Wave fronts and a change of speed' },
  [
    f('Wave fronts', 'Wave fronts are lines joining the same point on each wave, such as every crest.', 'one line per crest → a wavelength apart', 'Picture light arriving as a set of waves. Draw a line along each crest. These lines are called wave fronts. Neighbouring wave fronts are one wavelength apart. The wave travels at right angles to its wave fronts.', 'hwave-fronts'),
    f('One end slows first', 'The wave meets the glass at an angle, so one end of each wave front reaches it first and slows down.', 'one end in glass (slow), one end in air (fast)', 'Light travels more slowly in glass than in air. These wave fronts meet the boundary at an angle. So one end of each wave front reaches the glass first and slows down. The other end is still in the air, moving faster.', 'hwave-slow'),
    f('The wave front turns', 'The slow end falls behind, so each wave front turns. A wave that slows down bends towards the normal.', 'slow end lags → front turns → towards the normal', 'The slow end falls behind while the fast end keeps going. So each wave front turns as it crosses the boundary. The wave changes direction, so it is refracted. A wave that slows down bends towards the normal.', 'hwave-turn'),
    f('Shorter waves, same frequency', 'When the wave slows down, its wavelength gets shorter. Its frequency stays the same.', 'slower → fronts closer together', 'In the glass the wave fronts are closer together, so the wavelength is shorter. The number of waves reaching the boundary each second is the same as the number leaving it. So the frequency stays the same.', 'hwave-wavelength'),
    f('Put it together', 'Slowing down bends a wave towards the normal. Speeding up bends it away. Along the normal there is no bend.', 'slower → towards; faster → away; along the normal → straight on', 'It works the other way too. Light going from glass into air speeds up, so it bends away from the normal. A wave travelling along the normal reaches the boundary all at once. Its whole wave front changes speed together, so its wavelength changes but its direction does not.', 'hwave-all'),
  ],
  a => [
    a.choice('P56-H02', 'Light travels from air into glass at an angle. Why does it change direction?', ['The glass reflects one end of each wave front', 'One end of each wave front reaches the glass first and slows down, so the wave front turns', 'The light speeds up as soon as it touches the glass', 'The frequency of the light changes in the glass'], 1, 'Think about which end of a wave front reaches the glass first.', ['The wave fronts meet the boundary at an angle, so one end enters the glass first.', 'That end slows down while the other end is still fast, so each wave front turns.']),
    a.choice('P56-H03', 'The diagram shows wave fronts crossing a boundary from material 1 into material 2. In which material does the wave travel more slowly?', ['Material 1, because its wave fronts are further apart', 'Neither, because the frequency stays the same', 'Material 2, because its wave fronts are closer together', 'Material 2, because the wave bends away from the normal'], 2, 'Compare how far apart the wave fronts are on each side of the boundary.', ['In material 2 the wave fronts are closer together, so the wavelength is shorter. The frequency stays the same, so the wave is slower there.', 'The wave also bends towards the normal, which is what happens when a wave slows down.'], 'dataInterpretation', false, 'hwave-q-fronts'),
    a.choice('P56-H04', 'A light wave travels from air into water along the normal. What happens to it?', ['It slows down and its wavelength gets shorter, but it does not change direction', 'It slows down and bends towards the normal', 'It keeps the same speed and the same wavelength', 'It slows down, its wavelength gets shorter and its frequency gets lower'], 0, 'Along the normal, the whole wave front reaches the boundary at the same time.', ['Light is slower in water, so its wavelength gets shorter. Its frequency stays the same.', 'Along the normal the whole wave front slows at once, so it does not change direction.'], 'application', true),
  ])

// Physics Lesson 58 · Higher p230: radio waves made by oscillating charges, and absorbed to give an ac of the same frequency. Before "On your own".
const makingRadio = addition('P-WAV-058-P', 'P58-12', 'P-HIGHER-RADIO-AC', ['6.6.2.3'],
  { id: 'P58-H01', higher: true, label: 'Making radio waves', detail: 'Oscillating electrons in aerials' },
  [
    f('Charges that move to and fro', 'In an alternating current, electrons move one way, then back again, over and over. This is called oscillating.', 'back and forth → oscillate', 'You met alternating current when you learned about mains electricity. In an alternating current, the electrons in a wire move one way, then the other, again and again. Moving to and fro like this is called oscillating.', 'hwave-radio-ac'),
    f('Making radio waves', 'Electrons oscillating in a transmitter aerial produce radio waves.', 'oscillating electrons → radio waves out', 'A transmitter sends an alternating current into a metal rod called an aerial. The electrons in the aerial oscillate. Oscillating charges like these produce radio waves. The radio waves spread out and transfer energy away from the aerial.', 'hwave-radio-make'),
    f('Absorbed by a receiver', 'When radio waves are absorbed by a receiver aerial, they make its electrons oscillate.', 'waves absorbed → electrons oscillate', 'The radio waves reach the aerial of a receiver, such as a radio, and are absorbed. The energy they carry makes the electrons in the receiver aerial oscillate too. It is the same process as in the transmitter, but in reverse.', 'hwave-radio-receive'),
    f('The same frequency', 'The oscillating electrons make an alternating current with the same frequency as the radio wave.', 'same number of to-and-fros each second', 'The electrons oscillating in the receiver aerial make an alternating current in its circuit. This current has the same frequency as the radio wave that made it. The radio uses this current to pick up the programme.', 'hwave-radio-same'),
    f('Put it together', 'Alternating current → oscillating electrons → radio waves → oscillating electrons → alternating current.', 'ac in, waves across, ac out at the same frequency', 'At the transmitter, an alternating current makes the electrons in the aerial oscillate, and this produces radio waves. At the receiver, the radio waves are absorbed and make the electrons oscillate. This gives an alternating current with the same frequency as the wave.', 'hwave-radio-all'),
  ],
  a => [
    a.choice('P58-H02', 'How are radio waves produced in a transmitter?', ['Sound in the studio pushes waves out of the aerial', 'A direct current heats the aerial until it glows', 'Atoms in the aerial give out gamma rays', 'An alternating current makes electrons in the aerial oscillate'], 3, 'Think about what the electrons in the aerial do.', ['An alternating current flows in the transmitter aerial.', 'The electrons in it oscillate, and oscillating charges produce radio waves.'], 'recall'),
    a.choice('P58-H03', 'Screen X shows the alternating current in a transmitter aerial. Which screen could show the current that its radio waves make in a receiver aerial?', ['Screen A', 'Screen B', 'Screen C'], 1, 'Count the waves across each screen.', ['The current in the receiver has the same frequency as the radio wave, and so the same frequency as the current in the transmitter.', 'Screen B has the same number of waves across it as screen X. Screen A has twice as many, and screen C is a direct current.'], 'dataInterpretation', false, 'hwave-q-traces'),
    a.choice('P58-H04', 'A radio station sends out radio waves with a frequency of 100 MHz. What is the frequency of the alternating current they make in a receiver aerial?', ['50 MHz', '200 MHz', '100 MHz', 'There is no frequency, because they make a direct current'], 2, 'Compare the current in the receiver with the wave that made it.', ['The radio waves make the electrons in the receiver aerial oscillate.', 'This gives an alternating current with the same frequency as the wave: 100 MHz.'], 'application', true),
  ])

export const higherP6: HigherAddition[] = [wavefronts, makingRadio]
