import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { lungsFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.2.2.2 Structure and function of the lungs; adaptation for gaseous exchange' }
const a = author('B-LUNGS', ['4.2.2.2'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])
const visual = <S extends ReturnType<typeof a.choice>>(state: S, id: string, description: string): S => ({ ...state, visual: { id, kind: 'cellModel' as const, brief: 'Original Revily schematic; not to scale.', accessibleDescription: description, assessmentDescription: 'An unlabelled original schematic. All information needed to answer is provided in the question.' } })

export const lungsSections = [
  { id: 'B10-01', label: 'Start here', detail: 'Why you breathe hard when you run' },
  { id: 'B10-02', label: 'Follow one breath', detail: 'Trachea, bronchi and alveoli' },
  { id: 'B10-05', label: 'Where air meets blood', detail: 'Oxygen in, carbon dioxide out' },
  { id: 'B10-08', label: 'Why alveoli work so well', detail: 'Large area, thin walls, good blood supply' },
  { id: 'B10-11', label: 'Why keep breathing?', detail: 'Ventilation keeps the difference big' },
  { id: 'B10-14', label: 'On your own', detail: 'Errors, data and a new case' },
]

const states: ScienceState[] = [
  { ...a.choice('B10-01', 'You run for a bus. Afterwards you are breathing hard. Why does your body breathe faster when you run?', ['To cool down your stomach', 'Your working muscles need more oxygen from the air', 'To get rid of digested food'], 1, 'Which gas in the air do your muscles need?', ['Running muscles work hard, so they need more oxygen.', 'So you breathe faster and deeper to take in more air.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B10-02', 'Follow one breath'),
  visual(a.choice('B10-03', 'Air passes points 1, 2, 3 and 4 in order. Which list names them in order?', ['Bronchi, trachea, smaller tubes, alveoli', 'Alveoli, smaller tubes, bronchi, trachea', 'Trachea, bronchi, smaller tubes, alveoli', 'Trachea, alveoli, bronchi, smaller tubes'], 2, 'Which tube is in your neck, and where does the route end?', ['Air goes down the trachea first, then splits into the two bronchi.', 'So it passes through smaller tubes last and ends in the alveoli.']), 'lung-route-question', 'A branching airway inside two lungs, with four numbered pointers from the top tube to the tiny air sacs.'),
  a.choice('B10-04', 'Why do the tubes in the lungs branch again and again?', ['To carry air to every part of the lung', 'To slow the air down so it warms up', 'To pump blood around the lungs'], 0, 'What did the branches do, like the branches of a tree?', ['Each bronchus branches many times inside the lung.', 'So air is carried to millions of alveoli all through the lung, not just the middle.']),
  t('B10-05', 'Where air meets blood'),
  visual(a.choice('B10-06', 'Arrow X points from the air in an alveolus into the blood. Which gas moves this way?', ['Oxygen', 'Carbon dioxide', 'Both gases, taking turns'], 0, 'Which gas does fresh air in the alveolus have lots of?', ['Fresh air in the alveolus has more oxygen than the blood arriving.', 'So oxygen diffuses along arrow X, from the air into the blood.']), 'lung-gas-question', 'An alveolus beside a capillary, with arrow X from air to blood and arrow Y from blood to air.'),
  a.choice('B10-07', 'Why does carbon dioxide move from the blood into the alveolus?', ['The alveolus sucks it out of the blood', 'The air in the alveolus has more carbon dioxide than the blood', 'The blood has more carbon dioxide than the air in the alveolus'], 2, 'Where is there lots of carbon dioxide, and where is there less?', ['Blood arriving at the lungs carries lots of carbon dioxide from your cells.', 'The air in the alveolus has less, so carbon dioxide diffuses into the alveolus.']),
  t('B10-08', 'Why alveoli work so well'),
  a.choice('B10-09', 'How do thin walls help gas exchange?', ['They stop blood leaking into the air', 'Gases only have a short distance to travel', 'They give the lungs more alveoli'], 1, 'How far does a gas travel across a wall one cell thick?', ['The alveolus wall and the capillary wall are each one cell thick.', 'So gases travel only a short distance, and diffusion is fast.']),
  a.choice('B10-10', 'Why does blood need to keep flowing past the alveoli?', ['To warm the air in the alveoli', 'To push air down the trachea', 'To make new alveoli', 'To carry oxygen away, so more can diffuse in'], 3, 'What would happen if the same blood stayed next to the alveolus?', ['Flowing blood carries oxygen-rich blood away and brings blood with less oxygen.', 'So the difference stays big, and oxygen keeps diffusing into the blood.']),
  t('B10-11', 'Why keep breathing?'),
  a.choice('B10-12', 'What is ventilation?', ['Moving air in and out of the lungs', 'Oxygen diffusing into the blood', 'Blood flowing past the alveoli'], 0, 'What does breathing in and out do to the air in your lungs?', ['Breathing in brings fresh air in, and breathing out takes used air out.', 'So moving air in and out of the lungs is called ventilation.'], 'recall'),
  a.choice('B10-13', 'When you run, you breathe faster and deeper. How does this help your blood get more oxygen?', ['It makes the alveolus walls thicker', 'It makes the heart pump air into the lungs', 'Fresh air comes in faster, so the oxygen difference stays big'], 2, 'What does ventilation do to the oxygen in the alveoli?', ['Faster, deeper breathing brings fresh air into the alveoli more quickly.', 'So the air stays high in oxygen, and oxygen keeps diffusing into the blood quickly.'], 'application'),
  a.choice('B10-14', 'A student writes: “Gas exchange happens in the trachea, because it is the biggest airway.” What is wrong?', ['Gas exchange happens in the bronchi, not the trachea', 'Gas exchange happens in the alveoli, at the ends of the smallest tubes', 'Gas exchange happens in the heart', 'Nothing, the student is right'], 1, 'Where do the capillaries wrap around the airway?', ['The trachea and bronchi only carry air into the lungs.', 'Capillaries wrap around the alveoli, so gas exchange happens there.'], 'understanding', true),
  a.choice('B10-15', 'A student tests air. In this test, breathed-in air had 21% oxygen and breathed-out air had 16% oxygen. Which conclusion fits?', ['Breathed-out air has no oxygen at all', 'All the oxygen breathed in passed into the blood', 'This proves everyone takes in the same amount of oxygen', 'In this test, breathed-out air had less oxygen, so some oxygen passed into the blood'], 3, 'What do the two numbers show, and what can’t they show?', ['Breathed-out air had 16% oxygen: less than the 21% breathed in, but not zero.', 'So in this test, some oxygen passed into the blood. One test cannot show what happens in everyone.'], 'dataInterpretation', true),
  a.choice('B10-16', 'In one lung disease, the thin walls between alveoli break down. The person has fewer, bigger air sacs. Why do they get out of breath easily?', ['The surface area is smaller, so less oxygen gets into the blood', 'The trachea is blocked, so no air gets in', 'The air sacs are bigger, so more oxygen gets into the blood'], 0, 'Do a few big sacs have more or less surface than millions of tiny ones?', ['Fewer, bigger sacs have a smaller total surface area than many tiny ones.', 'So less oxygen can diffuse into the blood at once, and the person gets out of breath.'], 'application', true),
  a.written('B10-17', 'Follow one breath. Explain how oxygen gets from the air into your blood, and why this happens quickly.', 'First trace the route. Then say how oxygen crosses into the blood. Then name the features that make it fast.', 'Air goes down the trachea, into the bronchi and through smaller tubes to the alveoli. Oxygen diffuses from the air in the alveoli into the blood, because the air has more oxygen. Millions of alveoli give a large surface area, and the thin walls make the distance short. Blood flow and ventilation keep the oxygen difference big.', ['Air travels down the trachea, then the bronchi, to the alveoli.', 'Oxygen diffuses from the air in the alveoli into the blood.', 'Many alveoli give a large surface area.', 'Thin walls give a short distance for diffusion.', 'Blood flow or ventilation keeps the oxygen difference big.'], ['Gas exchange is said to happen in the trachea or bronchi.', 'Oxygen is said to move from the blood into the alveoli.', 'Thick walls are said to help gas exchange.']),
]

export const lesson10: ScienceLesson = {
  id: 'B-ORG-010-B', contentVersion: '0.3.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'The lungs', prerequisites: ['B-DIFFUSION'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
