import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { copperFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.10.1.4 Alternative methods of extracting metals (HT): copper ores becoming scarce, low-grade ores, phytomining and bioleaching, copper from solutions by displacement with scrap iron or by electrolysis, as on the supplied revision page' }
const skill = 'C-EXTRACT'
const copper = author(skill, ['5.10.1.4'], ['aqa-chemistry'])
const t = (id: keyof typeof frames, title: string) => copper.teach(id, title, frames[id])

export const copperSections = [
  { id: 'C50H-01', label: 'Start here', detail: 'What does finite mean?' },
  { id: 'C50H-02', label: 'Copper is running short', detail: 'Copper-rich and low-grade ores' },
  { id: 'C50H-05', label: 'Bioleaching', detail: 'Bacteria and a leachate of copper ions' },
  { id: 'C50H-08', label: 'Phytomining', detail: 'Plants, a furnace and ash' },
  { id: 'C50H-11', label: 'From solution to copper', detail: 'Electrolysis, scrap iron, and the pros and cons' },
  { id: 'C50H-15', label: 'On your own', detail: 'A diagram, some data and a new metal' },
]

const states: ScienceState[] = [
  { ...copper.choice('C50H-01', 'Copper is a finite resource. What does finite mean?', ['It is made again as fast as we use it', 'There is only so much, so it will run out', 'It is only found in plants', 'It can never be recycled'], 1, 'Think about what happens if we keep using it.', ['A finite resource is not being made again, so there is a limited amount and it will run out.', 'Copper can be recycled, but the copper ores in the ground will not last for ever. This lesson is about new ways to make them last.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t('C50H-02', 'Copper is running short'),
  copper.choice('C50H-03', 'What is a low-grade ore?', ['An ore with only a small amount of metal in it', 'An ore with lots of copper in it', 'Copper that has been recycled', 'A rock with no metal in it at all'], 0, 'Low-grade is the opposite of copper-rich.', ['A low-grade ore contains only a small amount of the metal.', 'A copper-rich ore has lots of copper in it. A low-grade ore still has some copper, just not much.'], 'recall'),
  copper.choice('C50H-04', 'Why is copper now being extracted from low-grade ores?', ['Low-grade ores contain more copper', 'Low-grade ores are easier to dig up', 'Copper-rich ores are running out', 'Copper is a renewable resource'], 2, 'Think about the supply of copper-rich ore.', ['Copper-rich ores are in short supply, because most have already been used.', 'There is still lots of low-grade ore, so getting copper from it makes the copper last longer.']),

  t('C50H-05', 'Bioleaching'),
  copper.choice('C50H-06', 'In bioleaching, what do the bacteria do?', ['They eat the copper and grow bigger', 'They turn copper into iron', 'They melt the ore', 'They convert copper compounds in the ore into soluble copper compounds'], 3, 'What has to happen for the copper to get into the solution?', ['The bacteria convert the copper compounds in the ore into soluble copper compounds.', 'These dissolve, so the copper moves out of the rock and into the solution.']),
  copper.choice('C50H-07', 'Bioleaching produces a leachate. What is the leachate?', ['Solid copper metal', 'A solution that contains copper ions', 'The waste rock left over', 'A gas given off by the bacteria'], 1, 'The soluble copper compounds dissolve. What do they give?', ['The leachate is the solution made in bioleaching.', 'It contains copper ions, Cu²⁺, from the soluble copper compounds. It is not copper metal yet.'], 'recall'),

  t('C50H-08', 'Phytomining'),
  copper.choice('C50H-09', 'Which shows the steps of phytomining in the right order?', ['Burn plants → grow plants → harvest → dry', 'Harvest → grow plants → burn → dry', 'Grow plants → harvest → dry → burn', 'Grow plants → burn → dry → harvest'], 2, 'The plants must take in copper before they are cut down.', ['The plants grow in copper soil first, so copper builds up in their leaves.', 'Then they are harvested, dried and burned. The ash contains the copper compounds.']),
  copper.choice('C50H-10', 'In phytomining, why are the plants burned?', ['To leave ash that contains copper compounds', 'To melt the copper so it runs out', 'To kill the bacteria in the leaves', 'To turn the copper into a gas'], 0, 'What is left after the plants have burned?', ['Burning gets rid of the plant material, but the copper stays behind.', 'It is left in the ash as soluble copper compounds.']),

  t('C50H-11', 'From solution to copper'),
  copper.worked('C50H-12', 'Get copper from a leachate with scrap iron', 'A leachate contains copper sulfate. Explain how scrap iron can be used to get copper metal from it.', ['Iron is more reactive than copper.', 'So when scrap iron is added to the leachate, the iron displaces the copper from the solution.', 'Word equation: iron + copper sulfate → iron sulfate + copper.', 'Copper metal forms and can be collected. The iron ends up in the solution as iron sulfate.'], 'hcopper-worked-iron'),
  copper.choice('C50H-13', 'A solution of copper ions is electrolysed. Where does copper metal form?', ['At the positive electrode', 'In the air above the solution', 'Spread evenly through the solution', 'At the negative electrode'], 3, 'Copper ions are Cu²⁺. Which electrode attracts positive ions?', ['Copper ions are positive, so they move to the negative electrode.', 'There they gain electrons and form copper metal.']),
  copper.choice('C50H-14', 'Compared with traditional mining, what is the main disadvantage of bioleaching and phytomining?', ['They do more damage to the land', 'They are slow', 'They only work with copper-rich ores', 'They make waste rock heaps'], 1, 'They have a much smaller impact on the environment. So what is the problem?', ['Bioleaching and phytomining do much less damage than traditional mining.', 'Their disadvantage is that they are slow, so the copper takes a long time to get.']),

  copper.choice('C50H-15', 'The diagram shows phytomining. At which numbered point does copper build up because the plant cannot use it?', ['Point 1', 'Point 2', 'Point 3', 'Point 4'], 1, 'Where in the plant does the copper end up?', ['The roots take in copper from the soil at point 1, but the copper does not stay there.', 'The plant cannot use it or get rid of it, so it builds up in the leaves, at point 2.'], 'understanding', true, 'hcopper-question-phyto'),
  copper.choice('C50H-16', 'The table shows made-up data for three ways of getting copper. Which conclusion do the data support?', ['Bioleaching is better than mining in every way', 'Traditional mining dumped the least waste rock', 'Phytomining is the cheapest method', 'Phytomining dumped the least waste rock but was the slowest'], 3, 'Look at both columns. Does the table say anything about cost?', ['Phytomining dumped 0 tonnes of waste rock, the least, but took 5 years, the longest time.', 'Bioleaching was slower than mining, so it is not better in every way. The table says nothing about cost.'], 'dataInterpretation', true, 'hcopper-data-methods'),
  copper.choice('C50H-17', 'Some plants take up nickel from the soil. How could these plants be used to extract nickel?', ['Grow, harvest, dry and burn them, then get the nickel from the ash', 'Squeeze the leaves to collect nickel metal', 'Add bacteria to the leaves to make them grow', 'Dig up the soil and throw the plants away'], 0, 'This is the same idea as phytomining for copper.', ['Phytomining can be used for other metals too. The nickel builds up in the plants.', 'The plants are harvested, dried and burned, and the nickel compounds are left in the ash.'], 'application', true),
  copper.choice('C50H-18', 'A student adds silver to copper sulfate solution to get copper. No copper forms. Why?', ['Silver is more reactive than copper', 'Only electrolysis can get copper from a solution', 'Silver is less reactive than copper', 'Copper sulfate does not contain copper'], 2, 'A metal can only displace a less reactive metal.', ['Silver is less reactive than copper, so it cannot displace copper from its compounds.', 'A more reactive metal, such as scrap iron, would work. So electrolysis is not the only way.'], 'application', true),
  copper.written('C50H-19', 'Describe how phytomining is used to get copper metal. Give one advantage and one disadvantage compared with traditional mining.', 'Think: grow, build up, harvest, burn, then turn the copper ions into metal. Then compare with digging up rock.', 'Plants are grown in soil that contains copper. Their roots take in copper compounds, and because the plants cannot use or get rid of the copper, it builds up in the leaves. The plants are harvested, dried and burned in a furnace. The ash contains soluble copper compounds, so it can be dissolved to give a solution of copper ions. Copper metal is then extracted by electrolysis or by displacement with scrap iron. An advantage is that phytomining has a much smaller impact on the environment, because no huge amounts of rock are dug up, moved and dumped. A disadvantage is that it is slow.', ['Plants are grown in soil that contains copper.', 'The copper builds up in the plants (in the leaves) because they cannot use it or get rid of it.', 'The plants are harvested, dried and burned; the ash contains soluble copper compounds.', 'A solution of copper ions is made, and copper metal is extracted by electrolysis or by displacement with scrap iron.', 'Advantage: much less damage to the environment, because no huge amounts of rock are dug up, moved and dumped.', 'Disadvantage: it is slow.'], ['Saying the plants make copper, or turn into copper.', 'Saying the copper is melted out of the plants.', 'Describing bacteria instead of plants (that is bioleaching).', 'Saying phytomining is faster than traditional mining.']),
]

export const lessonC50H: ScienceLesson = {
  id: 'C-RES-050H-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Extracting copper', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
