import type { TeachingFrame } from '../../teachingFrame'

// Extracting copper builds on finite resources and sustainability (the lessons just before), electrolysis and
// displacement. Each teaching section keeps one drawing on screen and adds to it frame by frame: three panels for why
// copper is running short, a tank of bacteria for bioleaching, a row of plants to ash for phytomining, and a solution
// of copper ions that branches into electrolysis and scrap iron. The last frame of each puts the steps together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const copperFrames: Record<string, TeachingFrame[]> = {
  'C50H-02': [
    f('Copper is finite', 'Copper is a finite resource, so the copper we can dig up will run out.', 'no more being made → it will run out', 'Copper is used for electrical wires and water pipes. We get it from rocks called ores. You met finite resources when you learned about using resources. Copper is one of them. No more is being made, so one day it will run out.', 'hcopper-short-finite'),
    f('Rich and low-grade ores', 'A copper-rich ore has lots of copper in it. A low-grade ore has only a little.', 'lots of copper → rich; a little → low-grade', 'Some copper ores have lots of copper in them. These are copper-rich ores. Other ores have only a small amount of copper. An ore like this is called a low-grade ore.', 'hcopper-short-grades'),
    f('Rich ores are running out', 'Copper-rich ores are in short supply, so copper is now taken from low-grade ores.', 'rich ores running out → use low-grade ores', 'Most of the copper-rich ores have already been dug up and used. The ones left are in short supply. But there is still lots of low-grade ore. Getting copper from low-grade ore makes our copper last longer. This helps make using copper more sustainable.', 'hcopper-short-running'),
    f('Mining does damage', 'Traditional mining digs up, moves and dumps huge amounts of rock, which damages the environment.', 'dig, move, dump → damage', 'Traditional copper mining digs huge amounts of rock out of the ground. The rock is moved away, and the waste rock is dumped. This damages the environment. A low-grade ore has so little copper that mining it this way would mean even more rock.', 'hcopper-short-mining'),
    f('Put it together', 'Bioleaching and phytomining are new ways to get copper from low-grade ores, using living things.', 'low-grade ore → bacteria or plants', 'So scientists have found new ways to get copper from low-grade ores. Both use living things. Bioleaching uses bacteria, and phytomining uses plants. Neither needs huge amounts of rock to be dug up, moved and dumped.', 'hcopper-short-all'),
  ],
  'C50H-05': [
    f('Bacteria do the work', 'Bioleaching uses bacteria to get copper out of low-grade ore.', 'bacteria + ore → bioleaching', 'Bacteria are tiny living things. Some kinds of bacteria can help get copper out of its ore. Using bacteria in this way is called bioleaching.', 'hcopper-bio-bacteria'),
    f('Ore into the solution', 'The copper ore is added to a solution that contains the bacteria.', 'ore goes into the bacteria solution', 'The low-grade copper ore is added to a solution. The solution has the bacteria in it. Now the bacteria are in contact with the ore.', 'hcopper-bio-added'),
    f('Making copper soluble', 'The bacteria convert copper compounds in the ore into soluble copper compounds.', 'copper compounds → soluble copper compounds', 'In the ore, the copper is in compounds that do not dissolve in water. The bacteria convert them into different copper compounds. These new compounds are soluble, which means they dissolve. So the copper moves out of the rock and into the solution.', 'hcopper-bio-soluble'),
    f('The leachate', 'The solution made contains copper ions. It is called a leachate.', 'solution with copper ions → leachate', 'When the copper compounds dissolve, they give copper ions, Cu²⁺. So the solution now contains copper ions. This solution is drained off and collected. It is called a leachate.', 'hcopper-bio-leachate'),
    f('Put it together', 'Ore in a solution of bacteria → soluble copper compounds → a leachate containing copper ions.', 'ore + bacteria → soluble → leachate', 'In bioleaching, low-grade ore is added to a solution of bacteria. The bacteria convert the copper compounds in the ore into soluble ones. These dissolve, so the solution becomes a leachate. The leachate contains copper ions. Next, the copper has to be got out of it.', 'hcopper-bio-all'),
  ],
  'C50H-08': [
    f('Plants on copper soil', 'In phytomining, plants are grown in soil that contains copper.', 'plants + copper soil → phytomining', 'Plants can also help get copper. The plants are grown in soil that contains copper compounds. Getting a metal with plants like this is called phytomining.', 'hcopper-phyto-grow'),
    f('Copper builds up in the leaves', 'The plants take in copper but cannot use it or get rid of it, so it builds up in the leaves.', 'roots take in copper → stuck in the leaves', 'As the plants grow, their roots take in copper compounds from the soil. The plants cannot use the copper, and they cannot get rid of it. So the copper gradually builds up in the plants, mostly in the leaves.', 'hcopper-phyto-absorb'),
    f('Harvest and dry', 'The plants are harvested, then dried.', 'cut, collect, dry', 'When the plants hold lots of copper, they are harvested. This means they are cut down and collected. Then they are dried.', 'hcopper-phyto-harvest'),
    f('Burn to ash', 'The dried plants are burned in a furnace. The ash contains soluble copper compounds.', 'burn → ash with copper compounds', 'The dried plants are burned in a furnace. The plant material burns away, but the copper stays behind. It is left in the ash, as soluble copper compounds. The ash can be dissolved to give a solution of copper ions.', 'hcopper-phyto-burn'),
    f('Put it together', 'Grow in copper soil → copper builds up in leaves → harvest and dry → burn → ash with copper compounds.', 'grow → build up → harvest → burn', 'In phytomining, plants grow in soil that contains copper. Copper builds up in their leaves, because they cannot use it or get rid of it. The plants are harvested, dried and burned. The ash contains soluble copper compounds.', 'hcopper-phyto-all'),
  ],
  'C50H-11': [
    f('One kind of solution', 'Bioleaching and phytomining both give a solution that contains copper ions.', 'leachate or dissolved ash → copper ions', 'Bioleaching gives a leachate. Phytomining gives ash, which can be dissolved. Both end with a solution that contains copper ions. The last job is to turn these ions into copper metal.', 'hcopper-finish-solution'),
    f('Electrolysis', 'Electrolysis of the solution makes copper metal at the negative electrode.', 'Cu²⁺ → negative electrode → copper', 'You met electrolysis when you learned about splitting compounds with electricity. Pass a current through the solution. The positive copper ions move to the negative electrode. There they gain electrons and form copper metal.', 'hcopper-finish-electrolysis'),
    f('Scrap iron', 'Scrap iron displaces copper from the solution, because iron is more reactive than copper.', 'iron more reactive → pushes copper out', 'Another way uses scrap iron, which is old iron that nobody needs. Iron is more reactive than copper. So when scrap iron is added to the solution, it displaces the copper. Copper metal forms, and the iron goes into the solution.', 'hcopper-finish-iron'),
    f('Cleaner but slower', 'The new methods do much less damage to the environment than traditional mining, but they are slow.', 'less damage, but slow', 'Bioleaching and phytomining have a much smaller impact on the environment than traditional mining. They avoid digging, moving and dumping huge amounts of rock. But they have one big disadvantage. They are slow, so getting the copper takes a long time.', 'hcopper-finish-impact'),
    f('Put it together', 'Low-grade ore → bioleaching or phytomining → solution of copper ions → electrolysis or scrap iron → copper metal.', 'ore → copper ions → copper metal', 'Bioleaching or phytomining turns low-grade ore into a solution of copper ions. Electrolysis or displacement with scrap iron then gives copper metal. These methods do much less damage than mining, but they are slow. They can be used to get other metals too.', 'hcopper-finish-all'),
  ],
}
