import type { TeachingFrame } from '../../teachingFrame'

// Lay the table out first (order, boxes, periods, groups), then explain the layout with electrons (group number,
// shells), then use it to predict, and only then split it into metals and non-metals and compare their properties.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const modernTableFrames: Record<string, TeachingFrame[]> = {
  'C8-02': [
    f('About 100 elements', 'The modern table lists the elements in order of atomic number.', 'atomic number 1, 2, 3 … → one box each', 'There are about 100 elements. The modern periodic table gives each one its own box. The boxes go in order of atomic number, the number of protons in an atom. Read each row from left to right, then carry on at the start of the next row.', 'mtab-order'),
    f('Reading a box', 'Each box shows a symbol and two numbers.', 'bottom number = atomic number; top number = relative atomic mass', 'Each box shows the element’s symbol and name. The number at the bottom is the atomic number. The number at the top is the relative atomic mass. For sodium, the atomic number is 11 and the relative atomic mass is 23.', 'mtab-box'),
    f('Rows', 'A row of the table is called a period.', 'row across → period', 'The rows go across the table, and there are seven of them. Each row is called a period. Sodium is in the third row, so it is in period 3.', 'mtab-periods'),
    f('Columns', 'A column of similar elements is called a group.', 'column down → group → similar elements', 'The columns go down the table. Elements in the same column have similar properties. A column like this is called a group. The groups are numbered 1 to 7, and the last column is Group 0. The elements in the wide middle block do not get a group number.', 'mtab-groups'),
    f('A repeating pattern', 'Similar properties come back again, row after row.', 'pattern repeats every row → periodic', 'Rows 2 to 6 each start with a very reactive metal in Group 1. Each of these rows ends with an unreactive gas in Group 0. So the same pattern repeats, row after row. A pattern that repeats like this is called periodic, which is how the periodic table got its name.', 'mtab-repeat'),
  ],
  'C8-05': [
    f('Group number', 'The group number is the number of electrons in the outer shell.', 'Group 1 → 1 outer electron', 'Lithium, sodium and potassium are all in Group 1. Lithium is 2,1, sodium is 2,8,1 and potassium is 2,8,8,1. Each one has a single electron in its outer shell. For Groups 1 to 7, the group number is the number of outer-shell electrons.', 'mtab-g1'),
    f('Across a period', 'One group to the right means one more outer electron.', 'Group 1 → Group 7: 1 → 7 outer electrons', 'Look along period 2, from lithium to fluorine. Each element has one more electron than the one before. So the outer shell gains one electron at each step. Carbon is in Group 4, and its outer shell holds 4 electrons.', 'mtab-period2'),
    f('Group 0', 'Group 0 elements have a full outer shell.', 'Group 0 → full outer shell (helium 2, the rest 8)', 'Group 0 does not follow the number rule. Its elements all have a full outer shell. Helium has only one shell, so its full outer shell holds 2 electrons. Neon, argon and the rest of Group 0 have 8 electrons in their outer shell.', 'mtab-g0'),
    f('Shells and periods', 'The period number is the number of shells.', 'one more period → one more shell', 'Lithium has electrons in 2 shells, and it is in period 2. Sodium has 3 shells and is in period 3. Potassium has 4 shells and is in period 4. So each new period starts a new shell of electrons.', 'mtab-shells'),
    f('Put it together', 'Where an element sits tells you about its electrons.', 'group → outer electrons; period → shells', 'Chlorine is in Group 7 and period 3. Group 7 means it has 7 electrons in its outer shell. Period 3 means its electrons are in 3 shells. So chlorine’s electronic structure is 2,8,7.', 'mtab-cl'),
  ],
  'C8-08': [
    f('Same outer shell', 'Elements in the same group react in similar ways.', 'same number of outer electrons → similar reactions', 'All the elements in a group have the same number of outer-shell electrons. How an atom reacts depends mostly on its outer shell. So elements in the same group react in similar ways. For example, every Group 1 element is a metal with one outer electron.', 'mtab-similar'),
    f('Predicting from one element', 'Knowing one element lets you predict the others in its group.', 'one element known → predict the rest of its group', 'Sodium reacts with cold water and makes hydrogen gas. Lithium and potassium are in the same group as sodium. So you can predict that they react with water too, and they do. You will learn more about Group 1 in the next lesson.', 'mtab-predict'),
    f('A trend', 'Some properties change steadily down a group.', 'down Group 1 → more violent reaction with water', 'Lithium fizzes steadily in water. Sodium reacts faster, and potassium reacts faster still. So the reaction gets more violent as you go down Group 1. A steady change like this is called a trend.', 'mtab-trend'),
    f('Put it together', 'A trend lets you predict an element you have not tested.', 'trend carries on → rubidium even more violent', 'Rubidium is below potassium in Group 1. It has one outer electron, so it should react with water like the others. The trend says it should react even more violently than potassium. Chemists use patterns like this to predict how elements behave.', 'mtab-next'),
  ],
  'C8-11': [
    f('Metals', 'Most elements are metals, on the left and towards the bottom.', 'left and bottom → metals', 'The shaded boxes are the metals. Most elements are metals. They are on the left of the table and towards the bottom. Sodium, iron and gold are all metals.', 'mtab-metals'),
    f('Non-metals', 'Non-metals are at the top right of the table.', 'top right → non-metals', 'The blue boxes are the non-metals. They are on the right of the table, towards the top. Oxygen, chlorine and neon are non-metals. Hydrogen, in its own box at the top, is a non-metal too. A zigzag staircase line separates the metals from the non-metals.', 'mtab-nonmetals'),
    f('Metals lose electrons', 'Metal atoms lose outer electrons to make positive ions.', 'few outer electrons → lose them → positive ion', 'Metal atoms have only a few electrons in their outer shell. When they react, they lose these electrons quite easily. This leaves a full outer shell underneath. The atom now has more protons than electrons, so it is a positive ion. You met ions when you learned about atoms.', 'mtab-lose'),
    f('Non-metals gain or share', 'Non-metal atoms gain or share electrons instead.', 'more outer electrons → gain or share', 'Most non-metal atoms have four or more electrons in their outer shell. It is easier for them to gain or share a few electrons than to lose many. Chlorine is 2,8,7, so it needs one more electron to fill its outer shell. Non-metals do not usually form positive ions.', 'mtab-gain'),
    f('Put it together', 'Where an element sits tells you how it reacts.', 'left: lose → positive ions; right: gain or share', 'Atoms react to get a full outer shell. Metals, on the left, lose electrons and form positive ions. Non-metals, on the right, gain or share electrons. You will see how ions and shared electrons hold atoms together in later lessons.', 'mtab-sides'),
  ],
  'C8-14': [
    f('Strong but bendable', 'Metals are strong but can be bent or hammered into shape.', 'hammer a metal → it changes shape, it does not break', 'Metals are strong, so they are hard to break. But you can bend them or hammer them into new shapes. A material that can be hammered into shape is called malleable. That is why metals can be pressed into cans and car bodies.', 'mtab-prop-strong'),
    f('Good conductors', 'Metals let heat and electricity pass through easily.', 'metal → heat and electricity pass through', 'Heat and electricity pass through metals easily. A material that lets them through is called a conductor. So metals are good conductors of heat and electricity. That is why wires are made of copper and pans are made of metal.', 'mtab-prop-conduct'),
    f('High melting points', 'Most metals have high melting and boiling points.', 'high melting point → solid at room temperature', 'Most metals only melt at high temperatures, and they boil at even higher ones. So most metals are solid at room temperature. Iron, for example, melts at about 1500 °C.', 'mtab-prop-melt'),
    f('Dull and brittle', 'Solid non-metals are often dull and break easily.', 'hit a solid non-metal → it shatters', 'Non-metals do not share the properties of metals. Solid non-metals tend to look dull, not shiny. If you try to bend them, they break. A material that breaks instead of bending is called brittle. Sulfur is a dull yellow solid that is brittle.', 'mtab-prop-brittle'),
    f('Other differences', 'Non-metals are not always solid and rarely conduct.', 'non-metals → often gases, poor conductors, low density', 'Non-metals are not always solid at room temperature. Oxygen is a gas and bromine is a liquid. Most non-metals do not conduct electricity. They also tend to have a lower density than metals.', 'mtab-prop-other'),
    f('Put it together', 'Metals and non-metals have opposite properties.', 'metal: strong, malleable, conducts; non-metal: brittle, dull, does not conduct', 'Metals are strong and malleable. They conduct heat and electricity, and they have high melting and boiling points. Non-metals are dull and brittle when solid, and many are gases. They do not usually conduct electricity. You will find out why metals behave like this in a later lesson.', 'mtab-prop-all'),
  ],
}
