import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { saltFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.4.2.2 Reactions of acids with metal oxides, hydroxides and carbonates (salt naming); 5.4.2.3 Soluble salts from an insoluble base and an acid (required practical: preparation of a pure, dry sample of a soluble salt), as on the supplied revision page' }
const skill = 'C-ACID-SALTS'
const naming = author(skill, ['5.4.2.2'], ['aqa-chemistry'])
const bases = author(skill, ['5.4.2.2'], ['aqa-chemistry'])
const carbonates = author(skill, ['5.4.2.2'], ['aqa-chemistry'])
const method = author(skill, ['5.4.2.3'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const saltSections = [
  { id: 'C23-01', label: 'Start here', detail: 'What an acid and a base make' },
  { id: 'C23-02', label: 'Which acid makes which salt?', detail: 'Chlorides, sulfates and nitrates' },
  { id: 'C23-05', label: 'What do oxides and hydroxides make?', detail: 'Salt and water' },
  { id: 'C23-08', label: 'What do carbonates make?', detail: 'Salt, water and carbon dioxide' },
  { id: 'C23-11', label: 'How do you make a pure, dry salt?', detail: 'The six-step method' },
  { id: 'C23-15', label: 'On your own', detail: 'New salts, the method and some data' },
]

const states: ScienceState[] = [
  { ...naming.choice('C23-01', 'A metal oxide is a base. When an acid reacts with a base, what is made?', ['A salt and hydrogen', 'A salt and water', 'Only water'], 1, 'Think about neutralisation. What are the two products?', ['An acid and a base neutralise each other to make a salt and water.', 'A metal oxide is a base, so it does the same.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(naming, 'C23-02', 'Which acid makes which salt?'),
  naming.choice('C23-03', 'Nitric acid reacts with sodium hydroxide. What is the salt called?', ['Sodium chloride', 'Sodium sulfate', 'Sodium nitrate', 'Nitric sodium'], 2, 'Which word comes from the base and which from the acid?', ['Sodium hydroxide gives the metal, sodium.', 'Nitric acid gives the family, nitrate. So the salt is sodium nitrate.']),
  naming.choice('C23-04', 'Which pair of reactants makes potassium sulfate?', ['Sulfuric acid and potassium hydroxide', 'Hydrochloric acid and potassium hydroxide', 'Sulfuric acid and sodium hydroxide', 'Nitric acid and potassium oxide'], 0, 'Which acid gives a sulfate? Which base gives potassium?', ['Sulfate comes from sulfuric acid.', 'Potassium comes from a potassium base, such as potassium hydroxide.']),
  t(bases, 'C23-05', 'What do oxides and hydroxides make?'),
  bases.choice('C23-06', 'Which word equation shows sulfuric acid reacting with copper oxide?', ['Sulfuric acid + copper oxide → copper sulfate + hydrogen', 'Sulfuric acid + copper oxide → copper chloride + water', 'Sulfuric acid + copper oxide → copper sulfate + carbon dioxide + water', 'Sulfuric acid + copper oxide → copper sulfate + water'], 3, 'Copper oxide is a base. How many products does an acid and a base make?', ['An acid and a metal oxide make a salt and water.', 'Copper comes from the oxide and sulfate from the acid, so the salt is copper sulfate.']),
  bases.choice('C23-07', 'In CuO + 2HCl → CuCl₂ + H₂O, why is there a 2 in front of HCl?', ['To show the acid is a solid', 'So each type of atom is the same on both sides', 'Because copper needs two oxygen atoms', 'Because acids always react in pairs'], 1, 'Count the chlorine atoms on the right-hand side.', ['CuCl₂ has 2 chlorine atoms, so 2 HCl are needed.', 'Two HCl also give 2 hydrogen atoms, which make the H₂O. Every atom now balances.'], 'understanding'),
  t(carbonates, 'C23-08', 'What do carbonates make?'),
  carbonates.choice('C23-09', 'Nitric acid reacts with calcium carbonate. Which products are made?', ['Calcium nitrate, water and carbon dioxide', 'Calcium nitrate and water only', 'Calcium chloride, water and carbon dioxide', 'Calcium nitrate and hydrogen'], 0, 'A carbonate makes one more product than an oxide does. Which?', ['Nitric acid makes a nitrate, and the metal is calcium: calcium nitrate.', 'A carbonate also makes water and carbon dioxide.']),
  carbonates.choice('C23-10', 'Acid is added to a metal carbonate and the mixture fizzes. What are the bubbles?', ['Water vapour', 'Hydrogen', 'Carbon dioxide', 'Oxygen'], 2, 'Which gas is the extra product when a carbonate reacts with an acid?', ['Carbonates react with acids to make a salt, water and carbon dioxide.', 'The fizzing is carbon dioxide gas escaping.']),
  t(method, 'C23-11', 'How do you make a pure, dry salt?'),
  method.choice('C23-12', 'Why is the insoluble base added until some solid stays at the bottom of the flask?', ['To make the solution hotter', 'To turn the acid into a solid', 'To make bigger crystals', 'To be sure all the acid has been used up'], 3, 'What does leftover solid tell you about the acid?', ['If solid is left over, the base is in excess.', 'That means there was enough base to react with all the acid, so no acid is left in the salt.']),
  method.choice('C23-13', 'What does the filter paper do in this method?', ['It dissolves the excess base', 'It holds back the leftover solid and lets the salt solution through', 'It turns the acid into a salt', 'It dries the crystals'], 1, 'Which is dissolved and which is a solid?', ['The salt is dissolved, so its solution runs through the paper.', 'The excess base is a solid, so it stays on the paper.']),
  method.choice('C23-14', 'Why is the salt solution heated gently until some water has gone, then left to cool?', ['It becomes more concentrated, so crystals form as it cools', 'The filter paper needs time to dry', 'The acid must boil away first', 'To change the salt into a base'], 0, 'What happens to the amount of water when you evaporate some?', ['Evaporating some water makes the solution more concentrated.', 'When it cools, crystals of the salt form.']),
  naming.choice('C23-15', 'Which pair of reactants could you use to make zinc chloride?', ['Sulfuric acid and zinc oxide', 'Hydrochloric acid and copper oxide', 'Nitric acid and zinc oxide', 'Hydrochloric acid and zinc oxide'], 3, 'Which acid gives a chloride? Which base gives zinc?', ['Chloride comes from hydrochloric acid.', 'Zinc comes from a zinc base, such as zinc oxide.'], 'application', true),
  method.choice('C23-16', 'A salt is made using this method. In which numbered stage is the leftover solid removed from the salt solution?', ['Stage 1', 'Stage 2', 'Stage 3', 'Stage 4'], 2, 'Which stage uses filter paper?', ['Stage 3 is the filter funnel. The filter paper holds back the excess solid.', 'The salt solution runs through into the flask below.'], 'application', true, 'salt-question-method'),
  method.choice('C23-17', 'A student adds copper oxide to warm sulfuric acid, as the table shows. Which conclusion do these data support?', ['Copper oxide is soluble in water', 'The acid had all reacted by the fourth portion', 'Exactly 3 g of copper oxide reacts with any amount of acid', 'The reaction made a gas'], 1, 'What does solid staying at the bottom mean?', ['Portions 1 to 3 disappeared, so they reacted. Solid stayed after portion 4, so the acid was used up by then.', 'The table does not show a gas, and one amount of acid cannot show a rule for any amount.'], 'dataInterpretation', true, 'salt-question-data'),
  carbonates.choice('C23-18', 'Magnesium carbonate reacts with sulfuric acid. Which products are made?', ['Magnesium sulfate, water and carbon dioxide', 'Magnesium sulfate and water only', 'Magnesium chloride, water and carbon dioxide', 'Magnesium sulfate and hydrogen'], 0, 'Which acid gives sulfate? What extra product does a carbonate make?', ['Sulfuric acid and a magnesium base make magnesium sulfate.', 'A carbonate also makes water and carbon dioxide.'], 'recall', true),
  method.written('C23-19', 'A student wants pure, dry crystals of magnesium chloride. Describe how to make them from an acid and an insoluble base.', 'Name the acid and the base first. Then give the steps in order: warm and react, filter, evaporate some water, cool, filter and dry.', 'Use hydrochloric acid, because it gives the chloride, and magnesium oxide, an insoluble base that contains magnesium. Warm the dilute acid, turn off the burner, and add magnesium oxide until some solid stays at the bottom. Filter out the excess solid. Heat the solution gently to evaporate some water, then leave it to cool so crystals form. Filter off the crystals and dry them.', ['Choose hydrochloric acid, because it contains chloride, the same negative ion as the salt.', 'Choose magnesium oxide (or hydroxide or carbonate), an insoluble base that contains magnesium.', 'Warm the dilute acid and add the base until no more reacts and some solid stays at the bottom.', 'Filter to remove the excess solid; the solution that passes through is magnesium chloride solution.', 'Heat the solution gently to evaporate some water, then leave it to cool so crystals form.', 'Filter off the crystals and dry them.'], ['Choosing an acid or base that would make a different salt, such as sulfuric acid.', 'Missing out the filtering of the excess solid, or filtering before all the acid has reacted.', 'Saying to heat until all the water has gone with no cooling or crystals.']),
]

export const lessonC23: ScienceLesson = {
  id: 'C-CHG-023-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Reactions of acids and making salts', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
