import type { TeachingFrame } from '../../teachingFrame'

// One idea per section, each built on the same pattern: the metal comes from the base, the family (chloride, sulfate,
// nitrate) comes from the acid. Names first, then oxides and hydroxides, then carbonates (one extra product), then the
// method for a pure, dry soluble salt, drawn once and lit up step by step.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const saltFrames: Record<string, TeachingFrame[]> = {
  'C23-02': [
    f('What is a salt?', 'A salt is an acid whose hydrogen has been replaced by a metal.', 'acid → swap H for a metal → salt', 'You know that an acid reacting with a base makes a salt and water. Every acid contains hydrogen. In a salt, a metal has taken the place of that hydrogen. Hydrochloric acid is HCl. Swap the H for sodium, Na, and you get the salt sodium chloride, NaCl.', 'salt-name-what'),
    f('The acid gives the second word', 'Hydrochloric acid makes chlorides, sulfuric acid makes sulfates, nitric acid makes nitrates.', 'hydrochloric → chloride · sulfuric → sulfate · nitric → nitrate', 'The second word in a salt’s name comes from the acid. Hydrochloric acid makes salts called chlorides. Sulfuric acid makes sulfates. Nitric acid makes nitrates.', 'salt-name-acid'),
    f('The base gives the first word', 'The metal in the base is the first word of the salt’s name.', 'sodium hydroxide → a sodium salt', 'The first word in a salt’s name is the metal from the base. Sodium hydroxide gives a sodium salt. Copper oxide gives a copper salt. Potassium hydroxide gives a potassium salt.', 'salt-name-metal'),
    f('Put it together', 'Metal from the base, then the family of the acid.', 'base metal + acid family = salt name', 'Sulfuric acid reacts with sodium hydroxide. The metal is sodium and the acid family is sulfate. So the salt is sodium sulfate. Water is made as well.', 'salt-name-join'),
  ],
  'C23-05': [
    f('Two kinds of base', 'Metal oxides and metal hydroxides are both bases.', 'oxide or hydroxide → a base', 'Metal oxides, such as copper oxide, are bases. Metal hydroxides, such as sodium hydroxide, are bases too. Every base neutralises an acid. So each of these reacts with an acid to make a salt and water.', 'salt-base-types'),
    f('Acid + metal oxide', 'Acid + metal oxide → salt + water.', 'hydrochloric acid + copper oxide → copper chloride + water', 'Hydrochloric acid reacts with copper oxide. The products are copper chloride and water. The copper comes from the oxide and the chloride comes from the acid. The oxygen from the oxide ends up in the water.', 'salt-eq-oxide'),
    f('Acid + metal hydroxide', 'Acid + metal hydroxide → salt + water.', 'sulfuric acid + potassium hydroxide → potassium sulfate + water', 'Sulfuric acid reacts with potassium hydroxide. The products are potassium sulfate and water. The pattern is the same, because a hydroxide is a base too. Each name has its formula underneath.', 'salt-eq-hydroxide'),
    f('A balanced equation', 'Numbers in front of formulas make both sides match.', 'CuO + 2HCl → CuCl₂ + H₂O, atoms match', 'The symbol equation for copper oxide and hydrochloric acid is CuO + 2HCl → CuCl₂ + H₂O. The 2 in front of HCl makes the equation balanced. Count the atoms: there is 1 Cu, 1 O, 2 H and 2 Cl on each side. The letters in brackets are state symbols: s is solid, aq is dissolved in water, l is liquid.', 'salt-eq-count'),
  ],
  'C23-08': [
    f('A third product', 'Acid + metal carbonate → salt + water + carbon dioxide.', 'carbonate → salt + water + a gas', 'Metal carbonates are bases too. They react with acids to make a salt and water, as before. This time a gas is made as well, carbon dioxide. So there are three products, not two.', 'salt-carb-word'),
    f('Fizzing', 'Bubbles of carbon dioxide show that a carbonate is reacting.', 'fizzing → gas → carbon dioxide', 'When you add acid to a metal carbonate, the mixture fizzes. The bubbles are carbon dioxide gas escaping. The fizzing stops when the carbonate or the acid has run out. So fizzing is a sign that a carbonate is reacting.', 'salt-carb-fizz'),
    f('Another example', 'The same pattern works for any acid and any metal carbonate.', 'metal from the carbonate, family from the acid', 'Sulfuric acid reacts with calcium carbonate. The salt is calcium sulfate: calcium from the carbonate and sulfate from the acid. Water and carbon dioxide are made too. The symbol equation is H₂SO₄ + CaCO₃ → CaSO₄ + H₂O + CO₂.', 'salt-carb-symbols'),
  ],
  'C23-11': [
    f('Soluble and insoluble', 'A soluble solid dissolves in water. An insoluble solid does not.', 'dissolves → soluble · stays solid → insoluble', 'Copper sulfate is a soluble salt. It dissolves in water to make a blue solution. Copper oxide is insoluble in water. The black powder sinks and stays as a solid. This difference lets you make a pure salt.', 'salt-solubility'),
    f('Choose the reactants', 'Pick the acid with the right negative ion and an insoluble base with the right metal.', 'same negative ion → acid · same metal → base', 'To make copper sulfate, pick sulfuric acid, because it gives the sulfate. Then pick an insoluble base that contains copper. Copper oxide, copper hydroxide or copper carbonate will all work. You can also use some metals instead of a base.', 'salt-plan'),
    f('React, then add extra', 'Warm the acid, then add base until no more reacts.', 'step 1 warm · step 2 add base until some is left over', 'Step 1: warm the dilute acid in a flask, then turn off the Bunsen burner. Step 2: add the insoluble base a little at a time. Stop when some solid stays at the bottom. That leftover is the excess, so all the acid has been used up.', 'salt-m-react'),
    f('Filter out the extra', 'Filtering removes the excess solid and lets the salt solution through.', 'step 3 filter → excess stays on the paper', 'Step 3: filter the mixture. The filter paper holds back the excess solid. The salt is dissolved, so its solution runs through the paper. What is left in the flask is a solution of the salt.', 'salt-m-filter'),
    f('Crystallise', 'Evaporate some water, cool, then filter and dry the crystals.', 'steps 4, 5, 6 → solution → crystals → dry', 'Step 4: heat the solution gently, using a water bath or an electric heater. Some of the water evaporates. Step 5: stop heating and leave the solution to cool, and crystals form. Step 6: filter the crystals out and dry them. Turning a solution into crystals is called crystallisation.', 'salt-m-crystal'),
    f('Put it together', 'React, filter, crystallise: six steps give pure, dry crystals.', 'make the solution → remove the excess → crystallise', 'Steps 1 and 2 make the salt solution. Step 3 removes the excess base. Steps 4 to 6 turn the solution into pure, dry crystals. In the lab, wear eye protection and follow your teacher’s instructions.', 'salt-m-all'),
  ],
}
