/* Each lesson's teaching walkthroughs, keyed by the teaching screen they belong to. */
import type { LessonNumber } from './lessonNavigation'
import type { TeachingFrame } from './teachingFrame'
import { teachingFrames as cellsFrames } from './lesson-1/teachingFrames'
import { microscopyFrames } from './lesson-2/teachingFrames'
import { practicalFrames } from './lesson-3/teachingFrames'
import { specialisationFrames } from './lesson-4/teachingFrames'
import { divisionFrames } from './lesson-5/teachingFrames'
import { transportFrames } from './lesson-6/teachingFrames'
import { enzymeFrames } from './lesson-8/teachingFrames'
import { digestionFrames } from './lesson-9/teachingFrames'
import { organisationFrames } from './lesson-7/teachingFrames'
import { lungsFrames } from './lesson-10/teachingFrames'
import { heartFrames } from './lesson-11/teachingFrames'
import { vesselsFrames } from './lesson-12/teachingFrames'
import { bloodFrames } from './lesson-13/teachingFrames'
import { cardiovascularFrames } from './lesson-14/teachingFrames'
import { healthFrames } from './lesson-15/teachingFrames'
import { riskCancerFrames } from './lesson-16/teachingFrames'
import { plantTissueFrames } from './lesson-17/teachingFrames'
import { plantTransportFrames } from './lesson-18/teachingFrames'
import { pathogenFrames } from './lesson-19/teachingFrames'
import { humanDiseaseFrames } from './lesson-20/teachingFrames'
import { plantMalariaFrames } from './lesson-21/teachingFrames'
import { defenceFrames } from './lesson-22/teachingFrames'
import { vaccinationFrames } from './lesson-23/teachingFrames'
import { medicineFrames } from './lesson-24/teachingFrames'
import { drugTestingFrames } from './lesson-25/teachingFrames'
import { photosynthesisFrames } from './lesson-26/teachingFrames'

export const lessonFrames: Record<LessonNumber, Record<string, TeachingFrame[]>> = { 1: cellsFrames, 2: microscopyFrames, 3: practicalFrames, 4: specialisationFrames, 5: divisionFrames, 6: transportFrames, 7: organisationFrames, 8: enzymeFrames, 9: digestionFrames, 10: lungsFrames, 11: heartFrames, 12: vesselsFrames, 13: bloodFrames, 14: cardiovascularFrames, 15: healthFrames, 16: riskCancerFrames, 17: plantTissueFrames, 18: plantTransportFrames, 19: pathogenFrames, 20: humanDiseaseFrames, 21: plantMalariaFrames, 22: defenceFrames, 23: vaccinationFrames, 24: medicineFrames, 25: drugTestingFrames, 26: photosynthesisFrames }
