import type { TeachingFrame } from '../../teachingFrame'

// Solids first (filtration, then getting a dissolved salt back), then both together on rock salt,
// then liquids (simple distillation, then fractional distillation), each built on one drawing that changes frame by frame.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const separationFrames: Record<string, TeachingFrame[]> = {
  'C4-02': [
    f('Dissolving', 'Some solids dissolve in water.', 'dissolves → soluble', 'You met solutions when you learned about mixtures. Stir sugar into water and the grains seem to vanish. The sugar has broken up into particles too small to see, spread all through the water. A solid that dissolves in a liquid is called soluble.', 'sep-filter-soluble'),
    f('Not dissolving', 'Some solids do not dissolve.', 'does not dissolve → insoluble', 'Stir sand into water and the grains are still there. They make the water cloudy, then sink to the bottom. A solid that does not dissolve in a liquid is called insoluble. Sand, chalk and most rocks are insoluble in water.', 'sep-filter-insoluble'),
    f('Paper and funnel', 'A paper cone in a funnel works like a very fine sieve.', 'filter paper cone → funnel → beaker', 'Fold a circle of filter paper into a cone and sit it in a funnel. Stand the funnel in a beaker. The paper is full of tiny holes, far too small to see. Separating an insoluble solid from a liquid like this is called filtration.', 'sep-filter-setup'),
    f('The filtrate', 'The liquid passes through the paper.', 'liquid through the holes → filtrate', 'Pour the sandy water slowly into the paper cone. Keep the level below the top of the paper, or the mixture runs down the sides. The water is small enough to pass through the holes. The clear liquid that drips into the beaker is called the filtrate.', 'sep-filter-filtrate'),
    f('The residue', 'The solid is left on the paper.', 'solid left on the paper → residue', 'The sand grains are much bigger than the holes in the paper. So they cannot get through, and they collect on the filter paper. The solid left behind on the paper is called the residue.', 'sep-filter-residue'),
    f('Put it together', 'Filtration splits an insoluble solid from a liquid.', 'mixture → filtrate (liquid) + residue (solid)', 'Filtration works because the solid does not dissolve, so its grains are too big for the holes. The liquid passes through and becomes the filtrate. The solid stays on the paper as the residue. Filtration cannot remove a dissolved solid, because its particles pass through with the liquid.', 'sep-filter-all'),
  ],
  'C4-05': [
    f('The solvent', 'A salt solution is salt dissolved in a liquid.', 'liquid the salt dissolves in → solvent', 'Filtration cannot get a dissolved salt back, because the salt passes through the paper. Salt water is a solution of salt dissolved in water. The liquid that a solid dissolves in is called the solvent. To get the salt back, you remove the solvent.', 'sep-salt-solvent'),
    f('Evaporation', 'Heat the solution until only dry crystals are left.', 'heat → water evaporates → dry crystals', 'Pour the solution into an evaporating dish on a tripod and gauze. Heat it gently with a Bunsen burner. The water turns into a gas and escapes into the air, and crystals of salt form. Keep heating gently until only dry crystals are left. This is called evaporation.', 'sep-salt-evaporate'),
    f('Quick, but not for every salt', 'Some salts break down when they get too hot.', 'salt breaks down when hot → use a gentler method', 'Evaporation is quick. But some salts break down into other substances if they get too hot. Heating these salts until dry would spoil them, so you use a gentler method instead. The dish, tripod and gauze stay hot for a long time, so let them cool before touching them.', 'sep-salt-warning'),
    f('Crystallisation', 'Heat gently, then let crystals grow as it cools.', 'heat gently → stop when crystals start → cool', 'Heat the solution gently in an evaporating dish. Stop heating when some of the water has gone, or when crystals start to form at the edge. Leave the dish to cool, and more crystals grow in the solution. This is called crystallisation.', 'sep-salt-crystallise'),
    f('Filter and dry', 'Filter the crystals out, then dry them.', 'filter → crystals on the paper → dry in a warm place', 'Some water is still left around the crystals. So filter the mixture, and the crystals stay on the filter paper. Then leave them somewhere warm to dry. Crystallisation also gives bigger, better-shaped crystals than evaporation.', 'sep-salt-dry'),
    f('Put it together', 'Two ways to get a soluble salt back.', 'evaporation = quick; crystallisation = gentle, for salts that break down', 'Both methods remove the solvent and leave crystals of the salt. Evaporation heats until dry, so it is quick. Crystallisation stops early, then the crystals are cooled, filtered and dried. Use crystallisation when the salt breaks down on heating. Wear eye protection, because hot solution can spit.', 'sep-salt-all'),
  ],
  'C4-08': [
    f('Rock salt', 'Rock salt is a mixture of salt and sand.', 'salt dissolves; sand does not', 'Rock salt is dug out of the ground and spread on icy roads in winter. It is a mixture of salt and sand. Salt is soluble in water, but sand is insoluble. You can use this difference to separate them.', 'sep-rock-mix'),
    f('Grind and dissolve', 'Crush the lumps, then stir them into water.', 'grind → add water → stir', 'First, grind the rock salt with a pestle and mortar. Small pieces dissolve much faster than big lumps. Then stir it into water, and warm it a little to help the salt dissolve. The salt dissolves, but the sand does not.', 'sep-rock-dissolve'),
    f('Filter off the sand', 'The sand is the residue; the salt water is the filtrate.', 'sand → residue; salt solution → filtrate', 'Next, filter the mixture. The sand grains are too big for the holes, so they are left on the paper as the residue. The salt is dissolved, so it passes through with the water. The filtrate is a salt solution.', 'sep-rock-filter'),
    f('Get the salt back', 'Evaporate or crystallise the filtrate.', 'salt solution → evaporation or crystallisation → dry salt', 'Last, pour the filtrate into an evaporating dish. Use evaporation or crystallisation to remove the water. Dry crystals of salt are left behind. The sand is on the filter paper, so the two parts of the mixture are now apart.', 'sep-rock-dry'),
    f('Put it together', 'Grind, dissolve, filter, evaporate.', 'grind → dissolve → filter → evaporate', 'Each step uses a difference between salt and sand: one dissolves, the other does not. No new substances are made, so this is a physical way of separating a mixture. The salt you end up with is much purer than the rock salt you started with.', 'sep-rock-all'),
  ],
  'C4-11': [
    f('Keeping the liquid', 'Distillation collects the liquid instead of losing it.', 'boil → gas → cool → liquid', 'Evaporation lets the water escape into the air. But sometimes the liquid is the part you want, like pure water from sea water. You can boil the liquid, then cool the gas so it turns back into a liquid. This is called distillation.', 'sep-dist-heat'),
    f('Boiling off the water', 'The part with the lowest boiling point turns into a gas first.', 'lowest boiling point → evaporates first', 'Heat sea water in a flask. Water boils at 100 °C, but salt needs a far higher temperature. So only the water turns into a gas and rises up the flask. The thermometer bulb sits level with the side arm, so it reads the temperature of the gas.', 'sep-dist-boil'),
    f('The condenser', 'A cold tube turns the gas back into a liquid.', 'gas cools → condenses → liquid', 'The gas passes along a tube surrounded by a jacket of cold water. It cools and turns back into a liquid: it condenses. This cold tube is called a condenser. Cold water goes in at the bottom and out at the top, so the jacket stays full.', 'sep-dist-condense'),
    f('Collecting the water', 'Pure water drips out; the salt stays in the flask.', 'liquid drips out → collected; salt left behind', 'The liquid runs down the condenser and drips into a beaker. It is pure water, with no salt in it. The salt is left behind in the flask. The whole method is called simple distillation.', 'sep-dist-collect'),
    f('Put it together', 'Heat, boil, condense, collect.', 'heat → gas → condenser → pure liquid', 'Simple distillation separates a liquid from a solution. The liquid boils, travels into the condenser as a gas, and is cooled back into a liquid. It works because water and salt have very different boiling points. It cannot separate liquids with similar boiling points, because both boil off together.', 'sep-dist-all'),
  ],
  'C4-14': [
    f('A mixture of liquids', 'Two liquids that mix completely can still be separated.', 'mixture of liquids → fractionating column', 'Propanone is a liquid used in some nail-varnish removers. It mixes completely with water. Propanone boils at 56 °C and water boils at 100 °C. To separate them, you fit a tall glass tube packed with glass beads on top of the flask. This is called a fractionating column.', 'sep-frac-column'),
    f('Lowest boiling point first', 'The liquid with the lowest boiling point reaches the top first.', 'lowest boiling point → evaporates first → top of the column', 'Heat the flask gently. Propanone has the lower boiling point, so it evaporates first. The column is hottest at the bottom and cooler at the top. When the thermometer at the top reads 56 °C, propanone gas is passing into the condenser.', 'sep-frac-first'),
    f('Fractions', 'Each liquid is collected on its own.', 'one liquid at a time → a fraction', 'The propanone gas condenses and drips into a flask. When it stops dripping, you swap to a new flask. Each liquid collected separately like this is called a fraction.', 'sep-frac-fraction'),
    f('Raising the temperature', 'Heat more strongly to collect the next liquid.', 'raise the temperature → next boiling point → next fraction', 'Now heat the flask more strongly. The temperature at the top rises until it reaches 100 °C. Then water gas reaches the top, condenses, and is collected as the second fraction. With more liquids, you keep raising the temperature, one boiling point at a time.', 'sep-frac-next'),
    f('Put it together', 'Fractional distillation separates liquids by their boiling points.', 'lowest boiling point first, then raise the temperature', 'This method is called fractional distillation. It separates a mixture of liquids with different boiling points. The liquid with the lowest boiling point is collected first. The column lets it work even when the boiling points are fairly close. The same idea is used to separate crude oil.', 'sep-frac-all'),
  ],
}
