import type { TeachingFrame } from '../../teachingFrame'

// Build one bond first (two chlorine atoms share a pair), then use the same idea to count bonds for each atom,
// then extend it to double and triple bonds, then compare ways of drawing a molecule, and only then zoom out to a
// whole substance made of molecules (why it boils easily and does not conduct).
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const covalentFrames: Record<string, TeachingFrame[]> = {
  'C14-02': [
    f('Two atoms that both need one', 'Two chlorine atoms each have 7 outer electrons and each need 1 more.', 'both non-metals → both need to gain', 'When you learned about ionic bonding, a chlorine atom took an electron from a metal atom. But what if two chlorine atoms meet? Each has 7 outer electrons and needs 1 more to fill its outer shell. Neither atom gives an electron away. We draw only the outer shells, with dots for one atom’s electrons and crosses for the other’s.', 'cov-share-need'),
    f('Sharing a pair', 'Each atom puts one electron into the place where the two outer shells overlap.', 'one electron from each atom → two electrons shared', 'Instead, the two atoms move so close that their outer shells overlap. Each atom puts one of its electrons into the overlap. Both atoms now share these two electrons. Two electrons shared by two atoms like this are called a shared pair.', 'cov-share-overlap'),
    f('Both atoms count the pair', 'Each atom counts both shared electrons in its own outer shell.', '6 not shared + 2 shared = 8 each', 'Each atom counts the shared pair as part of its own outer shell. So each chlorine atom has 6 electrons that are not shared, plus the 2 in the shared pair. That makes 8 each. Both outer shells are now full, so the atoms are stable.', 'cov-share-count'),
    f('A covalent bond', 'The shared pair holds the two atoms together strongly.', 'shared pair → covalent bond → strong', 'The nucleus of each atom pulls on the shared pair. So the shared pair holds the two atoms together. A pair of electrons shared between two atoms is called a covalent bond. Covalent bonds are very strong. They form when non-metal atoms bond together.', 'cov-share-bond'),
    f('Put it together: a molecule', 'Atoms joined by covalent bonds make a molecule.', 'share → count 8 → bond → molecule', 'You met molecules when you learned about formulas: atoms joined together in a small group. Here, two chlorine atoms are joined by one covalent bond. This is a chlorine molecule, Cl₂. Chlorine gas is made of these molecules.', 'cov-share-molecule'),
  ],
  'C14-05': [
    f('Hydrogen', 'Two hydrogen atoms share one pair to make a hydrogen molecule.', 'H has 1, full shell holds 2 → 1 bond', 'A hydrogen atom has only 1 electron, in its only shell. That shell is full with just 2 electrons. So two hydrogen atoms share one pair, just like chlorine. Each atom now counts 2 electrons, a full shell. This is a hydrogen molecule, H₂.', 'cov-count-h2'),
    f('One bond, one extra electron', 'Each covalent bond gives an atom one extra electron to count.', 'electrons needed = bonds made', 'In hydrogen chloride, HCl, a hydrogen atom and a chlorine atom share one pair. Each covalent bond gives an atom one extra electron to count. So an atom usually makes as many bonds as the electrons it needs. Hydrogen and chlorine each need 1, so each makes 1 bond.', 'cov-count-hcl'),
    f('Water', 'Oxygen needs 2 more electrons, so it makes 2 bonds.', 'O has 6 → needs 2 → 2 bonds', 'An oxygen atom has 6 outer electrons, so it needs 2 more. It makes 2 covalent bonds, one with each of two hydrogen atoms. This is a water molecule, H₂O. Now the oxygen atom counts 8 outer electrons and each hydrogen atom counts 2.', 'cov-count-water'),
    f('Ammonia', 'Nitrogen needs 3 more electrons, so it makes 3 bonds.', 'N has 5 → needs 3 → 3 bonds', 'A nitrogen atom has 5 outer electrons, so it needs 3 more. It makes 3 covalent bonds with three hydrogen atoms. This is an ammonia molecule, NH₃. Count nitrogen’s outer shell: 2 electrons not shared plus 3 shared pairs makes 8.', 'cov-count-ammonia'),
    f('Put it together: methane', 'Carbon needs 4 more electrons, so it makes 4 bonds.', 'C has 4 → needs 4 → 4 bonds', 'A carbon atom has 4 outer electrons, so it needs 4 more. It makes 4 covalent bonds with four hydrogen atoms. This is a methane molecule, CH₄, the main gas in natural gas. For every atom in the table, bonds made = electrons needed.', 'cov-count-methane'),
  ],
  'C14-08': [
    f('Oxygen shares two pairs', 'Each oxygen atom needs 2 more electrons, so two oxygen atoms share two pairs.', 'needs 2 → share 2 pairs → double bond', 'Oxygen gas is made of O₂ molecules. Each oxygen atom has 6 outer electrons and needs 2 more. So each atom puts 2 electrons into the overlap, and the atoms share two pairs. Two shared pairs between the same two atoms are called a double bond.', 'cov-multi-oxygen'),
    f('Nitrogen shares three pairs', 'Each nitrogen atom needs 3 more electrons, so two nitrogen atoms share three pairs.', 'needs 3 → share 3 pairs → triple bond', 'Nitrogen gas is made of N₂ molecules. Each nitrogen atom has 5 outer electrons and needs 3 more. So the two atoms share three pairs. This is called a triple bond. Each atom counts 2 electrons not shared plus 6 shared, which makes 8.', 'cov-multi-nitrogen'),
    f('Put it together', 'Two atoms share as many pairs as each atom needs electrons.', '1 pair single, 2 pairs double, 3 pairs triple', 'Hydrogen atoms each need 1 electron, so H₂ has one shared pair, a single bond. Oxygen atoms need 2, so O₂ has a double bond. Nitrogen atoms need 3, so N₂ has a triple bond. In every case, each atom ends up with a full outer shell.', 'cov-multi-all'),
  ],
  'C14-10': [
    f('Dot-and-cross diagram', 'Dots and crosses show which atom each electron came from.', 'dots and crosses → where the electrons came from', 'The drawings so far are called dot-and-cross diagrams. Here is ammonia drawn this way. The shared pairs sit where the shells overlap. Dots and crosses show which atom each bonding electron came from. But the drawing does not show the real shape of the molecule or the sizes of the atoms.', 'cov-draw-dotcross'),
    f('Displayed formula', 'Each covalent bond is drawn as a line between two symbols.', 'one line = one covalent bond', 'A quicker drawing shows each atom as its symbol and each covalent bond as a line. This is called a displayed formula. A double bond is two lines, like O=O. It clearly shows which atoms are joined, even in big molecules. But it does not show the shape, or where the electrons came from.', 'cov-draw-displayed'),
    f('3D model', 'A model shows how the atoms are arranged in space.', 'balls and sticks → shape in space', 'A 3D model shows atoms as balls and covalent bonds as sticks. It shows how the atoms are arranged in space. Ammonia is shaped like a low pyramid, with nitrogen at the top. But models of big molecules can be confusing. They do not show where the electrons in each bond came from.', 'cov-draw-model'),
    f('Choosing a drawing', 'Each drawing shows some things and hides others.', 'electrons → dot-and-cross; joins → displayed; shape → 3D', 'No drawing shows everything. Use a dot-and-cross diagram to show where the bonding electrons came from. Use a displayed formula to show which atoms are joined. Use a 3D model to show the shape.', 'cov-draw-compare'),
    f('Molecular formula', 'Count the atoms of each element in one molecule to write its formula.', 'count each kind of atom → formula', 'You can find a molecule’s formula from any of these drawings. Count the atoms of each element. This hydrogen peroxide molecule has 2 hydrogen atoms and 2 oxygen atoms, so its formula is H₂O₂. A formula showing the number of atoms of each element in one molecule is called a molecular formula.', 'cov-draw-formula'),
  ],
  'C14-13': [
    f('A substance made of molecules', 'Liquid bromine is made of a huge number of separate Br₂ molecules.', 'many small molecules → simple molecular substance', 'Bromine is a liquid at room temperature. A bottle of it holds a huge number of Br₂ molecules. Each molecule is just two atoms joined by a covalent bond. Water, ammonia and methane are also made of small molecules. A substance made of small molecules is called a simple molecular substance.', 'cov-prop-molecules'),
    f('Weak forces between molecules', 'The forces between molecules are much weaker than the covalent bonds inside them.', 'strong inside, weak between', 'Inside each molecule, the covalent bond is very strong. There are also forces pulling the molecules towards each other. These forces are very weak. Forces between molecules are called intermolecular forces.', 'cov-prop-forces'),
    f('Boiling', 'When bromine boils, the molecules move apart but each one stays whole.', 'boil → overcome weak forces only → low boiling point', 'To boil bromine, you only need to overcome the weak intermolecular forces. The covalent bonds do not break, so each Br₂ molecule stays whole. This takes little energy, so bromine boils at only 59 °C. Simple molecular substances have low melting and boiling points. Most are gases or liquids at room temperature.', 'cov-prop-boil'),
    f('Bigger molecules', 'Bigger molecules have stronger intermolecular forces, so they boil at higher temperatures.', 'bigger molecule → stronger forces → higher boiling point', 'You met chlorine, bromine and iodine in Group 7. All three are made of molecules with two atoms, but the molecules get bigger from chlorine to iodine. Bigger molecules have stronger intermolecular forces. More energy is needed to overcome them, so the boiling point is higher. At room temperature chlorine is a gas, bromine a liquid and iodine a solid.', 'cov-prop-size'),
    f('No charge, no current', 'Simple molecular substances do not conduct electricity.', 'no overall charge → nothing to carry a current', 'To conduct electricity, a substance needs charged particles that can move. Molecules have no overall electric charge. So simple molecular substances do not conduct electricity, even as liquids. Ionic compounds are different: they conduct when melted or dissolved, because their ions can move.', 'cov-prop-conduct'),
  ],
}
