import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { alkaliFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.1.2.5 Group 1' }
const skill = 'C-GROUP1'
const meet = author(skill, ['5.1.2.5'], ['aqa-chemistry'])
const trends = author(skill, ['5.1.2.5'], ['aqa-chemistry'])
const water = author(skill, ['5.1.2.5'], ['aqa-chemistry'])
const others = author(skill, ['5.1.2.5'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const alkaliSections = [
  { id: 'C9-01', label: 'Start here', detail: 'Sodium’s outer shell' },
  { id: 'C9-02', label: 'What are the alkali metals?', detail: 'Group 1, one outer electron, soft and light' },
  { id: 'C9-05', label: 'What changes down the group?', detail: '1+ ions, reactivity and melting points' },
  { id: 'C9-08', label: 'What happens in water?', detail: 'Hydroxides, hydrogen and a lilac flame' },
  { id: 'C9-11', label: 'What about chlorine and oxygen?', detail: 'White salts and tarnishing' },
  { id: 'C9-14', label: 'On your own', detail: 'Potassium, rubidium and a new equation' },
]

const states: ScienceState[] = [
  { ...meet.choice('C9-01', 'Sodium’s electronic structure is 2,8,1. How many electrons are in its outer shell?', ['8', '1', '11'], 1, 'Which number stands for the outer shell?', ['The numbers go from the inner shell outwards, so the last number is the outer shell.', 'Sodium has 1 electron in its outer shell (11 electrons in all).']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(meet, 'C9-02', 'What are the alkali metals?'),
  meet.choice('C9-03', 'Lithium, sodium and potassium react in similar ways. Why?', ['They all have the same number of shells', 'They all float on water', 'They all have one electron in their outer shell', 'They all have the same relative atomic mass'], 2, 'Look at the last number in 2,1, 2,8,1 and 2,8,8,1.', ['Lithium is 2,1, sodium 2,8,1 and potassium 2,8,8,1.', 'Each has one electron in its outer shell, and elements with the same number of outer electrons react in similar ways.']),
  meet.choice('C9-04', 'A lump of sodium is cut easily with a knife, and a small piece floats on water. What do these show?', ['It is soft and has a low density', 'It is hard and has a high density', 'It is soft and has a high density', 'It is hard and has a low density'], 0, 'What does floating on water tell you about density?', ['Being easy to cut shows sodium is soft.', 'Floating shows it is less dense than water, so it has a low density.']),
  t(trends, 'C9-05', 'What changes down the group?'),
  trends.choice('C9-06', 'Why is potassium more reactive than sodium?', ['Potassium has more electrons in its outer shell', 'Potassium’s outer electron is closer to the nucleus', 'Potassium has a higher melting point', 'Potassium’s outer electron is further from the nucleus, so it is lost more easily'], 3, 'Potassium has one more shell than sodium. Where does that put its outer electron?', ['Both have one outer electron, but potassium has one more shell, so its outer electron is further from the nucleus.', 'It is less strongly attracted, so it is lost more easily. That makes potassium more reactive.']),
  trends.choice('C9-07', 'Melting points: lithium 181 °C, sodium 98 °C, potassium 63 °C. What is the best prediction for rubidium, just below potassium?', ['Higher than 181 °C', 'Between 98 °C and 181 °C', 'Between 63 °C and 98 °C', 'Lower than 63 °C'], 3, 'Which way do the melting points go as you move down?', ['The melting points get lower going down Group 1.', 'Rubidium is below potassium, so its melting point should be lower than 63 °C. It is 39 °C.'], 'dataInterpretation'),
  t(water, 'C9-08', 'What happens in water?'),
  water.choice('C9-09', 'Lithium reacts with water. What are the products?', ['Lithium oxide and water', 'Lithium hydroxide and hydrogen', 'Lithium chloride and hydrogen', 'Lithium hydroxide and oxygen'], 1, 'Alkali metal + water → metal hydroxide + ?', ['An alkali metal and water make a metal hydroxide and hydrogen.', 'So lithium makes lithium hydroxide and hydrogen.']),
  water.choice('C9-10', 'Potassium’s reaction with water makes a flame, but lithium’s does not. Why?', ['Potassium reacts more vigorously, giving out enough energy to set the hydrogen alight', 'Potassium makes oxygen instead of hydrogen', 'Lithium does not react with water', 'Potassium sinks, so it reacts faster'], 0, 'Which is further down the group, and what does that do to the reaction?', ['Potassium is further down Group 1, so it reacts more vigorously than lithium.', 'Its reaction gives out enough energy to set the hydrogen alight, which burns with a lilac flame.']),
  t(others, 'C9-11', 'What about chlorine and oxygen?'),
  others.choice('C9-12', 'Hot potassium is lowered into chlorine gas. What forms?', ['A green gas, potassium oxide', 'Hydrogen gas', 'A white solid, potassium chloride', 'A grey metal, potassium hydroxide'], 2, 'Alkali metal + chlorine → ?', ['An alkali metal and chlorine make a metal chloride.', 'Metal chlorides are white solids (salts), so potassium chloride forms as a white solid.']),
  others.choice('C9-13', 'A freshly cut piece of sodium is shiny, but it soon goes dull. Why?', ['It dries out in the air', 'It reacts with oxygen in the air to form sodium oxide', 'It reacts with chlorine in the air', 'It melts at room temperature'], 1, 'Which gas in the air do alkali metals react with?', ['Alkali metals react with oxygen in the air.', 'A thin, dull layer of sodium oxide forms on the surface. This is tarnishing.']),
  others.choice('C9-14', 'Potassium is added to water. The gas made catches fire at label 2. Which gas is it?', ['Oxygen', 'Hydrogen', 'Chlorine', 'Carbon dioxide'], 1, 'What gas do alkali metals make with water?', ['Alkali metal + water → metal hydroxide + hydrogen.', 'Potassium gives out enough energy to set the hydrogen alight, so the burning gas is hydrogen.'], 'application', true, 'alk-q-water'),
  water.choice('C9-15', 'The table shows example results for same-sized pieces added to water. Which conclusion do these results support?', ['Every element gets more reactive going down any group', 'Sodium is the most reactive of the three', 'For these three metals, reactivity increases going down Group 1', 'Rubidium would take exactly 1 second'], 2, 'A shorter time means a faster reaction. What do these three results show, and no more?', ['The times get shorter from lithium (40 s) to sodium (11 s) to potassium (3 s), so the reaction gets faster down the group.', 'The data only covers these three metals in water. It says nothing exact about rubidium or about other groups.'], 'dataInterpretation', true, 'alk-q-data'),
  trends.choice('C9-16', 'Rubidium is below potassium in Group 1. What would you expect when a tiny piece is added to water?', ['A more vigorous reaction than potassium, making rubidium hydroxide and hydrogen', 'No reaction, because rubidium atoms are too heavy', 'A slower reaction than lithium, making rubidium oxide', 'It sinks and makes chlorine gas'], 0, 'Use the trend in reactivity and the general word equation.', ['Reactivity increases going down Group 1, so rubidium reacts more vigorously than potassium.', 'Like the others, it makes a metal hydroxide and hydrogen: rubidium hydroxide and hydrogen.'], 'application', true),
  others.choice('C9-17', 'Which is the balanced symbol equation for lithium reacting with chlorine?', ['Li + Cl₂ → LiCl', '2Li + Cl → 2LiCl', '2Li + 2Cl₂ → 2LiCl', '2Li + Cl₂ → 2LiCl'], 3, 'Chlorine gas is Cl₂. Count each kind of atom on both sides.', ['Chlorine gas is Cl₂, and the product is lithium chloride, LiCl.', 'Two lithium atoms react with one Cl₂ molecule: 2Li + Cl₂ → 2LiCl, with 2 lithium and 2 chlorine on each side, like sodium.'], 'application', true),
  trends.written('C9-18', 'Explain why potassium reacts more vigorously with water than sodium does. Name the products of the reaction.', 'Compare their electronic structures, say how far the outer electron is from the nucleus, and give the word equation.', 'Sodium (2,8,1) and potassium (2,8,8,1) both have one electron in their outer shell, which they lose when they react. Potassium has one more shell, so its outer electron is further from the nucleus. It is less strongly attracted to the nucleus, so it is lost more easily, which makes potassium more reactive. Potassium reacts with water to make potassium hydroxide and hydrogen.', ['Both have one electron in their outer shell, which is lost when they react.', 'Potassium’s outer electron is further from the nucleus, because it has more shells.', 'So it is less strongly attracted to the nucleus and is lost more easily, making potassium more reactive.', 'The products are potassium hydroxide and hydrogen.'], ['Saying potassium has more outer electrons than sodium.', 'Saying potassium’s outer electron is closer to the nucleus or more strongly attracted.', 'Saying the products are potassium oxide and water, or that oxygen is made.']),
]

export const lessonC9: ScienceLesson = {
  id: 'C-PER-009-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Group 1: the alkali metals', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
