import type { TeachingFrame } from '../../teachingFrame'

// Meet the group first (where it is, its one outer electron, soft and light), then the trends and why they happen,
// then the three reactions the spec names in the order of the page (water, chlorine, oxygen), ending on the 1+ ion.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const alkaliFrames: Record<string, TeachingFrame[]> = {
  'C9-02': [
    f('Group 1', 'The first column of the periodic table is Group 1.', 'first column → Group 1 → the alkali metals', 'Group 1 is the first column of the periodic table. It holds lithium, sodium, potassium, rubidium, caesium and francium. They are all metals. Together they are called the alkali metals. Hydrogen often sits above lithium, but it is not an alkali metal.', 'alk-group-table'),
    f('One outer electron', 'Every alkali metal atom has one electron in its outer shell.', 'same number of outer electrons → similar reactions', 'You met electronic structures when you learned about electron shells. Lithium is 2,1, sodium is 2,8,1 and potassium is 2,8,8,1. Each has just one electron in its outer shell. Elements with the same number of outer electrons react in similar ways. So the alkali metals have similar properties.', 'alk-group-electron'),
    f('Soft metals', 'Alkali metals are soft enough to cut with a knife.', 'a knife cuts it easily → soft', 'Most metals are hard. The alkali metals are soft, so a knife cuts them easily. The outside of a lump looks dull. But a freshly cut surface is shiny, like other metals.', 'alk-group-soft'),
    f('Low density', 'Lithium, sodium and potassium float on water.', 'less dense than water → floats', 'Density tells you how heavy a material is for its size. Lithium, sodium and potassium are all less dense than water. So they float on water. Most metals, such as iron, are much denser and sink.', 'alk-group-light'),
  ],
  'C9-05': [
    f('Losing one electron', 'Alkali metals react by losing their one outer electron.', 'lose 1 electron → full outer shell → 1+ ion', 'When an alkali metal reacts, each atom loses its one outer electron. The shell underneath is full, so now the outer shell is full. The atom has one more proton than electrons, so it has a charge of 1+. You met charged particles like this, called ions, when you learned about atoms. Sodium forms the ion Na⁺.', 'alk-trend-ion'),
    f('More reactive', 'Going down Group 1, the metals get more reactive.', 'down the group → more reactive → a trend', 'Going down Group 1, the metals get more reactive. Lithium fizzes steadily in water. Potassium reacts so fast that the hydrogen it makes catches fire. A pattern like this, going down a group, is called a trend.', 'alk-trend-reactive'),
    f('Why reactivity increases', 'Further down, the outer electron is lost more easily.', 'more shells → further away → less attracted → lost more easily', 'Each step down the group adds one more shell of electrons. So the outer electron is further from the nucleus. The positive nucleus attracts it less strongly. So the outer electron is lost more easily, and the metal is more reactive.', 'alk-trend-why'),
    f('Melting and boiling points', 'Melting and boiling points get lower going down the group.', 'down the group → lower melting and boiling points', 'Lithium melts at 181 °C, sodium at 98 °C and potassium at only 63 °C. So melting points get lower going down Group 1. Boiling points get lower too. Caesium melts at 28 °C, just above room temperature.', 'alk-trend-melt'),
    f('Put it together', 'Three trends run down Group 1.', 'reactivity up, melting and boiling points down, mass up', 'Going down Group 1, reactivity increases. Melting and boiling points decrease. Relative atomic mass increases, from 7 for lithium to 133 for caesium. You can use these trends to predict how an element behaves from its place in the group.', 'alk-trend-all'),
  ],
  'C9-08': [
    f('What you see', 'Sodium floats, moves around and fizzes on water.', 'floats, moves, fizzes → a gas is made', 'A teacher drops a tiny piece of sodium into a trough of water, behind a safety screen. It floats, because it is less dense than water. It moves around on the surface. It fizzes, which shows that a gas is being made. Lithium and potassium do the same.', 'alk-water-see'),
    f('The products', 'The reaction makes a metal hydroxide and hydrogen.', 'alkali metal + water → metal hydroxide + hydrogen', 'The gas in the bubbles is hydrogen. The other product is sodium hydroxide, which dissolves in the water. A compound like this is called a metal hydroxide. Its solution is alkaline, which is how the alkali metals got their name.', 'alk-water-products'),
    f('The symbol equation', 'The balanced equation is 2Na + 2H₂O → 2NaOH + H₂.', 'count each kind of atom on both sides', 'You met balancing when you learned about chemical equations. Hydrogen gas is made of H₂ molecules, so two sodium atoms must react. The balanced equation is 2Na + 2H₂O → 2NaOH + H₂. Count the atoms: 2 sodium, 4 hydrogen and 2 oxygen on each side.', 'alk-water-equation'),
    f('Down the group', 'The reaction with water gets more vigorous going down.', 'lithium steady → sodium fast → potassium catches fire', 'Lithium fizzes steadily. Sodium fizzes faster and moves around quickly. Potassium reacts so vigorously that it gives out enough energy to set the hydrogen alight. The hydrogen burns with a lilac flame. The further down the group, the more violent the reaction.', 'alk-water-trend'),
  ],
  'C9-11': [
    f('Reacting with chlorine', 'Hot sodium reacts vigorously with chlorine gas.', 'alkali metal + chlorine → metal chloride, a white salt', 'Chlorine is a pale green, poisonous gas. Hot sodium lowered into chlorine reacts vigorously. White clouds form and settle as a white powder of sodium chloride. White solids like this metal chloride are called salts.', 'alk-cl-react'),
    f('The symbol equation', 'The balanced equation is 2Na + Cl₂ → 2NaCl.', 'Cl₂ has two atoms → two sodium atoms needed', 'Chlorine gas is made of Cl₂ molecules, with two atoms in each. So two sodium atoms react with each chlorine molecule. The balanced equation is 2Na + Cl₂ → 2NaCl. Going down the group, the reaction with chlorine gets more vigorous.', 'alk-cl-equation'),
    f('Tarnishing', 'A freshly cut surface goes dull as it reacts with oxygen.', 'alkali metal + oxygen → metal oxide → dull surface', 'Alkali metals also react with oxygen in the air. A freshly cut surface of lithium is shiny. Within minutes, a thin layer of lithium oxide forms on it, so it looks dull. This dulling is called tarnishing.', 'alk-ox-tarnish'),
    f('Put it together', 'Alkali metals form ionic compounds.', 'lose 1 electron → 1+ ion → ionic compound', 'With water, an alkali metal makes a metal hydroxide and hydrogen. With chlorine, it makes a metal chloride. With oxygen, it makes a metal oxide. Each time, the metal atom loses its outer electron and forms a 1+ ion. Compounds made of ions like this are called ionic compounds.', 'alk-react-all'),
  ],
}
