import type { TeachingFrame } from '../../teachingFrame'

// Start with what an ion is (charge = protons − electrons, one sodium atom and one chlorine atom), then why atoms
// lose or gain electrons (a noble gas's full outer shell), and only then the shortcut: read the charge from the group.
// Ionic bonding (the ions together, dot-and-cross compounds) is the next topic, so every drawing here is one atom becoming one ion.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const ionFrames: Record<string, TeachingFrame[]> = {
  'C12-02': [
    f('Atoms have no charge', 'An atom has the same number of protons and electrons.', 'protons (+) = electrons (−) → no overall charge', 'You met protons and electrons when you learned what is inside an atom. Each proton has a positive charge and each electron has a negative charge. A sodium atom has 11 protons and 11 electrons. The charges cancel out, so the atom has no overall charge.', 'ion-what-atom'),
    f('Losing an electron', 'Losing an electron leaves a particle with a positive charge.', 'lose an electron → more + than − → positive', 'When atoms react, they can lose or gain electrons. The protons in the nucleus do not change. A sodium atom can lose its one outer electron. Then it has 11 protons but only 10 electrons, so its overall charge is 1+. A charged particle like this is called an ion.', 'ion-what-lose'),
    f('Gaining an electron', 'Gaining an electron gives a particle a negative charge.', 'gain an electron → more − than + → negative', 'A chlorine atom has 17 protons and 17 electrons. It can gain one electron into its outer shell. Then it has 18 electrons but still 17 protons, so its overall charge is 1−. This negative ion is called a chloride ion.', 'ion-what-gain'),
    f('Writing the charge', 'The charge on an ion equals the number of electrons lost or gained.', 'lost 2 → 2+; gained 2 → 2−', 'The number of electrons lost or gained is the size of the charge. Write the charge at the top right of the symbol. A sodium ion is Na⁺ and a chloride ion is Cl⁻. A plus or minus on its own means a charge of 1. A magnesium atom loses 2 electrons, so its ion is Mg²⁺.', 'ion-what-write'),
  ],
  'C12-05': [
    f('The goal: a full outer shell', 'Noble gas atoms have full outer shells, so they are stable.', 'full outer shell → stable', 'You met full outer shells when you learned about electronic structure. The noble gases are in Group 0 of the periodic table. Neon (2,8) and argon (2,8,8) have full outer shells, so they are very stable. When other atoms lose or gain electrons, they end up with a full outer shell too.', 'ion-why-goal'),
    f('Sodium loses one', 'A sodium ion has the same electronic structure as neon.', 'sodium 2,8,1 → lose 1 → 2,8 like neon', 'A sodium atom is 2,8,1. Losing 1 electron is much easier than gaining 7 more. When its outer electron goes, the full second shell becomes the outer shell. So a sodium ion is 2,8, the same electronic structure as neon. This arrangement is called a noble gas electronic structure.', 'ion-why-sodium'),
    f('Chlorine gains one', 'A chloride ion has the same electronic structure as argon.', 'chlorine 2,8,7 → gain 1 → 2,8,8 like argon', 'A chlorine atom is 2,8,7. It needs just 1 more electron to fill its outer shell. So it gains 1 electron and becomes 2,8,8. That is the same electronic structure as argon, a noble gas. So the chloride ion is stable.', 'ion-why-chlorine'),
    f('Put it together', 'Metal atoms lose electrons; non-metal atoms gain them.', 'metal → lose → positive; non-metal → gain → negative', 'Metal atoms, like sodium, have only a few outer electrons. They lose them to form positive ions. Non-metal atoms, like chlorine, have nearly full outer shells. They gain electrons to form negative ions. Either way, the ion has a full outer shell like a noble gas.', 'ion-why-all'),
  ],
  'C12-09': [
    f('Same group, same outer shell', 'Elements in one group have the same number of outer electrons.', 'same group → same outer electrons → same charge', 'Elements in the same group of the periodic table have the same number of outer electrons. So they lose or gain the same number of electrons to get a full outer shell. That means they form ions with the same charge. You can read the charge from the group number.', 'ion-group-table'),
    f('Groups 1 and 2 lose', 'Group 1 metals form 1+ ions; Group 2 metals form 2+ ions.', 'Group 1 → lose 1 → 1+; Group 2 → lose 2 → 2+', 'Groups 1 and 2 are metals. Group 1 atoms have 1 outer electron, so they lose it and form 1+ ions. Group 2 atoms have 2 outer electrons. A magnesium atom (2,8,2) loses both and becomes Mg²⁺ (2,8). Its 12 protons now outnumber its 10 electrons by 2.', 'ion-group-metals'),
    f('Groups 6 and 7 gain', 'Group 7 non-metals form 1− ions; Group 6 non-metals form 2− ions.', 'Group 7 → gain 1 → 1−; Group 6 → gain 2 → 2−', 'Groups 6 and 7 are non-metals. Group 7 atoms have 7 outer electrons, so they gain 1 and form 1− ions. Group 6 atoms have 6 outer electrons, so they gain 2. An oxygen atom (2,6) becomes 2,8 with a 2− charge. This ion, O²⁻, is called an oxide ion.', 'ion-group-nonmetals'),
    f('Put it together', 'Read the charge from the group: 1+, 2+, 2−, 1−.', 'Group 1: 1+, Group 2: 2+, Group 6: 2−, Group 7: 1−', 'You do not need to learn the ion of every element. Find the element’s group. Group 1 forms 1+ ions, like Na⁺. Group 2 forms 2+ ions, like Mg²⁺. Group 6 forms 2− ions, like O²⁻, and Group 7 forms 1− ions, like Cl⁻.', 'ion-group-all'),
  ],
}
