import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { periodicFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.1.2.2 Development of the periodic table (with 5.1.1.5 isotopes, used to explain the order)' }
const skill = 'C-PERIODIC-HISTORY'
const early = author(skill, ['5.1.2.2'], ['aqa-chemistry'])
const mendeleev = author(skill, ['5.1.2.2'], ['aqa-chemistry'])
const gaps = author(skill, ['5.1.2.2'], ['aqa-chemistry'])
const isotopes = author(skill, ['5.1.2.2', '5.1.1.5'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const periodicSections = [
  { id: 'C7-01', label: 'Start here', detail: 'What chemists could not know' },
  { id: 'C7-02', label: 'How were the first tables made?', detail: 'Atomic weight, groups and missing elements' },
  { id: 'C7-05', label: 'What did Mendeleev change?', detail: 'Switching elements and leaving gaps' },
  { id: 'C7-08', label: 'Was Mendeleev right?', detail: 'Predictions and germanium' },
  { id: 'C7-11', label: 'Why was weight order wrong?', detail: 'Isotopes, tellurium and iodine' },
  { id: 'C7-14', label: 'On your own', detail: 'Gallium, argon and a gap in a group' },
]

const states: ScienceState[] = [
  { ...early.choice('C7-01', 'In the early 1800s, nobody had discovered protons. Which of these could chemists not know about an element?', ['How heavy its atoms are compared with other atoms', 'Its atomic number', 'How it reacts with water'], 1, 'What does the atomic number count?', ['The atomic number is the number of protons in an atom.', 'So without knowing about protons, nobody could know atomic numbers. They could still weigh things and watch reactions.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(early, 'C7-02', 'How were the first tables made?'),
  early.choice('C7-03', 'How did chemists in the early 1800s put the elements in order?', ['By atomic number', 'By the date each was discovered', 'By atomic weight', 'In alphabetical order'], 2, 'What could they measure without knowing about protons?', ['Protons had not been discovered, so atomic numbers were unknown.', 'So chemists put the elements in order of atomic weight.']),
  early.choice('C7-04', 'Early tables ordered strictly by atomic weight put iodine with oxygen and sulfur. Why was this a problem?', ['Iodine reacts like chlorine and bromine, not like oxygen and sulfur', 'Iodine had not been discovered yet', 'Iodine has no atomic weight', 'Oxygen and sulfur are in no group'], 0, 'Which elements does iodine behave like?', ['A group should hold elements with similar properties.', 'Iodine behaves like chlorine and bromine, so putting it with oxygen and sulfur put it in the wrong group.']),
  t(mendeleev, 'C7-05', 'What did Mendeleev change?'),
  mendeleev.choice('C7-06', 'Mendeleev put tellurium before iodine, even though tellurium is heavier. Why?', ['He made a mistake with the weights', 'To keep iodine in the same group as elements it is like', 'Tellurium was discovered first', 'To leave a gap for a new element'], 1, 'Which elements is iodine like?', ['Weight order would have put iodine in the group with oxygen and sulfur.', 'Mendeleev switched them, so iodine stayed in the same group as chlorine and bromine.']),
  mendeleev.choice('C7-07', 'Why did Mendeleev leave gaps in his table?', ['To make every row the same length', 'For isotopes of known elements', 'Because some elements had no atomic weight', 'For elements that had not been discovered yet'], 3, 'What did he say belonged in each gap?', ['No known element fitted those spaces.', 'So he left gaps for elements that had not been discovered yet.']),
  t(gaps, 'C7-08', 'Was Mendeleev right?'),
  gaps.choice('C7-09', 'How did Mendeleev predict the properties of the missing element below silicon?', ['He measured a sample of it', 'He chose values at random', 'He copied the properties of oxygen', 'He used the elements above and below it in its group'], 3, 'Nobody had a sample. What could he look at instead?', ['Nobody had found the element, so there was nothing to measure.', 'So he used silicon above it and tin below it, because elements in a group are similar.']),
  gaps.choice('C7-10', 'Mendeleev predicted a density of about 5.5 g/cm³. Germanium’s density is 5.3 g/cm³. What does this show?', ['The prediction was close, which supports his table', 'The prediction was wrong, so his table was wrong', 'Germanium does not fit the gap', 'Germanium was found before 1869'], 0, 'How far apart are 5.5 and 5.3?', ['5.3 g/cm³ is very close to the 5.5 g/cm³ he predicted before germanium was found.', 'So the result is evidence that his table and its gaps were right.'], 'dataInterpretation'),
  t(isotopes, 'C7-11', 'Why was weight order wrong?'),
  isotopes.choice('C7-12', 'Chlorine-35 and chlorine-37 have different masses. Why do they share one place in the periodic table?', ['They have the same mass number', 'They are the same element, with the same properties', 'They were discovered at the same time', 'They have the same number of neutrons'], 1, 'How many protons does each have?', ['Both have the same number of protons, so both are chlorine.', 'They only differ in neutrons, so they have the same properties and the same place.']),
  isotopes.choice('C7-13', 'Tellurium has fewer protons than iodine. Why is its atomic weight higher?', ['Tellurium has more electrons', 'Iodine atoms have no neutrons', 'Most tellurium atoms are heavy isotopes', 'Its atomic weight was measured wrongly'], 2, 'Which isotopes are most tellurium atoms?', ['Most tellurium atoms are tellurium-128 or tellurium-130, but every natural iodine atom is iodine-127.', 'So tellurium’s average mass is higher, even though it has fewer protons.']),
  gaps.choice('C7-14', 'This group has a gap at box 3. What did Mendeleev expect the missing element to be like?', ['Like the elements in boxes 2 and 4, in the same group', 'Like no other known element', 'Like the elements in the next group along', 'Lighter than every other element in the group'], 0, 'What do elements in the same group share?', ['Elements in one group have similar properties.', 'So the missing element should be like aluminium and indium around it. It was gallium, found in 1875.'], 'understanding', true, 'ptable-question'),
  gaps.choice('C7-15', 'The table compares Mendeleev’s predictions with gallium, found in 1875. Which conclusion does the data support?', ['Every prediction Mendeleev made was exactly right', 'Gallium does not fit the gap he left', 'The predictions were close, which supports his table', 'Gallium’s atomic weight is exactly 68'], 2, 'Are the values close, or exactly the same?', ['The predicted atomic weight (about 68) is close to 69.7, and the predicted density (5.9) matches 5.9 g/cm³.', 'So the data supports his table, but it does not show that every prediction was exactly right.'], 'dataInterpretation', true, 'ptable-gallium'),
  mendeleev.choice('C7-16', 'Argon’s atomic weight is 39.9 and potassium’s is 39.1. Potassium reacts like sodium. Why is argon placed before potassium?', ['Argon was discovered first', 'Potassium is heavier than argon', 'To leave a gap for a new element', 'So potassium stays in the same group as sodium'], 3, 'Which group should potassium be in?', ['Potassium is lighter, so strict weight order would put it before argon, in the wrong group.', 'So the order is switched, like tellurium and iodine, to keep potassium with sodium.'], 'application', true),
  mendeleev.written('C7-17', 'Explain how Mendeleev’s table was different from earlier tables, and why later discoveries showed he was right.', 'Say what he did to the order, what he left, and what was found later. Use tellurium, iodine or germanium as an example.', 'Earlier tables put elements strictly in order of atomic weight, so some ended up in the wrong group. Mendeleev mainly used atomic weight, but he switched some elements, such as tellurium and iodine, so elements with similar properties stayed in the same group. He also left gaps for undiscovered elements and predicted their properties. Later, germanium was found. It fitted the gap below silicon and matched his predictions. Much later, isotopes explained why weight order was sometimes wrong.', ['He switched the order of some elements (e.g. tellurium and iodine) so elements with similar properties stayed in the same group.', 'He left gaps for elements that had not been discovered yet.', 'He used the gaps to predict the properties of the missing elements.', 'Elements found later (e.g. germanium, gallium) fitted the gaps and matched his predictions, showing he was right.'], ['Saying Mendeleev ordered the elements by atomic number.', 'Saying the gaps were mistakes or spaces to make rows equal.', 'Saying the switched elements had the wrong atomic weights.']),
]

export const lessonC7: ScienceLesson = {
  id: 'C-PER-007-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Building the periodic table', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
