import type { TeachingFrame } from '../../teachingFrame'

// Follow the table through time: first ordered by weight (and why that went wrong), then Mendeleev's two fixes
// (switching and gaps), then the proof (germanium fits its gap), and only then the later explanation (isotopes).
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const periodicFrames: Record<string, TeachingFrame[]> = {
  'C7-02': [
    f('No atomic numbers yet', 'Early chemists sorted elements by how heavy their atoms were.', 'no protons known → compare masses instead', 'In the early 1800s, nobody had discovered protons, neutrons or electrons. So nobody knew any atomic numbers. But chemists could compare how heavy the atoms of different elements were. This mass was called the atomic weight. Today we call it relative atomic mass.', 'ptable-weight-strip'),
    f('Not every element yet', 'Many elements had not been discovered.', 'missing elements → table not complete', 'Chemists put the known elements in order of atomic weight. But many elements had not been found yet. For example, the gases neon and argon were not found until the 1890s. So the early tables were not complete.', 'ptable-weight-missing'),
    f('Rows and columns', 'Similar elements were lined up in columns.', 'similar properties → same column → group', 'Chemists wrote the elements in rows, in order of atomic weight. They started a new row so that elements with similar properties lined up. For example, chlorine and bromine react in very similar ways. A column of elements with similar properties is called a group.', 'ptable-weight-rows'),
    f('Some in the wrong group', 'Strict weight order put some elements with the wrong family.', 'weight order → iodine in the wrong group', 'Iodine reacts like chlorine and bromine. But iodine’s atomic weight is a little less than tellurium’s. So strict weight order put iodine in the column with oxygen and sulfur. Iodine does not behave like them, so it was in the wrong group.', 'ptable-weight-misfit'),
  ],
  'C7-05': [
    f('Mendeleev’s table', 'In 1869 Mendeleev arranged all the known elements in a table.', '1869 → Mendeleev → mainly by atomic weight', 'In 1869, a Russian chemist called Dmitri Mendeleev took all the elements known at the time. There were about 60 of them. He arranged them in a table, mainly in order of atomic weight. The drawing shows a small part of his idea, drawn the modern way round.', 'ptable-mend-table'),
    f('Switching places', 'He swapped some elements so each stayed with its family.', 'similar properties matter more than weight order', 'Tellurium is slightly heavier than iodine. Weight order would put iodine first. Mendeleev switched them, so tellurium went before iodine. This kept iodine in the same group as chlorine and bromine, which it is like.', 'ptable-mend-switch'),
    f('Leaving gaps', 'He left empty spaces where no known element fitted.', 'no element fits → leave a gap', 'Sometimes the next known element did not match the group it would fall into. So Mendeleev left an empty space in the table, called a gap. He said each gap was for an element that had not been discovered yet. One gap was below silicon.', 'ptable-mend-gap'),
  ],
  'C7-08': [
    f('Predicting from a gap', 'The elements around a gap showed what the missing element would be like.', 'neighbours in the group → predict properties', 'Mendeleev used the elements around each gap to describe the missing element. The one below silicon should be like silicon above it and tin below it. He predicted an atomic weight of about 72. He predicted a dark grey solid with a density of about 5.5 g/cm³.', 'ptable-predict'),
    f('Germanium is found', 'In 1886 a new element was found that fitted the gap.', 'new element → fits the gap', 'In 1886, a chemist in Germany discovered a new element. It was named germanium. Its properties were like those of silicon and tin. So it fitted exactly into the gap below silicon.', 'ptable-found'),
    f('Checking the predictions', 'Germanium matched Mendeleev’s predictions closely.', 'predicted ≈ found → evidence he was right', 'Germanium’s atomic weight is 72.6, very close to the 72 Mendeleev predicted. Its density is 5.3 g/cm³, close to his 5.5. The predictions were made years before anyone had seen germanium. So they were good evidence that his table was right.', 'ptable-compare'),
    f('Put it together', 'Several new elements filled Mendeleev’s gaps.', 'gaps → predictions → discoveries → table accepted', 'Germanium was not the only one. Gallium was found in 1875 and scandium in 1879, and both fitted gaps. Each time, the new element matched what Mendeleev had predicted. So more and more scientists accepted his table.', 'ptable-found-all'),
  ],
  'C7-11': [
    f('Isotopes', 'Atoms of one element can have different masses.', 'same protons, different neutrons → different masses', 'Early in the 1900s, long after Mendeleev’s table, isotopes were discovered. You met isotopes when you learned about atoms: same number of protons, different numbers of neutrons. So isotopes of one element have different masses. They have the same properties, so they share the same place in the table.', 'ptable-iso-same'),
    f('A mix of masses', 'An element’s atomic weight is an average of its isotopes.', 'mostly heavy isotopes → high average', 'An element’s atomic weight is an average of the masses of its isotopes. Most tellurium atoms are tellurium-128 or tellurium-130. Every natural iodine atom is iodine-127. So tellurium’s average mass, 127.6, is higher than iodine’s, 126.9.', 'ptable-iso-mix'),
    f('Why the order flipped', 'Tellurium has fewer protons than iodine, even though it is heavier.', 'fewer protons but heavier isotopes → weight order wrong', 'A tellurium atom has 52 protons and an iodine atom has 53. So tellurium really does come before iodine. Its heavy isotopes make it look out of order by weight. Mendeleev was right to switch them, even before anyone knew why.', 'ptable-iso-order'),
    f('Put it together', 'Each new discovery built on the one before.', 'weight order → Mendeleev → germanium → isotopes', 'Early tables used atomic weight and were not complete. Mendeleev switched some elements and left gaps. New elements such as germanium then filled the gaps. Later, isotopes explained why weight order was sometimes wrong.', 'ptable-timeline'),
  ],
}
