import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { redoxFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.4.1.4 Oxidation and reduction in terms of electrons (HT): oxidation is loss of electrons, reduction is gain; ionic equations for displacement reactions; identifying the species oxidised and reduced in equations and half equations; 5.4.2.1 Reactions of acids with metals as redox reactions (HT), as on the supplied revision pages' }
const skill = 'C-REDOX'
const electrons = author(skill, ['5.4.1.4'], ['aqa-chemistry'])
const half = author(skill, ['5.4.1.4'], ['aqa-chemistry'])
const ionic = author(skill, ['5.4.1.4'], ['aqa-chemistry'])
const acid = author(skill, ['5.4.2.1'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const redoxSections = [
  { id: 'C25H-01', label: 'Start here', detail: 'How a magnesium ion forms' },
  { id: 'C25H-02', label: 'Losing and gaining electrons', detail: 'Oxidation, reduction and redox' },
  { id: 'C25H-06', label: 'Half equations', detail: 'Balancing charge with electrons' },
  { id: 'C25H-11', label: 'Displacement and ionic equations', detail: 'Spectator ions and what really changes' },
  { id: 'C25H-15', label: 'On your own', detail: 'New reactions, a diagram and a mistake' },
]

const states: ScienceState[] = [
  { ...electrons.choice('C25H-01', 'A magnesium atom becomes a magnesium ion, Mg²⁺. What happens to the atom?', ['It gains 2 electrons', 'It loses 2 electrons', 'It loses 2 protons'], 1, 'An ion is positive when it has fewer electrons than protons.', ['Mg²⁺ has a charge of 2+, so it has 2 more protons than electrons.', 'Protons stay in the nucleus. The atom has lost its 2 outer electrons. Losing and gaining electrons is what this topic is about.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(electrons, 'C25H-02', 'Losing and gaining electrons'),
  electrons.choice('C25H-03', 'Which statement about oxidation and reduction is correct?', ['Oxidation is gain of electrons', 'Reduction is loss of electrons', 'Oxidation is loss of electrons', 'Reduction is loss of protons'], 2, 'Remember OIL RIG.', ['OIL RIG: Oxidation Is Loss of electrons. Reduction Is Gain of electrons.', 'Protons stay in the nucleus. Only electrons move from one particle to another.']),
  electrons.choice('C25H-04', 'Sodium and chlorine react to form Na⁺ and Cl⁻ ions. Which reactant is reduced?', ['Sodium, because it loses an electron', 'Chlorine, because it loses electrons', 'Sodium, because it gains an electron', 'Chlorine, because it gains electrons'], 3, 'Which reactant forms a negative ion?', ['Each sodium atom loses an electron to form Na⁺, so sodium is oxidised.', 'Each chlorine atom gains an electron to form Cl⁻. Gain of electrons is reduction, so chlorine is reduced.']),
  electrons.choice('C25H-05', 'Why is one reactant always reduced when another is oxidised?', ['Electrons lost by one reactant are gained by the other', 'Both reactants always gain oxygen', 'Electrons are made during the reaction', 'Only metals can be reduced'], 0, 'Electrons are not made or destroyed. Where do the lost electrons go?', ['Electrons cannot just disappear. The electrons one reactant loses are gained by another reactant.', 'So oxidation and reduction always happen together. This is why the reaction is called redox.'], 'application'),

  t(half, 'C25H-06', 'Half equations'),
  half.worked('C25H-07', 'Write half equations for a redox reaction', 'Sodium burns in chlorine: 2Na + Cl₂ → 2NaCl. Sodium chloride is made of Na⁺ and Cl⁻ ions. Write a half equation for each element.', ['Write the equation with ions: 2Na + Cl₂ → 2Na⁺ + 2Cl⁻.', 'Sodium half: Na → Na⁺. The right is 1+, so add 1 electron to the right: Na → Na⁺ + e⁻.', 'Chlorine half: Cl₂ → 2Cl⁻. The atoms balance. The right is 2−, so add 2 electrons to the left: Cl₂ + 2e⁻ → 2Cl⁻.', 'Sodium loses electrons, so it is oxidised. Chlorine gains electrons, so it is reduced.'], 'hredox-worked-nacl'),
  half.choice('C25H-08', 'An aluminium atom forms an Al³⁺ ion. Which is the balanced half equation?', ['Al + 3e⁻ → Al³⁺', 'Al → Al³⁺ + e⁻', 'Al → Al³⁺ + 3e⁻', 'Al → Al³⁻ + 3e⁻'], 2, 'Add electrons to the more positive side until both sides have the same charge.', ['Al has no charge and Al³⁺ has a charge of 3+, so the right is more positive.', 'Add 3 electrons to the right: Al → Al³⁺ + 3e⁻. Now both sides have a total charge of 0.']),
  acid.choice('C25H-09', 'Which half equation shows hydrogen ions, H⁺, being reduced to hydrogen gas?', ['H₂ → 2H⁺ + 2e⁻', '2H⁺ + 2e⁻ → H₂', '2H⁺ → H₂ + 2e⁻', 'H⁺ + 2e⁻ → H₂'], 1, 'Reduction is gain of electrons. Check the atoms and the charges too.', ['Reduction is gain, so the electrons go on the left. Two H⁺ ions make one H₂ molecule.', 'The left is 2+ take 2 = 0 and the right is 0, so 2H⁺ + 2e⁻ → H₂ is balanced.']),
  half.choice('C25H-10', 'To combine Na → Na⁺ + e⁻ and Cl₂ + 2e⁻ → 2Cl⁻, what should you do first?', ['Halve the chlorine half equation', 'Add them as they are', 'Cross out Cl₂ on both sides', 'Multiply the sodium half equation by 2'], 3, 'Both halves must have the same number of electrons.', ['Sodium loses 1 electron but chlorine gains 2, so double the sodium half: 2Na → 2Na⁺ + 2e⁻.', 'Adding the halves and cancelling 2e⁻ gives 2Na + Cl₂ → 2Na⁺ + 2Cl⁻.'], 'application'),

  t(ionic, 'C25H-11', 'Displacement and ionic equations'),
  ionic.worked('C25H-12', 'Write an ionic equation for a displacement reaction', 'Magnesium displaces copper from copper sulfate solution: Mg + CuSO₄ → MgSO₄ + Cu. Write the ionic equation.', ['The full equation is already balanced: Mg + CuSO₄ → MgSO₄ + Cu.', 'Write the dissolved compounds as ions: Mg + Cu²⁺ + SO₄²⁻ → Mg²⁺ + SO₄²⁻ + Cu.', 'The sulfate ions are the same on both sides, so cross them out as spectator ions.', 'The ionic equation is Mg + Cu²⁺ → Mg²⁺ + Cu. There is 2+ on each side.', 'Magnesium atoms lose electrons, so they are oxidised. Copper ions gain electrons, so they are reduced.'], 'hredox-worked-mgcu'),
  ionic.choice('C25H-13', 'Zinc displaces copper: Zn + CuSO₄ → ZnSO₄ + Cu. Which ions are spectator ions?', ['Cu²⁺ ions', 'Zn²⁺ ions', 'SO₄²⁻ ions', 'There are none'], 2, 'Write the dissolved compounds as ions. Which ion is the same on both sides?', ['With ions: Zn + Cu²⁺ + SO₄²⁻ → Zn²⁺ + SO₄²⁻ + Cu.', 'The sulfate ions do not change, so they are spectator ions. Cu²⁺ is reduced and Zn becomes Zn²⁺.']),
  ionic.choice('C25H-14', 'Iron displaces copper from copper chloride solution, CuCl₂. What is the ionic equation?', ['Fe + Cu²⁺ → Fe²⁺ + Cu', 'Fe + 2Cl⁻ → FeCl₂', 'Fe + Cu → Fe²⁺ + Cu²⁺', 'Cu²⁺ + 2Cl⁻ → CuCl₂'], 0, 'The chloride ions are the same on both sides. What is left when you cross them out?', ['With ions: Fe + Cu²⁺ + 2Cl⁻ → Fe²⁺ + 2Cl⁻ + Cu.', 'Cross out the chloride spectator ions to leave Fe + Cu²⁺ → Fe²⁺ + Cu, the same as with copper sulfate.'], 'application'),

  ionic.choice('C25H-15', 'For 2Al + 3Cu²⁺ → 2Al³⁺ + 3Cu, which statement is correct?', ['Aluminium atoms are reduced and copper ions are oxidised', 'Copper ions are oxidised because they gain electrons', 'Both aluminium and copper are oxidised', 'Aluminium atoms are oxidised and copper ions are reduced'], 3, 'Which particle loses electrons, and which gains them?', ['Aluminium atoms lose 3 electrons each to form Al³⁺, so they are oxidised.', 'Copper ions gain 2 electrons each to form copper atoms, so they are reduced.'], 'understanding', true),
  ionic.choice('C25H-16', 'A magnesium strip is in copper sulfate solution. Which numbered particle is reduced as they react?', ['Particle 1', 'Particle 2', 'Particle 3', 'None of them'], 1, 'In displacement, which particle gains electrons?', ['Particle 2 is a copper ion, Cu²⁺. It gains 2 electrons from magnesium and becomes a copper atom, so it is reduced.', 'Particle 1, magnesium, loses electrons and is oxidised. Particle 3, sulfate, is a spectator ion.'], 'application', true, 'hredox-question-particles'),
  ionic.choice('C25H-17', 'Copper displaces silver from silver nitrate solution. Silver ions are Ag⁺. Which ionic equation is balanced?', ['Cu + Ag⁺ → Cu²⁺ + Ag', 'Cu²⁺ + 2Ag → Cu + 2Ag⁺', 'Cu + 2Ag⁺ → Cu²⁺ + 2Ag', 'Cu + 2Ag⁺ → Cu²⁺ + Ag'], 2, 'Check the atoms first, then the total charge on each side.', ['Copper atoms are oxidised to Cu²⁺ and silver ions are reduced to Ag. The nitrate ions are spectators.', 'Two Ag⁺ ions are needed to take 2 electrons: Cu + 2Ag⁺ → Cu²⁺ + 2Ag. The charge is 2+ on each side.'], 'calculation', true),
  ionic.choice('C25H-18', 'A student wrote an ionic equation for magnesium with iron chloride solution. Which numbered line has the first mistake?', ['Line 1', 'Line 2', 'Line 3', 'Line 4'], 1, 'Only dissolved compounds are split into ions. Is magnesium dissolved?', ['Line 2 writes magnesium as Mg²⁺ on the left. Magnesium is a solid metal, so it stays as Mg atoms.', 'Correct line 2: Mg + Fe²⁺ + 2Cl⁻ → Mg²⁺ + 2Cl⁻ + Fe. So the ionic equation is Mg + Fe²⁺ → Mg²⁺ + Fe.'], 'application', true, 'hredox-question-working'),
  acid.written('C25H-19', 'Magnesium reacts with dilute hydrochloric acid. Explain why this is a redox reaction. Include two half equations.', 'Which particle loses electrons and which gains them? Write a half equation for each, with the electrons on the correct side.', 'Magnesium atoms lose 2 electrons each to form Mg²⁺ ions: Mg → Mg²⁺ + 2e⁻. Loss of electrons is oxidation, so magnesium is oxidised. Hydrogen ions from the acid gain these electrons to form hydrogen gas: 2H⁺ + 2e⁻ → H₂. Gain of electrons is reduction, so the hydrogen ions are reduced. Oxidation and reduction happen at the same time, so this is a redox reaction. The chloride ions are spectator ions.', ['Magnesium atoms lose electrons, so magnesium is oxidised.', 'A balanced half equation for magnesium: Mg → Mg²⁺ + 2e⁻.', 'Hydrogen ions gain electrons to form hydrogen gas, so they are reduced.', 'A balanced half equation for hydrogen: 2H⁺ + 2e⁻ → H₂.', 'Oxidation and reduction happen at the same time, so it is a redox reaction.'], ['Saying magnesium is reduced or hydrogen ions are oxidised.', 'Explaining redox only as gain or loss of oxygen.', 'Half equations with electrons on the wrong side, or with charges that do not balance.']),
]

export const lessonC25H: ScienceLesson = {
  id: 'C-REDOX-025H-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Redox and ionic equations', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
