import type { FeedbackDefinition, InteractionDefinition, LearningState, LessonDefinition, MicroSkillId } from '../../number-types/types'
import type { PlaceHint, PlaceLessonVisual } from './model'
import type { LessonVideoDefinition, TutorOperationsVisualDefinition } from '../../order-of-operations/variant-c/variantCLesson'

type Calculation = Extract<TutorOperationsVisualDefinition, { kind: 'stacked-worked' }>
export type PlaceWorked = { kind: 'cumulative'; value?: string; highlights?: number[]; calculation: Calculation }
export type TutorPlaceState = LearningState & {
  sourceRef: string
  visual: Exclude<PlaceLessonVisual, { kind: 'worked' }> | PlaceWorked
  hints?: PlaceHint[]
  video?: LessonVideoDefinition
}
type Working = NonNullable<FeedbackDefinition['workedExplanation']>
const number = (value: string, ...highlights: number[]): TutorPlaceState['visual'] => ({ kind: 'number', value, highlights })
const numeric = (value: number, displayAnswer: string): InteractionDefinition => ({ type: 'numericInput', correctAnswer: value, displayAnswer, acceptanceRule: 'normalisedNumber', placeholder: 'Your answer' })
const select = (labels: string[], correct: number): InteractionDefinition => ({ type: 'select', options: labels.map((label, i) => ({ id: String(i), label })), correctAnswer: String(correct) })
const working = (answer: string, ...steps: Array<[string, string]>): Working => ({ answer, steps: steps.map(([title, line]) => ({ title, lines: [line] })) })
const hint = (text: string, guide?: { value: string; index: number }): PlaceHint[] => [{ label: 'Method', text, guide }]
const valueHint = (value: string, index: number) => hint('Count every column, including zeroes. Multiply the digit by one unit of its column.', { value, index })
const calculate = (math: string, result: string, title: string, evidence: string): Calculation => ({ kind: 'stacked-worked', math, steps: [{ math: result, previousMath: `\\underline{${math}}`, title, evidence }] })
const states: TutorPlaceState[] = []
function add(topic: MicroSkillId, title: string, sourceRef: string, visual: TutorPlaceState['visual'], interaction: InteractionDefinition = { type: 'continue' }, explanation?: Working, hints?: PlaceHint[], body?: string, video?: LessonVideoDefinition) {
  states.push({ id: `L3-${String(states.length + 1).padStart(2, '0')}`, microSkillId: topic, phase: interaction.type === 'continue' ? 'teach' : 'independent', teachingIntent: title, sourceRef, content: { title, body }, visual, hints, video,
    component: { type: 'placeValueChart', props: { value: 'value' in visual ? visual.value ?? '0' : '0' } }, interaction,
    feedback: explanation ? { correct: { message: 'Correct.', workedExplanation: explanation }, incorrect: { message: 'Here’s the working.', workedExplanation: explanation } } : undefined,
    transition: {}, completionCondition: 'Study the teaching or submit an answer, then view the complete working and continue regardless of accuracy.' })
}
const large = 'digit-place-value', decimal = 'decimal-places'
add(large, 'A digit’s place tells you its value', 'Retained Lesson 3 introduction', { kind: 'explore', value: '3,333', initialIndex: 1 }, undefined, undefined, undefined, 'Tap a 3 to see its value. Each column to the left is worth ten times more.')
const largeCalculation = calculate('2\\times10{,}000', '20{,}000', 'The 2 is in the ten-thousands column.', '2 ten-thousands = 20,000.')
largeCalculation.additionalExamples = [calculate('8\\times1', '8', 'The 8 is in the units column.', '8 units = 8.')]
add(large, 'What is the value of the digit 2 in 526,908?', 'N3.1 Q1; Video 12.45.00 (digit 2 and digit 8)', { kind: 'cumulative', value: '526,908', highlights: [1, 5], calculation: largeCalculation }, undefined, undefined, undefined, undefined, {
  id: 'place-value-large', src: '/media/lesson-3/large-numbers.mp4', poster: '/media/lesson-3/large-numbers.jpg', title: 'Place value in 526,908', durationSeconds: 39.2, sourceFile: 'WhatsApp Video 2026-09-16 at 12.45.00.mp4', textAlternative: ['Count from the right: units, tens, hundreds, thousands, ten-thousands, hundred-thousands.', '2 is in ten-thousands: 2 × 10,000 = 20,000.', '8 is in units: 8 × 1 = 8.'] })
add(large, 'In 7,364, what is the value of the digit 3?', 'N3.1 Q2', number('7,364', 1), numeric(300, '300'), working('300', ['Find the column.', 'Counting from the right: 4 units, 6 tens, 3 hundreds.'], ['Multiply by one hundred.', '3 × 100 = 300']), valueHint('7,364', 1))
add(large, 'In 812,047, what is the value of the digit 8, and how many times bigger is it than the value of the digit 4?', 'N3.1 Q3', number('812,047', 0, 4), select(['800,000; 20,000 times as large', '800,000; 10 times as large', '80,000; 2,000 times as large', '800,000; 200,000 times as large'], 0), working('800,000; 20,000 times as large as the value of the 4', ['Find the value of the 8.', '8 × 100,000 = 800,000'], ['Find the value of the 4.', '4 × 10 = 40'], ['Divide the two values.', '800,000 ÷ 40 = 20,000']), hint('First find each digit’s value. To find how many times as large one value is, divide the larger value by the smaller value.'))
add(large, 'Keep a column for every place', 'Retained Lesson 3 placeholder teaching (whole-number bridge)', { kind: 'cumulative', calculation: {
  kind: 'stacked-worked', math: '5\\times1000+7\\times10', steps: [
    { math: '5000+7\\times10', previousMath: '\\underline{5\\times1000}+7\\times10', title: 'Find the thousands value.', evidence: '5 × 1,000 = 5,000.' },
    { math: '5000+70', previousMath: '5000+\\underline{7\\times10}', title: 'Find the tens value.', evidence: '7 × 10 = 70.' },
    { math: '5070', previousMath: '\\underline{5000+70}', title: 'Add the two values.', evidence: '5,000 + 70 = 5,070. Zeroes hold hundreds and units.' },
  ],
} }, undefined, undefined, undefined, 'A zero holds an empty place. It keeps the other digits in their intended columns.')
add(large, 'Write the number that has 4 ten-thousands, 6 hundreds and 2 units. All its other digits are 0.', 'N3.1 Q4a', { kind: 'parts', parts: ['4 ten-thousands', '6 hundreds', '2 units'] }, numeric(40602, '40,602'), working('40,602', ['Find each part’s value.', '4 × 10,000 = 40,000; 6 × 100 = 600; 2 × 1 = 2.'], ['Add the parts, keeping empty columns.', '40,000 + 600 + 2 = 40,602. Zeroes hold the thousands and tens places.']), hint('Write the named places in order. Include a zero in each place with no stated units.'))
add(large, 'What is the value of the 6 in the number you just wrote?', 'N3.1 Q4b', number('40,602', 2), numeric(600, '600'), working('600', ['Use the number from part a: 40,602.', '6 is in the hundreds column.'], ['Calculate its value.', '6 × 100 = 600']), valueHint('40,602', 2))
add(large, 'A number has an 8 in the hundred-thousands column and a 3 in the tens column. Every other digit is 0. Write the number.', 'N3.1 Q5a', { kind: 'parts', parts: ['8 hundred-thousands', '3 tens'] }, numeric(800030, '800,030'), working('800,030', ['Find the two non-zero values.', '8 × 100,000 = 800,000; 3 × 10 = 30.'], ['Add them and hold every empty place.', '800,000 + 30 = 800,030']), hint('Start at hundred-thousands and work towards units. Put the 3 in tens, then fill each other place with zero.'))
add(large, 'What is the value of the 8 in the number you just wrote?', 'N3.1 Q5b', number('800,030', 0), numeric(800000, '800,000'), working('800,000', ['Use the number from part a: 800,030.', '8 is in hundred-thousands.'], ['Multiply by one hundred-thousand.', '8 × 100,000 = 800,000']), valueHint('800,030', 0))
add(large, 'Tom says: “The value of a digit only depends on the digit itself, not on where it is in the number.” Is Tom correct? Give a reason using an example.', 'N3.1 Q5c (reason and example choices)', { kind: 'parts', parts: ['5,000', '500'] }, select(['No. The 5 is worth 5,000 in 5,000, but 500 in 500.', 'Yes. The digit 5 is always worth 5.', 'No. The 5 is worth 500 in 5,000, but 5,000 in 500.'], 0), working('No. A digit’s position changes its value.', ['Use the same digit in two places.', 'In 5,000: 5 × 1,000 = 5,000. In 500: 5 × 100 = 500.'], ['Compare its values.', 'The digit is 5 in both numbers, but its values differ. Position matters.']), hint('Test the claim with the same digit in two different columns. Does multiplying by each column’s unit give the same value?'))
add(decimal, 'After the decimal point, each column is one tenth as large', 'Retained Lesson 3 decimal introduction', { kind: 'explore', value: '4.444', initialIndex: 1 }, undefined, undefined, undefined, 'After the point: tenths, hundredths, thousandths, and so on.')
add(decimal, 'In 0.428, what is the value of the digit 2?', 'N3.2 Q1', { kind: 'cumulative', value: '0.428', highlights: [2], calculation: calculate('2\\times0.01', '0.02', 'The 2 is in the hundredths column.', '4 tenths, 2 hundredths, 8 thousandths. Two hundredths is 0.02.') })
add(decimal, 'In 0.37, what is the value of the digit 7?', 'N3.2 Q2', number('0.37', 2), numeric(0.07, '0.07'), working('0.07', ['Count after the decimal point.', '3 is in tenths; 7 is in hundredths.'], ['Multiply by one hundredth.', '7 × 0.01 = 0.07']), valueHint('0.37', 2))
const decimalCalculation = calculate('5\\times0.001', '0.005', 'The 5 is in the thousandths column.', 'Count the zero in hundredths too. Five thousandths is 0.005.')
decimalCalculation.additionalExamples = [calculate('9\\times0.0001', '0.0009', 'The 9 is in the ten-thousandths column.', 'Nine ten-thousandths is 0.0009.')]
add(decimal, 'Find each digit’s value in 0.6059', 'Video 12.45.27; prepares N3.2 Q3', { kind: 'cumulative', value: '0.6059', highlights: [3, 4], calculation: decimalCalculation }, undefined, undefined, undefined, undefined, {
  id: 'place-value-decimal', src: '/media/lesson-3/decimals.mp4', poster: '/media/lesson-3/decimals.jpg', title: 'Place value in 0.6059', durationSeconds: 37.7, sourceFile: 'WhatsApp Video 2026-09-16 at 12.45.27.mp4', textAlternative: ['After the point: tenths, hundredths, thousandths, ten-thousandths.', '5 is in thousandths: 5 × 0.001 = 0.005.', '9 is in ten-thousandths: 9 × 0.0001 = 0.0009.'] })
add(decimal, 'Decimal places can be written as fractions', 'Bridge to N3.2 Q3', { kind: 'cumulative', value: '0.003', highlights: [3], calculation: calculate('3\\times\\frac{1}{1000}', '\\frac{3}{1000}', 'One thousandth is 1/1000.', 'Three thousandths is 3/1000, the same value as 0.003.') }, undefined, undefined, undefined, 'The column gives the denominator: tenths use 10, hundredths use 100, and thousandths use 1,000.')
add(decimal, 'In 0.6059, what is the value of the digit 5, written as a fraction?', 'N3.2 Q3', number('0.6059', 3), { type: 'numericInput', correctAnswer: 0.005, displayAnswer: '5/1000 or 1/200', acceptanceRule: 'fraction', placeholder: 'e.g. 3/1000' }, working('5/1000 = 1/200', ['Count the decimal columns, including the zero.', '6 tenths, 0 hundredths, 5 thousandths.'], ['Write five thousandths as a fraction.', '5 × 1/1000 = 5/1000. Divide numerator and denominator by 5 to get 1/200.']), hint('Write digit / denominator. Use 10 for tenths, 100 for hundredths, 1,000 for thousandths. Enter a fraction using /.'))
add(decimal, 'In 0.20074, what is the value of the digit 7?', 'N3.2 Q4a', number('0.20074', 4), numeric(0.0007, '0.0007'), working('0.0007', ['Count every column after the point.', '2 tenths, 0 hundredths, 0 thousandths, 7 ten-thousandths.'], ['Multiply by one ten-thousandth.', '7 × 0.0001 = 0.0007']), valueHint('0.20074', 4))
add(decimal, 'One column left means a unit ten times as large', 'Clarification for corrected N3.2 Q4b', { kind: 'cumulative', calculation: calculate('0.0001\\div0.00001', '10', 'Compare one unit of each column.', 'A ten-thousandth is ten times a hundred-thousandth.') }, undefined, undefined, undefined, 'To compare two digits, work out each digit’s value first.')
add(decimal, 'In 0.20074, is the value of the 7 ten times the value of the 4? Give a reason.', 'N3.2 Q4b (corrected false premise)', number('0.20074', 4, 5), select(['No. 0.0007 ÷ 0.00004 = 17.5, so it is 17.5 times as large.', 'Yes. The digits are in neighbouring columns, so their values differ by 10.', 'No. 7 ÷ 4 = 1.75, so it is 1.75 times as large.'], 0), working('No. The 7’s value is 17.5 times the 4’s value.', ['Calculate both digit values.', '7 × 0.0001 = 0.0007; 4 × 0.00001 = 0.00004.'], ['Divide the values.', '0.0007 ÷ 0.00004 = 17.5'], ['Distinguish digit values from column units.', 'The neighbouring column units differ by 10. The digits 7 and 4 also differ, so their values do not differ by 10.']), hint('Find each digit’s value before dividing. Neighbouring column units differ by ten, but the digits in those columns can be different.'))
add(decimal, 'A decimal number has a 6 in the thousandths column and a 9 in the ten-thousandths column. Every other digit is 0. Write the number.', 'N3.2 Q5a', { kind: 'parts', parts: ['6 thousandths', '9 ten-thousandths'] }, numeric(0.0069, '0.0069'), working('0.0069', ['Find each part’s value.', '6 × 0.001 = 0.006; 9 × 0.0001 = 0.0009.'], ['Add them, keeping zeroes in empty places.', '0.006 + 0.0009 = 0.0069. The tenths and hundredths are zero.']), hint('Write columns from units through ten-thousandths. Put the 6 and 9 in their named columns, and use zeroes elsewhere.'))
add(decimal, 'What is the value of the 9 in the number you just wrote?', 'N3.2 Q5b', number('0.0069', 4), numeric(0.0009, '0.0009'), working('0.0009', ['Use the number from part a: 0.0069.', '9 is in the ten-thousandths column.'], ['Multiply by one ten-thousandth.', '9 × 0.0001 = 0.0009']), valueHint('0.0069', 4))
add(decimal, 'Priya says: “The digit furthest to the right in a decimal is always worth the least.” Is Priya correct? Give a reason using an example.', 'N3.2 Q5c (reason and example choices)', number('0.08'), select(['No. In 0.08, the rightmost 8 is worth 0.08, more than the 0 in tenths.', 'Yes. The rightmost column is the smallest, so its digit always has the least value.', 'No. In 0.08, the 8 is worth 0.8.'], 0), working('No. The smallest column need not contain the least digit value.', ['Test 0.08.', 'The 0 in tenths is worth 0 × 0.1 = 0. The rightmost 8 is worth 8 × 0.01 = 0.08.'], ['Compare the actual values.', '0.08 > 0. A zero further left is worth less than the non-zero digit on the right.']), hint('Test a decimal that has zero in a column to the left of a non-zero digit. Zero times any column unit is still zero.'))
add('mixed', 'Find the place, then calculate the value', 'Lesson 3 consolidation', { kind: 'parts', parts: ['Digit × column unit', 'Zero holds a place', 'Compare actual values'] }, undefined, undefined, undefined, 'Find the column, then multiply the digit by the column’s value. Zeros hold empty places.')
states.forEach((state, index) => { state.transition.onComplete = states[index + 1]?.id })
export const tutorPlaceValueLesson: LessonDefinition & { states: TutorPlaceState[] } = { id: 'L003', title: 'Place value', level: 'GCSE Foundation', goal: 'Read digit values in large numbers and decimals, use zero placeholders, and compare actual digit values.', states }
export const tutorPlaceValueLabels: Partial<Record<MicroSkillId, string>> = { 'digit-place-value': 'Large numbers', 'decimal-places': 'Decimals', mixed: 'Review' }
