import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { wsDesignFrames as frames } from './teachingFrames'

const source = { id: 'aqa-working-scientifically', title: 'AQA 8464 Working scientifically and practical skills', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification', locator: 'WS 2.1 (hypotheses and predictions), WS 2.2 (fair tests, variables, control experiments, repeatable, reproducible and valid results), as on the supplied revision page' }
const skill = 'W-MTH-004-W'
const a = author(skill, ['WS 2.1', 'WS 2.2'], ['aqa-working-scientifically'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const wsDesignSections = [
  { id: 'W4-01', label: 'Start here', detail: 'Finding out fairly' },
  { id: 'W4-02', label: 'From idea to prediction', detail: 'Observation, hypothesis, prediction and evidence' },
  { id: 'W4-05', label: 'How do you make it fair?', detail: 'Independent, dependent and control variables' },
  { id: 'W4-09', label: 'Can you trust the results?', detail: 'Repeatable, reproducible and valid' },
  { id: 'W4-12', label: 'On your own', detail: 'Variables, repeats and planning' },
]

const states: ScienceState[] = [
  { ...a.choice('W4-01', 'You think a heavier bag slows you down on the walk to school. How could you test this fairly?', ['Walk the same route with different bag weights and time each walk', 'Walk different routes with different bags and guess the times', 'Carry the heaviest bag once and see how it feels', 'Ask a friend which bag they like best'], 0, 'You want to change one thing only, and measure the result.', ['Use the same route each time, change only the weight of the bag, and time each walk.', 'If the route also changes, you could not tell whether the bag or the route made the difference.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('W4-02', 'From idea to prediction'),
  a.choice('W4-03', 'A student thinks that warmer water dissolves sugar faster. Which of these is a prediction?', ['Sugar is a solid', 'Temperature affects dissolving', 'Sugar will dissolve in less time in water at 60 °C than in water at 20 °C', 'Warm water is better'], 2, 'A prediction says what you expect to happen, and you can check it in a test.', ['This statement says what you expect to measure: a shorter time at the higher temperature.', 'The other statements are general facts or ideas, so they cannot be checked directly with one test.'], 'understanding'),
  a.choice('W4-04', 'The results of a careful test do not match the prediction. What does this suggest?', ['The results should be thrown away', 'The hypothesis may be wrong', 'The hypothesis must be right', 'The test was a waste of time'], 1, 'Evidence can support a hypothesis or show that it is wrong.', ['If good evidence does not match the prediction, the hypothesis may need to change.', 'Results that surprise you are still useful. You should check the method, but you should not just throw them away.']),
  t('W4-05', 'How do you make it fair?'),
  a.choice('W4-06', 'A student tests how the concentration of acid affects the time a reaction takes. What is the independent variable?', ['The time the reaction takes', 'The volume of acid', 'The concentration of the acid', 'The temperature of the room'], 2, 'It is the one thing the student chooses to change.', ['The student changes the concentration on purpose, so concentration is the independent variable.', 'The time is what is measured, so it is the dependent variable.'], 'understanding'),
  a.choice('W4-07', 'In a test of how ramp height affects a trolley’s speed, which is a control variable?', ['The height of the ramp', 'The speed of the trolley', 'The time on the stopwatch', 'The mass of the trolley'], 3, 'A control variable is something that could affect the result, but is kept the same.', ['The mass of the trolley could affect the result, so it is kept the same each time.', 'The ramp height is changed, and the speed is measured.'], 'application'),
  a.choice('W4-08', 'What is the job of a control experiment?', ['To show what happens when you do not change the independent variable', 'To make the results bigger', 'To replace the main experiment', 'To find the mean of the results'], 0, 'It is kept in the same conditions, but nothing is changed in it.', ['A control experiment is kept in the same conditions but has no change made to it.', 'You compare it with the rest, so you can see the effect of the change you made.'], 'understanding'),
  t('W4-09', 'Can you trust the results?'),
  a.choice('W4-10', 'A student wants to check that a result is repeatable. What should they do?', ['Ask another group to do it', 'Repeat the readings at least three times and check they are similar', 'Use a bigger piece of equipment', 'Change the independent variable each time'], 1, 'Repeatable means the same person gets similar results again.', ['The same person should repeat the readings, at least three times.', 'Asking another group tests whether the result is reproducible instead.']),
  a.choice('W4-11', 'Two groups run the same experiment and get similar results. But in each, the room temperature changed. Are the results valid?', ['Yes, because two groups got similar results', 'Yes, because they used the same method', 'No, because the results were different', 'No, because it was not a fair test'], 3, 'Valid results come from a fair test and answer the original question.', ['A control variable changed, so the test was not fair.', 'Results from an unfair test are not valid, even if they are reproducible.'], 'understanding'),
  a.choice('W4-12', 'Look at the numbered parts. Which part shows the dependent variable in this plant experiment?', ['Part 1', 'Part 2', 'Part 3', 'Part 4'], 0, 'This is what the student measures at the end.', ['Part 1 is the height of each plant, which is measured.', 'The amount of fertiliser is changed, and pot size, light and water are kept the same.'], 'application', true, 'wsdesign-q-plants'),
  a.choice('W4-13', 'Two students each take three readings of a reaction time. Which student’s results are more repeatable?', ['Student P, because all three readings are close', 'Student Q, because the readings are far apart', 'Neither, because there are only three', 'Both, because they used the same equipment'], 0, 'Repeatable results are similar each time the same person repeats the test.', ['Student P’s readings are close together, so they are similar each time.', 'Student Q’s readings are spread out, so they are less repeatable.'], 'dataInterpretation', true, 'wsdesign-q-repeats'),
  a.choice('W4-14', 'A group tests if fertiliser affects growth. They give one plant fertiliser and put another in a dark cupboard. What is wrong?', ['They measured the height', 'They used only two plants and no water', 'They changed light as well as fertiliser, so it is not a fair test', 'They wrote down the results'], 2, 'Only one thing should change between the plants.', ['Fertiliser and light both changed, so growth could be due to either.', 'Light is a control variable and must stay the same.'], 'practicalReasoning', true),
  a.written('W4-15', 'Plan a fair test to find out if ramp height changes how fast a trolley reaches the bottom.', 'Name what you change, what you measure and what you keep the same.', 'I would change the height of the ramp, for example using 10 cm, 20 cm and 30 cm. I would measure the time the trolley takes to reach the bottom with a stopwatch. I would keep the same trolley, the same ramp length and the same surface. I would repeat each height at least three times. Then I would compare the results.', ['The independent variable is the ramp height.', 'The dependent variable is the time taken, or the speed of the trolley.', 'At least two control variables, such as the trolley, the ramp length or the surface.', 'Repeat the readings at least three times.'], ['Changing more than one variable at once.', 'Saying the trolley is the independent variable.', 'Forgetting to say what is measured.']),
]

export const lessonW4: ScienceLesson = {
  id: skill, contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'skills',
  title: 'Designing investigations', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
