import type { TeachingFrame } from '../../teachingFrame'

// Set-up (variables, series loop, voltmeter in parallel, crocodile clips), method with the cooling safety point, then results: R = V ÷ I, table, graph, direct proportion.
// This prepares students for the real practical; it never claims to replace it.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const wireResistFrames: Record<string, TeachingFrame[]> = {
  'P17-02': [
    f('The question', 'We change the length of a wire and measure its resistance. Length is the independent variable, resistance the dependent variable.', 'what changes, what is measured', 'We want to know how the length of a wire affects its resistance. The length is what we change, so it is the independent variable. The resistance is what we measure, so it is the dependent variable. This lesson prepares you for the practical, and you still carry it out with your teacher.', 'wirer-question'),
    f('A series loop', 'Build one loop: battery, switch, test wire and ammeter. The ammeter goes in series with the wire.', 'ammeter in the loop', 'Build one closed loop with a battery, a switch, the test wire and an ammeter. The ammeter measures the current, in amperes. It must be in series with the test wire. Series means one after another in the same loop.', 'wirer-loop'),
    f('Voltmeter in parallel', 'The voltmeter measures the pd across the test wire. It goes in parallel, on its own branch.', 'across the wire, not in the loop', 'The voltmeter measures the potential difference across the test wire, in volts. It is connected in parallel. That means it is joined across the wire on its own branch, and it is not part of the main loop.', 'wirer-voltmeter'),
    f('Crocodile clips on a ruler', 'The test wire lies along a metre ruler. One clip stays at 0 cm and the other slides to change the length.', 'clips choose the length', 'The test wire is stretched straight along a metre ruler. One crocodile clip stays at the 0 cm mark. The other clip is moved along the wire. The wire between the two clips is the length being tested.', 'wirer-clips'),
  ],
  'P17-05': [
    f('Set the first length', 'Put the first clip at 0 cm and the second about 10 cm along. Write down the length between the clips.', 'record the length', 'Put the first clip at 0 cm on the ruler. Put the second clip a short way along, for example at 10 cm. Write down the length of wire between the clips. A thin wire gives the best results, and it must be straight so the length is accurate.', 'wirer-set-length'),
    f('Take the readings', 'Close the switch. Read the current on the ammeter and the pd on the voltmeter. Write both down.', 'two readings', 'Close the switch so that current flows. Read the current from the ammeter and the potential difference from the voltmeter. Write both numbers down straight away, with their units.', 'wirer-read'),
    f('Open the switch to cool', 'The wire heats up when current flows, and that changes its resistance. Open the switch between readings.', 'keep the wire cool', 'The wire may heat up while current flows. Heating changes its resistance, which would spoil the results. So open the switch as soon as you have taken the readings. Leave it open to let the wire cool down. Do not touch the wire while the circuit is switched on.', 'wirer-cool'),
    f('Repeat for more lengths', 'Move the second clip about 10 cm further along. Close the switch, take readings, then open it again.', 'a range of lengths', 'Move the second clip another 10 cm along the wire. Close the switch, take the two readings, then open the switch again. Repeat this for a range of lengths, such as 10, 20, 30, 40 and 50 cm.', 'wirer-repeat'),
  ],
  'P17-08': [
    f('Work out the resistance', 'For each length, use R = V ÷ I. Example: 0.60 V and 0.30 A give 2.0 Ω.', 'resistance = pd ÷ current', 'For each length, work out the resistance from your two readings. Use R = V ÷ I, which comes from V = IR by dividing both sides by I. For example, the 10 cm length gave a pd of 0.60 V and a current of 0.30 A. So R = 0.60 ÷ 0.30 = 2.0 Ω.', 'wirer-calc'),
    f('A table of results', 'Doing this for every length gives a table. The longer the wire, the greater the resistance.', 'length and resistance side by side', 'Doing the same calculation for each length gives a table like this one. Here 10 cm has a resistance of 2.0 Ω, 20 cm has 4.0 Ω, 30 cm has 6.0 Ω and 40 cm has 8.0 Ω. As the length goes up, the resistance goes up.', 'wirer-table'),
    f('Plot the graph', 'Plot resistance up the side and length along the bottom. Draw a line of best fit through the points.', 'line of best fit', 'Plot resistance on the vertical axis and length of wire on the horizontal axis. Mark each result with a small cross. Then draw a line of best fit with a ruler. A line of best fit passes as close as possible to all the points, and it does not join them up one by one.', 'wirer-graph'),
    f('A straight line through the origin', 'The graph is a straight line through the origin. Resistance is directly proportional to length.', 'twice as long, twice the resistance', 'The line is straight and it passes through the origin, where the length and the resistance are both zero. This means resistance is directly proportional to length. If you double the length of the wire, you double its resistance. The longer the wire, the greater the resistance.', 'wirer-prop'),
  ],
}
