import type { DecimalOperationStage, DecimalOperationVisual, LearningState, LessonDefinition, MicroSkillId } from '../number-types/types'

function worked(id: string, skill: MicroSkillId, title: string, prompt: string, kind: DecimalOperationVisual['props']['kind'], expression: string, stages: DecimalOperationStage[], answer: string, next: string): LearningState {
  return { id, microSkillId: skill, phase: 'teach', teachingIntent: 'Model one visible mathematical change at a time.', content: { title, prompt }, component: { type: 'decimalOperation', props: { kind, expression, mode: 'stepper', stages, answer } }, interaction: { type: 'continue' }, transition: { onComplete: next }, completionCondition: 'Learner reaches the last animation step and continues.', analytics: { eventName: `lesson_6_${id.toLowerCase().replaceAll('-', '_')}` } }
}

function question({ id, skill, phase = 'independent', title, prompt, kind, expression, rows, answer, displayAnswer, correct, incorrect, next, misconception }: {
  id: string; skill: MicroSkillId; phase?: LearningState['phase']; title: string; prompt?: string; kind: DecimalOperationVisual['props']['kind']; expression: string; rows?: string[]; answer: number; displayAnswer?: string; correct: string; incorrect: string; next: string; misconception: string
}): LearningState {
  return { id, microSkillId: skill, phase, teachingIntent: 'Check accurate use of decimal place value.', content: { title, prompt }, component: { type: 'decimalOperation', props: { kind, expression, rows, result: displayAnswer ?? String(answer) } }, interaction: { type: 'numericInput', correctAnswer: answer, displayAnswer, acceptanceRule: 'normalisedNumber', placeholder: 'Type your answer' }, feedback: { correct: { message: correct }, incorrect: { message: incorrect } }, transition: { onComplete: next }, completionCondition: `Learner enters ${displayAnswer ?? answer}.`, analytics: { misconceptionId: misconception, eventName: `lesson_6_${id.toLowerCase().replaceAll('-', '_')}` } }
}

const additionStages: DecimalOperationStage[] = [
  { label: 'Start with the calculation', narration: 'The numbers have different lengths after the decimal point.', expression: '985.4 + 81.767', rows: ['985.4', '+ 81.767'] },
  { label: 'Line up the points', narration: 'Slide the numbers until the decimal points are in one vertical column.', expression: '985.4 + 81.767', rows: ['985.4', ' 81.767'], markers: ['decimal points aligned'] },
  { label: 'Add place-holding zeroes', narration: 'Write 985.4 as 985.400. Its value has not changed.', expression: '985.400 + 81.767', rows: ['985.400', '+81.767'], markers: ['4.5 = 4.50 = 4.500'] },
  { label: 'Add by columns', narration: 'Add from the right, carrying when a column totals ten or more.', expression: '985.400 + 81.767', rows: ['  1 1  ', '985.400', '+81.767', '1067.167'], markers: ['LINE UP → ADD'], durationMs: 3000 },
  { label: 'Keep the decimal column', narration: 'The answer’s decimal point stays in the same aligned column.', expression: '985.400 + 81.767 = 1067.167', rows: ['985.400', '+81.767', '1067.167'] },
]

const subtractionStages: DecimalOperationStage[] = [
  { label: 'Start with the calculation', narration: 'Line up the decimal points before subtracting.', expression: '567.63 − 92.478', rows: ['567.63', '−92.478'] },
  { label: 'Fill the empty place', narration: 'Write 567.63 as 567.630. The zero holds the thousandths place.', expression: '567.630 − 92.478', rows: ['567.630', '−92.478'], markers: ['567.63 = 567.630'] },
  { label: 'Regroup the thousandths', narration: 'Zero thousandths cannot subtract eight, so regroup one hundredth as ten thousandths.', expression: '567.630 − 92.478', rows: ['567.6²10', '−92.478'], markers: ['one place at a time'], durationMs: 3000 },
  { label: 'Regroup across the columns', narration: 'Continue from right to left. Keep every digit in its place-value column.', expression: '567.630 − 92.478', rows: ['5⁴16 12¹10', '567.630', '−92.478', '475.152'], markers: ['LINE UP → ADD ZEROS → SUBTRACT'], durationMs: 3200 },
  { label: 'Read the difference', narration: 'The difference is 475.152. The decimal point has not moved.', expression: '567.630 − 92.478 = 475.152', rows: ['567.630', '−92.478', '475.152'] },
]

const multiplicationStages: DecimalOperationStage[] = [
  { label: 'Start with the decimals', narration: 'Keep the original calculation visible: 7.68 multiplied by 2.5.', expression: '7.68 × 2.5', rows: ['7.68', '×2.5'] },
  { label: 'Calculate the digits', narration: 'Calculate the digits as a whole-number multiplication first: 768 multiplied by 25.', expression: '768 × 25', rows: ['768', '×25', '19200'] },
  { label: 'Count decimal places', narration: 'The factors have two decimal places and one decimal place: three altogether.', expression: '7.68 × 2.5', rows: ['7.68  → 2 places', '2.5   → 1 place'], markers: ['2 + 1 = 3 decimal places'] },
  { label: 'Place the decimal point', narration: 'Count three places from the right in 19200. The product is 19.200.', expression: '19200 → 19.200', rows: ['19.200'], markers: ['MULTIPLY → COUNT → PLACE'], durationMs: 3000 },
  { label: 'Simplify at the end', narration: 'The final two zeroes are not needed, so 19.200 is 19.2.', expression: '7.68 × 2.5 = 19.2', rows: ['19.200 = 19.2'] },
]

const divisionStages: DecimalOperationStage[] = [
  { label: 'Look at the divisor', narration: 'The divisor is 1.2. Make it a whole number before dividing.', expression: '7.488 ÷ 1.2', rows: ['dividend 7.488', 'divisor  1.2'] },
  { label: 'Choose the scale', narration: 'Multiplying 1.2 by 10 makes 12.', expression: '1.2 × 10 = 12', rows: ['1.2 → 12'], markers: ['×10'] },
  { label: 'Move both together', narration: 'Apply the same multiplication to the dividend: 7.488 becomes 74.88.', expression: '(7.488 × 10) ÷ (1.2 × 10)', rows: ['7.488 → 74.88', '1.2   → 12'], markers: ['both numbers ×10'], durationMs: 3200 },
  { label: 'Lock the equivalent calculation', narration: 'The equivalent calculation is 74.88 divided by 12. Its value is unchanged.', expression: '74.88 ÷ 12', rows: ['7.488 ÷ 1.2', '= 74.88 ÷ 12'], markers: ['same quotient'] },
  { label: 'Divide by 12', narration: 'Lesson 6 supplies this two-digit division step: use multiples of 12 to build the quotient.', expression: '74.88 ÷ 12', rows: ['12 × 6 = 72', '12 × 0.2 = 2.4', '12 × 0.04 = 0.48'], markers: ['6 + 0.2 + 0.04'] },
  { label: 'Read the quotient', narration: 'Add the quotient parts. The answer is 6.24.', expression: '7.488 ÷ 1.2 = 6.24', rows: ['74.88 ÷ 12 = 6.24'], markers: ['MAKE IT WHOLE → DO THE SAME → DIVIDE'] },
]

const states: LearningState[] = [
  { id: 'L6-START', microSkillId: 'decimal-addition', phase: 'hook', teachingIntent: 'Connect all four operations to place value.', content: { eyebrow: 'Lesson 6', title: 'Decimals are built from place value', body: 'Digits after the decimal point represent tenths, hundredths, thousandths and smaller places.', prompt: 'In every operation, keep track of what each digit is worth.' }, component: { type: 'decimalOperation', props: { kind: 'place-value', expression: '4.5 = 4.50 = 4.500', rows: ['ones . tenths hundredths thousandths'], result: 'Same value' } }, interaction: { type: 'continue' }, transition: { onComplete: 'L6-A-WORKED' }, completionCondition: 'Learner continues.', analytics: { eventName: 'lesson_6_start' } },
  worked('L6-A-WORKED', 'decimal-addition', 'Add decimals: line up the points', 'Predict each change, then use Next to reveal it.', 'add', '985.4 + 81.767', additionStages, '985.4 + 81.767 = 1067.167', 'L6-A-ALIGN'),
  { id: 'L6-A-ALIGN', microSkillId: 'decimal-addition', phase: 'guided', teachingIntent: 'Diagnose final-digit alignment.', content: { title: 'Which setup is correct?', prompt: 'Choose the layout that lines up equal place values.' }, component: { type: 'decimalOperation', props: { kind: 'add', expression: '17.6 + 4.829', rows: ['17.600', '+4.829'] } }, interaction: { type: 'select', options: [
    { id: 'points', label: '17.600 + 4.829', detail: 'Decimal points aligned' },
    { id: 'ends', label: '17.6 + 4.829', detail: 'Final digits aligned', misconceptionId: 'DEC-ALIGNS-FINAL-DIGITS', feedback: 'Aligning the final digits puts tenths under thousandths. Line up the decimal points.' },
    { id: 'moved', label: '176.00 + 4.829', detail: 'First point moved', misconceptionId: 'DEC-MOVES-POINT', feedback: 'Moving a decimal point changes the value. Add zeroes on the right instead.' },
  ], correctAnswer: 'points', acceptanceRule: 'exact' }, feedback: { correct: { message: 'Correct. Ones, tenths and hundredths now share columns.' }, incorrect: { message: 'Line up the decimal points and use trailing zeroes as place holders.' } }, transition: { onComplete: 'L6-A1' }, completionCondition: 'Learner selects the aligned setup.', analytics: { misconceptionId: 'DEC-ALIGNMENT', eventName: 'lesson_6_add_alignment' } },
  question({ id: 'L6-A1', skill: 'decimal-addition', phase: 'guided', title: 'Add 4.7 + 3.6', prompt: 'Line up the decimal points.', kind: 'add', expression: '4.7 + 3.6', rows: ['4.7', '+3.6'], answer: 8.3, correct: 'Correct. Seven tenths plus six tenths requires one carry.', incorrect: '7 + 6 = 13 tenths: write 3 tenths and carry 1 one. The answer is 8.3.', next: 'L6-A2', misconception: 'DEC-ADD-CARRY' }),
  question({ id: 'L6-A2', skill: 'decimal-addition', title: 'Add 8.42 + 5.31', kind: 'add', expression: '8.42 + 5.31', rows: ['8.42', '+5.31'], answer: 13.73, correct: 'Correct. The sum is 13.73.', incorrect: 'Keep hundredths under hundredths and tenths under tenths. The sum is 13.73.', next: 'L6-A3', misconception: 'DEC-ADD-PLACE-VALUE' }),
  question({ id: 'L6-A3', skill: 'decimal-addition', title: 'Add 17.6 + 4.829', prompt: 'You may write 17.6 as 17.600.', kind: 'add', expression: '17.600 + 4.829', rows: ['17.600', '+4.829'], answer: 22.429, correct: 'Correct. The sum is 22.429.', incorrect: 'Align the points: 17.600 + 4.829 = 22.429.', next: 'L6-A4', misconception: 'DEC-ADD-MISSING-ZEROES' }),
  question({ id: 'L6-A4', skill: 'decimal-addition', title: 'Add 284.73 + 56.908', kind: 'add', expression: '284.730 + 56.908', rows: ['284.730', '+56.908'], answer: 341.638, correct: 'Correct. The sum is 341.638.', incorrect: 'Write 284.73 as 284.730, then add each aligned column. The answer is 341.638.', next: 'L6-S-WORKED', misconception: 'DEC-ADD-INDEPENDENT' }),
  worked('L6-S-WORKED', 'decimal-subtraction', 'Subtract decimals: keep the columns fixed', 'Watch the place-holding zero and each regroup.', 'subtract', '567.63 − 92.478', subtractionStages, '567.630 − 92.478 = 475.152', 'L6-S-ZERO'),
  { id: 'L6-S-ZERO', microSkillId: 'decimal-subtraction', phase: 'guided', teachingIntent: 'Treat an absent decimal digit as zero.', content: { title: 'What belongs in the empty thousandths place?', prompt: 'Complete 32.5 so it can be aligned with 7.286.' }, component: { type: 'decimalOperation', props: { kind: 'subtract', expression: '32.5__ − 7.286', rows: ['32.5__', '−7.286'] } }, interaction: { type: 'select', options: [
    { id: 'zeros', label: '32.500', detail: 'Add two trailing zeroes' },
    { id: 'blank', label: 'Leave it blank', detail: 'Treat the places as absent', misconceptionId: 'DEC-ABSENT-NOT-ZERO', feedback: 'Empty decimal places still have a value of zero. Write 32.500.' },
    { id: 'front', label: '032.5', detail: 'Add a zero at the front', misconceptionId: 'DEC-ZERO-WRONG-SIDE', feedback: 'A zero at the front does not fill the hundredths or thousandths places.' },
  ], correctAnswer: 'zeros', acceptanceRule: 'exact' }, feedback: { correct: { message: 'Correct. 32.5 and 32.500 have the same value.' }, incorrect: { message: 'Add trailing zeroes after the final decimal digit: 32.500.' } }, transition: { onComplete: 'L6-S1' }, completionCondition: 'Learner selects 32.500.', analytics: { misconceptionId: 'DEC-PLACEHOLDER-ZERO', eventName: 'lesson_6_subtract_zero' } },
  question({ id: 'L6-S1', skill: 'decimal-subtraction', phase: 'guided', title: 'Subtract 9.8 − 4.3', kind: 'subtract', expression: '9.8 − 4.3', rows: ['9.8', '−4.3'], answer: 5.5, correct: 'Correct. The difference is 5.5.', incorrect: 'Eight tenths minus three tenths is five tenths. The answer is 5.5.', next: 'L6-S2', misconception: 'DEC-SUB-BASIC' }),
  question({ id: 'L6-S2', skill: 'decimal-subtraction', title: 'Subtract 15.72 − 8.41', kind: 'subtract', expression: '15.72 − 8.41', rows: ['15.72', '−8.41'], answer: 7.31, correct: 'Correct. The difference is 7.31.', incorrect: 'Subtract each aligned column from right to left. The answer is 7.31.', next: 'L6-S3', misconception: 'DEC-SUB-ORDER' }),
  question({ id: 'L6-S3', skill: 'decimal-subtraction', title: 'Subtract 32.5 − 7.286', prompt: 'Use 32.500 for the top number.', kind: 'subtract', expression: '32.500 − 7.286', rows: ['32.500', '−7.286'], answer: 25.214, correct: 'Correct. The difference is 25.214.', incorrect: 'Regroup from right to left in 32.500. The answer is 25.214.', next: 'L6-S4', misconception: 'DEC-SUB-ACROSS-ZERO' }),
  question({ id: 'L6-S4', skill: 'decimal-subtraction', title: 'Subtract 503.04 − 87.659', prompt: 'First write 503.040.', kind: 'subtract', expression: '503.040 − 87.659', rows: ['503.040', '−87.659'], answer: 415.381, correct: 'Correct. The difference is 415.381.', incorrect: 'Keep the decimal column fixed and regroup one place at a time. The answer is 415.381.', next: 'L6-M-WORKED', misconception: 'DEC-SUB-INDEPENDENT' }),
  worked('L6-M-WORKED', 'decimal-multiplication', 'Multiply decimals: calculate, count, place', 'Do the whole-number multiplication first, then restore place value.', 'multiply', '7.68 × 2.5', multiplicationStages, '7.68 × 2.5 = 19.2', 'L6-M-COUNT'),
  { id: 'L6-M-COUNT', microSkillId: 'decimal-multiplication', phase: 'guided', teachingIntent: 'Count decimal places across both factors.', content: { title: 'How many decimal places altogether?', prompt: 'Count them in 5.7 × 6.32.' }, component: { type: 'decimalOperation', props: { kind: 'multiply', expression: '5.7 × 6.32', rows: ['5.7 → 1 place', '6.32 → 2 places'] } }, interaction: { type: 'select', options: [
    { id: '3', label: '3', detail: '1 + 2 decimal places' },
    { id: '2', label: '2', detail: 'Counted only 6.32', misconceptionId: 'DEC-COUNTS-ONE-FACTOR', feedback: 'Count decimal places in both factors: 1 + 2 = 3.' },
    { id: '5', label: '5', detail: 'Counted all digits', misconceptionId: 'DEC-COUNTS-DIGITS', feedback: 'Count places after the decimal points, not every digit.' },
  ], correctAnswer: '3', acceptanceRule: 'exact' }, feedback: { correct: { message: 'Correct. The product needs three decimal places.' }, incorrect: { message: 'There is one decimal place in 5.7 and two in 6.32: three altogether.' } }, transition: { onComplete: 'L6-M1' }, completionCondition: 'Learner selects three.', analytics: { misconceptionId: 'DEC-MULTIPLY-PLACE-COUNT', eventName: 'lesson_6_multiply_count' } },
  question({ id: 'L6-M1', skill: 'decimal-multiplication', phase: 'guided', title: 'Multiply 3.2 × 4.5', prompt: '32 × 45 = 1440. Place two decimal places.', kind: 'multiply', expression: '3.2 × 4.5', rows: ['32 × 45 = 1440', '2 decimal places'], answer: 14.4, correct: 'Correct. 14.40 is 14.4.', incorrect: 'Count two places from the right in 1440: 14.40, which is 14.4.', next: 'L6-M2', misconception: 'DEC-MULTIPLY-POINT' }),
  question({ id: 'L6-M2', skill: 'decimal-multiplication', title: 'Multiply 6.4 × 2.7', prompt: '64 × 27 = 1728.', kind: 'multiply', expression: '6.4 × 2.7', rows: ['64 × 27 = 1728', '2 decimal places'], answer: 17.28, correct: 'Correct. The product is 17.28.', incorrect: 'The factors have two decimal places altogether. 1728 becomes 17.28.', next: 'L6-M3', misconception: 'DEC-MULTIPLY-WHOLE-PRODUCT' }),
  question({ id: 'L6-M3', skill: 'decimal-multiplication', title: 'Multiply 3.25 × 1.4', prompt: '325 × 14 = 4550.', kind: 'multiply', expression: '3.25 × 1.4', rows: ['325 × 14 = 4550', '3 decimal places'], answer: 4.55, correct: 'Correct. 4.550 is 4.55.', incorrect: 'Count three decimal places from the right: 4.550 = 4.55.', next: 'L6-M4', misconception: 'DEC-MULTIPLY-TRAILING-ZERO' }),
  question({ id: 'L6-M4', skill: 'decimal-multiplication', title: 'Multiply 4.08 × 2.35', prompt: '408 × 235 = 95880.', kind: 'multiply', expression: '4.08 × 2.35', rows: ['408 × 235 = 95880', '4 decimal places'], answer: 9.588, correct: 'Correct. 9.5880 is 9.588.', incorrect: 'There are four decimal places altogether. 95880 becomes 9.5880 = 9.588.', next: 'L6-D-WORKED', misconception: 'DEC-MULTIPLY-INDEPENDENT' }),
  worked('L6-D-WORKED', 'decimal-division', 'Divide decimals: move both numbers together', 'This sequence includes the two-digit divisor support needed here.', 'divide', '7.488 ÷ 1.2', divisionStages, '7.488 ÷ 1.2 = 6.24', 'L6-D-SAME'),
  { id: 'L6-D-SAME', microSkillId: 'decimal-division', phase: 'guided', teachingIntent: 'Apply the same scale factor to both numbers.', content: { title: 'Which equivalent calculation is correct?', prompt: 'Make 0.12 a whole-number divisor in 4.68 ÷ 0.12.' }, component: { type: 'decimalOperation', props: { kind: 'divide', expression: '4.68 ÷ 0.12', rows: ['make 0.12 whole', 'move both together'] } }, interaction: { type: 'select', options: [
    { id: 'both100', label: '468 ÷ 12', detail: 'Both numbers ×100' },
    { id: 'divisorOnly', label: '4.68 ÷ 12', detail: 'Only the divisor moved', misconceptionId: 'DEC-DIVIDE-MOVES-ONE', feedback: 'Multiplying only the divisor changes the quotient. Multiply both numbers by 100.' },
    { id: 'both10', label: '46.8 ÷ 1.2', detail: 'Both numbers ×10', misconceptionId: 'DEC-DIVIDE-NOT-WHOLE', feedback: 'Both moved together, but the divisor is still decimal. Use ×100.' },
  ], correctAnswer: 'both100', acceptanceRule: 'exact' }, feedback: { correct: { message: 'Correct. Multiplying both numbers by 100 keeps the quotient unchanged.' }, incorrect: { message: 'Make the divisor whole and apply exactly the same multiplication to the dividend.' } }, transition: { onComplete: 'L6-D1' }, completionCondition: 'Learner selects 468 ÷ 12.', analytics: { misconceptionId: 'DEC-DIVIDE-EQUIVALENCE', eventName: 'lesson_6_divide_equivalent' } },
  question({ id: 'L6-D1', skill: 'decimal-division', phase: 'guided', title: 'Divide 8.4 ÷ 1.2', prompt: 'First transform it to 84 ÷ 12.', kind: 'divide', expression: '8.4 ÷ 1.2 = 84 ÷ 12', rows: ['12 × 7 = 84'], answer: 7, correct: 'Correct. Both numbers moved by ×10, and 84 ÷ 12 = 7.', incorrect: 'Multiply both by 10, then use 12 × 7 = 84. The answer is 7.', next: 'L6-D2', misconception: 'DEC-DIVIDE-BY-12' }),
  question({ id: 'L6-D2', skill: 'decimal-division', title: 'Divide 9.45 ÷ 1.5', prompt: 'Transform it to 94.5 ÷ 15.', kind: 'divide', expression: '9.45 ÷ 1.5 = 94.5 ÷ 15', rows: ['15 × 6 = 90', '15 × 0.3 = 4.5'], answer: 6.3, correct: 'Correct. 6 + 0.3 = 6.3.', incorrect: '94.5 = 90 + 4.5. Divide each part by 15: 6 + 0.3 = 6.3.', next: 'L6-D3', misconception: 'DEC-DIVIDE-TWO-DIGIT-SUPPORT' }),
  question({ id: 'L6-D3', skill: 'decimal-division', title: 'Divide 6.72 ÷ 0.8', prompt: 'Transform it to 67.2 ÷ 8.', kind: 'divide', expression: '6.72 ÷ 0.8 = 67.2 ÷ 8', rows: ['8 × 8 = 64', '8 × 0.4 = 3.2'], answer: 8.4, correct: 'Correct. 67.2 ÷ 8 = 8.4.', incorrect: 'Multiply both numbers by 10. Then 67.2 ÷ 8 = 8.4.', next: 'L6-D4', misconception: 'DEC-DIVIDE-ONE-DIGIT' }),
  question({ id: 'L6-D4', skill: 'decimal-division', title: 'Divide 4.68 ÷ 0.12', prompt: 'Transform it to 468 ÷ 12.', kind: 'divide', expression: '4.68 ÷ 0.12 = 468 ÷ 12', rows: ['12 × 39 = 468'], answer: 39, correct: 'Correct. Both numbers moved by ×100, and 468 ÷ 12 = 39.', incorrect: 'Multiply both by 100, then use 12 × 39 = 468. The answer is 39.', next: 'L6-R1', misconception: 'DEC-DIVIDE-INDEPENDENT' }),
  question({ id: 'L6-R1', skill: 'mixed', phase: 'mastery', title: 'Retrieval: add 6.436 + 8.992', kind: 'add', expression: '6.436 + 8.992', rows: ['6.436', '+8.992'], answer: 15.428, correct: 'Correct. The sum is 15.428.', incorrect: 'Line up the points and carry by columns. The answer is 15.428.', next: 'L6-R2', misconception: 'DEC-RETRIEVAL-ADD' }),
  question({ id: 'L6-R2', skill: 'mixed', phase: 'mastery', title: 'Retrieval: subtract 62.059 − 5.118', kind: 'subtract', expression: '62.059 − 5.118', rows: ['62.059', '−5.118'], answer: 56.941, correct: 'Correct. The difference is 56.941.', incorrect: 'Keep the columns fixed and regroup where needed. The answer is 56.941.', next: 'L6-R3', misconception: 'DEC-RETRIEVAL-SUBTRACT' }),
  question({ id: 'L6-R3', skill: 'mixed', phase: 'transfer', title: 'Transfer: a ribbon is 5.7 m long', prompt: 'You use 1.85 m. How many metres remain?', kind: 'subtract', expression: '5.70 − 1.85', rows: ['5.70', '−1.85'], answer: 3.85, correct: 'Correct. 3.85 m remains.', incorrect: 'Write 5.7 as 5.70, then subtract. 3.85 m remains.', next: 'L6-R4', misconception: 'DEC-TRANSFER-MEASURE' }),
  question({ id: 'L6-R4', skill: 'mixed', phase: 'transfer', title: 'Transfer: share 12.6 litres equally', prompt: 'Each container holds 0.6 litres. How many containers are filled?', kind: 'divide', expression: '12.6 ÷ 0.6 = 126 ÷ 6', rows: ['both numbers ×10'], answer: 21, correct: 'Correct. 21 containers are filled.', incorrect: 'Multiply both numbers by 10: 126 ÷ 6 = 21.', next: 'L6-END', misconception: 'DEC-TRANSFER-DIVIDE' }),
  { id: 'L6-END', microSkillId: 'mixed', phase: 'mastery', teachingIntent: 'Retrieve the four memory prompts.', content: { eyebrow: 'Lesson complete', title: 'Place value controls every decimal operation', body: 'Add and subtract: line up. Multiply: calculate, count, place. Divide: make it whole, do the same, divide.', prompt: 'You can now choose and carry out all four decimal operations.' }, component: { type: 'decimalOperation', props: { kind: 'place-value', expression: 'LINE UP · COUNT · MOVE BOTH', rows: ['+ −  line up points', '×    count places', '÷    move both together'], result: 'Decimals mastered' } }, interaction: { type: 'continue' }, transition: {}, completionCondition: 'Learner finishes the lesson.', analytics: { eventName: 'lesson_6_complete' } },
]

export const decimalsLesson: LessonDefinition = { id: 'lesson-6-decimals', title: 'Decimals', level: 'GCSE Foundation', goal: 'Add, subtract, multiply and divide decimals using place value.', states }

export const decimalMicroSkillLabels: Partial<Record<MicroSkillId, string>> = {
  'decimal-addition': 'Add', 'decimal-subtraction': 'Subtract', 'decimal-multiplication': 'Multiply', 'decimal-division': 'Divide', mixed: 'Recall',
}
