import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { warmingFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.7.3.3 Land use: building, quarrying, farming, dumping waste, destroying peat bogs; 4.7.3.4 Deforestation: reasons and effects; 4.7.3.5 Global warming: carbon dioxide and methane, biological consequences' }
const a = author('B-LAND-AND-CLIMATE', ['4.7.3.3', '4.7.3.4', '4.7.3.5'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const warmingSections = [
  { id: 'B52-01', label: 'Start here', detail: 'Trees and carbon dioxide' },
  { id: 'B52-02', label: 'What keeps the Earth warm?', detail: 'Greenhouse gases and global warming' },
  { id: 'B52-05', label: 'What could global warming do?', detail: 'Seas, species and migration' },
  { id: 'B52-08', label: 'How do humans use land?', detail: 'Building, farming and peat bogs' },
  { id: 'B52-11', label: 'Why is cutting down forests a problem?', detail: 'Deforestation' },
  { id: 'B52-14', label: 'On your own', detail: 'A seaside town, energy arrows and a bird survey' },
]

const states: ScienceState[] = [
  { ...a.choice('B52-01', 'Trees take carbon dioxide out of the air. Which process do they use to do this?', ['Respiration', 'Photosynthesis', 'Decay', 'Burning'], 1, 'Which process makes glucose in the leaves?', ['Respiration, decay and burning all put carbon dioxide into the air.', 'Plants take it out of the air by photosynthesis. You met this in the carbon cycle.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B52-02', 'What keeps the Earth warm?'),
  a.choice('B52-03', 'Why would the Earth be very cold without greenhouse gases?', ['Much more of the energy would be lost into space', 'No energy from the Sun would reach the Earth', 'The Earth would move further from the Sun'], 0, 'What do greenhouse gases do to energy leaving the Earth?', ['Greenhouse gases trap energy, so not all of it escapes into space.', 'Without them, much more energy would be lost into space, so the Earth would be very cold.']),
  a.choice('B52-04', 'Which two greenhouse gases are increasing in the atmosphere?', ['Oxygen and nitrogen', 'Carbon dioxide and methane', 'Oxygen and hydrogen'], 1, 'Which gas is released when fossil fuels burn?', ['Oxygen, nitrogen and hydrogen are not the gases causing global warming.', 'Carbon dioxide and methane are greenhouse gases, and the levels of both are increasing.']),
  t('B52-05', 'What could global warming do?'),
  a.choice('B52-06', 'Why could global warming make low-lying land flood more often?', ['The land sinks as it warms up', 'Rain only falls on mountains', 'Ice melts and seawater expands, so the sea level rises'], 2, 'What happens to ice and seawater when it gets warmer?', ['Higher temperatures melt ice and make seawater expand.', 'So the sea level rises, and low-lying land floods more often.']),
  a.choice('B52-07', 'A plant only grows in cool conditions near a mountain top. The mountain warms up. What most likely happens to its area?', ['Its area gets smaller', 'Its area gets bigger', 'It spreads down the mountain'], 0, 'Where on the mountain will it still be cool enough?', ['As the mountain warms, only the highest parts stay cool enough for the plant.', 'So it is left with a smaller area to live in. Its distribution changes.']),
  t('B52-08', 'How do humans use land?'),
  a.choice('B52-09', 'A meadow is covered with a new housing estate. Why does this reduce biodiversity there?', ['The houses take in carbon dioxide', 'More food grows on the land', 'There is less land left for other organisms to live on'], 2, 'Where do the meadow’s plants and animals live now?', ['Building takes the land that the meadow’s plants and animals lived on.', 'So there is less land left for other organisms, and biodiversity falls.']),
  a.choice('B52-10', 'Why does draining a peat bog add carbon dioxide to the air?', ['Microorganisms can now break down the peat, and they respire', 'The peat starts to photosynthesise', 'The water in the bog turns into carbon dioxide'], 0, 'What stopped the dead plants rotting in the wet bog?', ['In a wet, acidic bog, microorganisms cannot break down dead plants fully.', 'Once it is drained, they break down the peat and release carbon dioxide as they respire.']),
  t('B52-11', 'Why is cutting down forests a problem?'),
  a.choice('B52-12', 'Give one reason why tropical rainforests are cut down.', ['To make the air cleaner', 'To clear land for farming, such as growing rice', 'To increase biodiversity'], 1, 'What is the cleared land used for?', ['Cutting down forests does not clean the air or increase biodiversity.', 'Forests are cleared for farming, such as cattle or rice, and to grow crops for biofuels.']),
  a.choice('B52-13', 'Look at the numbered arrows. Which one shows carbon dioxide released by microorganisms feeding on dead wood?', ['Arrow 1', 'Arrow 2', 'Arrow 3'], 1, 'Find the arrow that starts at the fallen logs.', ['Arrow 1 rises from the fire, and arrow 3 carries carbon dioxide down into the trees.', 'Arrow 2 rises from the microorganisms on the logs, which release carbon dioxide as they respire.'], 'understanding', false, 'earth-forest-question'),
  a.choice('B52-14', 'A town is built on flat land just above the sea. Why could global warming be a problem for it?', ['Rising sea levels could flood the town more often', 'The sea could freeze over more often', 'The town would have fewer greenhouse gases'], 0, 'What is happening to the sea level?', ['Global warming melts ice and makes seawater expand, so the sea level rises.', 'The town is on low-lying land, so it is likely to flood more often.'], 'application', true),
  a.choice('B52-15', 'Look at the numbered arrows. Which one shows energy that gases in the atmosphere stop from escaping into space?', ['Arrow 1', 'Arrow 2', 'Arrow 3'], 2, 'Which arrow from the Earth does not reach space?', ['Arrow 1 is energy arriving from the Sun, and arrow 2 escapes into space.', 'Arrow 3 is turned back by gases in the atmosphere, so this energy is trapped and keeps the Earth warm.'], 'understanding', true, 'earth-green-question'),
  a.choice('B52-16', 'Students counted the kinds of bird in three areas of one forest. Which conclusion fits their results?', ['Cutting down forests makes every bird species extinct', 'Every farm has 8 kinds of bird', 'The cleared area had the most kinds of bird', 'In this survey, fewer kinds of bird were found where more forest was cleared'], 3, 'What do these three counts show, and no more?', ['They found 42 kinds in untouched forest, 25 where it was partly cleared and 8 where it was cleared for farming.', 'One survey cannot show what happens in every forest, and some birds were still found. In this survey, fewer kinds were found where more forest was cleared.'], 'dataInterpretation', true, 'earth-bird-data'),
  a.written('B52-17', 'Explain how cutting down and burning a large area of rainforest can add to global warming.', 'Think about photosynthesis, burning, decay, and what carbon dioxide does in the atmosphere.', 'Trees take in carbon dioxide for photosynthesis, so with fewer trees less carbon dioxide is removed from the air, and less carbon is locked up in wood. Burning the trees releases carbon dioxide. Microorganisms feeding on the dead wood release carbon dioxide as they respire. So the level of carbon dioxide in the atmosphere rises. Carbon dioxide is a greenhouse gas, so more energy is trapped and the Earth heats up.', ['Fewer trees means less carbon dioxide is taken in for photosynthesis.', 'Less carbon is locked up in wood.', 'Burning the trees releases carbon dioxide.', 'Microorganisms decaying the dead wood release carbon dioxide as they respire.', 'Carbon dioxide is a greenhouse gas, so more energy is trapped and the Earth warms.'], ['Saying trees give out carbon dioxide by photosynthesis.', 'Saying cutting down trees makes a hole in the atmosphere that lets heat in.', 'Saying global warming is caused by oxygen.']),
]

export const lesson52: ScienceLesson = {
  id: 'B-ECO-052-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Global warming, deforestation and land use', prerequisites: ['B-MATERIAL-CYCLES', 'B-BIODIVERSITY'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
