import type { TeachingFrame } from '../teachingFrame'

// Why the Earth is warm first, then what extra warming could do, then how land use and cutting down forests add carbon dioxide and cut biodiversity.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const warmingFrames: Record<string, TeachingFrame[]> = {
  'B52-02': [
    f('Energy from the Sun', 'The Sun warms the Earth, and the Earth gives off energy.', 'Sun → Earth → back towards space', 'Energy from the Sun reaches the Earth and warms its surface. The warm Earth then gives off energy back towards space. The Earth is wrapped in a layer of gases. This layer is called the atmosphere.', 'earth-green-sun'),
    f('Trapped by gases', 'Some gases stop energy escaping into space.', 'energy trapped → Earth stays warm', 'Some gases in the atmosphere trap energy, so not all of it is lost into space. This keeps the Earth warm. Gases that do this are called greenhouse gases. Without them, the Earth would be very cold.', 'earth-green-trap'),
    f('More greenhouse gases', 'Levels of carbon dioxide and methane are rising.', 'more gas → more energy trapped', 'Carbon dioxide is a greenhouse gas. Another one is a gas called methane. The levels of both gases in the atmosphere are increasing. Burning fossil fuels is one cause, as you saw in the carbon cycle. More of these gases trap more energy.', 'earth-green-more'),
    f('Global warming', 'The Earth is getting warmer.', 'rising gas levels → Earth heats up', 'Because more energy is trapped, the Earth is heating up. This is called global warming. Most scientists agree that human activity has caused most of the recent warming. They are still working out exactly what the effects will be.', 'earth-green-warming'),
  ],
  'B52-05': [
    f('Rising seas', 'Sea levels rise, so low land floods more often.', 'warmer → ice melts, seawater expands → sea rises', 'Higher temperatures make ice melt and make seawater expand. So the sea level rises. Land that is only just above the sea is called low-lying land. It floods more often as the sea rises, so habitats and homes there could be lost.', 'earth-effect-sea'),
    f('Species on the move', 'Some species spread, and others have less room.', 'warmer → warm-lovers spread, cool-lovers squeezed', 'Global warming is changing the temperature and rainfall in some areas. Species that do well in warm conditions can spread into new areas. Species that need cooler conditions are left with a smaller area. Where a species is found is called its distribution.', 'earth-effect-spread'),
    f('Some species lost', 'Some species may not survive, so biodiversity falls.', 'cannot cope → extinct → less biodiversity', 'Some species may not be able to survive the change in climate. They could die out completely. This is called extinction. Each species lost reduces biodiversity.', 'earth-effect-extinct'),
    f('Changing journeys', 'Some animals are changing where they migrate.', 'warmer north → birds fly further north', 'Some animals travel to different places at different times of year. This is called migration. As areas further north get warmer, some birds may now migrate further north than before.', 'earth-effect-migrate'),
    f('Put it together', 'Global warming could have several serious effects.', 'flooding, spreading, extinction, migration', 'So global warming could cause flooding, change where species live, reduce biodiversity and change migration patterns. Scientists are still working out how large each effect will be.', 'earth-effect-all'),
  ],
  'B52-08': [
    f('Building and quarrying', 'People build on land and dig rock out of it.', 'houses and roads, rock to build with', 'Humans use land to build houses, roads and factories. They also dig rock out of the ground to build with. Digging rock out like this is called quarrying.', 'earth-land-build'),
    f('Farming and waste', 'Land is also used for farms and for dumping waste.', 'fields for food, holes for rubbish', 'Large areas of land are used for farming, to grow crops and keep animals. Land is also used for dumping waste in landfill sites. You met landfill when you learned about pollution.', 'earth-land-farm'),
    f('Less land for other species', 'Each use leaves less land for other organisms.', 'more land for us → less for other species', 'Every time people use land like this, there is less land left for other organisms. Some uses also harm the environment, for example by causing pollution. So biodiversity can fall.', 'earth-land-less'),
    f('Peat bogs', 'In a bog, dead plants build up to form peat.', 'wet, acidic → plants only partly rot → peat', 'Some land is bog, which is wet and acidic. When bog plants die, microorganisms cannot break them down fully there. The partly rotted plants build up over many years. This is called peat, and the carbon from the plants is stored in it.', 'earth-bog-store'),
    f('Draining bogs', 'Destroying bogs releases carbon dioxide and harms wildlife.', 'drained or burnt peat → carbon dioxide', 'Bogs are drained so peat can be dug up and sold as garden compost or as fuel. Then microorganisms can break the peat down, and they release carbon dioxide as they respire. Burning peat releases carbon dioxide too. Destroying a bog also removes a habitat, so biodiversity falls.', 'earth-bog-drain'),
  ],
  'B52-11': [
    f('Clearing forests', 'Forests are cut down to make space for farms.', 'trees cut → land for cattle and crops', 'Cutting down forests is called deforestation. Often the land is cleared for farming, such as keeping cattle or growing rice, to provide more food. It often happens on a large scale in tropical rainforests.', 'earth-forest-clear'),
    f('Crops for fuel', 'Some land is cleared to grow crops for fuel.', 'crops → fuel', 'Forests are also cleared to grow crops that are made into fuel. Fuels made from crops like this are called biofuels.', 'earth-forest-fuel'),
    f('Less carbon dioxide taken in', 'Fewer trees take in less carbon dioxide.', 'fewer trees → less photosynthesis', 'Trees take in carbon dioxide from the air for photosynthesis. Some of the carbon is locked up in their wood for many years. So when trees are cut down, less carbon dioxide is removed from the air, and less carbon is locked up.', 'earth-forest-less'),
    f('More carbon dioxide released', 'Burning and decay release carbon dioxide.', 'burning and decay → carbon dioxide in the air', 'Trees are often burnt to clear the land, and this releases carbon dioxide. Microorganisms also feed on the dead wood that is left behind. They release carbon dioxide as they respire, just as in the carbon cycle.', 'earth-forest-release'),
    f('Fewer species', 'Forests have high biodiversity, so a lot can be lost.', 'forest gone → habitats gone → species lost', 'Forests are home to many species of plants and animals, so they have high biodiversity. When a forest is destroyed, those species lose the place where they live. Some may become extinct, so biodiversity falls.', 'earth-forest-species'),
    f('Put it together', 'Deforestation adds carbon dioxide to the air and reduces biodiversity.', 'less taken in + more released → more global warming', 'After deforestation, less carbon dioxide is taken in and more is released. So the level of carbon dioxide in the air rises, and this adds to global warming. Deforestation also reduces biodiversity.', 'earth-forest-all'),
  ],
}
