import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { breedingFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.6.2.3 Selective breeding: process, uses and inbreeding; 4.6.2.4 Genetic engineering: GM crops, insulin, gene therapy, benefits and concerns' }
const a = author('B-BREEDING-GM', ['4.6.2.3', '4.6.2.4'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const breedingSections = [
  { id: 'B44-01', label: 'Start here', detail: 'Where did all the dog breeds come from?' },
  { id: 'B44-02', label: 'Choosing the parents', detail: 'Selective breeding, step by step' },
  { id: 'B44-05', label: 'What is the downside?', detail: 'Inbreeding and fewer alleles' },
  { id: 'B44-07', label: 'Changing the DNA', detail: 'Genetic engineering: insulin, crops, gene therapy' },
  { id: 'B44-10', label: 'Weighing it up', detail: 'Benefits and concerns' },
  { id: 'B44-12', label: 'On your own', detail: 'Hens, insulin steps, a maize trial and a dog breed' },
]

const states: ScienceState[] = [
  { ...a.choice('B44-01', 'Poodles, sheepdogs and dachshunds are all one species. How did so many different breeds come about?', ['People chose which dogs to breed, over many generations', 'Each dog changed to suit its owner', 'They caught different diseases', 'Wild dogs split into new species'], 0, 'Who decided which dogs had puppies together?', ['A dog cannot change its genes to suit its owner, and the breeds are still one species.', 'People chose which dogs to breed, over many generations.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B44-02', 'Choosing the parents'),
  a.choice('B44-03', 'In selective breeding, what decides which individuals breed?', ['The environment', 'Chance', 'People', 'Predators'], 2, 'Why is it also called artificial selection?', ['In natural selection, the environment decides who survives to breed.', 'In selective breeding, people choose.']),
  a.choice('B44-04', 'A grower wants wheat that is not killed by a disease. What should she do first?', ['Spray all her wheat with medicine', 'Choose the plants that best resist the disease, and breed them together', 'Breed the tallest plants'], 1, 'Pick parents with the feature you want.', ['Selective breeding starts by choosing parents that already have the feature.', 'She should breed together the plants that best resist the disease.']),
  t('B44-05', 'What is the downside?'),
  a.choice('B44-06', 'Why can a new disease wipe out a whole field of a selectively bred crop?', ['The plants grow too fast', 'The plants are too far apart', 'Selective breeding causes the disease', 'The plants have few different alleles, so few or none can resist it'], 3, 'Think about alleles in an inbred population.', ['Inbreeding reduces the number of different alleles.', 'So it is unlikely any plant has alleles to resist the new disease, and they are all affected.']),
  t('B44-07', 'Changing the DNA'),
  a.choice('B44-08', 'What is genetic engineering?', ['Cutting a gene out of one organism and putting it into another organism’s cells', 'Choosing which animals breed together', 'Growing plants in a laboratory', 'Giving animals antibiotics'], 0, 'What happens to the gene?', ['Choosing which animals breed is selective breeding.', 'Genetic engineering moves a gene from one organism into another’s cells.']),
  a.choice('B44-09', 'Why might a farmer grow a GM crop that is resistant to herbicides?', ['It grows without any water', 'Insects cannot eat it', 'She can spray to kill weeds without harming the crop', 'It never needs to be harvested'], 2, 'What do herbicides kill?', ['Herbicides kill plants, including weeds.', 'A herbicide-resistant crop survives the spray, so she can kill the weeds without harming it.']),
  t('B44-10', 'Weighing it up'),
  a.choice('B44-11', 'Which of these is a concern about GM animals?', ['They always grow faster', 'Some develop health problems later in life', 'They make human insulin'], 1, 'Think about effects that are hard to predict.', ['Changing an animal’s DNA can have effects that are hard to predict.', 'Some GM animals develop health problems later in life.']),
  a.choice('B44-12', 'A farmer wants hens that lay more eggs. Which plan is selective breeding?', ['Feed the hens more so they lay more eggs, then breed them', 'Put a gene from another species into the hens', 'Breed hens together at random', 'Breed the hens that lay the most eggs, then breed their best offspring, for several generations'], 3, 'Selective breeding means choosing parents with the feature, again and again.', ['Extra food changes the hens, not their genes, and adding a gene is genetic engineering.', 'Breeding the best layers, then their best offspring, over several generations is selective breeding.'], 'application', true),
  a.choice('B44-13', 'Look at the four numbered steps for making insulin. Which step shows the gene being put into a bacterium?', ['Step 1', 'Step 2', 'Step 3', 'Step 4'], 1, 'Follow the gene from the human cell.', ['Step 1 cuts the gene out of a human cell, step 3 shows the bacteria multiplying and step 4 shows insulin collected.', 'Step 2 shows the gene being put into a bacterium.'], 'understanding', true, 'evolve-ge-question'),
  a.choice('B44-14', 'The chart shows maize yields from two same-sized fields on one farm, in one year. One grew GM maize. Which conclusion fits?', ['GM crops always give bigger yields', 'On this farm, in this year, the GM maize gave a bigger yield', 'The GM maize is safe to eat', 'The GM maize reduced the number of wild flowers'], 1, 'The chart shows one farm, one year and one measurement.', ['The GM field gave 9.4 tonnes and the other field 8.1 tonnes.', 'The chart cannot show what happens on every farm, or anything about safety or wild flowers.'], 'dataInterpretation', true, 'evolve-gm-data'),
  a.choice('B44-15', 'A dog breed came from a few closely related dogs. Many now have the same inherited health problem. Why?', ['Inbreeding left few different alleles, so a harmful allele is more likely to be inherited from both parents', 'The dogs caught the health problem from each other', 'The dogs were not fed well', 'Selective breeding makes new diseases'], 0, 'Think about alleles in a population of close relatives.', ['Close relatives share many of the same alleles, so there are few different alleles in the breed.', 'So a harmful allele is more likely to be inherited from both parents.'], 'application', true),
  a.written('B44-16', 'Genetic engineering is used in farming and in medicine. Give two benefits and two concerns.', 'Give one benefit in farming and one in medicine, then one concern about GM animals and one about GM crops.', 'In farming, GM crops can be made resistant to insects, disease or herbicides, which can increase crop yield. In medicine, GM bacteria make human insulin to treat diabetes. But it can be hard to predict how changing an animal’s DNA will affect it, and some GM animals develop health problems. Some people worry that GM crops could reduce wild flowers and insects, or have effects on human health we do not yet understand.', ['A benefit in farming, such as resistance to insects, disease or herbicides, or a bigger crop yield.', 'A benefit in medicine, such as bacteria making human insulin, or gene therapy.', 'A concern about GM animals, such as health problems later in life, effects that are hard to predict, or many embryos not surviving.', 'A concern about GM crops, such as fewer wild flowers and insects, or unknown effects on human health.'], ['Describing selective breeding instead of genetic engineering.', 'Giving only benefits, or only concerns.', 'Saying GM crops are proven to harm human health.', 'Saying genetic engineering changes the genes of everyone who eats GM food.']),
]

export const lesson44: ScienceLesson = {
  id: 'B-GEN-044-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Selective breeding and genetic engineering', prerequisites: ['B-VARIATION'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
