import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { massConservationFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.3.1.1 Conservation of mass and balanced chemical equations (no atoms lost or made; total relative formula mass of reactants equals that of products; finding a missing mass by difference), as on the supplied revision page' }
const skill = 'C-CONSERVATION-MASS'
const conserve = author(skill, ['5.3.1.1'], ['aqa-chemistry'])
const missing = author(skill, ['5.3.1.1'], ['aqa-chemistry'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const massConservationSections = [
  { id: 'C19-01', label: 'Start here', detail: 'What happens to atoms in a reaction' },
  { id: 'C19-02', label: 'Where does the mass go?', detail: 'Atoms are not lost or made' },
  { id: 'C19-06', label: 'Finding a missing mass', detail: 'Add one side, then take away' },
  { id: 'C19-11', label: 'On your own', detail: 'Totals, balanced equations and data' },
]

const states: ScienceState[] = [
  { ...conserve.choice('C19-01', 'Hydrogen and oxygen react to make water. What happens to the atoms in the reaction?', ['Some of the atoms are destroyed', 'The atoms join up in a different way', 'New atoms are made'], 1, 'Think about the atoms in a formula equation: are any added or removed?', ['In a chemical reaction the atoms are rearranged. They join up in a new way.', 'No atoms are destroyed and no new atoms are made.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t(conserve, 'C19-02', 'Where does the mass go?'),
  conserve.worked('C19-03', 'Show that mass is conserved in 2H₂ + O₂ → 2H₂O', 'Hydrogen burns in oxygen to make water: 2H₂ + O₂ → 2H₂O. Aᵣ: H = 1, O = 16. Show that the total Mᵣ is the same on both sides.', ['Left-hand side: Mᵣ of H₂ is 2 × 1 = 2, and Mᵣ of O₂ is 2 × 16 = 32.', 'Two H₂ and one O₂: (2 × 2) + 32 = 4 + 32 = 36.', 'Right-hand side: Mᵣ of H₂O is (2 × 1) + 16 = 18. Two H₂O: 2 × 18 = 36.', 'Both sides total 36, so mass is conserved.'], 'cons-worked-water'),
  conserve.choice('C19-04', '2Ca + O₂ → 2CaO (Ca = 40, O = 16). What is the total Mᵣ of the products?', ['56', '96', '112', '72'], 2, 'Work out the Mᵣ of one CaO first, then count how many there are.', ['Mᵣ of CaO = 40 + 16 = 56.', 'There are two CaO, so the total Mᵣ of the products is 2 × 56 = 112. The reactants also total (2 × 40) + 32 = 112.'], 'calculation'),
  conserve.choice('C19-05', 'Which two things are the same on both sides of a balanced symbol equation?', ['The number of each type of atom, and the total Mᵣ', 'The number of molecules, and the state symbols', 'The number of substances, and the total Mᵣ', 'The formulae of the substances'], 0, 'What did you count in the magnesium example?', ['No atoms are lost or made, so each type of atom appears the same number of times on both sides.', 'The atoms are the same, so the total Mᵣ is the same too. The number of molecules and the substances can change.']),
  t(missing, 'C19-06', 'Finding a missing mass'),
  missing.worked('C19-07', 'Work out the mass of magnesium sulfate formed', 'Magnesium reacts with copper sulfate to make copper and magnesium sulfate. 2.4 g of magnesium reacts with 16.0 g of copper sulfate, and 6.4 g of copper is made. What mass of magnesium sulfate is formed?', ['Add the reactants, where every mass is known: 2.4 + 16.0 = 18.4 g.', 'The products must total 18.4 g too, and copper is 6.4 g of it.', 'Take away the known product: 18.4 − 6.4 = 12.0.', 'So 12.0 g of magnesium sulfate is formed.'], 'cons-worked-mg'),
  missing.choice('C19-08', '3.25 g zinc reacts with 8.0 g copper sulfate, making 3.2 g copper. What mass of zinc sulfate forms?', ['11.25 g', '14.45 g', '4.8 g', '8.05 g'], 3, 'Add the reactants first. Then take away the copper.', ['Total mass of reactants: 3.25 + 8.0 = 11.25 g.', 'The products total 11.25 g. Zinc sulfate = 11.25 − 3.2 = 8.05 g.'], 'calculation'),
  missing.choice('C19-09', '6.5 g zinc reacts with copper sulfate, making 6.4 g copper and 16.1 g zinc sulfate. What mass of copper sulfate reacted?', ['22.5 g', '16.0 g', '9.7 g', '29.0 g'], 1, 'This time the missing mass is on the reactant side. Total the products first.', ['Total mass of products: 6.4 + 16.1 = 22.5 g.', 'The reactants must total 22.5 g too. Copper sulfate = 22.5 − 6.5 = 16.0 g.'], 'calculation'),
  missing.choice('C19-10', 'Every mass in a reaction is known except one reactant. What is the correct way to find it?', ['Add all the known masses on both sides', 'Subtract the mass of the products from the mass of the known reactant', 'Take the known reactants away from the total mass of the products', 'Double the total mass of the products'], 2, 'Which side of the equation do you know every mass on?', ['Total the side where every mass is known. That total is the same for both sides.', 'Then subtract the known masses on the other side. The difference is the missing reactant.']),
  conserve.choice('C19-11', '2Na + Cl₂ → 2NaCl (Na = 23, Cl = 35.5). What is the total Mᵣ of the reactants?', ['117', '94.5', '58.5', '234'], 0, 'Cl₂ has two chlorine atoms, and there are two sodium atoms.', ['Mᵣ of 2Na = 2 × 23 = 46. Mᵣ of Cl₂ = 2 × 35.5 = 71.', 'Total = 46 + 71 = 117. The products, 2 × 58.5, also make 117.'], 'calculation', true),
  missing.choice('C19-12', '5.6 g iron reacts with 16.0 g copper sulfate, making 6.4 g copper. What mass of iron sulfate forms?', ['28.0 g', '10.4 g', '21.6 g', '15.2 g'], 3, 'Add the two reactants, then take away the copper.', ['Total mass of reactants: 5.6 + 16.0 = 21.6 g.', 'Iron sulfate = 21.6 − 6.4 = 15.2 g.'], 'calculation', true),
  conserve.choice('C19-13', 'A student wrote four equations. In which line are the atoms, and so the mass, NOT the same on both sides?', ['Line 1', 'Line 2', 'Line 3', 'Line 4'], 1, 'Count each type of atom on the left and then on the right.', ['Line 2 has 1 calcium atom on the left but 2 on the right, so it is not balanced.', 'The other three lines have the same atoms on both sides.'], 'application', true, 'cons-question-equations'),
  conserve.choice('C19-14', 'The table shows three reactions in sealed flasks. Which conclusion do these data support?', ['Mass is conserved in every reaction ever carried out', 'Bigger flasks lose more mass', 'In these three sealed flasks, the mass did not change', 'Every reaction makes new atoms'], 2, 'Is the claim about these three runs, or about all reactions?', ['In each run, the mass before equals the mass after: 120.4 g, 135.0 g and 128.6 g.', 'Three runs support a claim about these runs only, so the first answer claims too much.'], 'dataInterpretation', true, 'cons-data-sealed'),
  conserve.written('C19-15', '“2Mg + O₂ → 2MgO: 3 particles become 2, so mass is lost.” Explain the error. (Mg = 24, O = 16)', 'Count atoms, not particles. Then add the Mᵣ values on each side.', 'The number of particles can change, but atoms are not lost or made in a reaction. There are 2 magnesium atoms and 2 oxygen atoms on both sides, so the mass is the same. Left: (2 × 24) + 32 = 80. Right: 2 × (24 + 16) = 80. The total Mᵣ is the same, so mass is conserved.', ['Atoms are not lost or made, only rearranged; the number of particles can change.', 'Both sides have 2 magnesium atoms and 2 oxygen atoms.', 'Left total Mᵣ: (2 × 24) + 32 = 80.', 'Right total Mᵣ: 2 × 40 = 80, so mass is conserved.'], ['Saying some mass has been lost or turned into energy.', 'Comparing the number of particles instead of the atoms.', 'Giving totals with no working or no explanation.']),
]

export const lessonC19: ScienceLesson = {
  id: 'C-QNT-019-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'Conservation of mass', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
