import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { wsConcludeFrames as frames } from './teachingFrames'

const source = { id: 'aqa-working-scientifically', title: 'AQA 8464 Working scientifically and practical skills', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification', locator: 'WS 3.5 (interpreting data and drawing conclusions), WS 3.6 (correlation and cause), as on the supplied revision page' }
const skill = 'W-DAT-011-W'
const a = author(skill, ['WS 3.5', 'WS 3.6'], ['aqa-working-scientifically'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const wsConcludeSections = [
  { id: 'W11-01', label: 'Start here', detail: 'Two things happening together' },
  { id: 'W11-02', label: 'What can you conclude?', detail: 'Only what the data shows' },
  { id: 'W11-05', label: 'Does the data support the hypothesis?', detail: 'Matching data to the idea' },
  { id: 'W11-07', label: 'Does correlation mean cause?', detail: 'Chance, a third variable, or a cause' },
  { id: 'W11-11', label: 'On your own', detail: 'Conclusions from data' },
]

const states: ScienceState[] = [
  { ...a.choice('W11-01', 'A friend says: "It rained every time I forgot my umbrella, so forgetting it makes it rain." What is wrong with this?', ['Nothing, it happened every time', 'Umbrellas are not related to rain', 'Two things happening together does not mean one causes the other', 'Rain only happens on Mondays'], 2, 'Think about whether forgetting an umbrella could really change the weather.', ['Two things can happen together without one causing the other.', 'The weather does not depend on your umbrella.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('W11-02', 'What can you conclude?'),
  a.choice('W11-03', 'Bean plants grew a mean of 14 mm with food A and 9 mm with food B. Which conclusion matches?', ['Food A makes every type of plant grow more', 'These bean plants grew more with food A than with food B', 'Food B stops plants growing', 'Plant food is good for people'], 1, 'Only say what the data shows, about these plants.', ['The data is about bean plants and two foods.', 'A conclusion must not go beyond the data, so it cannot be about every plant or about people.'], 'dataInterpretation'),
  a.choice('W11-04', 'Which sentence best justifies the conclusion that food A gave more growth than food B?', ['Food A is the best food', 'Everyone prefers food A', 'The plants looked greener', 'Plants with food A grew a mean of 5 mm more, as 14 − 9 = 5'], 3, 'Use the results themselves to back up the conclusion.', ['A justification quotes the data.', 'The difference in mean growth was 14 − 9 = 5 mm.'], 'dataInterpretation'),
  t('W11-05', 'Does the data support the hypothesis?'),
  a.choice('W11-06', 'Warmer water should dissolve sugar faster. Times were 90 s, 45 s and 20 s at 20, 40 and 60 °C. Conclusion?', ['The data supports the hypothesis for these temperatures', 'The data does not support the hypothesis', 'The data proves that all solids dissolve faster in warm water', 'The data shows the temperature had no effect'], 0, 'Compare the pattern in the times with what the hypothesis says.', ['The time falls as the temperature rises, which matches the hypothesis.', 'The data supports it for sugar and these temperatures, but does not prove it for every solid.'], 'dataInterpretation'),
  t('W11-07', 'Does correlation mean cause?'),
  a.choice('W11-08', 'In one town, more sunburn cases happen in weeks when more ice cream is sold. What is the most likely explanation?', ['Ice cream causes sunburn', 'Sunburn makes people buy ice cream', 'Both are linked to sunny weather, a third variable', 'It is only chance'], 2, 'Ask what could be affecting both things.', ['Sunny weather makes people buy ice cream and spend time in the sun.', 'The two are correlated, but ice cream does not cause sunburn.']),
  a.choice('W11-09', 'A study finds a link between birth month and running speed. Repeats find no link. What is the explanation?', ['A third variable', 'It was probably chance', 'Birth month causes speed', 'The runners were cheating'], 1, 'If others cannot repeat the correlation, it may have been a fluke.', ['A correlation that other scientists do not get again may be down to chance.', 'A real cause would show up again.']),
  a.choice('W11-10', 'When can scientists say that a change in one variable causes a change in another?', ['When the two variables are correlated', 'When the graph has a steep line', 'When one study says so', 'When other variables that could affect the result have been controlled'], 3, 'Think about what a fair test does.', ['A cause can only be concluded when other variables have been controlled.', 'This isolates the effect of the one variable that was changed.']),
  a.choice('W11-11', 'The table shows how long a trolley took to roll down a ramp with three surfaces. Which conclusion matches the table?', ['The trolley took longest on the sandpaper of the three surfaces', 'Rough surfaces slow every object down', 'The trolley stopped on the sandpaper', 'Smooth surfaces are always the fastest'], 0, 'Only say what these three results show.', ['Sandpaper had the highest time, 3.4 s.', 'The other statements go beyond this data.'], 'dataInterpretation', true, 'wsconclude-q-table'),
  a.choice('W11-12', 'The graph shows a correlation between the shoe size of children and reading score. What is the most likely explanation?', ['Big feet cause better reading', 'Age affects both shoe size and reading score', 'Reading makes feet grow', 'It is only chance'], 1, 'Think about what changes for both variables as children get older.', ['Older children have bigger feet and have also learned more reading.', 'Age is the third variable behind both.'], 'dataInterpretation', true, 'wsconclude-q-scatter'),
  a.choice('W11-13', 'A student changes only the voltage across a wire. More voltage gives more current. Everything else was controlled. What can they conclude?', ['The result is only chance', 'A third variable caused the change', 'No conclusion is possible', 'The increase in voltage caused the increase in current'], 3, 'The other variables were controlled.', ['Because all other variables were controlled, the change in voltage can be linked to the change in current.', 'This is the situation in which you can conclude a cause.'], 'application', true),
  a.choice('W11-14', 'Salt should lower water freezing points. Freezing points: 0 °C, −3 °C with 5 g salt, −6 °C with 10 g. Conclusion?', ['The data supports the hypothesis for the amounts of salt tested', 'The data proves salt lowers the freezing point of every liquid', 'The data does not support the hypothesis', 'Salt makes water hotter'], 0, 'Say whether the data supports the idea, but stay inside the data.', ['The freezing point falls as more salt is added, so the data supports the hypothesis.', 'The data covers water and these amounts of salt only.'], 'dataInterpretation', true),
  a.written('W11-15', 'Pupils with higher attendance get higher test scores. A student says attendance causes this. Is that the only possible conclusion?', 'Think about the three reasons for a correlation.', 'It is a correlation, but a correlation does not always mean cause. Another factor, such as how motivated the pupils are, could affect both attendance and scores. It could also be chance. To show that attendance causes higher scores, the school would need to control other variables and test it fairly.', ['Says there is a correlation between attendance and scores.', 'Says a correlation does not always mean one variable causes the other.', 'Gives a possible third variable, such as motivation or health.', 'Says other variables would need to be controlled to show a cause.'], ['Saying attendance definitely causes higher scores.', 'Saying there is no link at all.', 'Only saying the study is wrong with no reason.']),
]

export const lessonW11: ScienceLesson = {
  id: skill, contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'skills',
  title: 'Drawing conclusions', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
