import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { motorEffectFrames as frames } from './teachingFrames'

const source = { id: 'aqa-physics', title: 'AQA 8464 Physics subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', locator: '6.7.2.2 Fleming’s left-hand rule (HT): the motor effect, the force at right angles to the field and the current, F = B I l and magnetic flux density; 6.7.2.3 Electric motors (HT): a coil carrying a current in a magnetic field rotates, as on the supplied revision pages' }
const skill = 'P-MAG-064H-P'
const effect = author(skill, ['6.7.2.2'], ['aqa-physics'])
const motor = author(skill, ['6.7.2.3'], ['aqa-physics'])
const both = author(skill, ['6.7.2.2', '6.7.2.3'], ['aqa-physics'])
const t = (a: ReturnType<typeof author>, id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const motorEffectSections = [
  { id: 'P64H-01', label: 'Start here', detail: 'What a current makes around a wire' },
  { id: 'P64H-02', label: 'The motor effect', detail: 'A current in a magnetic field feels a force' },
  { id: 'P64H-05', label: 'Fleming’s left-hand rule', detail: 'Field, current and motion on one hand' },
  { id: 'P64H-08', label: 'How big is the force?', detail: 'Magnetic flux density and F = B I l' },
  { id: 'P64H-13', label: 'The dc motor', detail: 'Opposite forces and a split-ring commutator' },
  { id: 'P64H-16', label: 'On your own', detail: 'A calculation, a diagram, some data and a motor' },
]

const states: ScienceState[] = [
  { ...effect.choice('P64H-01', 'A current flows through a wire. What does the current make around the wire?', ['Static charge on the wire', 'A beam of light', 'A magnetic field', 'A north pole at each end'], 2, 'Think of a compass placed next to the wire.', ['A current makes a magnetic field. The field is a set of circles around the wire.', 'Put that wire between the poles of a magnet and the two fields act on each other. That is what this topic is about.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },

  t(effect, 'P64H-02', 'The motor effect'),
  effect.choice('P64H-03', 'A wire carrying a current sits between two magnetic poles. When is the force on it biggest?', ['When the wire is at 90° to the field', 'When the wire is parallel to the field', 'When the wire is at 45° to the field', 'When the current is switched off'], 0, 'Think about how the wire crosses the field lines.', ['The force is biggest when the wire is at right angles (90°) to the field.', 'Parallel to the field there is no force, and at angles in between there is some. With no current there is no force at all.']),
  effect.choice('P64H-04', 'Which statement about the direction of the force on the wire is correct?', ['It acts along the wire, the same way as the current', 'It acts at right angles to both the field and the current', 'It acts along the field lines, from N to S', 'It always acts towards the north pole'], 1, 'In the picture, the field went across and the current came towards you. Which way did the force go?', ['The force is at right angles to the field and at right angles to the current.', 'In the picture, the field went across and the current came towards you, so the force pushed the wire up.']),

  t(effect, 'P64H-05', 'Fleming’s left-hand rule'),
  effect.choice('P64H-06', 'In Fleming’s left-hand rule, what does your second finger point along?', ['The force on the wire', 'The magnetic field', 'The current', 'The motion of the magnets'], 2, 'Say the word slowly, with its capital letter: seCond.', ['seCond finger: Current. First finger: Field. thuMb: Motion.', 'So your second finger points along the current, and your thumb then shows the force.'], 'recall'),
  effect.choice('P64H-07', 'Use Fleming’s left-hand rule. Which way does the force on the wire in the diagram act?', ['Up', 'Down', 'Towards the S pole', 'Along the wire'], 1, 'First finger from N to S. Second finger along the current arrow, away from you.', ['Point your first finger across the gap from N to S. Point your second finger along the current, away from you.', 'Your thumb points down, so the force is down. The current is the reverse of the one you saw before, so the force is reversed too.'], 'application', false, 'hmotor-question-left-hand'),

  t(effect, 'P64H-08', 'How big is the force?'),
  effect.worked('P64H-09', 'Work out the force on a wire', 'A wire 0.40 m long sits at 90° to a magnetic field of 0.25 T. A current of 3.0 A flows through it. What force acts on the wire?', ['Write the equation: F = B I l.', 'Put in the numbers: F = 0.25 × 3.0 × 0.40.', 'Work it out: 0.25 × 3.0 = 0.75, and 0.75 × 0.40 = 0.30.', 'So the force on the wire is 0.30 N.'], 'hmotor-worked-force'),
  effect.worked('P64H-10', 'Work out the magnetic flux density', 'A 50 cm wire sits at 90° to a magnetic field. It carries a current of 2.5 A and feels a force of 0.25 N. What is the magnetic flux density?', ['Change the length into metres: 50 cm = 0.50 m.', 'Rearrange F = B I l to get B = F ÷ (I × l).', 'Work out I × l first: 2.5 × 0.50 = 1.25.', 'B = 0.25 ÷ 1.25 = 0.20 T.'], 'hmotor-worked-flux'),
  effect.choice('P64H-11', 'A 0.50 m wire at 90° to a 0.30 T field carries 4.0 A. What is the force on the wire?', ['2.4 N', '4.8 N', '0.15 N', '0.60 N'], 3, 'Multiply all three together: F = B I l.', ['F = B I l = 0.30 × 4.0 × 0.50.', '0.30 × 4.0 = 1.2, and 1.2 × 0.50 = 0.60 N.'], 'calculation'),
  effect.choice('P64H-12', 'A 15 cm wire at 90° to a 0.20 T field feels a force of 0.12 N. What current flows through it?', ['4.0 A', '0.0036 A', '0.25 A', '0.040 A'], 0, 'Change 15 cm into metres. Then divide the force by B × l.', ['Change the length into metres: 15 cm = 0.15 m.', 'Rearrange: I = F ÷ (B × l). B × l = 0.20 × 0.15 = 0.030.', 'I = 0.12 ÷ 0.030 = 4.0 A.'], 'calculation'),

  t(motor, 'P64H-13', 'The dc motor'),
  motor.choice('P64H-14', 'Why does the coil in a simple dc motor rotate?', ['The forces on its two sides act in opposite directions', 'The magnets attract the metal of the coil', 'The current heats the coil and it expands', 'Both sides of the coil are pushed upwards'], 0, 'Compare the current in the two sides of the coil.', ['The current flows in opposite directions in the two sides of the coil.', 'So the forces on the two sides act in opposite directions, one up and one down. This makes the coil rotate.']),
  motor.choice('P64H-15', 'Which numbered part of the motor swaps the contacts every half turn?', ['Part 1', 'Part 2', 'Part 3', 'Part 4'], 2, 'It is a ring split into two halves, on the axle.', ['Part 3 is the split-ring commutator. Every half turn its two halves swap which contact they touch.', 'This reverses the current in the coil, so the coil keeps turning the same way. Part 1 is a side of the coil, part 2 is a magnetic pole and part 4 is a contact.'], 'recall', false, 'hmotor-question-parts'),

  effect.choice('P64H-16', 'A 30 cm wire carries 2.5 A at 90° to a 0.080 T field. What is the force on the wire?', ['6.0 N', '0.060 N', '0.60 N', '0.0096 N'], 1, 'Change the length into metres first. Then use F = B I l.', ['30 cm = 0.30 m.', 'F = B I l = 0.080 × 2.5 × 0.30 = 0.060 N. Using 30 instead of 0.30 gives 6.0 N, which is 100 times too big.'], 'calculation', true),
  effect.choice('P64H-17', 'The poles have been swapped. Using Fleming’s left-hand rule, which way does the force on the wire act?', ['Down', 'Towards the N pole', 'Along the wire, away from you', 'Up'], 3, 'The field still goes from N to S. Which way is that now?', ['The field goes from N to S, so now it points to the left. The current flows away from you.', 'First finger to the left, second finger away from you: your thumb points up. So the force is up.'], 'application', true, 'hmotor-question-poles-swapped'),
  effect.choice('P64H-18', 'A student measured the force on one wire at different currents. Which conclusion do these results support?', ['In these results, doubling the current doubled the force', 'The force does not depend on the current', 'Doubling the current always doubles the force, for any current', 'A longer wire would feel a smaller force'], 0, 'Compare 1.0 A with 2.0 A, and 2.0 A with 4.0 A. Is the claim only about these results?', ['From 1.0 A to 2.0 A the force went from 0.05 N to 0.10 N. From 2.0 A to 4.0 A it went from 0.10 N to 0.20 N.', 'So in these results, doubling the current doubled the force. The student only tested up to 4.0 A, and never changed the length of the wire.'], 'dataInterpretation', true, 'hmotor-data-current'),
  motor.choice('P64H-19', 'A motor needs to spin faster and in the opposite direction. Which change does both?', ['Increase the current only', 'Reverse the current and swap the poles', 'Reverse the current and use fewer turns', 'Swap the poles and increase the current'], 3, 'Which changes reverse the motor? Which make it faster? Doing two reversals cancels out.', ['Swapping the poles reverses the field, so the motor turns the other way. A bigger current makes it spin faster.', 'Reversing the current and swapping the poles together cancel out. Fewer turns would make it slower.'], 'application', true),
  both.written('P64H-20', 'Explain why a simple dc motor’s coil rotates and keeps turning the same way. Give one way to speed it up.', 'Think about the current in each side of the coil, the forces on them, the split-ring commutator, and what makes the forces bigger.', 'Each side of the coil carries a current in a magnetic field, so each side feels a force (the motor effect). The current flows in opposite directions in the two sides, so one side is pushed up and the other down. These opposite forces make the coil rotate. Every half turn, the split-ring commutator swaps the contacts. This reverses the current in the coil, so the forces keep turning it the same way. To make it faster, increase the current, add more turns of wire or use a stronger magnetic field.', ['Each side of the coil carries a current in a magnetic field, so it feels a force (the motor effect).', 'The current flows in opposite directions in the two sides, so the forces act in opposite directions (one up, one down).', 'The opposite forces make the coil rotate.', 'The split-ring commutator swaps the contacts every half turn, which reverses the current in the coil so it keeps turning the same way.', 'Faster: a bigger current, more turns on the coil, or a stronger magnetic field (bigger magnetic flux density).'], ['Saying the magnets simply attract the coil, with no current or force on the wire.', 'Saying both sides of the coil are pushed the same way.', 'Saying the commutator reverses the magnetic field.', 'Saying that reversing the current makes the motor faster.']),
]

export const lessonP64H: ScienceLesson = {
  id: 'P-MAG-064H-P', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'physics',
  title: 'The motor effect', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
