import type { TeachingFrame } from '../../teachingFrame'

// The motor effect builds on electromagnetism (a current makes circles of field round a wire, the right-hand thumb rule)
// and on magnets (field lines from N to S, red north and blue south). Each teaching section keeps one drawing on screen
// and changes it frame by frame: a wire across the gap between a north and a south pole (drawn in perspective, so the
// field goes across, the current comes towards you and the force goes up), then the same picture with Fleming's left
// hand beside it, then with the sizes B, I and l marked, and finally a coil on an axle with a split-ring commutator.
// The last frame of each puts the steps together.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const motorEffectFrames: Record<string, TeachingFrame[]> = {
  'P64H-02': [
    f('A field between two poles', 'Between a north pole and a south pole facing each other, the field lines go straight across from N to S.', 'field lines go from N to S', 'You met magnetic fields when you learned about magnets. Put a north pole and a south pole facing each other with a gap between them. In the gap, the field lines go straight across from N to S.', 'hmotor-effect-field'),
    f('Add a current', 'A wire carrying a current has its own magnetic field. Between the poles, the two fields act on each other.', 'current → its own field → the fields act on each other', 'Now put a wire across the gap and pass a current through it. You know that a current makes circles of magnetic field around a wire. This field and the field of the magnets act on each other. So the wire and the magnets push on each other.', 'hmotor-effect-current'),
    f('The motor effect', 'A wire carrying a current in a magnetic field feels a force. This is called the motor effect.', 'current + field → force', 'A wire carrying a current in a magnetic field feels a force, which can make it move. This is called the motor effect. The force acts at right angles to the field and at right angles to the current. Here the field goes across, the current comes towards you and the force pushes the wire up.', 'hmotor-effect-force'),
    f('The angle matters', 'The force is biggest when the wire is at 90° to the field. There is no force when the wire is parallel to it.', '90° → full force; parallel → no force', 'Look down on the poles from above. The wire can cross the field lines at different angles. At 90° to the field, the wire feels the full force. If it runs parallel to the field lines, there is no force at all. At angles in between, there is some force.', 'hmotor-effect-angle'),
    f('Put it together', 'Current + magnetic field → a force at right angles to both. It is biggest at 90°.', 'force ⟂ field and ⟂ current; biggest at 90°', 'A wire carrying a current in a magnetic field feels a force. This is the motor effect. The force is at right angles to both the field and the current. It is biggest when the wire is at 90° to the field. There is no force if the wire is parallel to the field, or if no current flows.', 'hmotor-effect-all'),
  ],
  'P64H-05': [
    f('Three directions', 'The field, the current and the force are each at right angles to the other two.', 'three directions, all at 90°', 'The field, the current and the force all point in different directions. Each one is at right angles to the other two. If you know two of them, you can find the third. You need a rule to do it.', 'hmotor-flem-three'),
    f('Use your left hand', 'Fleming’s left-hand rule: First finger = Field, seCond finger = Current, thuMb = Motion.', 'First → Field, seCond → Current, thuMb → Motion', 'Hold out your left hand with your thumb, first finger and second finger all at right angles. Your First finger points along the Field, from N to S. Your seCond finger points along the Current. Your thuMb shows the force, which gives the Motion. This is called Fleming’s left-hand rule.', 'hmotor-flem-hand'),
    f('Line up your fingers', 'Point your first finger along the field and your second finger along the current. Your thumb shows the force.', 'first finger N → S; second finger along the current; read the thumb', 'Look at the wire between the poles. Point your first finger across the gap from N to S. Turn your hand so your second finger points along the current, towards you. Your thumb now points up, so the force pushes the wire up.', 'hmotor-flem-use'),
    f('Reverse the current or the field', 'Reversing the current or the field reverses the force.', 'flip the current or the field → the force flips', 'Now make the current flow the other way, away from you. Your second finger turns round, and your thumb points down. So the force is reversed. Swapping the poles reverses the field, and that also reverses the force.', 'hmotor-flem-reverse'),
    f('Put it together', 'Left hand: First finger along the Field, seCond finger along the Current, thuMb gives the Motion.', 'left hand: field, current, motion', 'Always use your left hand, not your right. Point your first finger along the field, from N to S. Point your second finger along the current. Your thumb gives the direction of the force. Reverse either the current or the field and the force reverses.', 'hmotor-flem-all'),
  ],
  'P64H-08': [
    f('Magnetic flux density', 'Magnetic flux density is how many field lines there are in a region. It shows how strong the field is.', 'more field lines in a region → stronger field', 'A stronger magnet has more field lines packed into the same space. The number of field lines in a region shows how strong the field is. This is called the magnetic flux density. Its symbol is B and it is measured in tesla, T.', 'hmotor-size-flux'),
    f('Current and length', 'A bigger current, or a longer piece of wire in the field, gives a bigger force.', 'more current or more length → bigger force', 'The size of the force also depends on the current, I, in amps. It depends on the length of wire inside the field, l, in metres. Only the part of the wire between the poles counts. More current or more length gives a bigger force.', 'hmotor-size-current'),
    f('The equation', 'When the wire is at 90° to the field: force = magnetic flux density × current × length, or F = B I l.', 'F = B × I × l', 'When the wire is at 90° to the field, you can work out the force with an equation. Force = magnetic flux density × current × length. In symbols, F = B I l. F is in newtons, B in tesla, I in amps and l in metres.', 'hmotor-size-equation'),
    f('Put it together', 'Use F = B I l with the length in metres. Rearrange it to find B or I.', 'metres first; B = F ÷ (I × l); I = F ÷ (B × l)', 'Write the equation, put in the numbers, then work it out. Change any length in centimetres into metres first: 50 cm = 0.50 m. To find B, divide the force by I × l. To find the current, divide the force by B × l.', 'hmotor-size-all'),
  ],
  'P64H-13': [
    f('A coil in a field', 'In a simple motor, a coil of wire carrying a current sits between two magnetic poles, on an axle.', 'coil + current + field', 'A simple electric motor uses the motor effect. A rectangular coil of wire sits between a north and a south pole, on an axle. A direct current (dc) supply pushes a current round the coil. The current flows away from you along one side and back towards you along the other.', 'hmotor-dc-coil'),
    f('Opposite forces', 'The current flows opposite ways in the two sides, so the forces on them act in opposite directions and the coil turns.', 'opposite currents → opposite forces → rotation', 'Each side of the coil is a wire at 90° to the field, so each one feels a force. The current flows in opposite directions in the two sides. So the forces are opposite too: one side is pushed up and the other is pushed down. Together they make the coil rotate.', 'hmotor-dc-forces'),
    f('The split-ring commutator', 'A split-ring commutator swaps the contacts every half turn, so the coil keeps turning the same way.', 'every half turn: contacts swap → current reverses → same way round', 'After half a turn, each side of the coil has moved to the other side of the axle. If nothing changed, the forces would now push it back again. So the coil is joined to the supply through a ring split into two halves. Every half turn, the halves swap which contact they touch. This reverses the current in the coil, so it keeps turning the same way. The ring is called a split-ring commutator.', 'hmotor-dc-commutator'),
    f('Make it turn the other way', 'To make the motor turn the other way, reverse the current or swap the magnetic poles.', 'reverse the current or swap the poles', 'Use Fleming’s left-hand rule on one side of the coil to find which way it turns. To make it turn the other way, reverse the current from the supply. Or swap the magnetic poles over, which reverses the field. Either change reverses the forces on the coil.', 'hmotor-dc-reverse'),
    f('Put it together', 'Opposite forces turn the coil, the commutator keeps it turning one way, and more current, more turns or a stronger field make it faster.', 'faster: more current, more turns, stronger field', 'Opposite forces on the two sides of the coil make it rotate. The split-ring commutator keeps it turning the same way. To make the motor spin faster, increase the current. You can also add more turns of wire to the coil. Or use a stronger magnetic field, with a bigger magnetic flux density.', 'hmotor-dc-all'),
  ],
}
