import type { TeachingFrame } from '../../teachingFrame'

// Parallel circuits: branches and independence, pd and current rules (with one worked example), then total resistance.
// Series circuits are taught in the previous lesson; only a one-clause contrast is made here.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const parallelFrames: Record<string, TeachingFrame[]> = {
  'P21-02': [
    f('Each lamp has its own loop', 'In a parallel circuit every component sits on its own loop, called a branch.', 'one branch per component', 'In a series circuit the current has only one route. In a parallel circuit there are several. Each component sits on its own loop, joined separately to the cell or battery. Each loop is called a branch.', 'parallel-branches'),
    f('Take one branch away', 'If you remove one branch, the components on the other branches carry on working.', 'other lamps stay lit', 'Because every branch is connected to the supply on its own, the branches do not depend on each other. Unscrew one lamp and the other lamps stay lit. The current simply has one fewer route to take.', 'parallel-remove'),
    f('Switches work one at a time', 'A switch on one branch turns off only that branch.', 'switch on one branch', 'This means parts of a parallel circuit can be switched on and off without affecting each other. A switch on one branch controls only that branch. A switch next to the battery controls the whole circuit.', 'parallel-switch'),
    f('Why homes and cars use them', 'Most everyday circuits are parallel, so each device works on its own.', 'each device works alone', 'Most everyday things are wired in parallel, including the lights and sockets in a home and the electrics in a car. You can use the kettle without turning on the television. Some circuits mix series and parallel parts.', 'parallel-everyday'),
  ],
  'P21-05': [
    f('Same pd on every branch', 'Every branch gets the full pd of the cell or battery. So the pd is the same across each branch.', 'full pd on each branch', 'Each branch is connected straight across the supply. So every component gets the full potential difference of the cell or battery. A 6 V battery gives 6 V across each branch. We write this as V₁ = V₂ = V total. A voltmeter is connected across a component, in parallel with it.', 'parallel-same-pd'),
    f('Current splits at a junction', 'At a junction the current splits between the branches, then joins up again.', 'split and rejoin', 'A junction is a point where wires meet. The current coming into a junction splits between the branches. Where the branches meet again, the currents join up. The current going into a junction always equals the current coming out.', 'parallel-junction'),
    f('Add up the branches', 'The total current is the sum of the currents in the branches: I total = I₁ + I₂ + …', 'branches add to the total', 'Add the currents in all the branches to get the total current from the battery. In words: total current = current in branch 1 + current in branch 2. If two identical components are in parallel, each branch carries the same current.', 'parallel-add'),
    f('Worked example: the pd', 'A 12 V battery is connected to two lamps in parallel. Each lamp has 12 V across it.', 'battery pd on each lamp', 'A 12 V battery supplies two lamps in parallel. The ammeter next to the battery reads 3.0 A. The lamp on branch 1 carries 1.2 A. Step 1: the pd across each branch is the same as the battery, so each lamp has 12 V.', 'parallel-worked-pd'),
    f('Worked example: the current', 'Total current 3.0 A minus 1.2 A in branch 1 leaves 1.8 A in branch 2.', 'total minus the known branch', 'Step 2: the currents in the branches must add up to the total. So 3.0 A = 1.2 A + I₂. To find I₂, take 1.2 A away from 3.0 A. I₂ = 3.0 − 1.2 = 1.8 A. The lamp on branch 2 carries 1.8 A.', 'parallel-worked-current'),
  ],
  'P21-08': [
    f('Another branch, another route', 'Adding a branch gives the current one more way to go, and the pd across each branch stays the same.', 'one more route', 'Now add a third lamp on a new branch. The pd across every branch is still the full battery pd. So the "push" on each branch has not changed, and the existing branches carry the same current as before.', 'parallel-add-branch'),
    f('The total current goes up', 'The new branch takes its own current, so the total current from the battery increases.', 'existing branches + the new one', 'The old branches still carry the same current. The new branch takes extra current too. Adding branches only adds more current, so the total current from the battery gets larger.', 'parallel-more-current'),
    f('So the total resistance goes down', 'The same pd with a bigger total current means a smaller total resistance, because R = V ÷ I.', 'same pd, more current', 'Resistance is pd divided by current, R = V ÷ I. The pd stays the same but the total current rises. So the total resistance of the circuit falls. Adding a resistor in parallel always reduces the total resistance.', 'parallel-less-resistance'),
    f('Smaller than any single branch', 'The total resistance of resistors in parallel is less than the resistance of any one of them.', 'below the smallest', 'The total resistance of resistors in parallel is always less than the resistance of any one of them. Two 10 Ω resistors in parallel have a total resistance below 10 Ω. In series it is the other way round: resistances add up.', 'parallel-total-r'),
  ],
}
