import type { TeachingFrame } from '../../teachingFrame'

// Three walkthroughs. The first builds one cell drawing (electrolyte, electrodes, poles, movement, discharge). The second
// reuses it for molten lead bromide and adds the metal/non-metal pattern. The third applies it to aluminium.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const electrolysisFrames: Record<string, TeachingFrame[]> = {
  'C26-02': [
    f('The electrolyte', 'An electrolyte is a liquid or solution that can conduct electricity.', 'ions free to move → conducts', 'Electrolysis means splitting up a compound using electricity. It needs a liquid or solution that can conduct. This is called the electrolyte. An ionic compound works when it is melted or dissolved in water, because its ions are then free to move.', 'elec-electrolyte'),
    f('The electrodes', 'An electrode is a solid rod that dips into the electrolyte and carries current.', 'rods carry current in and out', 'Two solid rods dip into the electrolyte. Each one conducts electricity and is joined by a wire to a power supply. A rod like this is called an electrode. The ions react at the electrodes.', 'elec-electrode'),
    f('Cathode and anode', 'The negative electrode is the cathode. The positive electrode is the anode.', 'cathode negative · anode positive', 'The power supply makes one electrode negative and the other positive. The negative electrode is called the cathode. The positive electrode is called the anode.', 'elec-poles'),
    f('Ions on the move', 'Positive ions go to the cathode and gain electrons. Negative ions go to the anode and lose electrons.', 'opposites attract', 'Opposite charges attract. Positive ions move to the negative cathode, where they gain electrons. Negative ions move to the positive anode, where they lose electrons. The moving ions make a flow of charge through the electrolyte.', 'elec-move'),
    f('Discharged ions', 'An ion that gains or loses electrons becomes an uncharged element: it is discharged.', 'ion → gains or loses electrons → uncharged', 'Once an ion has gained or lost electrons, it has no charge. It has become an atom of an uncharged element. We say the ion has been discharged. So the compound breaks down into its elements.', 'elec-discharge'),
  ],
  'C26-05': [
    f('Solid or molten?', 'A solid ionic compound cannot be electrolysed. A molten one can.', 'ions fixed → no current · ions free → current', 'In a solid ionic compound, the ions are held in fixed places. They cannot move, so a solid cannot be electrolysed. When the compound melts, it is molten and the ions are free to move. Molten ionic compounds can be electrolysed.', 'elec-molten-why'),
    f('Molten lead bromide', 'Lead forms at the cathode and bromine forms at the anode.', 'Pb²⁺ → cathode · Br⁻ → anode', 'Molten lead bromide contains positive lead ions, Pb²⁺, and negative bromide ions, Br⁻. The lead ions move to the cathode and become lead atoms. The bromide ions move to the anode and become bromine. So lead metal forms at the cathode and bromine at the anode.', 'elec-molten-pbbr2'),
    f('The pattern', 'The metal forms at the cathode and the non-metal forms at the anode.', 'metal → cathode · non-metal → anode', 'A molten ionic compound is always broken up into its elements. The metal forms at the cathode, because metal ions are positive. The non-metal forms at the anode. This works for any molten compound of a metal and a non-metal.', 'elec-molten-rule'),
    f('Inert electrodes', 'Inert electrodes do not react with the electrolyte or with the products.', 'inert = unreactive', 'The electrodes are often made of an inert material. Inert means unreactive. An inert electrode does not react with the electrolyte or with the substances that form. So only the ions in the electrolyte take part.', 'elec-molten-inert'),
  ],
  'C26-08': [
    f('Aluminium and cryolite', 'Aluminium oxide is dissolved in molten cryolite, which lowers the melting point.', 'high melting point → add cryolite', 'Aluminium is extracted from an ore that contains aluminium oxide, Al₂O₃. Aluminium oxide has a very high melting point, which would cost a huge amount of energy to reach. So it is dissolved in molten cryolite instead. Cryolite lowers the melting point.', 'elec-al-why'),
    f('Inside the cell', 'Aluminium forms at the cathode and oxygen forms at the anode.', 'Al³⁺ → cathode · O²⁻ → anode', 'The molten mixture contains aluminium ions, Al³⁺, and oxide ions, O²⁻. Aluminium ions move to the cathode and become aluminium atoms. The aluminium is a liquid at this temperature, so it sinks to the bottom. Oxide ions move to the anode and form oxygen gas, O₂.', 'elec-al-cell'),
    f('The graphite anode', 'Oxygen reacts with the carbon anode to make carbon dioxide, so the anode wears away.', 'oxygen + carbon → carbon dioxide', 'The anode is made of graphite, a form of carbon. At this high temperature, carbon reacts with the oxygen made at the anode. This makes carbon dioxide gas. So the graphite anodes wear away and must be replaced regularly.', 'elec-al-graphite'),
    f('The overall equation', 'Aluminium oxide → aluminium + oxygen, written 2Al₂O₃ → 4Al + 3O₂.', 'compound → two elements', 'Overall, aluminium oxide splits into aluminium and oxygen. The symbol equation is 2Al₂O₃ → 4Al + 3O₂. There are 4 aluminium atoms and 6 oxygen atoms on each side. The (l) means liquid and the (g) means gas.', 'elec-al-equation'),
  ],
}
