import type { TeachingFrame } from '../../teachingFrame'

// Three phases told in order: volcanoes, then carbon dioxide removed (oceans, sediments, plants and algae), then oxygen builds up.
// Crude oil formation is linked in one clause, not re-taught. Photosynthesis is recalled from Biology, with the equation shown once.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const atmosphereFrames: Record<string, TeachingFrame[]> = {
  'C45-02': [
    f('Volcanoes everywhere', 'For the first billion years or so, the Earth was covered in volcanoes that gave out lots of gas.', 'volcanoes released the gases', 'The Earth is about 4.6 billion years old. In its first billion years or so, its surface was covered in volcanoes. They erupted and gave out lots of gas. Scientists think these gases formed the early atmosphere.', 'atmos-volcanoes'),
    f('A best theory', 'Nobody can measure the early atmosphere, so this is our best theory, not a certain fact.', 'a theory, not a certainty', 'It is hard to find evidence from so long ago. So the story of the atmosphere is a theory. It is the best explanation scientists have. Ideas about it have changed a lot over time.', 'atmos-theory'),
    f('Mostly carbon dioxide', 'The early atmosphere was probably mostly carbon dioxide, with little or no oxygen.', 'lots of carbon dioxide, hardly any oxygen', 'The early atmosphere was probably mostly carbon dioxide. There was little or no oxygen. This is quite like the atmospheres of Mars and Venus today.', 'atmos-early-gases'),
    f('The other gases', 'Volcanoes also gave out nitrogen, water vapour and small amounts of methane and ammonia.', 'nitrogen built up over time', 'Volcanoes also gave out nitrogen, which built up in the atmosphere over time. They gave out water vapour too. There were small amounts of methane and ammonia as well.', 'atmos-volcano-other'),
    f('The oceans form', 'The Earth cooled. Water vapour condensed into liquid water and formed the oceans.', 'vapour cools into liquid', 'As the Earth cooled, the water vapour in the early atmosphere condensed. This means it turned into liquid water. The liquid water collected and formed the oceans.', 'atmos-oceans'),
  ],
  'C45-05': [
    f('Carbon dioxide is removed', 'Over time much of the carbon dioxide left the atmosphere. A lot of it dissolved in the oceans.', 'the amount of carbon dioxide fell', 'Over time, much of the carbon dioxide was removed from the atmosphere. Lots of it dissolved in the oceans. The next frames show where the carbon went.', 'atmos-dissolve'),
    f('Carbonates and sediments', 'Dissolved carbon dioxide formed carbonates, which settled as small solid particles called sediments.', 'dissolved carbon becomes solid', 'The dissolved carbon dioxide formed carbonates. These carbonates precipitated as small, solid particles. Precipitation is when an insoluble solid forms from a solution. The particles are called sediments.', 'atmos-sediments'),
    f('Plants and algae join in', 'When algae and green plants evolved, they took in carbon dioxide for photosynthesis.', 'plants and algae take in carbon dioxide', 'Later, algae and green plants evolved. They took in some of the carbon dioxide for photosynthesis. So they removed carbon dioxide from the air too.', 'atmos-photo-uptake'),
    f('Carbon locked in rock', 'Dead sea creatures were buried and squashed over millions of years. This made sedimentary rocks and fossil fuels.', 'buried remains trap carbon', 'When sea creatures die, they fall to the seabed and get buried. Over millions of years they are squashed. This forms sedimentary rocks and fuels such as oil and gas. The carbon from the creatures gets trapped inside them.', 'atmos-locked'),
    f('Fossil fuels and limestone', 'Coal, crude oil and natural gas are fossil fuels. Limestone is mostly calcium carbonate from shells and skeletons.', 'coal from plants, limestone from shells', 'Coal, crude oil and natural gas are called fossil fuels. Crude oil and natural gas form from plankton that settled on the seabed, as you saw in the crude oil lesson. Coal forms from thick layers of plants. Limestone is mostly calcium carbonate from shells and skeletons of sea creatures.', 'atmos-fossil'),
  ],
  'C45-08': [
    f('Algae make oxygen', 'Algae evolved about 2.7 billion years ago. Green plants evolved over the next billion years or so.', 'algae first, then plants', 'Algae evolved about 2.7 billion years ago. Green plants evolved over the next billion years or so. Both use photosynthesis, and photosynthesis makes oxygen.', 'atmos-algae'),
    f('Photosynthesis', 'Photosynthesis uses carbon dioxide and water, with light, to make glucose and oxygen.', 'carbon dioxide in, oxygen out', 'In photosynthesis, carbon dioxide and water react, using light, to make glucose and oxygen. The symbol equation is 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. Notice that carbon dioxide is used up and oxygen is made.', 'atmos-photo-eq'),
    f('Oxygen builds up', 'Over time oxygen built up in the atmosphere. This meant that animals could evolve.', 'oxygen rises, carbon dioxide falls', 'Over time, oxygen levels built up in the atmosphere. Carbon dioxide levels fell as it was taken in and locked away. The extra oxygen meant that animals could evolve.', 'atmos-oxygen-rise'),
    f('The air today', 'For about the last 200 million years the air has been about 80% nitrogen and 20% oxygen.', 'four fifths nitrogen, one fifth oxygen', 'The proportions of gases in the atmosphere have been similar for about the last 200 million years. Air is about 80% (four fifths) nitrogen and 20% (one fifth) oxygen. There are also small amounts, less than 1%, of other gases.', 'atmos-air-today'),
    f('The other gases', 'The remaining gases are mainly carbon dioxide, noble gases and water vapour.', 'a tiny slice of the air', 'The small amounts of other gases are mainly carbon dioxide, noble gases and water vapour. Together they make up less than 1% of the air.', 'atmos-other-gases'),
    f('Three phases together', 'Phase 1: volcanoes gave out gases. Phase 2: carbon dioxide was removed. Phase 3: plants and algae made oxygen.', 'volcanoes, then removal, then oxygen', 'Put the story in order. First, volcanoes gave out gases and the oceans formed. Next, carbon dioxide was removed by the oceans, algae and plants. Then algae and plants produced oxygen.', 'atmos-timeline'),
  ],
}
