import type { TeachingFrame } from '../../teachingFrame'

// Follow one pair of atoms, sodium and chlorine, from electron transfer to the ionic bond, then learn to draw it
// (dot and cross, then MgO and MgCl2), zoom out to the giant lattice, read a formula from it, and finally explain the
// properties from the lattice. Each step needs the one before: no lattice without the bond, no properties without the lattice.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const ionicFrames: Record<string, TeachingFrame[]> = {
  'C13-02': [
    f('Metal meets non-metal', 'Sodium is a metal and chlorine is a non-metal.', 'metal + non-metal → neither outer shell is full', 'Metals and non-metals can react together. Sodium is a metal with one electron in its outer shell. Chlorine is a non-metal with seven electrons in its outer shell. Neither atom has a full outer shell.', 'ionic-bond-atoms'),
    f('One electron moves', 'Sodium’s outer electron moves across to chlorine.', 'sodium loses 1 → chlorine gains 1', 'When they react, sodium’s one outer electron moves to the chlorine atom. So sodium loses an electron and chlorine gains one. Moving electrons from one atom to another is called electron transfer. In the drawing, sodium’s electrons are dots and chlorine’s are crosses.', 'ionic-bond-transfer'),
    f('Two ions', 'Both atoms become ions with full outer shells.', 'lose → positive ion, gain → negative ion', 'You met ions when you learned how ions form. Sodium has lost an electron, so it becomes a positive sodium ion, Na⁺. Chlorine has gained one, so it becomes a negative chloride ion, Cl⁻. Both ions now have a full outer shell, like a noble gas.', 'ionic-bond-ions'),
    f('Opposites attract', 'The positive and negative ions pull strongly on each other.', 'positive + negative → strong pull', 'Opposite charges attract each other. So the positive sodium ion and the negative chloride ion pull strongly towards each other. A pull between electric charges is called an electrostatic force.', 'ionic-bond-attract'),
    f('Put it together', 'The strong attraction between the ions is an ionic bond.', 'transfer → ions → attraction → ionic bond', 'Sodium gave one electron to chlorine, and the ions formed attract each other strongly. This strong attraction between oppositely charged ions is called an ionic bond. It holds the ions together in a compound, sodium chloride. A compound held together by ionic bonds is an ionic compound.', 'ionic-bond-all'),
  ],
  'C13-05': [
    f('Dots and crosses', 'Each electron is drawn as a dot or a cross.', 'dot = from one atom, cross = from the other', 'This drawing is called a dot and cross diagram. It shows how the electrons are arranged in atoms and ions. Here, the dots are sodium’s electrons and the crosses are chlorine’s. So you can see which atom each electron came from: the chloride ion has one dot among its crosses.', 'ionic-dc-nacl'),
    f('Brackets and charges', 'Each ion goes in square brackets with its charge.', 'ion → square brackets → charge at top right', 'Each ion is drawn inside square brackets. Its charge is written outside the brackets, at the top right. The sodium ion has +, and the chloride ion has −. When the charge is more than one, the number goes first, for example 2+.', 'ionic-dc-brackets'),
    f('Outer shells only', 'Magnesium gives two electrons to oxygen.', 'Mg loses 2 → Mg²⁺; O gains 2 → O²⁻', 'Diagrams often show only the outer shells, because those electrons are the ones that move. Magnesium is in Group 2, so it loses its two outer electrons. Oxygen is in Group 6, so it gains two. This makes a magnesium ion, Mg²⁺, and an oxide ion, O²⁻: magnesium oxide.', 'ionic-dc-mgo'),
    f('One magnesium, two chlorines', 'One magnesium atom gives one electron to each of two chlorine atoms.', 'Mg loses 2, each Cl gains 1 → MgCl₂', 'A chlorine atom only needs one extra electron. But a magnesium atom must lose two. So one magnesium atom gives one electron to each of two chlorine atoms. This makes one Mg²⁺ ion and two Cl⁻ ions: magnesium chloride, MgCl₂.', 'ionic-dc-mgcl2'),
    f('What they leave out', 'Dot and cross diagrams are useful, but they do not show everything.', 'shows where electrons came from, not size or arrangement', 'Dot and cross diagrams are good for showing how ionic compounds form. But they do not show how big the ions are. They do not show how the ions are arranged in the compound. They also make dots and crosses look different, but really all electrons are the same.', 'ionic-dc-limits'),
  ],
  'C13-08': [
    f('A regular pattern', 'In an ionic compound, the ions are packed in a regular pattern.', 'many + and − ions → alternating pattern → lattice', 'A single grain of salt holds billions of ions, not just one pair. The positive and negative ions are packed in a regular, repeating pattern. Each ion sits next to ions with the opposite charge. This huge, regular arrangement of ions is called a giant ionic lattice.', 'ionic-lattice-layer'),
    f('Bonds in all directions', 'Each ion is attracted by the oppositely charged ions all around it.', 'one ion → pulled from every side → strong structure', 'Pick any sodium ion in the lattice. It is surrounded by chloride ions, and it attracts every one of them. So the ionic bonds act in all directions, including above and below this layer. This holds the whole lattice together very strongly.', 'ionic-lattice-directions'),
    f('Ball-and-stick model', 'Balls for ions and sticks between them show the arrangement.', 'shows the arrangement, but the gaps are not real', 'This drawing is called a ball-and-stick model. It shows clearly how the sodium and chloride ions alternate in 3D. But it makes the ions look far apart, with gaps between them. Really, the ions are packed tightly together. It does not show the sizes of the ions either.', 'ionic-lattice-ballstick'),
    f('Space-filling model', 'Touching balls show how big the ions are.', 'shows the sizes, but only the outside can be seen', 'In a space-filling model, the ions are drawn touching, at their real relative sizes. It shows that chloride ions are bigger than sodium ions. It also shows the regular pattern. But you can only see the ions on the outside of the model.', 'ionic-lattice-spacefill'),
  ],
  'C13-11': [
    f('Count the ions', 'A lattice diagram lets you count each kind of ion.', 'count the Na⁺ ions, count the Cl⁻ ions', 'You can find the formula of an ionic compound from a diagram of its lattice. First, count each kind of ion in the diagram. This ball-and-stick model has 9 sodium ions and 9 chloride ions.', 'ionic-formula-count'),
    f('Simplest ratio', 'Cancel the numbers down to the smallest whole numbers.', '9 : 9 → 1 : 1 → NaCl', 'Next, cancel the numbers down to the simplest whole-number ratio. 9 : 9 cancels to 1 : 1, so there is one sodium ion for every chloride ion. So the formula is NaCl. A formula that gives the simplest ratio of ions is called an empirical formula.', 'ionic-formula-ratio'),
    f('Use the charges', 'The charges in a formula must add up to zero.', 'K⁺ and O²⁻ → total charge must be 0', 'You can also find a formula from the charges on the ions. Potassium is in Group 1, so it forms K⁺ ions. Oxygen is in Group 6, so it forms O²⁻ ions. An ionic compound has no overall charge, so the charges must add up to zero.', 'ionic-formula-charges'),
    f('Balance and write', 'Two K⁺ ions balance one O²⁻ ion, so the formula is K₂O.', '+1 + 1 − 2 = 0 → K₂O', 'One K⁺ ion only balances half of the 2− charge. So you need two K⁺ ions for each O²⁻ ion. Check: +1 + 1 − 2 = 0. So the empirical formula of potassium oxide is K₂O. The small 2 after K means two potassium ions.', 'ionic-formula-balance'),
  ],
  'C13-13': [
    f('Hard to melt', 'Ionic compounds have high melting and boiling points.', 'many strong bonds → lots of energy → high melting point', 'To melt a solid, its particles must be pulled apart. In an ionic lattice, that means breaking lots of strong ionic bonds. This takes a lot of energy. So ionic compounds have high melting points and high boiling points. Sodium chloride melts at 801 °C.', 'ionic-prop-melt'),
    f('Solid: no current', 'Solid ionic compounds do not conduct electricity.', 'ions held in place → cannot carry charge', 'An electric current is a flow of charge. In a solid ionic compound, the ions are charged but held in place in the lattice. They cannot move, so they cannot carry charge. So solid ionic compounds do not conduct electricity.', 'ionic-prop-solid'),
    f('Molten: current flows', 'Melted ionic compounds do conduct.', 'melted → ions free to move → carry charge', 'When an ionic compound melts, the ions are free to move around. Moving ions can carry electric charge. So a melted ionic compound conducts electricity. A melted substance is called molten.', 'ionic-prop-molten'),
    f('Dissolved: current flows', 'Ionic compounds dissolved in water conduct too.', 'dissolved → ions move through the water → conducts', 'Many ionic compounds dissolve in water. The lattice breaks up and the ions spread out through the water. The ions can move in the solution, so they carry charge. So a solution of an ionic compound conducts electricity.', 'ionic-prop-dissolved'),
    f('Put it together', 'Ions that can move carry charge; ions held in place cannot.', 'solid ✗ · molten ✓ · dissolved ✓', 'Ionic compounds have high melting points because of their many strong ionic bonds. They conduct electricity only when their ions can move: when molten or dissolved. Next, you will see how non-metal atoms bond in a different way, by sharing electrons.', 'ionic-prop-summary'),
  ],
}
