import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { hormonesFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.5.3.1 Human endocrine system: endocrine glands, hormones carried in the blood to target organs, the six named glands, and the endocrine system compared with the nervous system' }
const a = author('B-HORMONES', ['4.5.3.1'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const hormonesSections = [
  { id: 'B33-01', label: 'Start here', detail: 'What does the blood carry?' },
  { id: 'B33-02', label: 'What is a hormone?', detail: 'Glands, the blood and target organs' },
  { id: 'B33-05', label: 'Where are the glands?', detail: 'Six glands and their hormones' },
  { id: 'B33-09', label: 'Nerves or hormones?', detail: 'Fast and precise, or slower and longer' },
  { id: 'B33-12', label: 'On your own', detail: 'Glands, responses and data' },
]

const states: ScienceState[] = [
  { ...a.choice('B33-01', 'Blood carries many substances around the body. Which part of the blood carries dissolved substances, such as glucose?', ['Red blood cells', 'Plasma', 'Platelets', 'White blood cells'], 1, 'You met the parts of the blood when you learned about blood.', ['Red blood cells carry oxygen, platelets help blood clot and white blood cells defend the body.', 'Plasma is the liquid part of the blood, so it carries dissolved substances.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B33-02', 'What is a hormone?'),
  a.choice('B33-03', 'How does a hormone travel from its gland to its target organ?', ['Along neurones, as an electrical impulse', 'Through a tube, straight to the target organ', 'In the blood', 'Through the air in the lungs'], 2, 'Where does an endocrine gland release its hormone?', ['Endocrine glands release hormones directly into the blood, not into a tube.', 'So the blood carries hormones to their target organs.']),
  a.choice('B33-04', 'A hormone reaches every organ in the body, but only the liver responds to it. What is the liver for this hormone?', ['The gland that made it', 'The endocrine system', 'A nerve', 'A target organ'], 3, 'What do we call an organ that responds to a hormone?', ['The hormone reaches almost every organ, but most do not respond.', 'An organ that responds to a hormone is a target organ.']),
  t('B33-05', 'Where are the glands?'),
  a.choice('B33-06', 'Look at the numbered glands. Which number shows the pancreas?', ['Gland 1', 'Gland 2', 'Gland 3', 'Gland 4'], 3, 'The pancreas sits just below the stomach.', ['Gland 1 is the pituitary gland, gland 2 the thyroid gland and gland 3 the adrenal glands.', 'Gland 4, just below the stomach, is the pancreas.'], 'understanding', false, 'hormone-glands-question'),
  a.choice('B33-07', 'Why is the pituitary gland called the “master gland”?', ['It is the largest gland in the body', 'Its hormones act on other glands and make them release hormones', 'It makes every hormone in the body', 'It sends electrical impulses to the brain'], 1, 'What do many of its hormones act on?', ['Many pituitary hormones have other glands as their target organs.', 'They make those glands release their own hormones, so the pituitary is called the master gland.']),
  a.choice('B33-08', 'Which hormone gets the body ready for “fight or flight”?', ['Adrenaline', 'Insulin', 'Thyroxine', 'Testosterone'], 0, 'Think about the glands on top of the kidneys.', ['Insulin controls blood glucose, thyroxine affects metabolism and testosterone controls puberty in males.', 'Adrenaline, from the adrenal glands, prepares the body for fight or flight.']),
  t('B33-09', 'Nerves or hormones?'),
  a.choice('B33-10', 'Which statement about hormones, compared with nerves, is correct?', ['Hormones act faster than nerves', 'Hormones act more slowly, and their effects last longer', 'Hormones act only on one precise area', 'Hormones travel along neurones'], 1, 'How do hormones travel, and how does that affect speed?', ['Hormones travel in the blood, which is slower than an electrical impulse along a neurone.', 'So hormones act more slowly, and their effects last longer.']),
  a.choice('B33-11', 'Which response is most likely to be controlled by nerves?', ['Growing taller during puberty', 'Making sperm over many years', 'Blinking when dust flies towards your eye', 'Keeping blood glucose steady all day'], 2, 'Which response needs to be very fast and precise?', ['Puberty, sperm production and blood glucose control all happen over a long time, so hormones control them.', 'Blinking must happen very fast in one precise place, so nerves control it.']),
  a.choice('B33-12', 'Before a race, Priya’s heart is pounding and she is ready to run. Which gland released the hormone causing this?', ['Thyroid gland', 'Pancreas', 'Adrenal glands', 'Testes'], 2, 'Which hormone gets the body ready for action?', ['Adrenaline gets the body ready for fight or flight, such as a race.', 'Adrenaline is released by the adrenal glands.'], 'application', true),
  a.choice('B33-13', 'Look at the numbered glands. Which gland releases a hormone that controls puberty and sperm production?', ['Gland 1', 'Gland 3', 'Gland 5', 'Gland 6'], 3, 'Which hormone controls sperm production, and where is it made?', ['Testosterone controls puberty and sperm production in males.', 'Testosterone is made by the testes, gland 6.'], 'understanding', true, 'hormone-glands-question'),
  a.choice('B33-14', 'The table shows two responses measured in one person. Which conclusion fits the data best?', ['Response A is more likely to be controlled by hormones', 'Response B is more likely to be controlled by hormones', 'Both responses must be controlled by nerves', 'The data prove that every slow response is caused by hormones'], 1, 'Hormones act more slowly and for longer. Which response matches?', ['Response B starts later and lasts much longer than response A, but two responses cannot prove a rule for every response.', 'So response B is more likely to be controlled by hormones.'], 'dataInterpretation', true, 'hormone-response-data'),
  a.choice('B33-15', 'A hormone is added to the blood of a mouse. Only the mouse’s liver responds. What is the best explanation?', ['The liver is a target organ for this hormone', 'The hormone only reached the liver', 'The liver made the hormone', 'Nerves carried the hormone to the liver'], 0, 'Does the blood carry a hormone to one organ, or all of them?', ['The blood carries a hormone all around the body, so it reached almost every organ.', 'Only the liver responded, so the liver is a target organ for this hormone.'], 'application', true),
  a.written('B33-16', 'Explain how insulin gets from the pancreas to the liver. Give one way this differs from a nerve response.', 'Say where the gland releases the hormone, how it travels and why the liver responds. Then compare speed or how long the effect lasts.', 'The pancreas is an endocrine gland, so it releases insulin directly into the blood. The blood carries insulin all around the body. The liver responds because it is a target organ for insulin. Hormones act more slowly than nerves, but their effects last longer.', ['The pancreas releases insulin directly into the blood.', 'The blood carries insulin around the body.', 'The liver responds because it is a target organ for insulin.', 'A correct difference: hormones act more slowly, last longer or act more generally than nerves.'], ['Saying insulin travels along nerves or neurones.', 'Saying insulin travels through a tube straight to the liver.', 'Saying hormones act faster than nerves.', 'Saying the liver makes insulin.']),
]

export const lesson33: ScienceLesson = {
  id: 'B-HOM-033-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Hormones and the endocrine system', prerequisites: ['B-BLOOD'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
