import type { ScienceLesson, ScienceState } from '../types'
import { author, biologySource, sampledRequirements } from '../lessonAuthoring'
import { exchangeFrames as frames } from './teachingFrames'

const a = author('B-CELL-TRANSPORT', ['4.1.3.1', '4.1.3.2', '4.1.3.3'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])
const visual = <S extends ReturnType<typeof a.choice>>(state: S, id: string, description: string): S => ({ ...state, visual: { id, kind: 'cellModel' as const, brief: 'Original Revily schematic; not to scale.', accessibleDescription: description, assessmentDescription: 'An unlabelled original schematic. All information needed to answer is provided in the question.' } })

export const exchangeSections = [
  { id: 'B6-60', label: 'Start here', detail: 'Which way did the water go?' },
  { id: 'B6-13', label: 'Can cells move things uphill?', detail: 'Active transport in roots and the gut' },
  { id: 'B6-15', label: 'Which process is it?', detail: 'Diffusion, osmosis and active transport' },
  { id: 'B6-18', label: 'Why does size matter?', detail: 'Surface area to volume ratio' },
  { id: 'B6-19', label: 'Work out SA:V', detail: 'A cube, step by step' },
  { id: 'B6-21', label: 'What makes a good exchange surface?', detail: 'Large, thin and well supplied' },
  { id: 'B6-38', label: 'On your own', detail: 'Ratios, data and a root hair' },
]

const states: ScienceState[] = [
  { ...a.choice('B6-60', 'In the osmosis practical, a piece of potato in pure water gained mass. Which way did water move overall?', ['Out of the potato and into the pure water', 'Into the potato, from the dilute water to the more concentrated cell contents', 'Water stopped moving once the potato was in the water'], 1, 'Which side was more dilute: the pure water or the potato cells?', ['Pure water is more dilute than the cell contents.', 'So water moved into the potato by osmosis, and the potato gained mass.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B6-13', 'Can cells move things uphill?'),
  a.choice('B6-14', 'Mineral ions move from dilute soil water into a higher concentration in a root hair cell. What does this need?', ['Energy from respiration', 'A higher concentration in the soil than in the cell', 'No cell membrane at all'], 0, 'Is this movement downhill or uphill?', ['Moving from a lower to a higher concentration is active transport, against the gradient.', 'So it needs energy from respiration.']),
  a.choice('B6-16', 'Sugar moves from a lower concentration in the gut to a higher concentration in the blood. Which process allows this?', ['Osmosis', 'Active transport', 'Diffusion down the gradient'], 1, 'Which way is the sugar moving: lower to higher, or higher to lower?', ['Sugar is not water, so this is not osmosis.', 'So moving it from lower to higher concentration needs active transport.']),
  t('B6-15', 'Which process is it?'),
  a.choice('B6-17', 'Which comparison is correct?', ['Osmosis moves all dissolved substances, using respiration', 'Diffusion always goes against the gradient', 'Active transport uses energy; diffusion has net movement down the gradient'], 2, 'Think about direction first. Then think about energy.', ['Active transport needs energy from respiration.', 'So diffusion, which needs no energy, has net movement from a higher to a lower concentration.']),
  a.choice('B6-61', 'Water moves from dilute soil water into a root hair cell, across its membrane. Which process is this?', ['Osmosis', 'Active transport', 'Diffusion of mineral ions'], 0, 'Ask the three questions. What is moving?', ['Only water is moving, from a dilute to a more concentrated solution.', 'So this is osmosis, and it needs no energy from respiration.']),
  t('B6-18', 'Why does size matter?'),
  a.choice('B6-20', 'A 1 cm cube has an SA:V of 6:1. A 2 cm cube has an SA:V of 3:1. Which has more surface compared with its volume?', ['The 1 cm cube', 'The 2 cm cube', 'Both are the same'], 0, 'Compare the ratios, not the total surface area.', ['6:1 is bigger than 3:1.', 'So the smaller cube has more surface for each cm³ of volume.'], 'calculation'),
  a.choice('B6-62', 'Why can a large animal not get enough oxygen through its skin alone?', ['Large animals need no oxygen in their inner cells', 'Diffusion only happens in plants', 'Its SA:V is small, and its inner cells are far from the surface', 'Its skin has a larger SA:V than a single cell'], 2, 'What happens to SA:V as an organism gets bigger?', ['A large animal has a small SA:V, and its inner cells are far from the outside.', 'So it needs exchange surfaces and a transport system instead.']),
  a.worked('B6-19', 'Work out SA:V', 'A cube has sides of 2 cm. Find its surface area and volume, then write SA:V.', ['Area of one face = 2 × 2 = 4 cm². A cube has six faces, so the surface area is 6 × 4 = 24 cm².', 'Volume = length × width × height = 2 × 2 × 2 = 8 cm³.', 'SA:V = 24:8. Divide both numbers by 8 to get 3:1. This ratio uses the given cm measurements.'], 'ratio-worked'),
  a.choice('B6-63', 'A cube has sides of 6 cm. What is its SA:V?', ['6:1', '1:6', '1:1'], 2, 'Find the area of one face, then times by six. Then find the volume.', ['One face is 6 × 6 = 36 cm², so the surface area is 6 × 36 = 216 cm². The volume is 6 × 6 × 6 = 216 cm³.', 'So SA:V = 216:216, which is 1:1.'], 'calculation'),
  t('B6-21', 'What makes a good exchange surface?'),
  a.choice('B6-22', 'Why does a thin exchange surface help diffusion?', ['It makes the particles bigger', 'It gives a shorter distance to cross', 'It stops all movement'], 1, 'What did a thin wall do to the diffusion distance?', ['A thin surface makes the diffusion distance short.', 'So substances cross it quickly.']),
  a.choice('B6-24', 'Which statement about plant exchange surfaces is correct?', ['Root hairs are supplied with blood', 'All leaf gases enter by active transport', 'Root hairs give a large area for taking in water and ions; stomata let gases in and out of leaves'], 2, 'Match each plant part to its job: taking in from the soil, or letting gases through.', ['Plants have no blood. Root hairs give a large surface area for taking in water and ions.', 'So the correct statement also says that stomata let gases in and out of the leaf.']),
  a.choice('B6-38', 'A model cube has sides of 3 cm. What is its SA:V?', ['27:54', '1:3', '6:1', '2:1'], 3, 'Find the surface area and the volume, then simplify.', ['Surface area = 6 × 3 × 3 = 54 cm². Volume = 3 × 3 × 3 = 27 cm³.', 'So SA:V = 54:27. Divide both by 27 to get 2:1.'], 'calculation', true),
  a.choice('B6-64', 'Jelly cubes were left in coloured dye. In this test, the 1 cm cube was coloured all through after 4 minutes, the 2 cm cube after 15 minutes and the 3 cm cube after 35 minutes. Which conclusion fits?', ['Dye cannot get into large cubes', 'Bigger cubes have a bigger SA:V, so they coloured faster', 'This proves that every large animal needs lungs', 'In this test, the bigger the cube, the longer the dye took to reach the middle'], 3, 'Only say what these results show.', ['The times went up from 4 to 15 to 35 minutes as the cubes got bigger.', 'So in this test, dye took longer to reach the middle of bigger cubes. One test with jelly cannot prove what happens in every animal.'], 'dataInterpretation', true),
  visual(a.choice('B6-37', 'This root hair cell is in soil. There are fewer mineral ions in the soil than inside the cell. How do the ions get in?', ['By diffusion, with no energy used', 'By active transport, using energy from respiration', 'By osmosis, like the water', 'They cannot get in until the soil has more ions'], 1, 'Are the ions moving downhill or uphill?', ['The ions move from a lower concentration in the soil to a higher one in the cell.', 'So they enter by active transport, which uses energy from respiration.'], 'application', true), 'root', 'One root hair cell reaching between soil particles, with arrows showing water and mineral ions moving into the hair.'),
  a.written('B6-65', 'A tiny single-celled organism gets enough oxygen through its surface. A cow cannot. Explain why, and describe two features that help the cow’s exchange surfaces work well.', 'First compare the two SA:V ratios. Then pick two features, and say how each one helps.', 'The single-celled organism has a large SA:V, and nothing inside it is far from the surface. The cow has a small SA:V, and its inner cells are far from the outside, so diffusion through the skin would be too slow. Its exchange surfaces have a large surface area, so more can cross at once. They are thin, so the diffusion distance is short. A good blood supply carries substances away, so the concentration gradient stays steep.', ['The single-celled organism has a large SA:V, so diffusion through its surface is enough.', 'The cow has a small SA:V, and its inner cells are far from the surface.', 'One feature explained, such as a large surface area letting more cross at once.', 'A second feature explained, such as a thin surface giving a short diffusion distance, or blood flow keeping the gradient steep.'], ['The cow is said to have a larger SA:V than the single-celled organism.', 'Features are listed with no explanation of how they help.', 'Diffusion across the exchange surface is said to need energy from respiration.']),
]

export const lesson6c: ScienceLesson = {
  id: 'B-CELL-006C-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Active transport and exchange surfaces', prerequisites: ['B-OSMOSIS-PRACTICAL', 'B-SPECIALISATION'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [biologySource], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
