import type { TeachingFrame } from '../../teachingFrame'

// The eight energy stores, the four ways energy is transferred, then systems and closed systems.
// Conservation, dissipation detail and calculations belong to the next lessons; only a one-clause pointer here.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const storeFrames: Record<string, TeachingFrame[]> = {
  'P1-02': [
    f('Energy is kept in stores', 'Energy is never used up. It is kept in different places called energy stores, and it can move from one store to another.', 'a store is where energy is kept', 'Energy is not something that gets used up. It is kept in different places called energy stores. When something happens, energy moves from one store to another. Each store has a name, so we can say exactly what has changed.', 'estore-idea'),
    f('Kinetic and thermal stores', 'Anything moving has energy in its kinetic store. Every object has energy in its thermal store, and the hotter it is, the more it holds.', 'moving = kinetic, hot = thermal', 'Anything that is moving has energy in its kinetic store. A rolling ball and a running dog both have one. Every object also has energy in its thermal store. The hotter the object is, the more energy is in this store.', 'estore-motion-heat'),
    f('The chemical store', 'Anything that can release energy by a chemical reaction has energy in its chemical store, such as food, fuel and batteries.', 'food, fuel, batteries', 'Food, fuel and batteries all have energy in a chemical store. It is released when a chemical reaction happens. Your body releases energy from the chemical store of food, and this lets you move.', 'estore-chemical'),
    f('Gravitational and elastic potential', 'Raised objects have energy in a gravitational potential store. Stretched or squashed objects have energy in an elastic potential store.', 'raised, or stretched and squashed', 'Any object raised above the ground has energy in its gravitational potential store. A book on a high shelf is an example. Anything stretched or squashed has energy in its elastic potential store. Springs and rubber bands are examples.', 'estore-potential'),
    f('Electrostatic and magnetic', 'Two charges that attract or repel each other have energy in an electrostatic store. Two magnets that attract or repel have energy in a magnetic store.', 'pushing or pulling at a distance', 'Some things push or pull on each other without touching. Two electric charges that attract or repel each other have energy in their electrostatic store. Two magnets that attract or repel each other have energy in their magnetic store.', 'estore-fields'),
    f('The nuclear store', 'The nucleus of an atom releases energy from its nuclear store in nuclear reactions. That makes eight stores altogether.', 'inside the atom, eight stores', 'The nucleus at the centre of an atom has energy in its nuclear store. This energy is released in nuclear reactions, such as those in a nuclear power station. Kinetic, thermal, chemical, gravitational potential, elastic potential, electrostatic, magnetic and nuclear make eight stores.', 'estore-nuclear'),
  ],
  'P1-06': [
    f('Energy moves between stores', 'Energy can be transferred, which means moved, from one store to another. Say which two stores it moves between.', 'from one store to another', 'Energy can be transferred, or moved, from one store to another. Think of a hot mug of tea warming your cold hands. Energy is transferred from the thermal store of the mug to the thermal store of your hands.', 'estore-transfer'),
    f('By heating and by radiation', 'Heating moves energy from a hotter object to a colder one. Radiation moves energy by light and sound.', 'hot to cold, light and sound', 'One way energy is transferred is by heating. This is when energy moves from a hotter object to a colder object. Another way is by radiation. This is when energy is transferred by light or sound. Energy from the Sun reaches the Earth by light.', 'estore-heat-radiation'),
    f('Mechanically and electrically', 'A force moving an object transfers energy mechanically. A current flowing transfers energy electrically.', 'force or current', 'A third way is mechanically. This happens when a force moves an object, such as when you push a box along the floor. The fourth way is electrically. This happens when a current flows, such as when a current flows through a lamp.', 'estore-mech-elec'),
    f('Describing a transfer', 'Name the store the energy leaves, the store it reaches and how it moves: from the ... store to the ... store by ...', 'from, to, by', 'To describe a transfer, name the store the energy leaves, the store it reaches, and the way it moves. When a battery-powered toy car speeds up, energy is transferred electrically from the chemical store of the battery to the kinetic store of the car.', 'estore-describe'),
  ],
  'P1-09': [
    f('What is a system?', 'A system is the object, or the group of objects, that you are looking at.', 'the thing you are studying', 'A system is the object or the group of objects that you are studying. It can be a single object, such as a tennis ball. It can also be a group of objects, such as a bat and a ball.', 'estore-system'),
    f('A changing system', 'When a system changes, energy is transferred to a different store, in one of the four ways.', 'change means a transfer', 'Something changes when energy is transferred. A bath of hot water is a system. As it cools, energy is transferred from the thermal store of the water to the thermal store of the room by heating.', 'estore-change'),
    f('Closed systems', 'In a closed system, no matter and no energy can enter or leave.', 'nothing in, nothing out', 'A closed system is a system where no matter can enter or leave. No energy can enter or leave either. It is like a locked box. Whatever happens inside, nothing goes in and nothing comes out.', 'estore-closed'),
    f('The total stays the same', 'When a closed system changes, there is no overall change in the total energy of the system.', 'energy moves around inside', 'Imagine a hot metal block and a cold metal block sealed in an insulated box. Energy is transferred by heating from the hot block to the cold block. Energy has moved inside the box, but the total energy is exactly the same as before.', 'estore-closed-blocks'),
  ],
}
