import type { TeachingFrame } from '../../teachingFrame'

// Comparing two products with LCA information (plastic and paper bags), reaching a conclusion, then the problems with LCAs.
// The four stages are recalled from the previous lesson, not re-taught. Fractional distillation, cracking and polymerisation are named from earlier lessons.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const lcaCompareFrames: Record<string, TeachingFrame[]> = {
  'C52-02': [
    f('Two bags, one question', 'LCA information can be used to compare similar products and decide which is the least harmful to the environment.', 'compare stage by stage', 'LCAs can be used to compare similar products. Here the products are a plastic bag and a paper bag. We compare them stage by stage. Then we decide which is the least harmful to the environment.', 'lcause-task'),
    f('Raw materials and making them', 'Plastic bags start as crude oil. Paper bags start as wood, which is pulped using lots of energy.', 'crude oil or wood', 'A plastic bag is made from compounds taken from crude oil by fractional distillation. They are then cracked and made into polymers. Other fractions of the oil have other uses, so little waste is made. A paper bag starts as wood. Making pulp from wood uses lots of energy and makes lots of waste.', 'lcause-make'),
    f('Using the bag', 'A plastic bag can be reused several times. A paper bag is usually used only once.', 'how many uses?', 'A plastic bag can be reused several times. It can also be used for other things, such as a bin liner. A paper bag is usually used only once.', 'lcause-use'),
    f('Throwing the bag away', 'Plastic bags are recyclable, but many types are not biodegradable and take up space in landfill. Paper is recyclable, biodegradable and non-toxic.', 'biodegradable or not', 'Biodegradable means it can be broken down naturally by microorganisms, which are tiny living things such as bacteria. Plastic bags can be recycled, but many types of plastic are not biodegradable. They take up space in landfill and pollute land. Paper bags can be recycled and are biodegradable and non-toxic.', 'lcause-dispose'),
    f('The comparison table', 'Put the four stages side by side for both bags, then weigh them up.', 'four rows, two bags', 'The table now has a row for each of the four stages and a column for each bag. Each bag has good points and bad points. To decide, we must look at all the rows together.', 'lcause-table'),
  ],
  'C52-05': [
    f('Weigh up the good and the bad', 'Each product has good and bad points. Pick the one that affects the environment the least overall.', 'least harm overall', 'No bag is perfect. Each has good and bad points at different stages. The job is to weigh them all up. Then pick the bag that affects the environment the least overall.', 'lcause-weigh'),
    f('A surprising conclusion', 'Plastic bags are not usually biodegradable, but they may be less harmful: they take less energy to make and last longer.', 'less energy and a longer life', 'LCAs have shown that plastic bags are not usually biodegradable. Even so, they may be less harmful to the environment than paper bags. This is because they take less energy to make. They also have a longer lifespan, because they can be reused.', 'lcause-verdict'),
    f('Back up each reason', 'A good conclusion names the stage each reason comes from, such as energy at manufacture or reuse at the using stage.', 'name the stage for each reason', 'When you give a conclusion, back it up with information from the table. Say which stage each reason comes from. Less energy to make comes from the manufacture stage. A longer lifespan comes from the using stage.', 'lcause-evidence'),
  ],
  'C52-08': [
    f('Some effects are easy to measure', 'Energy used, natural resources used and waste produced can be measured, so they can be given as numbers.', 'numbers you can measure', 'Some effects of a product are easy to measure, so they can be given as numbers in an LCA. Examples are the amount of energy used to make it and the natural resources used. The amount of waste produced is another.', 'lcause-measure'),
    f('Some are hard to measure', 'How unattractive litter looks is hard to measure, so the person doing the assessment must use their own judgement.', 'a judgement, not a number', 'Other effects are much harder to measure. Litter from plastic bags does not look nice. But there is no simple way to measure how unattractive something looks. The person doing the assessment has to use their own judgement.', 'lcause-hard'),
    f('Judgement can cause bias', 'Because judgements are involved, results can change depending on who does the assessment. This means an LCA can be biased.', 'different people, different results', 'So an LCA can include the feelings of the person doing it as well as facts. The results could change depending on who does the assessment. If something is biased, it favours one point of view in a way that is not backed up by facts.', 'lcause-bias'),
    f('Selective LCAs', 'A selective LCA shows only some of a product’s impacts, so it can be written to support a company’s claims.', 'only some impacts shown', 'A selective LCA only shows some of the impacts a product has on the environment. It can be written to support the claims of a company. That gives the company positive advertising, so a selective LCA can be biased too.', 'lcause-selective'),
  ],
}
