import type { TeachingFrame } from '../../teachingFrame'

// Current, potential difference and resistance first as three ideas with three units, then the closed loop, then charge and Q = I t
// (worked example and time conversion), then the circuit symbols in small groups, then the rules for drawing a circuit.
// V = IR is taught in the next lesson: here the link between resistance and current stays a plain statement.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const circuitFrames: Record<string, TeachingFrame[]> = {
  'P15-02': [
    f('Current is a flow of charge', 'Current is a flow of electrical charge. It is measured in amperes, A.', 'current = flow of charge', 'When electrical charge flows round a circuit, we call the flow a current. Current is measured in amperes. Amperes are often called amps, and the symbol is A.', 'circuit-current'),
    f('Potential difference is the push', 'Potential difference is the driving force that pushes charge round. It is measured in volts, V.', 'pd = the push', 'Charge needs a push to move round a circuit. This push is called potential difference. It is the driving force. A cell or battery provides the push. Potential difference is measured in volts, symbol V. It is also called voltage.', 'circuit-pd'),
    f('Resistance slows the flow', 'Resistance is anything that slows the flow of charge down. It is measured in ohms, Ω.', 'resistance = slows it down', 'Some parts of a circuit make it harder for charge to flow. This is called resistance. Anything that slows the flow of charge down has resistance. Resistance is measured in ohms. The symbol for ohms is the Greek letter omega, Ω.', 'circuit-resistance'),
    f('A complete loop', 'Charge only flows round a complete, closed loop with a source of potential difference. In a single loop the current is the same everywhere.', 'closed loop plus a push', 'Charge only flows if the circuit is a complete loop with no gaps. This is called a closed circuit. The loop must also include a cell or battery, to provide the potential difference. In a single closed loop, the current has the same value everywhere.', 'circuit-loop'),
    f('More resistance, less current', 'For the same potential difference, the greater the resistance, the smaller the current.', 'same push, bigger resistance, smaller current', 'The current through a component depends on two things. One is the potential difference across it. The other is its resistance. With the same push, a bigger resistance means a smaller current. A smaller resistance means a bigger current.', 'circuit-depends'),
  ],
  'P15-05': [
    f('Current is the rate of flow of charge', 'The size of the current tells you how much charge flows past a point every second. Charge is measured in coulombs, C.', 'bigger current, more charge each second', 'A bigger current means more charge passes a point every second. So the current is the rate of flow of charge. Charge itself is measured in coulombs, symbol C. The longer a current flows, the more charge passes through.', 'circuit-charge'),
    f('The equation', 'Charge flow = current × time. In symbols, Q = I × t.', 'Q = I × t', 'Here is the equation. Charge flow, in coulombs, equals current, in amperes, times time, in seconds. In symbols, Q = I × t. The letter Q stands for charge. The time must be in seconds.', 'circuit-formula'),
    f('Minutes into seconds', 'The time must be in seconds. To change minutes into seconds, multiply by 60.', 'minutes × 60 = seconds', 'The equation needs the time in seconds. If the time is in minutes, change it first. There are 60 seconds in 1 minute, so multiply the minutes by 60. For example, 2 minutes is 2 × 60 = 120 seconds.', 'circuit-time'),
  ],
  'P15-09': [
    f('Cell, battery and switches', 'A cell and a battery provide the potential difference. A switch opens or closes the loop.', 'cell, battery, switch', 'Circuit diagrams use standard symbols. A cell is drawn as one long thin line and one short thick line. The long line is the positive side. A battery is two or more cells joined together. A switch is drawn either open, with a gap, or closed.', 'circuit-cell-switch'),
    f('Lamp, fuse and LED', 'A filament lamp is a circle with a cross. A fuse is a rectangle with a line through it. An LED is a diode symbol with two arrows.', 'lamp, fuse, LED', 'A filament lamp is a circle with a cross inside it. A fuse is a rectangle with a line running through it. An LED is a diode symbol in a circle, with two arrows pointing away. The arrows show that it gives out light.', 'circuit-lamp'),
    f('Resistors', 'A resistor is a plain rectangle. A variable resistor is a rectangle with an arrow through it.', 'rectangle, and rectangle with arrow', 'A resistor is drawn as a plain rectangle. A variable resistor is a rectangle with an arrow drawn through it. The arrow shows that its resistance can be changed.', 'circuit-resistor'),
    f('Ammeter and voltmeter', 'An ammeter is a circle with an A. A voltmeter is a circle with a V.', 'A for current, V for potential difference', 'An ammeter is drawn as a circle with the letter A. It measures current. A voltmeter is drawn as a circle with the letter V. It measures potential difference.', 'circuit-meters'),
    f('Diode, LDR and thermistor', 'A diode is a triangle pointing at a bar. An LDR has two arrows pointing at it. A thermistor has a sloping line through it.', 'three special resistors', 'A diode is drawn as a triangle pointing at a bar, inside a circle. An LDR is a resistor inside a circle, with two arrows pointing at it. A thermistor is a resistor with a sloping line drawn through it.', 'circuit-sensors'),
  ],
  'P15-12': [
    f('Two drawing rules', 'Draw all the wires as straight lines, and make sure the circuit is closed.', 'straight wires, closed loop', 'Follow two rules when you draw a circuit. First, draw all the wires as straight lines, with square corners. Second, make sure that the circuit is closed. You should be able to follow a wire from one end of the cell or battery, through every component, to the other end.', 'circuit-rules'),
    f('An ammeter goes in the loop', 'An ammeter measures current, so it goes in the loop and the charge flows through it. This is called being in series.', 'in the loop', 'An ammeter measures the current, so the charge must flow through it. Draw it as part of the loop, in line with the component you are testing. This is called being in series.', 'circuit-series'),
    f('A voltmeter goes across a component', 'A voltmeter measures the potential difference across a component, so it is joined on its own branch. This is called being in parallel.', 'across the component', 'A voltmeter measures the potential difference across a component. So it is joined on a separate branch, across the two ends of that component. This is called being in parallel. The rest of the current does not flow through the voltmeter.', 'circuit-parallel'),
    f('A complete circuit', 'A cell, a closed switch, a lamp and an ammeter in one loop, with a voltmeter across the lamp.', 'check the loop, check the meters', 'Here is a whole circuit. A cell, a closed switch, a lamp and an ammeter are all in one loop. The voltmeter is across the lamp only. Every wire is straight, and the loop is closed, so current can flow.', 'circuit-whole'),
  ],
}
