import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { evolutionFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.6.2.2 Evolution: natural selection and speciation; 4.6.3.1 Evidence for evolution; 4.6.3.3 Extinction' }
const a = author('B-EVOLUTION', ['4.6.2.2', '4.6.3.1', '4.6.3.3'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const evolutionSections = [
  { id: 'B42-01', label: 'Start here', detail: 'Why are animals in snowy places often white?' },
  { id: 'B42-02', label: 'How do species change?', detail: 'Natural selection, one step at a time' },
  { id: 'B42-05', label: 'What is the evidence?', detail: 'Genes, fossils and bacteria' },
  { id: 'B42-08', label: 'How do new species form?', detail: 'Speciation' },
  { id: 'B42-10', label: 'How do species die out?', detail: 'Five causes of extinction' },
  { id: 'B42-13', label: 'On your own', detail: 'Rabbits, five pictures, a beetle graph and two fish' },
]

const states: ScienceState[] = [
  { ...a.choice('B42-01', 'Many animals that live in snowy places have white fur or feathers. Which is the best explanation?', ['The cold bleaches their fur or feathers white', 'White ones were harder to spot, so more of them survived and had young', 'Each animal chose to turn white', 'Rolling in snow turns them white'], 1, 'Think about which animals are more likely to be seen by a predator.', ['An animal cannot bleach or choose its colour, and snow does not change it.', 'White animals were harder to spot, so more survived and had young like them.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B42-02', 'How do species change?'),
  a.choice('B42-03', 'Why are green beetles more likely than brown beetles to pass on their genes?', ['They are more likely to survive and reproduce', 'They choose to have more offspring', 'Their genes change to protect them'], 0, 'Which beetles do the birds find more easily?', ['Birds spot brown beetles more easily on green leaves, so green beetles are more likely to survive.', 'Survivors are more likely to reproduce and pass on their genes.']),
  a.choice('B42-04', 'What happens to the number of green beetles in the population over many generations?', ['It stays the same', 'It falls', 'It rises', 'It rises, then every beetle becomes brown'], 2, 'Whose genes are passed on in each generation?', ['In each generation more green beetles survive to reproduce.', 'So green beetles become more common: their number rises.']),
  t('B42-05', 'What is the evidence?'),
  a.choice('B42-06', 'What could Darwin not explain in his time?', ['Why organisms compete for food', 'That species change over time', 'That some organisms survive better than others', 'How characteristics are passed on to offspring'], 3, 'What were scientists yet to discover in Darwin’s time?', ['Darwin explained survival and change by natural selection.', 'Nobody then knew about genes, so he could not explain how characteristics are passed on.']),
  a.choice('B42-07', 'Which of these is evidence that supports evolution by natural selection?', ['Bacteria becoming resistant to antibiotics', 'Plants growing towards light', 'People getting taller when they eat well'], 0, 'Which one is a change in a whole population, passed on in genes?', ['Growing towards light and eating well are changes during one life, not passed on in genes.', 'Bacteria evolving resistance to antibiotics is evidence for evolution.']),
  t('B42-08', 'How do new species form?'),
  a.choice('B42-09', 'When have two populations become two separate species?', ['When they live in different places', 'When they can no longer breed together to produce fertile offspring', 'When they are different colours', 'When one population is bigger'], 1, 'Think about what the two populations can no longer do.', ['Living apart or looking different does not by itself make separate species.', 'They are separate species when they cannot breed together to produce fertile offspring.']),
  t('B42-10', 'How do species die out?'),
  a.choice('B42-11', 'What does it mean when a species is extinct?', ['No individuals of the species are left', 'The species has become very rare', 'The species has moved to a new habitat'], 0, 'How many are left?', ['A rare species still has some individuals alive.', 'A species is extinct when no individuals are left.']),
  a.choice('B42-12', 'A new snail species reaches an island and eats the native snail’s food plants. Why might the native snail die out?', ['The new snail is a predator of the native snail', 'The environment has changed too slowly', 'A volcano erupted', 'It cannot compete with the new snail for food'], 3, 'What do the two snails both need?', ['The new snail eats the same plants; it is a competitor, not a predator.', 'If the native snail cannot compete for food, it may become extinct.']),
  a.choice('B42-13', 'Some rabbits have thicker fur because of their genes. Winters become colder. What is most likely over many generations?', ['Each rabbit grows thicker fur because it is cold, and passes this on', 'Rabbits with thick fur become more common', 'All the rabbits become extinct straight away', 'Nothing changes'], 1, 'Which rabbits are more likely to survive and reproduce?', ['Rabbits with genes for thick fur are more likely to survive the cold and reproduce.', 'Their genes are passed on, so thick-furred rabbits become more common.'], 'application', true),
  a.choice('B42-14', 'Look at the five numbered pictures of causes of extinction. Which one shows a catastrophic event?', ['Picture 1', 'Picture 2', 'Picture 3', 'Picture 4', 'Picture 5'], 2, 'A catastrophic event is a sudden disaster.', ['Picture 1 is a destroyed habitat, 2 a new predator, 4 a new disease and 5 a new competitor for food.', 'Picture 3, a volcanic eruption, is a catastrophic event.'], 'understanding', true, 'evolve-ext-question'),
  a.choice('B42-15', 'The graph shows the percentage of green beetles in a population over 30 generations. Which conclusion fits it?', ['Every beetle turned green', 'Green beetles are a new species', 'Green beetles became more common over 30 generations', 'Brown beetles will be extinct by generation 40'], 2, 'Describe the line. Does the graph show anything after generation 30?', ['The percentage of green beetles rose from 50% to 85%; some beetles were still brown.', 'The graph shows green beetles became more common; it does not show what happens after generation 30.'], 'dataInterpretation', true, 'evolve-ns-data'),
  a.choice('B42-16', 'Two populations of a lake fish now look very different. How could scientists tell whether they are separate species?', ['Measure how big each population is', 'See whether they can breed together to produce fertile offspring', 'Compare their colours'], 1, 'What is the test for being one species?', ['Size and colour differences alone do not show separate species.', 'If they cannot breed together to produce fertile offspring, they are separate species.'], 'application', true),
  a.written('B42-17', 'Hares in a snowy region have white fur in winter. Explain how natural selection could have led to this.', 'Start with variation, then say which hares survive, then what is passed on, over many generations.', 'In the past, the hares varied in fur colour because of their genes. White hares were harder for predators to spot in the snow, so they were better adapted and more likely to survive. They were more likely to reproduce and pass on the genes for white fur to their offspring. Over many generations, white fur became more common in the population.', ['The hares varied in fur colour because of their genes.', 'White hares were better adapted: harder for predators to spot in the snow.', 'White hares were more likely to survive and reproduce.', 'The genes for white fur were passed on to offspring.', 'Over many generations, white fur became more common.'], ['Saying the hares turned white because they needed to, or chose to.', 'Saying the cold or snow changed the hares’ fur colour, and this was passed on.', 'Saying each hare evolved during its own life.', 'Leaving out that genes are passed on to offspring.']),
]

export const lesson42: ScienceLesson = {
  id: 'B-GEN-042-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Evolution, speciation and extinction', prerequisites: ['B-VARIATION'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
