import type { TeachingFrame } from '../../teachingFrame'

// What an I–V characteristic is (linear and non-linear, R = V ÷ I at a point), the required-practical method, then the three graph shapes.
// Resistance in a wire is the previous lesson; series and parallel rules come later.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const ivFrames: Record<string, TeachingFrame[]> = {
  'P18-02': [
    f('A graph of current against pd', 'An I–V characteristic is a graph. It shows how the current through a component changes as the pd across it increases.', 'current up, pd along', 'An I–V characteristic is a graph. It shows how the current, I, through a component changes as the potential difference, V, across it increases. Current goes on the vertical axis. Potential difference goes on the horizontal axis.', 'ivchar-meaning'),
    f('Linear and non-linear', 'A straight-line graph means a linear component. A curved graph means a non-linear component.', 'straight or curved', 'Some components give a straight line on an I–V graph. They are called linear components, and a fixed resistor is one. Other components give a curved line. They are called non-linear components. Filament lamps and diodes are non-linear.', 'ivchar-linear'),
    f('Read off a point', 'To find the resistance at a point, read off the current and the pd at that point.', 'read I and V', 'You can find the resistance of a component at any point on its graph. First read off the values of current and pd at that point. Then use them in a short calculation.', 'ivchar-point'),
    f('Worked example: R = V ÷ I', 'At one point V = 4.0 V and I = 0.50 A, so R = 4.0 ÷ 0.50 = 8.0 Ω.', 'resistance = pd ÷ current', 'Use R = V ÷ I, which comes from V = IR. Suppose a point on the graph has a pd of 4.0 V and a current of 0.50 A. Then R = 4.0 ÷ 0.50 = 8.0 Ω. The unit is ohms.', 'ivchar-calc'),
  ],
  'P18-05': [
    f('The circuit', 'A battery, a variable resistor, the component, an ammeter in series and a voltmeter across the component.', 'ammeter in series, voltmeter across', 'This lesson prepares you for the practical, and you still carry it out with your teacher. The circuit has a battery, a variable resistor, the component being tested and an ammeter, all in series. The voltmeter is connected in parallel across the component only.', 'ivchar-circuit'),
    f('Change the current and read the meters', 'Alter the variable resistor to change the current and the pd. At each setting, read the ammeter and the voltmeter.', 'vary, then read both meters', 'The variable resistor changes the current in the circuit. This also changes the pd across the component. At each setting, read the ammeter and the voltmeter and write both down. Take several sets of readings. Switch off between readings, because lamps and wires can get hot.', 'ivchar-vary'),
    f('Reverse the direction', 'Swap over the wires connected to the battery so the current flows the other way. Then take more readings.', 'swap the battery wires', 'Now swap over the two wires connected to the battery. This reverses the direction of the current. Take more readings of pd and current in the same way. Some components behave differently when the current is reversed.', 'ivchar-reverse'),
    f('Plot the graph', 'Plot current against pd for the component. Readings from the reversed direction go on the other side of the origin.', 'both directions on one graph', 'Plot a graph of current against pd. Readings taken with the reversed current are plotted on the other side of the origin. Then draw a smooth line of best fit through the points.', 'ivchar-plot'),
    f('Testing a diode', 'For a diode, add a protective resistor in series and use a milliammeter, because the currents are small.', 'protect the diode', 'A diode needs extra care. Add a protective resistor in series with it. This increases the total resistance and protects the diode from a current that is too high. The currents are very small, so use a milliammeter instead of an ordinary ammeter.', 'ivchar-diode-circuit'),
  ],
  'P18-08': [
    f('Ohmic conductor', 'A straight line through the origin. The current is directly proportional to the pd, so the resistance is constant.', 'straight line, constant resistance', 'For an ohmic conductor, such as a resistor at a constant temperature, the graph is a straight line through the origin. The current is directly proportional to the potential difference. So its resistance stays constant.', 'ivchar-ohmic'),
    f('Filament lamp', 'A curve that gets less steep. The filament heats up, so its resistance increases and current flows less easily.', 'curve flattens as it heats', 'For a filament lamp, the graph is a curve that gets less steep as the pd increases. The temperature of the filament increases as the current increases. So its resistance increases, which makes it harder for the current to flow.', 'ivchar-lamp'),
    f('Diode', 'Current flows in one direction only. The graph is flat, then curves up quickly.', 'flat, then rises steeply', 'A diode only lets current flow in one direction. In the reverse direction its resistance is very high, so almost no current flows. The graph starts off flat and then curves up quickly when the pd is in the right direction.', 'ivchar-diode'),
    f('Three graphs together', 'Straight line: ohmic conductor. Curve that flattens: filament lamp. Flat, then a steep rise: diode.', 'match shape to component', 'Here are all three graphs together. A straight line through the origin is an ohmic conductor. A curve that gets less steep in both directions is a filament lamp. A graph that is flat on one side and rises quickly on the other is a diode.', 'ivchar-three'),
  ],
}
