import type { ScienceLesson, ScienceState } from '../../types'
import { author, sampledRequirements } from '../../lessonAuthoring'
import { historyFrames as frames } from './teachingFrames'

const source = { id: 'aqa-chemistry', title: 'AQA 8464 Chemistry subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', locator: '5.1.1.3 The development of the model of the atom' }
const skill = 'C-ATOM-HISTORY'
const a = author(skill, ['5.1.1.3'], ['aqa-chemistry'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const historySections = [
  { id: 'C5-01', label: 'Start here', detail: 'When evidence does not fit' },
  { id: 'C5-02', label: 'What did early scientists think?', detail: 'Solid spheres and the plum pudding model' },
  { id: 'C5-05', label: 'What did the gold foil show?', detail: 'The alpha particle scattering experiment' },
  { id: 'C5-08', label: 'What is the nuclear model?', detail: 'A tiny nucleus in mostly empty space' },
  { id: 'C5-11', label: 'What came next?', detail: 'Bohr’s shells, protons and neutrons' },
  { id: 'C5-14', label: 'On your own', detail: 'Order, paths, data and the plum pudding model' },
]

const states: ScienceState[] = [
  { ...a.choice('C5-01', 'Scientists find new evidence that does not fit their model. What should they do?', ['Ignore the new evidence', 'Change the model so it fits all the evidence', 'Keep the model, because it came first'], 1, 'What is a model for?', ['A model is only useful if it explains the evidence.', 'So when new evidence does not fit, scientists change the model or replace it.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('C5-02', 'What did early scientists think?'),
  a.choice('C5-03', 'Which description matches the plum pudding model of the atom?', ['A tiny positive nucleus with electrons in shells around it', 'A solid ball with nothing inside it', 'A ball of positive charge with electrons scattered through it', 'A ball of negative charge with protons scattered through it'], 2, 'What was the “pudding”, and what was scattered in it?', ['In the plum pudding model, the whole atom is a ball of positive charge.', 'The negative electrons are scattered through it, so there is no nucleus and there are no shells.']),
  a.choice('C5-04', 'Why did scientists stop using the solid sphere model of the atom?', ['They found electrons, so atoms have smaller particles inside', 'They found that atoms are too small to see', 'They found that atoms have an overall positive charge', 'They found that atoms are shaped like cubes'], 0, 'What did scientists find inside atoms?', ['The solid sphere model said atoms had nothing inside them.', 'Scientists found electrons, much smaller particles inside atoms, so the model had to change.']),
  t('C5-05', 'What did the gold foil show?'),
  a.choice('C5-06', 'Which result of the gold foil experiment did the plum pudding model not predict?', ['Most alpha particles went straight through', 'Alpha particles passed through the thin foil', 'Some alpha particles changed direction a little', 'A few alpha particles bounced back'], 3, 'Which result could spread-out positive charge never cause?', ['The plum pudding model predicted almost all alpha particles would go straight through, with small changes of direction.', 'It could not explain alpha particles bouncing back, so this result showed the model was wrong.']),
  a.choice('C5-07', 'Scientists fired alpha particles at thin gold foil. What happened to most of the alpha particles?', ['They bounced back', 'They went straight through', 'They stuck to the foil', 'They changed direction a lot'], 1, 'Think about the first result on the list.', ['Most alpha particles went straight through the gold foil.', 'Only some changed direction a lot, and a very small number bounced back.']),
  t('C5-08', 'What is the nuclear model?'),
  a.choice('C5-09', 'Why did most alpha particles go straight through the gold foil?', ['Most of each atom is empty space', 'Gold atoms have no nucleus', 'Alpha particles have no charge', 'The positive charge is spread through each atom'], 0, 'How big is the nucleus compared with the whole atom?', ['The nucleus is tiny, so most of the atom is empty space.', 'So most alpha particles pass through without going near a nucleus.']),
  a.choice('C5-10', 'A few alpha particles bounced back from the gold foil. What does this tell you about the nucleus?', ['It is negative and very light', 'It is spread through the whole atom', 'It is positive and holds most of the mass', 'It is made of empty space'], 2, 'What could push a positive alpha particle straight back?', ['An alpha particle is positive, so only something positive pushes it away.', 'To push it straight back, the nucleus must be positive and hold most of the mass in a tiny space.']),
  t('C5-11', 'What came next?'),
  a.choice('C5-12', 'What did Niels Bohr add to the nuclear model of the atom?', ['The atom is a ball of positive charge', 'The nucleus contains neutrons', 'Atoms are solid spheres', 'Electrons orbit the nucleus at fixed distances'], 3, 'Where did Bohr put the electrons?', ['Bohr suggested that electrons move around the nucleus in shells.', 'Each shell is a fixed distance from the nucleus, and experiments agreed with this.']),
  a.choice('C5-13', 'What did the experiments of James Chadwick show?', ['Atoms contain electrons', 'The nucleus also contains neutrons', 'Most of the atom is empty space', 'Electrons orbit in shells'], 1, 'Which particle was found last?', ['Chadwick showed that the nucleus contains particles with no charge.', 'These are neutrons. This was about 20 years after scientists agreed that atoms have a nucleus.']),
  a.choice('C5-14', 'Which list puts these models of the atom in the order scientists suggested them, earliest first?', ['plum pudding → solid sphere → nuclear → Bohr', 'solid sphere → nuclear → plum pudding → Bohr', 'solid sphere → plum pudding → nuclear → Bohr', 'solid sphere → plum pudding → Bohr → nuclear'], 2, 'Which was found first: the electron or the nucleus?', ['Solid spheres came first. Finding electrons led to the plum pudding model.', 'The gold foil experiment led to the nuclear model, and Bohr then added shells to it.'], 'understanding', true),
  a.choice('C5-15', 'Alpha particles were fired at gold foil. Which numbered path shows one that passed through empty space, far from any nucleus?', ['Path 1', 'Path 2', 'Path 3'], 1, 'What happens to an alpha particle that meets nothing on its way?', ['Path 1 bounced back and path 3 changed direction a lot: both came close to a nucleus.', 'Path 2 went straight through, so it passed through empty space, far from any nucleus.'], 'understanding', true, 'hist-question'),
  a.choice('C5-16', 'A computer model fires 10 000 alpha particles at gold foil. What does the table suggest about the gold atoms?', ['The nucleus fills most of each atom', 'Gold atoms are solid spheres', 'Positive charge is spread through each atom', 'Each atom is mostly empty space'], 3, 'What did almost all of the alpha particles do?', ['9 978 of the 10 000 alpha particles went straight through, so almost all met nothing in their way.', 'This suggests each atom is mostly empty space. The table does not tell you exactly how big the nucleus is.'], 'dataInterpretation', true, 'hist-data'),
  a.written('C5-17', 'Describe the plum pudding model of the atom. Explain how the gold foil experiment showed that it was wrong.', 'Say what the model looked like, what it predicted for the alpha particles, and what actually happened.', 'In the plum pudding model, the atom is a ball of positive charge with electrons scattered through it. So scientists predicted that almost all alpha particles would go straight through the gold foil, with only small changes of direction. Instead, some changed direction much more than expected and a few bounced back. Spread-out positive charge cannot do this, so the positive charge and most of the mass must be in a tiny nucleus. The plum pudding model was replaced by the nuclear model.', ['The plum pudding model is a ball of positive charge with electrons scattered through it.', 'It predicted that almost all alpha particles would go straight through, with only small changes of direction.', 'Instead, some alpha particles were deflected more than expected and a few bounced back.', 'So the positive charge and most of the mass must be in a tiny nucleus, and the nuclear model replaced it.'], ['Saying the plum pudding model has a nucleus or electron shells.', 'Saying most alpha particles bounced back.', 'Saying alpha particles are negative, or are attracted to the nucleus.']),
]

export const lessonC5: ScienceLesson = {
  id: 'C-PER-005-C', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'chemistry',
  title: 'How the model of the atom changed', prerequisites: [], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
