import type { TeachingFrame } from '../../teachingFrame'

// Follow the evidence in time order: each model is taught only after the evidence that broke the one before it.
// Solid spheres → electrons → plum pudding; then the gold foil prediction and results; then the nuclear model that explains them;
// then Bohr's shells, protons and neutrons, ending on the model the student already knows.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const historyFrames: Record<string, TeachingFrame[]> = {
  'C5-02': [
    f('Models change', 'Scientists use models to explain what they cannot see.', 'new evidence → new model', 'Atoms are far too small to see, so nobody could simply look inside one. Instead, scientists made a simple description that fitted the evidence they had. This is called a scientific model. When new evidence did not fit, the model was changed. The strip shows the models of the atom you will meet.', 'hist-early-model'),
    f('Solid spheres', 'The first model: atoms were tiny solid balls.', 'atom → solid ball, nothing inside', 'At first, scientists thought atoms were tiny solid balls with nothing inside them. They thought atoms could not be split into anything smaller. A ball shape is called a sphere, so this is called the solid sphere model.', 'hist-early-sphere'),
    f('Something smaller', 'Scientists found tiny negative particles inside atoms.', 'electrons found → atoms are not solid balls', 'Then scientists found that atoms contain even smaller particles. These particles have a negative charge. You already know them: they are electrons. So atoms could not be solid balls with nothing inside, and the model had to change.', 'hist-early-electron'),
    f('The plum pudding model', 'A ball of positive charge with electrons scattered in it.', 'ball of positive charge + scattered electrons', 'Atoms have no overall charge, so something positive must balance the negative electrons. Scientists pictured the atom as a ball of positive charge. The electrons were scattered through this ball, like fruit in a pudding. This is called the plum pudding model.', 'hist-early-pudding'),
  ],
  'C5-05': [
    f('Alpha particles', 'Scientists fired tiny positive particles at gold.', 'positive particles → very thin gold foil', 'Some substances give out tiny particles with a positive charge. These are called alpha particles. Scientists fired a narrow stream of them at a sheet of gold foil, far thinner than a hair. Then they looked at where the alpha particles went.', 'hist-alpha-setup'),
    f('The prediction', 'The plum pudding model said almost nothing would change.', 'positive charge spread out → straight through', 'In the plum pudding model, the positive charge is spread thinly through each atom. So scientists expected almost all the alpha particles to go straight through the foil. A few might change direction by a small amount. What a model says should happen is called a prediction.', 'hist-alpha-predict'),
    f('The results', 'Most went straight through, but not all.', 'most straight; some deflected a lot; a few back', 'Most alpha particles did go straight through the foil. But some changed direction far more than expected. A very small number even bounced back towards where they came from. When a particle is pushed off its path like this, it is called deflected.', 'hist-alpha-results'),
    f('The model was wrong', 'The results did not match the prediction.', 'results ≠ prediction → change the model', 'Positive charge spread thinly through the atom could never push an alpha particle straight back. So the results did not match the prediction. This meant the plum pudding model could not be right. Scientists needed a new model that explained every result.', 'hist-alpha-wrong'),
  ],
  'C5-08': [
    f('A tiny nucleus', 'The positive charge and most of the mass sit in a tiny centre.', 'positive charge + most of the mass → tiny centre', 'Scientists decided that the positive charge is not spread out. It is packed into a tiny centre, the nucleus, together with most of the mass. The electrons are found around the nucleus. This new picture is called the nuclear model.', 'hist-nuclear-atom'),
    f('Mostly empty space', 'Most alpha particles never go near the tiny nucleus.', 'nucleus tiny → most go straight through', 'The nucleus is tiny compared with the whole atom. So most of the atom is empty space. Most alpha particles pass through this space without going near a nucleus. So they go straight through the foil.', 'hist-nuclear-straight'),
    f('Pushed away', 'Two positive charges push each other away.', 'alpha (+) near nucleus (+) → pushed away', 'Alpha particles and the nucleus are both positive. Two positive charges push each other away: they repel. An alpha particle passing close to a nucleus is pushed off course, so it is deflected. One heading straight at a nucleus is pushed back the way it came.', 'hist-nuclear-close'),
    f('Put it together', 'The nuclear model explains every result.', 'plum pudding → nuclear model', 'In the plum pudding model, positive charge and mass are spread through the whole atom. In the nuclear model, they are packed into a tiny nucleus. The rest of the atom is mostly empty space, with electrons around the nucleus. This explains why most alpha particles go straight through, but a few bounce back.', 'hist-compare'),
  ],
  'C5-11': [
    f('Electron shells', 'Bohr suggested electrons orbit the nucleus at fixed distances.', 'electrons → orbit in shells at fixed distances', 'The scientist Niels Bohr changed the nuclear model. He suggested that electrons move around the nucleus in shells, each at a fixed distance from it. Moving round and round something like this is called orbiting. Many experiments agreed with Bohr’s idea, so scientists accepted it.', 'hist-later-bohr'),
    f('Protons', 'The nucleus is made of smaller positive particles.', 'positive charge of the nucleus → protons', 'Later experiments showed that the positive charge of a nucleus is shared between smaller particles. Each of these particles has the same amount of positive charge. They were named protons. You met protons when you learned what is inside an atom.', 'hist-later-proton'),
    f('Neutrons', 'Chadwick found particles with no charge in the nucleus.', 'Chadwick → neutrons in the nucleus', 'The scientist James Chadwick showed that the nucleus also contains particles with no charge. These particles are neutrons. This was about 20 years after scientists first agreed that atoms have a nucleus. It gave a model very close to the one scientists use today.', 'hist-later-neutron'),
    f('Put it together', 'Each new piece of evidence changed the model.', 'sphere → pudding → nuclear → Bohr → today', 'Solid spheres were replaced when electrons were found, giving the plum pudding model. The gold foil results then led to the nuclear model. Bohr added electron shells, and later experiments found protons and neutrons. This is the model you used when you learned about protons, neutrons and electrons. Science builds on earlier work, so models may change again.', 'hist-story'),
  ],
}
