import type { TeachingFrame } from '../../teachingFrame'

// Build one picture at a time: the particle model and the three states first, then the four changes between them,
// then why substances change state at different temperatures (and how to predict a state), and state symbols last,
// once "solid", "liquid", "gas" and "dissolved" all have a clear particle meaning.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const stateFrames: Record<string, TeachingFrame[]> = {
  'C17-02': [
    f('The particle model', 'Every substance is made of tiny particles, drawn as small solid balls.', 'atom, ion or molecule → one small ball', 'Every substance is made of tiny particles. The particles can be atoms, ions or molecules. To explain how substances behave, we draw each particle as a small, solid ball. This way of picturing substances is called the particle model.', 'state-model'),
    f('Solids', 'In a solid, strong forces hold the particles in fixed positions.', 'strong forces → fixed positions → fixed shape', 'In a solid, there are strong forces of attraction between the particles. The forces hold each particle in a fixed position, in a regular pattern. The particles can only vibrate on the spot. So a solid keeps a fixed shape and a fixed volume.', 'state-solid'),
    f('Liquids', 'In a liquid, the particles are close together but can move past each other.', 'weak forces → move past each other → flows', 'In a liquid, the forces between the particles are weak. The particles stay close together, but in a random order. They move around and slide past each other. So a liquid has a fixed volume, but it flows to fill the bottom of its container.', 'state-liquid'),
    f('Gases', 'In a gas, the particles are far apart and move in all directions.', 'very weak forces → far apart → fills the container', 'In a gas, the forces between the particles are very weak. The particles are far apart. They move quickly in straight lines, in random directions. So a gas has no fixed shape or volume, and it spreads out to fill any container.', 'state-gas'),
    f('Hotter means faster', 'Heating gives the particles more energy.', 'hotter → more energy → faster', 'When a substance gets hotter, its particles gain energy. In a solid, the particles vibrate more. In a liquid or a gas, the particles move faster. The hotter it gets, the more the particles move.', 'state-hotter'),
    f('Put it together', 'The forces between particles decide how each state behaves.', 'strong → weak → very weak forces', 'Solid, liquid and gas are the three states of matter. In a solid, strong forces hold the particles in place. In a liquid, weaker forces keep them close but let them move. In a gas, the forces are very weak and the particles spread out.', 'state-all'),
  ],
  'C17-06': [
    f('A physical change', 'Changing state does not make a new substance.', 'same particles, new arrangement', 'Ice, water and steam are all made of the same water particles. When a substance changes state, the particles themselves do not change. Only their arrangement and their energy change. A change like this, with no new substance made, is called a physical change.', 'state-change-physical'),
    f('Melting', 'Heating a solid can turn it into a liquid.', 'heat → vibrate more → break free', 'When a solid is heated, its particles gain energy and vibrate more. This weakens some of the forces between them. At one temperature, the particles have enough energy to break free from their fixed positions. The solid melts into a liquid. This temperature is called the melting point.', 'state-change-melt'),
    f('Boiling', 'Heating a liquid can turn it into a gas.', 'more heat → overcome the forces → gas', 'When a liquid is heated, its particles gain even more energy. The forces holding the liquid together get weaker. At one temperature, the particles have enough energy to overcome these forces and spread out. The liquid boils into a gas. This temperature is called the boiling point.', 'state-change-boil'),
    f('Condensing', 'Cooling a gas can turn it back into a liquid.', 'cool → less energy → forces pull together', 'When a gas cools, its particles lose energy and move more slowly. The forces between them get stronger. At the boiling point, the forces are strong enough to pull the particles close together. The gas turns into a liquid. This is called condensing.', 'state-change-condense'),
    f('Freezing', 'Cooling a liquid can turn it into a solid.', 'cool more → held in place → solid', 'When a liquid cools, its particles lose even more energy and move less. The forces between them get stronger still. At the melting point, the forces hold the particles in fixed positions. The liquid turns into a solid. This is called freezing.', 'state-change-freeze'),
    f('Put it together', 'Two temperatures mark the four changes of state.', 'melting point: melt or freeze · boiling point: boil or condense', 'Melting and boiling need energy, so they happen when a substance is heated. Condensing and freezing happen when it cools and loses energy. A substance melts and freezes at the same temperature, its melting point. It boils and condenses at its boiling point.', 'state-change-all'),
  ],
  'C17-09': [
    f('Forces and energy', 'Stronger forces need more energy to overcome.', 'stronger forces → more energy → higher melting point', 'To change state, particles need enough energy to overcome the forces between them. If the forces are weak, only a little energy is needed. If the forces are strong, a lot of energy is needed. So the stronger the forces, the higher the melting and boiling points.', 'state-mp-forces'),
    f('Comparing two substances', 'Different substances melt and boil at different temperatures.', 'higher melting and boiling points → stronger forces', 'Oxygen melts at −219 °C and boils at −183 °C. Water melts at 0 °C and boils at 100 °C. Both are much higher for water. This tells us the forces between water particles are stronger than those between oxygen particles.', 'state-mp-compare'),
    f('Below the melting point', 'Colder than its melting point, a substance is a solid.', 'below melting point → solid', 'You can use the melting and boiling points to predict the state of a substance. If the temperature is below the melting point, the substance is a solid. Water melts at 0 °C. So at −10 °C, water is a solid: ice.', 'state-predict-solid'),
    f('Above the boiling point', 'Hotter than its boiling point, a substance is a gas.', 'above boiling point → gas', 'If the temperature is above the boiling point, the substance is a gas. Water boils at 100 °C. So at 120 °C, water is a gas: steam.', 'state-predict-gas'),
    f('In between', 'Between its melting and boiling points, a substance is a liquid.', 'between the two → liquid', 'If the temperature is between the melting point and the boiling point, the substance is a liquid. Room temperature is usually taken as 25 °C. This is between 0 °C and 100 °C. So at room temperature, water is a liquid.', 'state-predict-liquid'),
    f('Put it together', 'Compare the temperature with both points, one substance at a time.', 'below → solid · between → liquid · above → gas', 'Chlorine boils at −34 °C, so 25 °C is above its boiling point: it is a gas. Mercury melts at −39 °C and boils at 357 °C, so it is a liquid. Sulfur melts at 115 °C, so 25 °C is below its melting point: it is a solid.', 'state-predict-example'),
  ],
  'C17-12': [
    f('State symbols', 'Short letters in an equation show each substance’s state.', '(s) solid · (l) liquid · (g) gas', 'A symbol equation can show the state of each substance. A short letter in brackets goes straight after each formula. (s) means solid, (l) means liquid and (g) means gas. These letters are called state symbols.', 'state-symbol-list'),
    f('Aqueous', 'A fourth symbol shows that a substance is dissolved in water.', 'dissolved in water → (aq)', 'Many reactions happen in water. When a substance is dissolved in water, it is not shown as a solid. It gets the state symbol (aq). This stands for aqueous, which means dissolved in water. Salt water is sodium chloride dissolved in water, so it is NaCl(aq).', 'state-symbol-aq'),
    f('Reading an equation', 'The state symbols tell you what each substance is like.', 'read each symbol after its formula', 'When magnesium reacts with hydrochloric acid, it makes magnesium chloride and hydrogen. Magnesium is a solid metal, so it is Mg(s). The acid and the magnesium chloride are both dissolved in water, so they are (aq). Hydrogen is a gas, so it is H₂(g).', 'state-symbol-equation'),
    f('Put it together', 'The same substance can have different state symbols.', 'same formula, different symbol', 'Ice, liquid water and steam all have the formula H₂O. The particles are the same, so the formula stays the same. Only the state symbol changes: H₂O(s), H₂O(l) or H₂O(g). This matches what you know: changing state is a physical change.', 'state-symbol-water'),
  ],
}
