import type { LearningState, LessonDefinition, LongMultiplicationStage, LongMultiplicationVisual, MicroSkillId, MultiplicationScaleVisual } from '../number-types/types'

function continueState(state: Omit<LearningState, 'interaction' | 'completionCondition'>): LearningState {
  return { ...state, interaction: { type: 'continue' }, completionCondition: 'Learner reaches the last animation step and continues.' }
}

function numberQuestion({ id, microSkillId, phase, title, prompt, component, answer, displayAnswer, correct, incorrect, next, misconceptionId }: {
  id: string; microSkillId: MicroSkillId; phase: LearningState['phase']; title: string; prompt?: string
  component: LongMultiplicationVisual | MultiplicationScaleVisual; answer: number; displayAnswer?: string
  correct: string; incorrect: string; next: string; misconceptionId: string
}): LearningState {
  return {
    id, microSkillId, phase, teachingIntent: 'Ask the learner to predict the next written step.',
    content: { title, prompt }, component,
    interaction: { type: 'numericInput', correctAnswer: answer, displayAnswer, acceptanceRule: 'normalisedNumber', placeholder: 'Type your answer' },
    feedback: { correct: { message: correct }, incorrect: { message: incorrect } },
    transition: { onComplete: next }, completionCondition: `Learner enters ${displayAnswer ?? answer}.`,
    analytics: { misconceptionId, eventName: `lesson_5_${id.toLowerCase().replaceAll('-', '_')}` },
  }
}

const setupStages: LongMultiplicationStage[] = [
  { label: 'Write 281', narration: 'Write the bigger number first.', nextPrompt: 'Where will 23 go?', showMultiplier: false, showRule: false },
  { label: 'Write 23 underneath', narration: 'Write 23 underneath. Put the 3 below the 1.', nextPrompt: 'What needs to be drawn underneath?', showRule: false, active: 'setup' },
  { label: 'Draw the line', narration: 'Draw a line. This is where the working will go.', nextPrompt: 'Which bottom digit will we use first?', active: 'setup' },
  { label: 'Start with 3', narration: 'Start with the 3 on the right. We will multiply 281 by 3 first.', active: 'setup', multiplicationPairs: [{ topIndex: 2, bottomIndex: 1 }], placeValue: { digit: '3', place: 'right-hand', value: 'use this first' } },
]

const main281Stages: LongMultiplicationStage[] = [
  { label: 'Start on the right', narration: 'Start with 3 × 1.', nextPrompt: 'What is 3 × 1?', active: 'setup', multiplicationPairs: [{ topIndex: 2, bottomIndex: 1 }] },
  { label: 'Write 3', narration: '3 × 1 = 3. Write 3 underneath.', nextPrompt: 'What is 3 × 8?', active: 'ones', multiplicationPairs: [{ topIndex: 1, bottomIndex: 1 }], onesRow: '3', working: ['3 × 1 = 3'] },
  { label: 'Work out 3 × 8', narration: '3 × 8 = 24. Write 4 and carry 2.', nextPrompt: 'What do we add after 3 × 2?', active: 'ones', multiplicationPairs: [{ topIndex: 1, bottomIndex: 1 }], onesRow: '43', carry: { value: '2', fromColumn: '8', toColumn: '2' }, working: ['3 × 8 = 24', 'write 4 · carry 2'] },
  { label: 'Finish the first row', narration: '3 × 2 = 6. Add the carried 2 to make 8. The first row is 843.', nextPrompt: 'What must we write before the next row?', active: 'ones', multiplicationPairs: [{ topIndex: 0, bottomIndex: 1 }], onesRow: '843', working: ['3 × 2 = 6', '6 + 2 = 8'] },
  { label: 'Write a zero', narration: 'Write a zero on the right before the second row. The 2 in 23 means 20.', nextPrompt: 'Now what is 2 × 1?', active: 'zero', onesRow: '843', placeValue: { digit: '2', place: 'tens', value: 'means 20' } },
  { label: 'Start the second row', narration: '2 × 1 = 2. Because this row is for 20, it appears as 20.', nextPrompt: 'What is 2 × 8?', active: 'tens', multiplicationPairs: [{ topIndex: 2, bottomIndex: 0 }], onesRow: '843', tensRow: '20', working: ['2 × 1 = 2'] },
  { label: 'Carry again', narration: '2 × 8 = 16. Write 6 and carry 1.', nextPrompt: 'What is 2 × 2, plus 1?', active: 'tens', multiplicationPairs: [{ topIndex: 1, bottomIndex: 0 }], onesRow: '843', tensRow: '620', carry: { value: '1', fromColumn: '8', toColumn: '2' }, working: ['2 × 8 = 16', 'write 6 · carry 1'] },
  { label: 'Finish the second row', narration: '2 × 2 = 4. Add the carried 1 to make 5. The second row is 5,620.', nextPrompt: 'What do we do with the two rows?', active: 'tens', multiplicationPairs: [{ topIndex: 0, bottomIndex: 0 }], onesRow: '843', tensRow: '5620', working: ['2 × 2 + 1 = 5'] },
  { label: 'Add the rows', narration: 'Add 843 and 5,620. The answer is 6,463.', active: 'add', onesRow: '843', tensRow: '5620', total: '6463', working: ['843 + 5,620 = 6,463'] },
]

const carrying347Stages: LongMultiplicationStage[] = [
  { label: 'Start with 6 × 7', narration: '6 × 7 = 42. Write 2 and carry 4.', nextPrompt: 'What is 6 × 4, plus 4?', active: 'ones', multiplicationPairs: [{ topIndex: 2, bottomIndex: 1 }], onesRow: '2', carry: { value: '4', fromColumn: '7', toColumn: '4' } },
  { label: 'Carry again', narration: '6 × 4 = 24. Add 4 to make 28. Write 8 and carry 2.', nextPrompt: 'What is 6 × 3, plus 2?', active: 'ones', multiplicationPairs: [{ topIndex: 1, bottomIndex: 1 }], onesRow: '82', carry: { value: '2', fromColumn: '4', toColumn: '3' }, working: ['24 + 4 = 28'] },
  { label: 'Finish the first row', narration: '6 × 3 = 18. Add 2 to make 20. The first row is 2,082.', nextPrompt: 'What goes on the right of the next row?', active: 'ones', multiplicationPairs: [{ topIndex: 0, bottomIndex: 1 }], onesRow: '2082' },
  { label: 'Make the second row', narration: 'Write the zero, then multiply by the 2. The second row is 6,940.', nextPrompt: 'What do we do with 2,082 and 6,940?', active: 'tens', multiplicationPairs: [{ topIndex: 2, bottomIndex: 0 }, { topIndex: 1, bottomIndex: 0 }, { topIndex: 0, bottomIndex: 0 }], onesRow: '2082', tensRow: '6940' },
  { label: 'Add the rows', narration: '2,082 + 6,940 = 9,022.', active: 'add', onesRow: '2082', tensRow: '6940', total: '9022' },
]

const zero405Stages: LongMultiplicationStage[] = [
  { label: 'Start with 2 × 5', narration: '2 × 5 = 10. Write 0 and carry 1.', nextPrompt: 'What is 2 × 0, plus 1?', active: 'ones', multiplicationPairs: [{ topIndex: 2, bottomIndex: 1 }], onesRow: '0', carry: { value: '1', fromColumn: '5', toColumn: '0' } },
  { label: 'Use the zero', narration: '2 × 0 = 0. Add the carried 1 to make 1.', nextPrompt: 'What is 2 × 4?', active: 'ones', multiplicationPairs: [{ topIndex: 1, bottomIndex: 1 }], onesRow: '10', working: ['2 × 0 + 1 = 1'] },
  { label: 'Finish the first row', narration: '2 × 4 = 8. The first row is 810.', nextPrompt: 'What must the next row end with?', active: 'ones', multiplicationPairs: [{ topIndex: 0, bottomIndex: 1 }], onesRow: '810' },
  { label: 'Make the second row', narration: 'The 3 means 30, so write the ending zero. The second row is 12,150.', nextPrompt: 'What do we do with the two rows?', active: 'tens', multiplicationPairs: [{ topIndex: 2, bottomIndex: 0 }, { topIndex: 1, bottomIndex: 0 }, { topIndex: 0, bottomIndex: 0 }], onesRow: '810', tensRow: '12150' },
  { label: 'Add the rows', narration: '810 + 12,150 = 12,960.', active: 'add', onesRow: '810', tensRow: '12150', total: '12960' },
]

const theatreStages: LongMultiplicationStage[] = [
  { label: 'Find the calculation', narration: 'There are 18 rows. Each row has 246 seats. That means 18 lots of 246.', nextPrompt: 'Which two numbers do we multiply?', showMultiplicand: false, showMultiplier: false, showRule: false, active: 'setup', working: ['18 lots of 246'] },
  { label: 'Write 246 × 18', narration: 'Write 246 × 18. Start with the 8 on the right.', nextPrompt: 'What is the first row?', active: 'setup' },
  { label: 'Make the first row', narration: 'Multiply 246 by 8. The first row is 1,968.', nextPrompt: 'What must the next row end with?', active: 'ones', multiplicationPairs: [{ topIndex: 2, bottomIndex: 1 }, { topIndex: 1, bottomIndex: 1 }, { topIndex: 0, bottomIndex: 1 }], onesRow: '1968' },
  { label: 'Make the second row', narration: 'The 1 in 18 means 10. The second row is 2,460.', nextPrompt: 'What do we do with the two rows?', active: 'tens', multiplicationPairs: [{ topIndex: 2, bottomIndex: 0 }, { topIndex: 1, bottomIndex: 0 }, { topIndex: 0, bottomIndex: 0 }], onesRow: '1968', tensRow: '2460' },
  { label: 'Add and name the answer', narration: '1,968 + 2,460 = 4,428. There are 4,428 seats.', active: 'add', onesRow: '1968', tensRow: '2460', total: '4428' },
]

const states: LearningState[] = [
  continueState({ id: 'L5-SETUP', microSkillId: 'long-multiplication-layout', phase: 'hook', teachingIntent: 'Teach the setup before asking the learner to use it.', content: { title: 'How do we set up 281 × 23?', prompt: 'Press Play, or use Next and Previous.' }, component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', mode: 'stepper', stages: setupStages, answer: 'Ready to multiply' } }, transition: { onComplete: 'L5-FIRST' } }),
  numberQuestion({ id: 'L5-FIRST', microSkillId: 'long-multiplication-layout', phase: 'guided', title: 'Which bottom digit do we use first?', prompt: 'Type the digit on the right.', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23' } }, answer: 3, correct: 'Yes. Start with the 3 on the right.', incorrect: 'Start with the bottom digit on the right: 3.', next: 'L5-W01', misconceptionId: 'LM-STARTS-LEFT' }),
  continueState({ id: 'L5-W01', microSkillId: 'long-multiplication-ones', phase: 'teach', teachingIntent: 'Model the full method with a prediction before each reveal.', content: { title: 'Now work through 281 × 23', prompt: 'At each step, guess what comes next before you press Next.' }, component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', mode: 'stepper', stages: main281Stages, answer: '281 × 23 = 6,463' } }, transition: { onComplete: 'L5-Q01' } }),
  numberQuestion({ id: 'L5-Q01', microSkillId: 'long-multiplication-ones', phase: 'guided', title: 'Start on the right: 3 × 1 = ?', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', onesRow: '3' } }, answer: 3, correct: 'Correct. Write 3.', incorrect: '3 × 1 = 3.', next: 'L5-Q02', misconceptionId: 'LM-FIRST-FACT' }),
  numberQuestion({ id: 'L5-Q02', microSkillId: 'long-multiplication-carrying', phase: 'guided', title: 'Next: 3 × 8 = ?', prompt: 'Type the whole answer before carrying.', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', visibleOnesRow: '3', onesRow: '43' } }, answer: 24, correct: 'Correct. Write 4 and carry 2.', incorrect: '3 × 8 = 24. Write 4 and carry 2.', next: 'L5-Q03', misconceptionId: 'LM-CARRY-FACT' }),
  numberQuestion({ id: 'L5-Q03', microSkillId: 'long-multiplication-ones', phase: 'guided', title: 'What is the whole first row?', prompt: '281 × 3 = ?', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', visibleOnesRow: '43', onesRow: '843' } }, answer: 843, correct: 'Yes. The first row is 843.', incorrect: '3 × 2 = 6, then add the carried 2. The first row is 843.', next: 'L5-Q04', misconceptionId: 'LM-FIRST-ROW' }),
  numberQuestion({ id: 'L5-Q04', microSkillId: 'long-multiplication-tens', phase: 'guided', title: 'What do we write first on the next row?', prompt: 'Type the one digit that keeps the row in the right place.', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', visibleOnesRow: '843', onesRow: '843', tensRow: '0' } }, answer: 0, correct: 'Correct. Start the second row with 0.', incorrect: 'Write 0 on the right. The 2 in 23 means 20.', next: 'L5-Q05', misconceptionId: 'LM-MISSES-ZERO' }),
  numberQuestion({ id: 'L5-Q05', microSkillId: 'long-multiplication-tens', phase: 'guided', title: 'What is the whole second row?', prompt: '281 × 20 = ?', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', visibleOnesRow: '843', visibleTensRow: '0', onesRow: '843', tensRow: '5620' } }, answer: 5620, displayAnswer: '5,620', correct: 'Yes. The second row is 5,620.', incorrect: '281 × 2 = 562, so 281 × 20 = 5,620.', next: 'L5-Q06', misconceptionId: 'LM-TENS-ROW' }),
  numberQuestion({ id: 'L5-Q06', microSkillId: 'long-multiplication-tens', phase: 'independent', title: 'Now add the two rows', prompt: '843 + 5,620 = ?', component: { type: 'longMultiplication', props: { multiplicand: '281', multiplier: '23', visibleOnesRow: '843', visibleTensRow: '5620', onesRow: '843', tensRow: '5620', total: '6463' } }, answer: 6463, displayAnswer: '6,463', correct: 'Correct. 281 × 23 = 6,463.', incorrect: 'Line up the columns and add. The answer is 6,463.', next: 'L5-W02', misconceptionId: 'LM-ADD-ROWS' }),
  continueState({ id: 'L5-W02', microSkillId: 'long-multiplication-carrying', phase: 'teach', teachingIntent: 'Show two carries, with a prediction before each reveal.', content: { title: 'Example: carry more than once', prompt: 'Guess the next step, then press Next.' }, component: { type: 'longMultiplication', props: { multiplicand: '347', multiplier: '26', mode: 'stepper', stages: carrying347Stages, answer: '347 × 26 = 9,022' } }, transition: { onComplete: 'L5-C01' } }),
  numberQuestion({ id: 'L5-C01', microSkillId: 'long-multiplication-carrying', phase: 'guided', title: '6 × 4 = 24. Add the carried 4.', prompt: 'What do you get?', component: { type: 'longMultiplication', props: { multiplicand: '347', multiplier: '26', visibleOnesRow: '2', onesRow: '82' } }, answer: 28, correct: 'Correct. Write 8 and carry 2.', incorrect: '24 + 4 = 28. Write 8 and carry 2.', next: 'L5-C02', misconceptionId: 'LM-SECOND-CARRY' }),
  numberQuestion({ id: 'L5-C02', microSkillId: 'long-multiplication-carrying', phase: 'independent', title: 'Finish 347 × 26', component: { type: 'longMultiplication', props: { multiplicand: '347', multiplier: '26', visibleOnesRow: '2082', visibleTensRow: '6940', onesRow: '2082', tensRow: '6940', total: '9022' } }, answer: 9022, displayAnswer: '9,022', correct: 'Correct. 2,082 + 6,940 = 9,022.', incorrect: 'Add 2,082 and 6,940. The answer is 9,022.', next: 'L5-W03', misconceptionId: 'LM-MULTIPLE-CARRIES' }),
  continueState({ id: 'L5-W03', microSkillId: 'long-multiplication-carrying', phase: 'teach', teachingIntent: 'Show how to carry through a zero.', content: { title: 'Example: there is a zero in 405', prompt: 'Do not skip the zero. Guess, then press Next.' }, component: { type: 'longMultiplication', props: { multiplicand: '405', multiplier: '32', mode: 'stepper', stages: zero405Stages, answer: '405 × 32 = 12,960' } }, transition: { onComplete: 'L5-Z01' } }),
  numberQuestion({ id: 'L5-Z01', microSkillId: 'long-multiplication-carrying', phase: 'guided', title: '2 × 0 = 0. Add the carried 1.', prompt: 'What do you write?', component: { type: 'longMultiplication', props: { multiplicand: '405', multiplier: '32', visibleOnesRow: '0', onesRow: '10' } }, answer: 1, correct: 'Correct. Write 1.', incorrect: '0 + 1 = 1. The zero does not make the carry disappear.', next: 'L5-Z02', misconceptionId: 'LM-ZERO-DROPS-CARRY' }),
  numberQuestion({ id: 'L5-Z02', microSkillId: 'long-multiplication-carrying', phase: 'independent', title: 'Finish 405 × 32', component: { type: 'longMultiplication', props: { multiplicand: '405', multiplier: '32', visibleOnesRow: '810', visibleTensRow: '12150', onesRow: '810', tensRow: '12150', total: '12960' } }, answer: 12960, displayAnswer: '12,960', correct: 'Correct. 405 × 32 = 12,960.', incorrect: 'Add 810 and 12,150. The answer is 12,960.', next: 'L5-W04', misconceptionId: 'LM-INTERNAL-ZERO' }),
  continueState({ id: 'L5-W04', microSkillId: 'long-multiplication-application', phase: 'teach', teachingIntent: 'Turn a short word problem into multiplication, one step at a time.', content: { title: 'Example: seats in a theatre', body: 'There are 18 rows. Each row has 246 seats.', prompt: 'Guess each next step before you reveal it.' }, component: { type: 'longMultiplication', props: { multiplicand: '246', multiplier: '18', mode: 'stepper', stages: theatreStages, answer: 'There are 4,428 seats' } }, transition: { onComplete: 'L5-A01' } }),
  numberQuestion({ id: 'L5-A01', microSkillId: 'long-multiplication-application', phase: 'transfer', title: 'There are 24 boxes', prompt: 'Each box has 416 screws. How many screws are there altogether?', component: { type: 'longMultiplication', props: { multiplicand: '416', multiplier: '24', onesRow: '1664', tensRow: '8320', total: '9984' } }, answer: 9984, displayAnswer: '9,984', correct: 'Correct. There are 9,984 screws.', incorrect: 'Work out 416 × 24. The answer is 9,984.', next: 'L5-W05', misconceptionId: 'LM-WORD-PROBLEM' }),
  continueState({ id: 'L5-W05', microSkillId: 'long-multiplication-application', phase: 'teach', teachingIntent: 'Show one simple place-value scaling step.', content: { title: 'Use an answer you already know', body: '24 × 16 = 384. Now 24 becomes 240.', prompt: '240 is 10 times bigger, so the answer is 10 times bigger too.' }, component: { type: 'multiplicationScale', props: { known: { left: '24', right: '16', product: '384' }, target: { left: '240', right: '16', product: '3,840' }, leftScale: 10, rightScale: 1 } }, transition: { onComplete: 'L5-S01' } }),
  numberQuestion({ id: 'L5-S01', microSkillId: 'long-multiplication-application', phase: 'guided', title: 'Both numbers are 10 times bigger', prompt: '10 × 10 = ? Type how many times bigger the answer is.', component: { type: 'multiplicationScale', props: { known: { left: '2.96', right: '3.2', product: '9.472' }, target: { left: '29.6', right: '32', product: '947.2' }, leftScale: 10, rightScale: 10, revealOnAnswer: true } }, answer: 100, correct: 'Correct. The answer is 100 times bigger.', incorrect: 'Both changes matter: 10 × 10 = 100.', next: 'L5-S02', misconceptionId: 'LM-SCALE-BOTH' }),
  numberQuestion({ id: 'L5-S02', microSkillId: 'long-multiplication-application', phase: 'transfer', title: '9.472 × 100 = ?', component: { type: 'multiplicationScale', props: { known: { left: '2.96', right: '3.2', product: '9.472' }, target: { left: '29.6', right: '32', product: '947.2' }, leftScale: 10, rightScale: 10, revealOnAnswer: true } }, answer: 947.2, correct: 'Correct. 29.6 × 32 = 947.2.', incorrect: 'Move every digit two places to the left: 947.2.', next: 'L5-I01', misconceptionId: 'LM-SCALE-ANSWER' }),
  numberQuestion({ id: 'L5-I01', microSkillId: 'mixed', phase: 'independent', title: 'Try this one: 132 × 21', component: { type: 'longMultiplication', props: { multiplicand: '132', multiplier: '21', onesRow: '132', tensRow: '2640', total: '2772' } }, answer: 2772, displayAnswer: '2,772', correct: 'Correct. 132 × 21 = 2,772.', incorrect: 'First row: 132. Second row: 2,640. Add them to get 2,772.', next: 'L5-I02', misconceptionId: 'LM-INDEPENDENT-ONE' }),
  numberQuestion({ id: 'L5-I02', microSkillId: 'mixed', phase: 'independent', title: 'Now try 243 × 32', component: { type: 'longMultiplication', props: { multiplicand: '243', multiplier: '32', onesRow: '486', tensRow: '7290', total: '7776' } }, answer: 7776, displayAnswer: '7,776', correct: 'Correct. 243 × 32 = 7,776.', incorrect: 'First row: 486. Second row: 7,290. Add them to get 7,776.', next: 'L5-I03', misconceptionId: 'LM-INDEPENDENT-TWO' }),
  numberQuestion({ id: 'L5-I03', microSkillId: 'mixed', phase: 'mastery', title: 'Last one: 527 × 43', component: { type: 'longMultiplication', props: { multiplicand: '527', multiplier: '43', onesRow: '1581', tensRow: '21080', total: '22661' } }, answer: 22661, displayAnswer: '22,661', correct: 'Correct. 527 × 43 = 22,661.', incorrect: 'First row: 1,581. Second row: 21,080. Add them to get 22,661.', next: 'L5-END', misconceptionId: 'LM-FINAL' }),
  continueState({ id: 'L5-END', microSkillId: 'mixed', phase: 'mastery', teachingIntent: 'Repeat the four plain-language steps.', content: { eyebrow: 'Lesson complete', title: 'First row → zero → second row → add', body: 'Start on the right. Carry when you need to. Do not skip a zero inside a number.', prompt: 'You can now use long multiplication.' }, component: { type: 'longMultiplication', props: { multiplicand: '527', multiplier: '43', onesRow: '1581', tensRow: '21080', total: '22661' } }, transition: {} }),
]

export const longMultiplicationLesson: LessonDefinition = { id: 'lesson-5-long-multiplication', title: 'Long multiplication', level: 'GCSE Foundation', goal: 'Use column multiplication to multiply larger numbers.', states }

export const longMultiplicationMicroSkillLabels: Partial<Record<MicroSkillId, string>> = {
  'long-multiplication-layout': 'Set it up', 'long-multiplication-ones': 'First row', 'long-multiplication-tens': 'Second row',
  'long-multiplication-carrying': 'Carry', 'long-multiplication-application': 'Problems', mixed: 'Practice',
}
