import type { TeachingFrame } from '../teachingFrame'

// One route: particles spread out (diffusion) → where it happens in the body → what speeds it up →
// the same idea for water across a membrane (osmosis) → plant cells in solutions. See STORYBOARD.md.
// One new word per screen. Plain meaning first, then the GCSE term.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const transportFrames: Record<string, TeachingFrame[]> = {
  'B6-02': [
    f('How much is in a space', 'Concentration compares amounts in the same volume.', 'more particles in the same space → higher concentration', 'Every cell, including the stem cells you just met, needs substances to move in and out. Think of strong and weak squash. Concentration means how much of a substance is in a given volume. More particles in the same volume means a higher concentration.', 'diffusion'),
    f('Particles never stop', 'Particles in a gas or liquid move about all the time.', 'any direction, no pattern', 'Particles in a gas or a liquid are always moving. They bump into each other and change direction. Moving with no set pattern is called random movement. So some particles go left while others go right.', 'diffusion'),
    f('More leave than return', 'More particles leave a crowded region than come back.', 'crowded → less crowded, overall', 'Look at two regions side by side. The left one has a higher concentration. More leave a higher-concentration region than return. The overall movement, once you count both ways, is called net movement.', 'diffusion'),
    f('Meet diffusion', 'Particles spread out overall from higher to lower concentration.', 'higher → lower, overall', 'This net spreading of particles from a higher to a lower concentration is called diffusion. It happens in gases and in liquids. The particles’ own movement does the work, so the cell does not supply energy.', 'diffusion'),
    f('Even spread, still moving', 'At equal concentrations there is no net movement.', 'still moving, but balanced', 'When both regions reach the same concentration, the particles still move. Just as many move each way. So the movements balance, and there is no net movement.', 'diffusion'),
    f('Put it together', 'Random movement gives net movement from higher to lower concentration.', 'random moves → net spread → balance', 'Particles move randomly all the time. More leave a crowded region than return, so there is net movement from higher to lower concentration. This is diffusion. It carries on until the concentrations are equal.', 'diffusion'),
  ],
  'B6-04': [
    f('A difference in concentration', 'Diffusion needs a difference between two places.', 'difference → diffusion can happen', 'Diffusion needs a difference in concentration between two places. This difference is called a concentration gradient. Particles diffuse down the gradient, from higher to lower concentration.', 'diffusion'),
    f('Oxygen gets into cells', 'Oxygen diffuses from the blood into cells.', 'blood high, cell low → oxygen in', 'Cells use oxygen all the time, so the oxygen concentration inside them stays low. Blood arriving at the cells has more oxygen. So oxygen diffuses from the blood into the cells.', 'diffusion-examples'),
    f('Carbon dioxide gets out', 'Carbon dioxide diffuses from cells into the blood.', 'cell high, blood low → carbon dioxide out', 'Cells make carbon dioxide as a waste gas. So its concentration is higher inside the cells than in the blood. Carbon dioxide diffuses out of the cells and into the blood.', 'diffusion-examples'),
    f('Another waste', 'Liver cells make a dissolved waste.', 'made in cells → builds up inside', 'Liver cells make a waste substance that dissolves in water. This waste is called urea. It builds up inside the cells, so its concentration there is higher than in the blood.', 'diffusion-examples'),
    f('Into the plasma', 'Urea diffuses into the liquid part of the blood.', 'cells → plasma → kidneys', 'The liquid part of the blood is called plasma. Urea diffuses from the cells into the plasma. The blood carries it to the kidneys, which remove it from the body.', 'diffusion-examples'),
    f('Put it together', 'Each substance diffuses down its own gradient.', 'check the gradient for each substance', 'Oxygen diffuses into cells. Carbon dioxide and urea diffuse out of cells. Each one moves from where its concentration is higher to where it is lower. So the direction depends on the gradient for that substance.', 'diffusion-examples'),
  ],
  'B6-06': [
    f('A bigger difference', 'A steeper gradient makes diffusion faster.', 'bigger difference → faster', 'A big difference in concentration is called a steep gradient. More particles move across overall each second. So diffusion is faster when the gradient is steeper.', 'diffusion-rate'),
    f('Warmer', 'A higher temperature makes diffusion faster.', 'more energy → faster particles', 'When it is warmer, particles have more energy. They move faster, so they spread out faster. So diffusion is faster at a higher temperature.', 'diffusion-rate'),
    f('More surface', 'A bigger surface lets more particles cross at once.', 'bigger surface → more crossing', 'Particles often diffuse across a surface, such as a cell membrane. The size of that surface is called its surface area. A larger surface area lets more particles cross at the same time.', 'diffusion-rate'),
    f('Change one thing at a time', 'Compare one factor and keep the others the same.', 'one change, everything else fixed', 'To see what one factor does, change only that factor. Keep the others the same. A test like this is called a fair test. Otherwise you cannot tell which change made diffusion faster.', 'diffusion-rate'),
    f('Put it together', 'Steeper, warmer or bigger surface: diffusion is faster.', 'gradient, temperature, surface area', 'Diffusion is faster when the gradient is steeper. It is faster when it is warmer. It is faster across a larger surface area. To compare them, test one factor at a time.', 'diffusion-rate'),
  ],
  'B6-08': [
    f('Some things through, some not', 'A cell membrane lets some substances through but not others.', 'small water through, some solutes blocked', 'A cell membrane lets some substances pass through, but not others. Small water molecules can pass. Some larger dissolved particles cannot. A membrane like this is called a partially permeable membrane.', 'osmosis'),
    f('Dissolved particles', 'A substance dissolved in water is called a solute.', 'sugar dissolved in water', 'When sugar dissolves in water, it makes a solution. The dissolved substance is called a solute. In squash, the sugar is a solute.', 'osmosis'),
    f('Dilute and concentrated', 'A dilute solution has little solute and lots of water.', 'less solute → more water', 'A solution with little solute in a given volume is called dilute. It has lots of water. A concentrated solution has more solute and less water.', 'osmosis'),
    f('Water moves across', 'Water moves from a dilute to a more concentrated solution.', 'more water → less water', 'Put a dilute and a concentrated solution on either side of a partially permeable membrane. Water can cross, but the solute cannot. The dilute side has more water, so water moves overall into the concentrated side. This is called osmosis.', 'osmosis'),
    f('Water keeps moving', 'Water crosses the membrane both ways all the time.', 'still moving, but balanced', 'Water molecules cross the membrane in both directions. When equal amounts cross each way, there is no net movement. The water has not stopped. Its movements balance.', 'osmosis'),
    f('Put it together', 'Osmosis is the diffusion of water across a partially permeable membrane.', 'water only, across a membrane, dilute → concentrated', 'Osmosis is a type of diffusion. Only water moves. It crosses a partially permeable membrane. Net movement is from a dilute solution to a more concentrated one.', 'osmosis'),
  ],
  'B6-11': [
    f('Compare outside and inside', 'Water can cross a plant cell’s membrane by osmosis.', 'outside compared with inside', 'A plant cell contains a solution of sugars and other solutes. Its membrane is partially permeable. So water moves in or out by osmosis. The direction depends on the solution outside compared with inside.', 'osmosis'),
    f('Outside more dilute', 'Water moves in, so the tissue gains mass.', 'dilute outside → water in → mass up', 'Put a piece of potato in pure water. The water outside is more dilute than the cell contents. So water moves into the cells by osmosis. The potato gains water, so its mass goes up.', 'tissue-gain'),
    f('Outside more concentrated', 'Water moves out, so the tissue loses mass.', 'concentrated outside → water out → mass down', 'Now put a piece in a very sugary solution. The outside is more concentrated than the cell contents. So water moves out of the cells by osmosis. The potato loses water, so its mass goes down.', 'tissue-loss'),
    f('The same inside and out', 'With no net movement, the mass stays the same.', 'equal → balanced → no change', 'If the outside solution matches the cell contents, water moves in and out equally. There is no net movement of water. So the mass of the potato stays the same.', 'osmosis'),
    f('Put it together', 'Compare outside with inside to predict the change.', 'dilute outside: up; concentrated outside: down', 'Compare the solution outside with the cell contents. More dilute outside: water in, mass up. More concentrated outside: water out, mass down. Next, you will measure this yourself in the osmosis practical.', 'tissue-loss'),
  ],
}
