import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { protectFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.7.3.6 Maintaining biodiversity: breeding programmes for endangered species, protection and regeneration of rare habitats, reintroduction of field margins and hedgerows, reduction of deforestation and carbon dioxide emissions, recycling instead of landfill' }
const a = author('B-PROTECT-BIODIVERSITY', ['4.7.3.6'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const protectSections = [
  { id: 'B53-01', label: 'Start here', detail: 'A field of wheat' },
  { id: 'B53-02', label: 'How can we save an endangered species?', detail: 'Breeding in captivity and release' },
  { id: 'B53-05', label: 'How can farms hold more species?', detail: 'Field margins and hedgerows' },
  { id: 'B53-08', label: 'How can we look after habitats?', detail: 'Protecting, regenerating and recycling' },
  { id: 'B53-11', label: 'What can governments do?', detail: 'Rules on forests and carbon dioxide' },
  { id: 'B53-14', label: 'On your own', detail: 'Otters, a farm map and an insect survey' },
]

const states: ScienceState[] = [
  { ...a.choice('B53-01', 'A large field grows nothing but wheat. What is its biodiversity likely to be?', ['High, because it has lots of plants', 'Low, because very few different species live there', 'High, because wheat grows quickly'], 1, 'Biodiversity is about how many different species there are.', ['Lots of wheat plants are still only one species.', 'Very few different species live there, so its biodiversity is low. You met biodiversity when you learned about waste and pollution.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B53-02', 'How can we save an endangered species?'),
  a.choice('B53-03', 'What is an endangered species?', ['A species that is at risk of dying out', 'A species that only lives in zoos', 'A species that eats other animals'], 0, 'Think about how many are left in the wild.', ['An endangered species has so few individuals left that it could die out.', 'Breeding programmes help species like this survive.']),
  a.choice('B53-04', 'A kind of frog has been wiped out from one lake. How could a breeding programme help?', ['Move the lake’s fish to a zoo', 'Stop all frogs from breeding', 'Release frogs bred in captivity into the lake'], 2, 'What can happen to animals bred in captivity?', ['Frogs of that species can be bred safely in captivity.', 'Some can then be released into the lake to replace the population that was wiped out.']),
  t('B53-05', 'How can farms hold more species?'),
  a.choice('B53-06', 'What is a field margin?', ['A line of bushes planted in a garden', 'A strip at the edge of a field where wild flowers and grasses grow', 'A field that grows only one crop'], 1, 'Where on the field is it, and what grows there?', ['A line of bushes along a field is a hedgerow, not a margin.', 'A field margin is a strip at the edge of a field where wild flowers and grasses are left to grow.']),
  a.choice('B53-07', 'How do hedgerows help to increase biodiversity on a farm?', ['They give food and shelter to many different species', 'They make the crop grow faster', 'They stop any animals from reaching the field'], 0, 'What do birds and insects find in a hedge?', ['A field of one crop gives few species anywhere to live.', 'Hedgerows give food and shelter to many species, so biodiversity goes up.']),
  t('B53-08', 'How can we look after habitats?'),
  a.choice('B53-09', 'Young trees are planted where an old wood was cut down. What is this called?', ['Recycling a habitat', 'Protecting a species in captivity', 'Regenerating a habitat'], 2, 'Is the habitat being kept, or being rebuilt?', ['Planting trees rebuilds the wood, so its habitat grows back.', 'Rebuilding a damaged habitat is called regenerating it.']),
  a.choice('B53-10', 'How can recycling help to protect ecosystems?', ['It makes more waste to bury', 'Less land is taken for landfill, so more ecosystems are left alone', 'It turns landfill sites into forests straight away'], 1, 'Where does waste go if it is not recycled?', ['Recycling means less waste is dumped in landfill sites.', 'So less land is needed for landfill, and more ecosystems can be left alone.']),
  t('B53-11', 'What can governments do?'),
  a.choice('B53-12', 'Why could limiting the carbon dioxide released by businesses help ecosystems?', ['It could help slow global warming', 'It makes forests grow faster straight away', 'It stops all pollution of rivers'], 0, 'What does carbon dioxide do in the atmosphere?', ['Carbon dioxide is a greenhouse gas, so it traps energy and warms the Earth.', 'Releasing less of it could help slow global warming, which threatens many species.']),
  a.choice('B53-13', 'A new law stops a forest being cut down. Why might some local people object?', ['The forest will release more carbon dioxide', 'Trees cannot grow without being cut', 'Biodiversity in the forest will fall', 'People paid to cut down trees could lose their jobs'], 3, 'Who earns money from cutting down the trees?', ['The law protects the forest, which is good for biodiversity.', 'But people who are paid to cut down trees could lose their jobs, so some may object.']),
  a.choice('B53-14', 'Otters died out along a river when it was polluted. The river is now clean. Which programme could bring otters back?', ['Plant more wheat beside the river', 'Recycle more plastic', 'Release otters bred in captivity along the river'], 2, 'Which programme puts animals back into the wild?', ['Otters bred in captivity can be released into the wild.', 'Released along the clean river, they could replace the population that was wiped out.'], 'application', true),
  a.choice('B53-15', 'Look at the numbered areas of the farm. Which one is a field margin?', ['Area 1', 'Area 2', 'Area 3'], 2, 'Find the strip of wild flowers and grasses at the field’s edge.', ['Area 1 is a line of bushes, a hedgerow, and area 2 is the wheat crop.', 'Area 3 is the strip of wild flowers and grasses at the edge of the field, so it is the field margin.'], 'understanding', true, 'earth-farm-question'),
  a.choice('B53-16', 'Students counted kinds of insect at the edges of three wheat fields. Which conclusion fits their results?', ['Insects only live in hedgerows', 'No insects were found where there was no margin', 'Every hedgerow has 23 kinds of insect', 'In this survey, more kinds of insect were found where fields had a margin and a hedgerow'], 3, 'What do these three counts show, and no more?', ['They found 5 kinds with no margin or hedgerow, 14 with a margin and 23 with a margin and a hedgerow.', 'Three fields cannot show what happens on every farm, and insects were found at all three. In this survey, more kinds were found with a margin and a hedgerow.'], 'dataInterpretation', true, 'earth-insect-data'),
  a.written('B53-17', 'A rare bird nests only in one wetland, and very few are left. Explain two programmes that could help it survive.', 'Think about the birds themselves, and about the place they live.', 'The bird is endangered, because it is at risk of dying out. In a breeding programme, some birds are bred in captivity, so the species survives even if the wild birds die. Some can be released into the wetland to make the wild population bigger. The wetland is a rare habitat, so it could be protected as a nature reserve so nobody builds on it or drains it. Damaged parts could be regenerated, so there is more habitat for the birds.', ['Breed some birds in captivity in a breeding programme.', 'So the species survives even if the wild birds die out.', 'Release captive-bred birds to make the wild population bigger.', 'Protect the wetland, for example as a nature reserve, so it is not built on or drained.', 'Regenerate damaged parts of the wetland, so there is more habitat.'], ['Saying the birds should all be moved to a zoo for ever, with no reason given.', 'Saying recycling makes the birds breed faster.', 'Saying an endangered species is one that is dangerous to people.']),
]

export const lesson53: ScienceLesson = {
  id: 'B-ECO-053-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Protecting ecosystems and biodiversity', prerequisites: ['B-BIODIVERSITY', 'B-LAND-AND-CLIMATE'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
