import type { TeachingFrame } from '../teachingFrame'

// Saving the rarest species first, then making room for many species on farmland, then protecting whole habitats and land,
// then rules made by governments and the reasons some people object.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const protectFrames: Record<string, TeachingFrame[]> = {
  'B53-02': [
    f('Only a few left', 'Some species have so few individuals left that they could die out.', 'fewer individuals → risk of dying out', 'Human activity can reduce biodiversity and damage ecosystems, as you saw with pollution and deforestation. Some species now have only a few individuals left in the wild. A species that is at risk of dying out is called an endangered species.', 'earth-breed-wild'),
    f('Bred in captivity', 'Some of the animals are kept safe by people and allowed to breed.', 'kept safe → young are born → numbers grow', 'Some individuals can be kept in a safe place, such as a zoo, and allowed to breed. Being kept and cared for by people like this is called captivity. The young are protected, so the number of animals grows.', 'earth-breed-captive'),
    f('A back-up population', 'If the wild ones die out, the species still survives in captivity.', 'wild ones lost → captive ones still alive', 'Suppose the last wild animals die, for example because their habitat is destroyed. Some individuals are still alive in captivity. So the species has not died out completely.', 'earth-breed-backup'),
    f('Back into the wild', 'Animals bred in captivity can be released into the wild.', 'released → wild population bigger or back again', 'Some animals bred in captivity can be released into the wild. This can make a small wild population bigger. It can also replace a wild population that has been wiped out.', 'earth-breed-release'),
    f('Put it together', 'Breeding in captivity and releasing animals helps endangered species.', 'wild → captivity → released', 'Breeding an endangered species in captivity, then sometimes releasing it, is called a breeding programme. It keeps the species alive and can help wild numbers recover.', 'earth-breed-all'),
  ],
  'B53-05': [
    f('A field of one crop', 'A field that grows only one crop has very low biodiversity.', 'one crop → very few species', 'Many farms grow one crop across a whole field, such as wheat. Almost nothing else is allowed to grow there. So very few species can live in the field, and it has very low biodiversity.', 'earth-farm-crop'),
    f('Field margins', 'Wild flowers and grasses are left to grow around the edge.', 'strip at the edge → wild plants grow', 'A farmer can leave a strip of land around the edge of a field. Wild flowers and grasses are left to grow there. This strip is called a field margin.', 'earth-farm-margin'),
    f('Hedgerows', 'A line of bushes is planted along the edge of the field.', 'bushes planted in a line → hedgerow', 'A farmer can also plant bushes close together along the edge of a field. As they grow, they form a hedge. A long line of hedge like this is called a hedgerow.', 'earth-farm-hedge'),
    f('Homes for many species', 'Field margins and hedgerows give food and shelter to many species.', 'more habitats → more species → higher biodiversity', 'Field margins and hedgerows give food and shelter to many different species, such as bees, butterflies, birds and small mammals. They are habitats that the crop field cannot provide. So adding them back to farmland raises biodiversity on the farm.', 'earth-farm-all'),
  ],
  'B53-08': [
    f('Rare habitats', 'Some habitats are only found in a few places.', 'few places left → species there at risk', 'Some habitats are only found in a few places, such as an old woodland or a wetland. Many species live only in habitats like these. A habitat that is found in only a few places is called a rare habitat.', 'earth-habitat-rare'),
    f('Protecting habitats', 'A protected area is kept safe from building and farming.', 'protected → habitat stays → species stay', 'An area of rare habitat can be protected so that nobody builds on it or farms it. The species that live there keep their habitat. A protected area like this is called a nature reserve.', 'earth-habitat-protect'),
    f('Regenerating habitats', 'A damaged habitat can be rebuilt.', 'rebuild habitat → species move back', 'A damaged habitat can be rebuilt, for example by planting young trees where a wood was cut down. Rebuilding a habitat like this is called regenerating it. As the habitat grows back, species can move back in.', 'earth-habitat-regrow'),
    f('Recycling', 'Recycling means less land is needed for landfill.', 'recycle → less landfill → land left alone', 'You met landfill sites when you learned about waste. Turning used materials into new things is called recycling. It means less waste is dumped, so less land is taken for landfill. More ecosystems can be left alone.', 'earth-habitat-recycle'),
    f('Put it together', 'Protecting, rebuilding and saving land all help other species.', 'more habitat left → more species survive', 'Protecting rare habitats keeps them safe, and regenerating damaged habitats brings them back. Recycling means less land is taken for landfill. Each one leaves more habitat for other species, so it helps protect biodiversity.', 'earth-habitat-all'),
  ],
  'B53-11': [
    f('Rules on forests', 'Some governments limit how many trees can be cut down.', 'fewer trees cut → less carbon dioxide added', 'Cutting down forests adds carbon dioxide to the air and destroys habitats, as you saw with deforestation. Some governments have made rules to reduce deforestation. A rule made by a government is called a law.', 'earth-rules-forest'),
    f('Rules on businesses', 'Some governments limit the carbon dioxide that businesses release.', 'less carbon dioxide → global warming slows', 'Some governments have also made rules to cut the carbon dioxide released by businesses, such as factories. Carbon dioxide is a greenhouse gas. So releasing less of it could help to slow global warming.', 'earth-rules-carbon'),
    f('Not everyone agrees', 'Some people object because of the cost or their jobs.', 'protect ecosystems ↔ money and jobs', 'Programmes like these can cost a lot of money. Some can affect people’s jobs, such as people who are paid to cut down trees. So not everyone agrees with them. Protecting ecosystems has to be balanced against people’s needs.', 'earth-rules-object'),
    f('Put it together', 'Rules on forests and carbon dioxide help protect ecosystems.', 'fewer trees cut + less carbon dioxide → ecosystems protected', 'Rules on forests keep habitats, and the trees left keep taking in carbon dioxide. Rules on businesses cut the carbon dioxide they release. Both could help slow global warming, but some people object because of the cost or lost jobs.', 'earth-rules-all'),
  ],
}
