import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { enzymeFrames as frames } from './teachingFrames'

const biology = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.2.2.1 Enzymes and the digestive system' }
const practical = { id: 'aqa-practical', title: 'AQA 8464 practical assessment', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/practical-assessment', locator: '10.2.4 Required practical 4; Biology AT1, AT2 and AT5' }
const handbook = { id: 'aqa-handbook', title: 'AQA Combined Science practical handbook', url: 'https://filestore.aqa.org.uk/resources/science/AQA-8464-8465-PRACTICALS-HB.PDF', locator: 'Teacher notes pp14–15; student worksheet pp66–68; school risk assessment governs the practical' }
const a = author('B-ENZYMES', ['4.2.2.1'])
const p = author('B-ENZYME-PRACTICAL', ['4.2.2.1', '10.2.4'], ['aqa-biology', 'aqa-practical', 'aqa-handbook'])
const t = (id: keyof typeof frames, title: string) => (Number(id.slice(3)) >= 9 ? p : a).teach(id, title, frames[id])

export const enzymeSections = [
  { id: 'B8-01', label: 'Start here', detail: 'Where digestion of bread begins' },
  { id: 'B8-02', label: 'What does saliva do to bread?', detail: 'Enzymes are biological catalysts' },
  { id: 'B8-04', label: 'Why only starch?', detail: 'Active sites and the lock-and-key model' },
  { id: 'B8-06', label: 'What changes the speed?', detail: 'Temperature, pH and denaturing' },
  { id: 'B8-09', label: 'Plan a fair test', detail: 'Required practical 4: amylase and pH' },
  { id: 'B8-13', label: 'Read the results', detail: 'Pattern, optimum and rate' },
  { id: 'B8-16', label: 'On your own', detail: 'Scenario, data, method and explanation' },
]

const states: ScienceState[] = [
  { ...a.choice('B8-01', 'You chew a piece of bread. In which organ does its digestion begin?', ['The stomach', 'The mouth', 'The small intestine'], 1, 'Where does food enter the digestive system?', ['Food enters the digestive system at the mouth.', 'Saliva is added there, so digestion of bread begins in the mouth.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B8-02', 'What does saliva do to bread?'),
  a.choice('B8-03', 'Amylase breaks down starch in your mouth. What happens to the amylase afterwards?', ['It becomes part of the sugars', 'It is used up and must be replaced each time', 'It is unchanged and can work again'], 2, 'Is a catalyst used up?', ['Amylase is a biological catalyst, so it is not used up.', 'So it is unchanged and can break down more starch.']),
  t('B8-04', 'Why does amylase only break down starch?'),
  a.choice('B8-05', 'Amylase breaks down starch but not protein. Why?', ['Its active site only fits the shape of starch', 'Protein is too small to reach the enzyme', 'Amylase is used up by the starch first', 'Protein does not dissolve in saliva'], 0, 'Which part of the enzyme must the substrate fit?', ['The active site has a shape that starch fits.', 'Protein has a different shape, so it does not fit and is not broken down.'], 'understanding', false, 'enzyme-match'),
  t('B8-06', 'What changes the speed?'),
  a.choice('B8-07', 'Amylase is slow at 10 °C, fastest at 37 °C and almost stops at 70 °C. Why does it almost stop at 70 °C?', ['The particles move too slowly to meet', 'It is denatured, so starch no longer fits the active site', 'The amylase has been used up', '70 °C is its optimum temperature'], 1, 'What does too much heat do to the active site?', ['Heat above the optimum changes the shape of the active site.', 'So starch no longer fits, and the enzyme is denatured.'], 'dataInterpretation'),
  a.choice('B8-08', 'Amylase works fastest at about pH 7. What happens to it in strong acid?', ['It works faster, because acid helps break down starch', 'It works just the same, because pH does not affect enzymes', 'It is used up by the acid', 'Its active site changes shape, so it slows down or stops'], 3, 'How far is strong acid from pH 7?', ['Strong acid is far from the optimum pH of amylase.', 'So the active site changes shape, starch fits less well, and the reaction slows or stops.']),
  t('B8-09', 'Plan a fair test'),
  p.choice('B8-10', 'In the amylase test, which is the independent variable?', ['The pH of each tube', 'The time until the starch is gone', 'The temperature of the water bath'], 0, 'Which one do you change on purpose?', ['The independent variable is the one thing you change on purpose.', 'You use a different buffer in each tube, so pH is the independent variable.'], 'practicalReasoning'),
  p.choice('B8-11', 'Why must every tube sit in the same water bath?', ['Water makes the iodine work', 'The buffer only works in water', 'Temperature affects enzymes, so it is a control variable', 'Warm water makes the starch dissolve'], 2, 'Apart from pH, what else changes how fast enzymes work?', ['Temperature also changes how fast enzymes work.', 'So keeping it the same means only pH changes between the tubes.'], 'practicalReasoning'),
  p.choice('B8-12', 'Why repeat each pH and work out a mean time?', ['To change the independent variable', 'To reduce the effect of random variation', 'To prove every result is exactly right', 'To make the reaction go faster'], 1, 'What can make one result a little off by chance?', ['One result can be a little off by chance, such as starting the clock late.', 'So a mean of several repeats reduces the effect of random variation.'], 'practicalReasoning'),
  t('B8-13', 'Read the results'),
  p.choice('B8-14', 'Look at the table. Which tested pH gave the fastest reaction?', ['pH 3', 'pH 7', 'pH 9'], 1, 'Which pH has the shortest time?', ['The shortest time in the table is 60 seconds.', 'So pH 7 gave the fastest reaction of the pH values tested.'], 'dataInterpretation', false, 'enzyme-results-question'),
  p.choice('B8-15', 'The starch is gone after 80 seconds. Using rate = 1000 ÷ time, what is the rate?', ['12.5', '0.08', '1080', '920'], 0, 'Which number goes first: 1000 or the time?', ['Rate = 1000 ÷ time.', 'So the rate is 1000 ÷ 80 = 12.5.'], 'calculation'),
  a.choice('B8-16', 'A washing powder contains enzymes that break down food stains. The box says to wash at 30 °C, not 90 °C. Why?', ['At 90 °C the enzymes are used up faster', 'Enzymes always work faster in cold water', 'At 90 °C the enzymes are denatured, so the stains are not broken down', 'Enzymes only work at exactly 30 °C'], 2, 'What does too much heat do to an enzyme?', ['At 90 °C, heat changes the shape of the active site.', 'So the enzymes are denatured and cannot break down the stains.'], 'application', true),
  p.choice('B8-17', 'A student tests amylase at four pH values. Times: pH 5, 90 s; pH 6, 40 s; pH 7, 45 s; pH 8, 100 s. Which conclusion fits?', ['The optimum pH of amylase is exactly 6', 'All enzymes work best at pH 6', 'Amylase does not work at all at pH 8', 'In this test, pH 6 was fastest; more pH values near 6 would pin down the optimum'], 3, 'Only say what these results show.', ['The shortest time was 40 seconds, at pH 6, and pH 7 was close behind.', 'So pH 6 was fastest in this test, but the optimum could lie a little either side.'], 'dataInterpretation', true),
  p.choice('B8-18', 'A student plans: “Put each tube in a water bath at a different temperature, with a different pH buffer. Sample into iodine every 30 seconds.” What is wrong?', ['Temperature and pH both change, so you cannot tell which caused a difference', 'Iodine cannot show whether starch is there', 'pH does not affect amylase', 'Sampling every 30 seconds is too often'], 0, 'How many things should you change on purpose?', ['Only the independent variable, pH, should change.', 'So temperature is a control variable and must be the same for every tube.'], 'practicalReasoning', true),
  p.written('B8-19', 'Explain how the amylase practical shows the effect of pH on the rate of reaction.', 'Say what you change, what you keep the same, how you spot the end point, how you make results trustworthy, and how you compare speeds.', 'Use a different buffer in each tube to change the pH. Keep the temperature the same in a water bath, and use the same volumes of amylase and starch. Every 30 seconds, put a drop of the mixture into iodine. Record the time when the iodine first stays brown-orange, because the starch has gone. Repeat each pH and take a mean. A shorter time, or a bigger rate from 1000 ÷ time, means a faster reaction. Far from the optimum pH, the active site changes shape, so the reaction is slower.', ['Change the pH using a different buffer in each tube.', 'Keep a control variable the same, such as temperature, volume or concentration.', 'Sample into iodine every 30 seconds until a drop stays brown-orange.', 'Repeat each pH and calculate a mean time.', 'A shorter time, or a bigger rate, means a faster reaction.', 'Far from the optimum pH, the active site changes shape, so the reaction slows.'], ['Temperature and pH are changed together.', 'Blue-black is treated as the end point where starch has gone.', 'Carry out the chemical investigation unsupervised at home.', 'A longer time is said to mean a faster reaction.']),
]

export const lesson8: ScienceLesson = {
  id: 'B-ORG-008-B', contentVersion: '0.3.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'Enzymes and reaction rates', prerequisites: ['B-ORGANISATION'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [biology, practical, handbook], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
