/* Every lesson's key facts, keyed by lesson id. One file per lesson folder. DRAFT: awaiting teacher review. */
import type { ScienceFactSet } from '../types'
import { facts as f1 } from './1'
import { facts as f1b } from './1b'
import { facts as f2 } from './2'
import { facts as f2b } from './2b'
import { facts as f3 } from './3'
import { facts as f4 } from './4'
import { facts as f5 } from './5'
import { facts as f5b } from './5b'
import { facts as f6 } from './6'
import { facts as f6b } from './6b'
import { facts as f6c } from './6c'
import { facts as f7 } from './7'
import { facts as f8 } from './8'
import { facts as f9 } from './9'
import { facts as f10 } from './10'
import { facts as f11 } from './11'
import { facts as f12 } from './12'
import { facts as f13 } from './13'
import { facts as f14 } from './14'
import { facts as f15 } from './15'
import { facts as f16 } from './16'
import { facts as f17 } from './17'
import { facts as f18 } from './18'
import { facts as f19 } from './19'
import { facts as f20 } from './20'
import { facts as f21 } from './21'
import { facts as f22 } from './22'
import { facts as f23 } from './23'
import { facts as f24 } from './24'
import { facts as f25 } from './25'
import { facts as f26 } from './26'

export const scienceFacts: Record<string, ScienceFactSet> = Object.fromEntries([f1, f1b, f2, f2b, f3, f4, f5, f5b, f6, f6b, f6c, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26].map(set => [set.lessonId, set]))
