import type { TeachingFrame } from '../../teachingFrame'

// Communicating science and the issues it creates: telling people, bias in reporting, four kinds of issue, and questions science cannot answer.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const wsIssueFrames: Record<string, TeachingFrame[]> = {
  'W2-02': [
    f('Discoveries change lives', 'Scientists tell the world about discoveries because they can make a big difference to people\'s lives.', 'who could this help', 'Scientists should tell the world about their discoveries, because discoveries can make a big difference to people\'s lives. When a new vaccine works, people can only benefit if they hear about it. They also need to understand what it does, so they can decide whether to have it.', 'wsissue-tell'),
    f('Advice on habits', 'Sometimes scientists need to advise people to change their habits.', 'evidence, then advice', 'Sometimes scientists need to advise people to change their habits. Evidence showed that sugary drinks cause tooth decay, so dentists advise cutting down on them. Advice is only useful if people hear it and trust it.', 'wsissue-habits'),
    f('New technologies', 'People also need to be told about new technologies and how to use them.', 'who needs to know', 'Scientists also need to tell people about new technologies. Suppose a new blood test can spot a disease early. Doctors need to know how to use it. Patients need to know what the results mean.', 'wsissue-tech'),
  ],
  'W2-05': [
    f('Reports can mislead', 'Reports in the media about scientific discoveries can sometimes be misleading.', 'newspaper, TV, website', 'Newspapers, TV and websites are together called the media. Reports in the media about scientific discoveries can sometimes be misleading. The writer may not fully understand the science, or may want a dramatic headline.', 'wsissue-media'),
    f('Not quite right', 'Data may be presented in a way that is not quite right, or that is oversimplified.', 'what has been left out', 'Data may be presented in a way that is not quite right. It may be oversimplified, so that important details are lost. A headline might say a drink "boosts memory" but leave out that only ten people were tested for two days. Then people may not properly understand what the scientists really found.', 'wsissue-oversimple'),
    f('Biased presentation', 'Data can be presented in a biased way: unfairly, ignoring one side of the argument.', 'fair to both sides?', 'People who want to make a point can also present data in a biased way. This means it is unfair, because it ignores one side of the argument. Sometimes this is done on purpose. Sometimes it happens by accident.', 'wsissue-bias'),
    f('Spotting bias', 'Ask whether the report gives evidence against the idea as well as for it.', 'is anything missing', 'A scientist might talk a lot about one pattern in the data and not mention the others. A news article might quote data that supports an idea and give no evidence against it. When you read a report, ask: is anything missing, and what is the evidence?', 'wsissue-biasex'),
  ],
  'W2-08': [
    f('Economic issues', 'Economic issues are about money: society cannot always afford what science recommends.', 'money', 'Economic issues are about money. Society cannot always afford to do what scientists recommend. A new medicine might work well but cost so much that a hospital can only give it to a few patients.', 'wsissue-economic'),
    f('Social issues', 'Social issues are about how decisions based on scientific evidence affect people as a whole.', 'people in general', 'Social issues are about how decisions based on scientific evidence affect people in general. Suppose evidence shows that sugary drinks harm health. A tax on them could improve health, but it changes what everyone pays in shops.', 'wsissue-social'),
    f('Personal issues', 'Personal issues affect particular individuals, who may be upset by a decision.', 'one person or family', 'Personal issues are about individuals. A decision that helps many people can still upset a few. For example, a wind farm may cut carbon dioxide emissions, but a family living next to it may not like the noise or the view.', 'wsissue-personal'),
    f('Environmental issues', 'Environmental issues are about how human activity affects the environment.', 'effect on nature', 'Environmental issues are about how human activity affects the environment. Spreading more fertiliser on fields helps crops to grow, but some can wash into rivers and harm the living things in them. Scientists and others must weigh up benefits against effects like this.', 'wsissue-environmental'),
  ],
  'W2-11': [
    f('Not enough data yet', 'Scientists sometimes disagree because there is not yet enough data to support one explanation.', 'evidence still missing', 'Scientists do not agree about every question. How life first began on Earth is one example. There is not yet enough data to support any one explanation. Eventually, better experiments may give an answer.', 'wsissue-unknown'),
    f('Ethical questions', 'Experiments cannot tell us whether something is ethically right or wrong.', 'can an experiment answer it', 'Some questions can never be answered by experiments. An experiment can show whether changing an animal\'s genes makes it grow faster. It cannot tell us whether it is right to do it. Questions about right and wrong are called ethical questions.', 'wsissue-ethics'),
    f('Deciding together', 'Science gives evidence; society decides what to do. The aim is a decision most people can live with.', 'evidence, then a shared decision', 'Science can supply evidence, but it cannot make the decision for us. That is for people and society. The best we can do is make a decision that most people are reasonably happy to live with. Scientists, governments and the public all have a say.', 'wsissue-decide'),
  ],
}
