import type { FeedbackDefinition, LearningState } from './types'

type WorkedExplanation = NonNullable<FeedbackDefinition['workedExplanation']>
const explanation = (answer: string, ...steps: Array<[string, ...string[]]>): WorkedExplanation => ({ answer, steps: steps.map(([title, ...lines]) => ({ title, lines })) })

// PDF-derived questions and worked explanations transcribe Aniksha's N1.1-N1.5
// source sheets verbatim. Exam marks and teacher-only marking annotations are omitted.
// Three source corrections requested by the lesson owner are documented in the Lesson 1 spec.
const explanations: Record<string, WorkedExplanation> = {
  'D-I-11': explanation('−7, 0, 12/4, 26',
    ['Check the numbers that are already whole', '−7 and 0 and 26 have nothing after a decimal point'],
    ['Work out the fraction before deciding', '12/4 = 12 ÷ 4 = 3'],
    ['Work out the root before deciding', '√11 = 3·316…'],
    ['Rule out the two that are not whole', '1.5 and √11 are not integers']),
  'D-P-01': explanation('−15',
    ['Work out each number',
      '4.2 has a decimal part, so it is not an integer.',
      '3 ÷ 8 = 0.375, so it is not an integer.',
      '√7 = 2.645…, so it is not an integer.',
      '−15 is a whole number, so it is an integer.']),
  'D-P-02': explanation('6.5 and 11/4',
    ['Work out each expression',
      '20 ÷ 5 = 4',
      '√49 = 7',
      '11 ÷ 4 = 2.75'],
    ['Classify the values',
      '−2, 0, 4 and 7 are integers.',
      '6.5 and 2.75 are not integers.']),
  'D-P-03': explanation('18/6, −9 and √81',
    ['Work out each expression',
      '18 ÷ 6 = 3',
      '√20 = 4.472…',
      '√81 = 9'],
    ['Classify the values',
      '3, −9 and 9 are integers.',
      '4.472… and 2.75 are not integers.']),
  'D-P-04': explanation('√20 = 4·472… which is not whole',
    ['Work the root out and look at what comes after the decimal point', '√20 = 4·472135…', 'It does not come out exactly, so it is not a whole number']),
  'D-P-05': explanation('Yes — n = 36, which is an integer',
    ['Undo the square root by squaring both sides', 'n = 6 × 6 = 36'],
    ['36 has nothing after a decimal point, so it is a whole number']),
  'D-P-06': { ...explanation('6·5', ['Choose anything between them that is not whole', '6·5 or 6·2 or 13/2']), answerLabel: 'Example answer' },
  'D-P-07': explanation('No — halfway between 2 and 8 is 5',
    ['Test two integers that sit next to each other', 'halfway between 4 and 5 = 4·5', 'That one is not whole, so Maya looks right so far'],
    ['But she said always, so test a pair with a gap between them', '(2 + 8) ÷ 2 = 5', '5 is a whole number, so one example is enough to break her statement']),

  'D-I-02': explanation('Integer', ['Check whether −3 has a fractional part', '−3 has no fractional part. Integers can be negative, zero or positive.']),
  'D-I-03': explanation('Non-integer', ['Place 1.5 between its neighbouring integers', '1 < 1.5 < 2', '1.5 has a fractional part, so it is not an integer.']),
  'D-I-05': explanation('4', ['Work out the fraction by dividing', '20/5 = 20 ÷ 5 = 4']),
  'D-I-06': explanation('Integer', ['Work out the fraction first', '20/5 = 20 ÷ 5 = 4'], ['Classify its value', '4 is an integer, so 20/5 represents an integer too.']),
  'D-I-07': explanation('Each has the value 2.',
    ['Work out each representation',
      '2.0 = 2',
      '4 ÷ 2 = 2'],
    ['Check the values',
      'Each representation has the value 2.',
      'Therefore, they are all integers.']),
  'D-I-09': explanation('Integer', ['Find the number that squares to 81', '9 × 9 = 81, so √81 = 9'], ['Classify the result', '9 has no fractional part, so it is an integer.']),
  'D-I-10': explanation('Non-integer',
    ['Work out the square root', '√20 = 4.472…'],
    ['See where it sits', '4 squared is 16. 5 squared is 25.', '√20 is between 4 and 5, so it is not an integer.']),

  'D-SI-04': explanation('64 = 8² and 64 = 4³, so it is both a square and a cube number',
    ['Test it as a square number first', '8 × 8 = 64'],
    ['Now test it as a cube number', '4 × 4 × 4 = 64']),
  'D-SI-05': explanation('23, 29',
    ['Check each number for a factor other than 1 and itself',
      '21 = 3 × 7',
      '22 = 2 × 11',
      '24 = 2 × 12',
      '25 = 5 × 5',
      '26 = 2 × 13',
      '27 = 3 × 9',
      '28 = 2 × 14']),
  'D-SI-06': explanation('51 = 3 × 17, so it has factors other than 1 and itself',
    ['Try dividing by small numbers to find a factor', '51 ÷ 3 = 17']),
  'D-SI-07': explanation('49 is odd, so the number is 49',
    ['List the square numbers between 30 and 50', '36 and 49']),
  'D-SI-08': explanation('1, 8, 27',
    ['Multiply each number by itself three times',
      '1 × 1 × 1 = 1',
      '2 × 2 × 2 = 8',
      '3 × 3 × 3 = 27']),
  'D-SI-09': explanation('12 = 2 × 2 × 3',
    ['Split 12 into two factors first', '12 = 2 × 6'],
    ['6 is not prime, so split it again', '6 = 2 × 3']),
  'D-SI-10': explanation('No — a prime number has exactly two factors, but 1 only has one factor (itself)'),
  'D-SI-11': explanation('N = 25',
    ['List the two-digit square numbers', '16, 25, 36, 49, 64, 81'],
    ['Pick out the one that is also a multiple of 5']),

  'D-R-03': explanation('45/100 = 9/20, a fraction of two integers, so 0·45 is rational',
    ['Write the decimal as a fraction over a power of 10', '0·45 = 45/100']),
  'D-R-04': explanation('0·6',
    ['Check which of these can be written as an exact fraction', '√10 and √12 are not exact roots, and π never ends or repeats']),
  'D-R-05': explanation('x = 7/9',
    ['Let x = 0·7… and multiply by 10', '10x = 7·7…', '10x − x = 7']),
  'D-R-06': explanation('0·625 terminates, and 5/8 is already a fraction of integers, so it is rational',
    ['Divide the numerator by the denominator', '5 ÷ 8 = 0·625']),
  'D-R-07': explanation('x = 2/11',
    ['Let x equal the recurring decimal',
      'x = 0.181818…'],
    ['Multiply by 100',
      '100x = 18.181818…'],
    ['Subtract x',
      '100x − x = 18.181818… − 0.181818…',
      '99x = 18'],
    ['Divide by 99',
      'x = 18/99'],
    ['Simplify the fraction',
      'x = 2/11']),
  'D-R-08': explanation('Yes — every integer n can be written as the fraction n/1, so every integer is rational',
    ['Think about what a rational number needs: a numerator and a denominator that are both integers', 'Any integer n can be written as n ÷ 1', 'That is already a fraction of two integers, with a denominator of 1']),

  'D-IR-04': explanation('Irrational',
    ['Find the square numbers on either side of 20',
      '4² = 16',
      '5² = 25',
      '20 is between 16 and 25.',
      'Therefore, √20 is between 4 and 5.'],
    ['Look at the decimal',
      '√20 = 4.472135…',
      'The decimal does not stop or repeat.',
      'Therefore, √20 is irrational.']),
  'D-IR-05': explanation('√17',
    ['Check which of these has an exact whole-number or fraction value', '√16 = 4, and 0·5 and 3/4 are already exact fractions']),
  'D-IR-06': explanation('Irrational',
    ['Find the square numbers on either side of 30',
      '5² = 25',
      '6² = 36',
      '30 is between 25 and 36.',
      'Therefore, √30 is between 5 and 6.'],
    ['Look at the decimal',
      '√30 = 5.477225…',
      'The decimal does not stop or repeat.',
      'Therefore, √30 is irrational.']),
  'D-IR-07': explanation('3√5',
    ['Find a square factor of 45',
      '45 = 9 × 5'],
    ['Split the square root',
      '√45 = √9 × √5'],
    ['Work out the exact root',
      '√9 = 3'],
    ['Simplify',
      '√45 = 3√5'],
    ['Classify the answer',
      '5 is not a square number.',
      'Therefore, √5 is irrational.',
      'This means 3√5 is also irrational.']),
  'D-IR-08': { ...explanation('√10 (or √11, √12, √13, √14, √15)',
    ['Work out each option as a decimal',
      '√10 = 3.162277660…',
      '√11 = 3.316624790…',
      '√12 = 3.464101615…',
      '√13 = 3.605551275…',
      '√14 = 3.741657387…',
      '√15 = 3.872983346…',
      '3.5 is a terminating decimal, so it is rational.',
      '√16 = 4']), answerLabel: 'Accepted answers' },
  'D-IR-09': explanation('4 + √13 is irrational, because adding a rational number to an irrational one never creates a pattern or an end',
    ['Find the square numbers on either side of 13',
      '3² = 9',
      '4² = 16',
      '13 is between 9 and 16.',
      'Therefore, √13 is between 3 and 4.'],
    ['Work out the decimals',
      '√13 = 3.605551275…',
      '4 + √13 = 7.605551275…'],
    ['Classify the result',
      'The decimal still does not stop or repeat.',
      'Therefore, 4 + √13 is irrational.']),
  'D-IR-10': explanation('No — the square root of a square number, like √16 = 4, is a whole number, so it is rational',
    ['Check whether the number under the root sign is a square number first', '16 is a square number, since 4² = 16', 'That means the root comes out exactly, with nothing left over']),
  'D-IR-11': explanation('No — √5 × √5 = 5, which is rational, so Priya\'s statement is false',
    ['One counter-example is enough to disprove the word "always" — try squaring a surd', '√5 × √5 = 5'],
    ['Check that the result really is rational', '5 can be written as 5/1, a fraction of two integers']),
  'D-IR-12': { ...explanation('√5 (or √6, √7, √8)',
    ['Work out each option as a decimal',
      '√5 = 2.236067977…',
      '√6 = 2.449489743…',
      '√7 = 2.645751311…',
      '√8 = 2.828427125…',
      '2.5 is a terminating decimal, so it is rational.',
      '√9 = 3']), answerLabel: 'Accepted answers' },
  'D-IR-13': explanation('No — √2 + (−√2) = 0, which is rational, so Jack\'s statement is false',
    ['One counter-example is enough to disprove the word "always" — try to find two irrational numbers whose sum is not irrational', '√2 + (−√2) = 0'],
    ['Check that the result really is rational', '0 can be written as 0/1, a fraction of two integers']),

  'D-MF-05': explanation('1, 2, 3, 6, 7, 14, 21, 42',
    ['Find the factor pairs',
      '1 × 42 = 42',
      '2 × 21 = 42',
      '3 × 14 = 42',
      '6 × 7 = 42']),
  'D-MF-06': explanation('9, 18, 27, 36'),
  'D-MF-07': explanation('HCF = 12',
    ['List the factors of 24',
      '1, 2, 3, 4, 6, 8, 12, 24'],
    ['List the factors of 36',
      '1, 2, 3, 4, 6, 9, 12, 18, 36'],
    ['Find the common factors',
      '1, 2, 3, 4, 6, 12'],
    ['Choose the highest common factor',
      'HCF = 12']),
  'D-MF-08': explanation('LCM = 24',
    ['List multiples of 8',
      '8, 16, 24, 32'],
    ['List multiples of 12',
      '12, 24, 36'],
    ['Find the first number in both lists',
      'The first number in both lists is 24.']),
  'D-MF-09': { ...explanation('3 (or 9)'), answerLabel: 'Either answer works' },
  'D-MF-10': { ...explanation('12 and 18, or 18 and 24',
    ['List the multiples of 6 between 10 and 30', '12, 18, 24']), answerLabel: 'Accepted pairs' },
  'D-MF-11': explanation('Yes — any number divided by itself gives 1, with no remainder'),
  'D-MF-12': explanation('No — the LCM of 4 and 8 is 8, which is not bigger than 8',
    ['Try two numbers where one divides the other exactly', 'LCM of 4 and 8 = 8']),
}

export function withLessonExplanation(state: LearningState): LearningState {
  if (state.interaction.type === 'continue') return state
  const workedExplanation = explanations[state.id]
  if (!workedExplanation) throw new Error(`Missing Lesson 1 explanation: ${state.id}`)
  return { ...state, feedback: {
    correct: { ...state.feedback?.correct, message: 'Explanation', workedExplanation },
    incorrect: { ...state.feedback?.incorrect, message: 'Explanation', workedExplanation },
  } }
}
