import type { ScienceLesson, ScienceState } from '../types'
import { author, sampledRequirements } from '../lessonAuthoring'
import { photosynthesisRateFrames as frames } from './teachingFrames'

const source = { id: 'aqa-biology', title: 'AQA 8464 Biology subject content', url: 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', locator: '4.4.1.2 Rate of photosynthesis: limiting factors (light intensity, carbon dioxide concentration, temperature, amount of chlorophyll); required practical: effect of light intensity on the rate of photosynthesis using pondweed' }
const a = author('B-PHOTOSYNTHESIS-RATE', ['4.4.1.2'])
const t = (id: keyof typeof frames, title: string) => a.teach(id, title, frames[id])

export const photosynthesisRateSections = [
  { id: 'B27-01', label: 'Start here', detail: 'A plant in a dark cupboard' },
  { id: 'B27-02', label: 'What holds it back?', detail: 'Rate and limiting factors' },
  { id: 'B27-05', label: 'What do the graphs show?', detail: 'Light and carbon dioxide' },
  { id: 'B27-08', label: 'Too hot or too cold?', detail: 'Temperature and enzymes' },
  { id: 'B27-11', label: 'Test it with pondweed', detail: 'The required practical and a mean' },
  { id: 'B27-15', label: 'On your own', detail: 'Greenhouses, apparatus and results' },
]

const states: ScienceState[] = [
  { ...a.choice('B27-01', 'A potted plant is moved from a sunny windowsill into a dark cupboard. What happens to its photosynthesis?', ['It speeds up', 'It slows down and stops', 'It stays the same'], 1, 'You learned what photosynthesis needs to work.', ['Photosynthesis needs energy from light.', 'In the dark there is no light, so photosynthesis slows down and stops.']), phase: 'priorKnowledge', evidenceRole: 'diagnostic' },
  t('B27-02', 'What holds it back?'),
  a.choice('B27-03', 'What is a limiting factor?', ['Something that stops photosynthesis going any faster', 'Something a plant makes during photosynthesis', 'The fastest rate a plant can ever reach', 'A gas that leaves the leaf through the stomata'], 0, 'Think of the sandwich team that ran out of bread.', ['A limiting factor is the thing in shortest supply.', 'So it stops photosynthesis going any faster, even when everything else is plentiful.']),
  a.choice('B27-04', 'A plant grows in soil that is short of nutrients, and its leaves turn pale. Why does its rate of photosynthesis go down?', ['Its leaves take in too much carbon dioxide', 'Pale leaves get too hot', 'It has less chlorophyll, so it absorbs less light'], 2, 'What does chlorophyll do?', ['A lack of nutrients stops the plant making enough chlorophyll.', 'With less chlorophyll, the leaves absorb less light, so the rate goes down.']),
  t('B27-05', 'What do the graphs show?'),
  a.choice('B27-06', 'Look at the graph. At which numbered point is light intensity no longer the limiting factor?', ['Point 1', 'Point 2', 'Point 3'], 2, 'Where has the line stopped going up?', ['At points 1 and 2 the line is still rising, so more light still speeds photosynthesis up.', 'At point 3 the line is flat, so light is no longer the limiting factor.'], 'understanding', false, 'energy-graph-question'),
  a.choice('B27-07', 'A tomato plant has plenty of light and plenty of carbon dioxide, but its rate of photosynthesis has levelled off. What is probably the limiting factor?', ['Temperature', 'Light intensity', 'Carbon dioxide concentration', 'Oxygen'], 0, 'Which of the three factors is not plentiful?', ['Light and carbon dioxide are both plentiful, so neither is holding the rate back.', 'So temperature is probably the limiting factor.']),
  t('B27-08', 'Too hot or too cold?'),
  a.choice('B27-09', 'A plant is kept at 50 °C. Why does it not photosynthesise?', ['It has too much light', 'The enzymes it needs are damaged by the heat', 'Its enzymes work too slowly in the heat'], 1, 'What does too much heat do to enzymes?', ['Above the peak, heat damages the enzymes photosynthesis needs.', 'Photosynthesis stops at about 45 °C, so at 50 °C it does not happen.']),
  a.choice('B27-10', 'It is a sunny but frosty morning. Why is photosynthesis slow?', ['There is too much light', 'It is too cold, so the enzymes work slowly', 'The enzymes are damaged by the heat'], 1, 'Which factor is in short supply on a frosty morning?', ['There is plenty of light, but it is very cold.', 'Enzymes work slowly in the cold, so temperature is the limiting factor.']),
  t('B27-11', 'Test it with pondweed'),
  a.worked('B27-12', 'Work out a mean bubble length', 'With the lamp 10 cm away, three tests gave bubble lengths of 1.2 cm, 1.5 cm and 1.2 cm. What is the mean bubble length?', ['Add the three lengths: 1.2 + 1.5 + 1.2 = 3.9 cm.', 'Divide by the number of tests: 3.9 ÷ 3 = 1.3.', 'Add the units: the mean bubble length is 1.3 cm.'], 'energy-rp-mean'),
  a.choice('B27-13', 'With the lamp 20 cm away, three tests gave 0.8 cm, 0.9 cm and 1.0 cm. What is the mean bubble length?', ['2.7 cm', '0.9 cm', '0.8 cm', '1.0 cm'], 1, 'Add the three lengths, then divide by 3.', ['Add them: 0.8 + 0.9 + 1.0 = 2.7 cm.', 'Divide by 3 tests: 2.7 ÷ 3 = 0.9 cm.'], 'calculation'),
  a.choice('B27-14', 'In the pondweed practical, why must the temperature stay the same?', ['Pondweed can only live at one temperature', 'Warm water makes the bubbles easier to see', 'Temperature also affects the rate, so only the light should change'], 2, 'What else changes the rate of photosynthesis?', ['Temperature is also a limiting factor for photosynthesis.', 'If it changed, you could not tell whether the light caused the difference, so it is a control variable.'], 'practicalReasoning'),
  a.choice('B27-15', 'A greenhouse has bright winter sunshine and plenty of carbon dioxide, but the air inside is very cold. Which change would most likely speed up photosynthesis?', ['Add more lamps', 'Pump in more carbon dioxide', 'Heat the greenhouse', 'Give the plants less water'], 2, 'Which factor is in shortest supply?', ['Light and carbon dioxide are plentiful, but it is very cold.', 'Temperature is the limiting factor, so heating the greenhouse would speed photosynthesis up.'], 'application', true),
  a.choice('B27-16', 'Look at the numbered parts of the pondweed set-up. Which part collects the oxygen?', ['Part 1', 'Part 2', 'Part 3', 'Part 4'], 3, 'Follow the bubbles from the pondweed.', ['Part 1 is the lamp, part 2 is the ruler that sets the distance and part 3 is the pondweed.', 'Part 4 is the capillary tube, where the oxygen collects as a gas bubble.'], 'practicalReasoning', true, 'energy-rp-question'),
  a.choice('B27-17', 'Look at the results. What is the mean bubble length with the lamp 30 cm away?', ['1.8 cm', '0.7 cm', '0.6 cm', '0.5 cm'], 2, 'Add the three tests at 30 cm, then divide by 3.', ['Add them: 0.5 + 0.7 + 0.6 = 1.8 cm.', 'Divide by 3 tests: 1.8 ÷ 3 = 0.6 cm.'], 'calculation', true, 'energy-rp-data'),
  a.choice('B27-18', 'Which conclusion fits these results?', ['In this test, the closer the lamp, the longer the bubble, so the faster the rate', 'Pondweed stops photosynthesising when the lamp is more than 40 cm away', 'Light is the only thing that affects photosynthesis', 'The lamp at 10 cm heated the water'], 0, 'Only say what these results show.', ['The mean bubble length fell from 1.3 cm at 10 cm to 0.3 cm at 40 cm.', 'So in this test, the closer the lamp, the faster the rate. The results say nothing about distances beyond 40 cm or other factors.'], 'dataInterpretation', true, 'energy-rp-data'),
  a.written('B27-19', 'Describe how you could use pondweed to find out how light intensity affects the rate of photosynthesis.', 'Say what you change, what you measure, how you make it reliable and what you keep the same.', 'Put pondweed in a tube of water and use a ruler to place a lamp a set distance away. Leave it for a set time and collect the oxygen in a capillary tube, then measure the length of the gas bubble. Repeat twice more at that distance and work out the mean. Then repeat with the lamp at different distances, keeping the temperature and the time the same.', ['A ruler is used to put the lamp a set distance from the pondweed.', 'The pondweed is left to photosynthesise for a set time.', 'The oxygen is collected and the length of the gas bubble is measured (or the bubbles are counted).', 'Each distance is repeated and a mean is worked out.', 'The test is repeated with the lamp at different distances.', 'The temperature and the time are kept the same.'], ['Saying the pondweed gives off carbon dioxide, or measuring carbon dioxide.', 'Changing the lamp distance and the temperature at the same time.', 'Saying a longer bubble means a slower rate.']),
]

export const lesson27: ScienceLesson = {
  id: 'B-BIO-027-B', contentVersion: '0.1.0', qualification: 'AQA-8464F', strand: 'biology',
  title: 'The rate of photosynthesis', prerequisites: ['B-PHOTOSYNTHESIS'], reviewStatus: 'draftNeedsTeacherReview',
  sources: [source], misconceptions: [], states, retrieval: [], requirements: sampledRequirements(states),
}
