import type { TeachingFrame } from '../../teachingFrame'

// Build one lithium atom first (what is inside, how big), then put numbers on its particles (charge and mass),
// then describe it with two numbers, then group atoms into elements and isotopes, and only then average the isotopes.
const f = (label: string, summary: string, cue: string, text: string, focus: string): TeachingFrame => ({ label, summary, cue: `Think: ${cue}`, text, diagram: 'cellBiology', focus })

export const atomFrames: Record<string, TeachingFrame[]> = {
  'C1-02': [
    f('Tiny building blocks', 'Everything around you is made of atoms.', 'everything → made of atoms', 'Your desk, the air and your body are all made of tiny particles. They are far too small to see, even with a light microscope. These tiny particles are called atoms. The drawing shows one atom, made millions of times bigger than it really is.', 'atom-build-atom'),
    f('The nucleus', 'Every atom has a tiny centre.', 'middle of the atom → nucleus', 'Right in the middle of every atom is a tiny centre. This centre is called the nucleus. It is made of even smaller particles packed closely together.', 'atom-build-nucleus'),
    f('Protons', 'Some particles in the nucleus are positive.', 'proton → positive (+)', 'The nucleus holds two kinds of particle. One kind has a positive charge. These particles are called protons. They give the nucleus its positive charge. In the drawings, protons are red with a + sign.', 'atom-build-proton'),
    f('Neutrons', 'The other particles in the nucleus have no charge.', 'neutron → no charge', 'The other particles in the nucleus have no charge at all. They are called neutrons. In the drawings, neutrons are grey. This lithium atom has 3 protons and 4 neutrons in its nucleus.', 'atom-build-neutron'),
    f('Electrons', 'Tiny negative particles move around the nucleus.', 'electron → negative (−), in shells', 'Around the nucleus are much smaller particles with a negative charge. These are called electrons. They move around the nucleus in layers called shells. Electrons have almost no mass. In the drawings, electrons are blue with a − sign.', 'atom-build-electron'),
    f('How big?', 'Atoms are tiny, and the nucleus is tinier still.', 'atom radius ≈ 0.1 nm; nucleus ≈ 1/10 000 of that', 'The radius of an atom is about 0.1 nanometres (nm), or 1 × 10⁻¹⁰ m. A nanometre is one billionth of a metre. The radius of the nucleus is about 1 × 10⁻¹⁴ m. That is about 1/10 000 of the radius of the atom. So an atom is mostly empty space, but almost all its mass is in the nucleus.', 'atom-build-size'),
  ],
  'C1-05': [
    f('Relative charge', 'Each particle has a charge of +1, 0 or −1.', 'proton +1, neutron 0, electron −1', 'Scientists compare the charges of the three particles using simple numbers. A proton has a charge of +1. An electron has a charge of −1. A neutron has no charge, so its charge is 0. These numbers are called relative charges.', 'atom-particle-charge'),
    f('Relative mass', 'Protons and neutrons have the same mass; electrons are very light.', 'proton 1, neutron 1, electron very small', 'Masses are compared in the same way. A proton and a neutron have the same mass, so each has a mass of 1. An electron’s mass is very small compared with them. These numbers are called relative masses.', 'atom-particle-mass'),
    f('No overall charge', 'An atom has the same number of protons and electrons.', 'protons = electrons → charges cancel', 'In an atom, the number of electrons is the same as the number of protons. Each electron’s −1 cancels one proton’s +1. So the atom has no overall charge. An atom with no overall charge is called neutral.', 'atom-particle-neutral'),
    f('Put it together', 'One table sums up the three particles.', 'mass 1, 1, very small; charge +1, 0, −1', 'Protons and neutrons are heavy and sit in the nucleus. Electrons are very light and move around it. Protons are positive, electrons are negative and neutrons have no charge. An atom has equal numbers of protons and electrons, so it is neutral.', 'atom-particle-all'),
  ],
  'C1-08': [
    f('Atomic number', 'The atomic number is the number of protons.', 'atomic number = protons', 'Every lithium atom has 3 protons. The number of protons in an atom is called its atomic number. So the atomic number of lithium is 3.', 'atom-symbol-atomic'),
    f('Mass number', 'The mass number counts protons and neutrons together.', 'mass number = protons + neutrons', 'Our lithium atom has 3 protons and 4 neutrons. Together that makes 7 heavy particles in its nucleus. The total number of protons and neutrons is called the mass number. So the mass number of this atom is 7.', 'atom-symbol-mass'),
    f('The nuclear symbol', 'Both numbers are written beside the element’s letters.', 'top = mass number; bottom = atomic number', 'Li is the short way to write lithium. The mass number goes at the top left and the atomic number at the bottom left. Writing an atom like this is called its nuclear symbol. The top number is never smaller than the bottom one.', 'atom-symbol-symbol'),
    f('Counting the particles', 'Two numbers tell you all three particles.', 'neutrons = mass number − atomic number', 'Protons = atomic number, so lithium has 3 protons. Neutrons = mass number − atomic number, so 7 − 3 = 4 neutrons. The atom is neutral, so electrons = protons = 3. This matches the drawing of the lithium atom.', 'atom-symbol-count'),
    f('Ions', 'An atom can lose or gain electrons and become charged.', 'lose electrons → positive; gain → negative', 'Sometimes an atom loses or gains electrons. Then the protons and electrons no longer balance, so it has an overall charge. A charged particle like this is called an ion. A lithium ion, Li⁺, has lost 1 electron, so it has 3 − 1 = 2 electrons. A fluoride ion, F⁻, has gained 1, so it has 9 + 1 = 10.', 'atom-symbol-ion'),
  ],
  'C1-11': [
    f('Elements', 'An element is made of atoms with the same number of protons.', 'number of protons → which element', 'The number of protons decides what type of atom it is. Every atom with 3 protons is lithium. Every atom with 2 protons is helium. A substance made of atoms that all have the same number of protons is called an element. There are about 100 different elements.', 'atom-element-same'),
    f('Chemical symbols', 'Each element has a symbol of one or two letters.', 'one capital letter, then maybe one small letter', 'Each element can be written as a short code of one or two letters. This code is called its chemical symbol. The first letter is always a capital and a second letter is always small. Some come from old names, like Na for sodium and Fe for iron. You will find every symbol on the periodic table.', 'atom-element-symbols'),
    f('Isotopes', 'Atoms of one element can have different numbers of neutrons.', 'same protons, different neutrons', 'Most lithium atoms have 4 neutrons, but a few have only 3. Both kinds have 3 protons, so both are lithium. Atoms of the same element with different numbers of neutrons are called isotopes. We name them by their mass numbers: lithium-7 and lithium-6.', 'atom-isotope-pair'),
    f('Put it together', 'Isotopes have the same atomic number but different mass numbers.', 'same element, different mass', 'Lithium-6 and lithium-7 both have atomic number 3, and both have 3 electrons. Lithium-6 has 3 neutrons, so its mass number is 6. Lithium-7 has 4 neutrons, so its mass number is 7. They are the same element with slightly different masses.', 'atom-isotope-all'),
  ],
  'C1-14': [
    f('A mix of isotopes', 'Most elements are a mix of isotopes.', 'how common each isotope is → abundance', 'Chlorine has two isotopes: chlorine-35 and chlorine-37. In any sample of chlorine, about 3 out of every 4 atoms are chlorine-35. So 75% of the atoms are chlorine-35 and 25% are chlorine-37. How common an isotope is, is called its abundance.', 'atom-ram-mix'),
    f('An average mass', 'The relative atomic mass is an average for the element.', 'average that counts how common each isotope is', 'To describe chlorine with one number, we take an average of its mass numbers. The average takes account of how common each isotope is. This average is called the relative atomic mass, written Aᵣ. For chlorine, Aᵣ is 35.5: closer to 35, because chlorine-35 is more common.', 'atom-ram-average'),
    f('The rule', 'Multiply, add, then divide.', 'multiply → add → divide by the total abundance', 'First, multiply each isotope’s mass number by its abundance. Next, add these answers together. Then divide by the total of all the abundances. When the abundances are percentages, that total is 100.', 'atom-ram-rule'),
  ],
}
